// GameController (cube) — reconstructed declarations.
#ifndef CUBE_CONTROL_GAMECONTROLLER_H
#define CUBE_CONTROL_GAMECONTROLLER_H
#include "../include/cube_types.h"

void string_assignCStr(char *param_1);
void string_defaultInit(void);
void string_dtor(void);
void filebuf_dtor(void);
void string_move(undefined4 *param_1);
void string_grow(uint param_1,size_t param_2);
bool string_resize(uint param_1,char param_2);
void string_assignSubstr(int *param_1,uint param_2,uint param_3);
void string_assignFill(uint param_1,char param_2);
basic_streambuf<char,std::char_traits<char>_> * filebuf_close(void);
uint string_compare(uint param_1,uint param_2,undefined4 param_3,uint param_4);
void string_erase(uint param_1,uint param_2);
float10 fabs_f(float param_1);
undefined4 abstr::HelperIdentityClass::vfunc_0(void);
void ostrstream_str(void);
undefined4 ostrstream_str_wrap(undefined4 param_1);
float10 cosf_f(float param_1);
basic_ostream<wchar_t,std::char_traits<wchar_t>_> * wostream_insertWide(basic_ostream<wchar_t,std::char_traits<wchar_t>_> *param_1,wchar_t *param_2);
void setPair_b(undefined4 param_1,undefined4 param_2);
void setColor3b(undefined1 param_1,undefined1 param_2,undefined1 param_3);
void setVec3(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void setVec4(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void entityState_copy(undefined1 *param_1);
int arrayElem0x11c(int param_1);
int ptrAt_0x4c_0x20x8(void);
void repeatCall(undefined4 param_1,undefined4 param_2,int param_3,code *param_4);
int computeLevelDiffBonus(void);
void std_char_traits_assign(undefined2 *param_1,undefined2 *param_2);
undefined4 getField_0x3c(void);
undefined4 getField_0x34(void);
undefined4 getField_0x148(void);
undefined4 GameController_get_field_0x8006d0(void);
int GameController_get_field_ptr_0x800a1c(void);
void setFlagAtSlot(char param_1);
int count_0x11c(void);
void u16_ostrstream_str(void);
undefined4 u16_ostrstream_str_wrap(undefined4 param_1);
undefined4 getField_0x38(void);
undefined4 getField_0x40(void);
void array_lerp(float *param_1,float *param_2,int param_3,float param_4);
void vec2_copy(undefined4 *param_1);
void vec3_copy(undefined4 *param_1);
void int_toFixed16(uint param_1);
int addInt(int param_1);
int arrayElem_stride8(int param_1);
undefined4 vectorU32_at(int param_1);
float10 fixed16ToFloat(void);
void vec4_mulComponent(float *param_1,float *param_2);
void vec4_scale(float *param_1,float param_2);
void vec3_sub(float *param_1,float *param_2);
void int64_sub(int *param_1,uint *param_2);
void int64_subFn(int *param_1);
void int64_negate(int *param_1);
void vec3_add(float *param_1,float *param_2);
void int64_add(int *param_1,uint *param_2);
void int64_addFn(int *param_1);
float10 vec3_dot(float *param_1);
float * vec3_cross(float *param_1,float *param_2);
void mat4_mulLeft(float *param_1);
void vec3_scaleInPlace(float param_1);
void vec4_mulInPlace(float *param_1);
void vec3_addInPlace(float *param_1);
void vec3_subInPlace(float *param_1);
int mat_elemPtr(int param_1,int param_2);
void Creature_drawModel(undefined4 param_1,undefined4 param_2,undefined4 param_3,int param_4, undefined4 param_5,undefined4 param_6,float *param_7,float *param_8,uint param_9, undefined4 *param_10);
float10 vec3_length(void);
float10 computeYawFromDir(float param_1,float param_2,float param_3);
void vec3_normalize(void);
void mat4_rotateAxisAngle_v(undefined4 param_1,undefined4 *param_2);
void mat4_rotateAxisAngle(float param_1,float param_2,float param_3,float param_4);
void mat4_rotateX(float param_1);
void mat4_rotateY(float param_1);
void mat4_rotateZ(float param_1);
void mat4_scaleAxes(float param_1,float param_2,float param_3);
undefined4 getField_0x44(void);
undefined4 getField_0x48(void);
float10 vec2_lengthSq(void);
float10 vec3_lengthSq(void);
float * mat4_transformPoint(float *param_1,float *param_2);
void mat4_translateVec(float *param_1);
void mat4_translate(float param_1,float param_2,float param_3);
float10 sinf_f(float param_1);
float10 sqrtf_f(float param_1);
void vec3_scaleOut(float *param_1,float param_2);
float * vec3_normalizeOut(float *param_1);
void mat4_perspective(float param_1,float param_2,float param_3,float param_4);
undefined4 getField_0x110(void);
undefined4 getField_0x10c(void);
int storeVec2At(undefined4 *param_1);
int storeVec4At(undefined4 *param_1);
void copy3bytes(undefined1 *param_1);
undefined1 color3_differs(int param_1);
int arrayElem_stride4(int param_1);
int arrayElem_stride16(int param_1);
void math_vec4_sub(float *param_1,float *param_2);
void vec4_addInPlace(float *param_1);
void loadFirstElem_0x2c(undefined4 *param_1);
void getField_0x2c(undefined4 *param_1);
void cube::GameController::drawCharacterAppearancePanel(void);
int memberPtr_0xc(void);
void CharCreation_refresh_model(void);
void vec3_set(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void int64_setFromGen(void);
void Item_copyStruct(undefined1 *param_1);
int getPtrPlus8(void);
undefined4 getFirstDword(void);
int int64_ltFixed16(uint param_1);
void vec3i64_add(uint *param_1);
void int64_add_42c9b0(uint *param_1);
void vec3i64_sub(uint *param_1);
void int64_sub_42ca00(uint *param_1);
undefined4 map_valueAtOr0(int param_1);
void map_getRoot(undefined4 *param_1);
int int64_toIntFloor(undefined4 *param_1);
void counter_decrementClamp(void);
void flags_setOrClear114(ushort param_1,char param_2);
void state_initA(void);
void state_initB(void);
void buffer_freeAt0x11c(void);
void color_copy4(undefined1 *param_1);
undefined4 Item_equals(char *param_1);
/* Library Function - Single Match public: long __thiscall CRefTime::Millisecs(void) Libraries: Visual Studio 2012 Release, Visual Studio 2015 Release, Visual Studio 2017 Release, Visual Studio 2019 Release */ long __thiscall CRefTime::Millisecs(CRefTime *this);
int computeCellOffset(void);
int getTileCell32(uint param_1,uint param_2,int param_3);
float10 get_float_field_0x1000e78(void);
undefined * array_atChecked4(int param_1);
void cube::GameController::drawQuestHud(void);
int world_getChunkCell256(uint param_1,uint param_2,int param_3);
undefined1 block_isPassableType(void);
undefined4 getDword0x10(void);
float10 get_float_field_0xd4(void);
float10 get_float_field_0xd8(void);
undefined4 getDword0x28(void);
undefined4 region_getCell1024(int param_1,int param_2);
void mat_scaleColumns(float param_1,float param_2);
undefined4 getDword0x1c(void);
void mat_translateByCols(float param_1,float param_2);
byte getBlockType5bits(void);
void node_applyDamageColorFlash(float param_1);
int colorMap_allocNode(undefined4 param_1,undefined4 param_2,int param_3);
int list_makeNode(undefined4 param_1,undefined4 param_2,undefined4 param_3);
int list_insertNodeAt(undefined4 param_1,undefined4 param_2,undefined4 *param_3);
void list_allocNode32(undefined4 *param_1,undefined4 *param_2);
void textInput_insertChar(undefined4 param_1);
void NameInput_handle_key(short param_1);
undefined4 std_map_lower_bound(ushort param_1);
undefined4 getDword0xe8(void);
void textBuffer_clampScroll(void);
void text_layoutWordWrap(undefined4 *param_1,undefined2 *param_2);
void text_drawColoredString(undefined4 param_1,float *param_2);
void int64_subFixed16(int *param_1,uint param_2);
void int64_addFixed16(int *param_1,uint param_2);
uint * vec3i64_dotFixed(uint *param_1,undefined4 *param_2);
undefined4 block_isSolidType(void);
undefined4 vec3i64_selfDotFixed(undefined4 param_1);
void vec6_set(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5,undefined4 param_6);
void state_initFields10(void);
void struct_initSmallWithBuf(void);
void container_destroy(void);
float10 curve_level05(float param_1);
int combat_getAttackWindup(uint param_1);
int combat_getAttackTiming(void);
int * equipment_getActiveElement(int *param_1);
float10 stat_calcSpellPower(void);
undefined4 combat_isReadyToStrike(void);
bool combat_rollBlockSuccess(void);
undefined4 quest_checkItemThreshold(char *param_1);
bool ability_matchesId0x19(char *param_1);
int ability_getManaCost(undefined4 param_1,undefined4 param_2);
float10 ability_getPowerFactor(undefined4 param_1,int param_2);
undefined4 * list_findByTypeByte(uint param_1);
undefined1 combat_canBlockNow(void);
undefined1 physics_isLandingHard(void);
undefined4 weapon_isMeleeType(undefined4 param_1);
undefined1 weapon_isSpecialRunePtr(void);
undefined4 quest_hasActiveItemReq(void);
float10 ability_getResourceCost(undefined4 param_1,undefined4 param_2);
int shield_getBlockDuration(void);
int xp_getNextLevelCost(void);
char combat_selectAttackAnim(void);
void list_pushBack(undefined4 param_1);
void creature_getScaleVec4(undefined4 *param_1);
float10 curve_inverse20p1(float param_1);
void statusList_upsert(char *param_1);
void Player_resetCombatState(void);
void Player_resetPhysics(void);
float10 combat_getEffectiveHaste(void);
float10 stat_calcHasteBonus(void);
void xp_applyLevelUps(void);
void render_bindNodeTransformB(void);
void render_bindNodeTransformC(void);
void render_bindNodeTransformD(void);
void render_setVec3Uniform5c(undefined4 param_1);
void render_setVec3Uniform70(undefined4 *param_1);
void render_setUniform34(undefined4 param_1);
void render_setFogUniform64(float param_1);
void render_setInvUniform60(float param_1);
void render_setLightDirUniform(undefined4 param_1,undefined4 param_2,float *param_3,undefined4 param_4);
void render_setUniform30(undefined4 param_1);
void render_uploadModelViewMatrices(float *param_1,float *param_2,float *param_3);
void render_setVec3Uniform58(undefined4 param_1);
void render_setThreeUniforms(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void render_setVec3Uniform48(undefined4 param_1);
basic_ostream<char,std::char_traits<char>_> * ostream_writePadded(basic_ostream<char,std::char_traits<char>_> *param_1,char *param_2);
undefined4 ostream_writeEpilogue(void);
bool handle_isOpen(void);
undefined4 db_loadBlobByKey(undefined4 param_1,undefined4 *param_2,size_t *param_3);
undefined1 db_getBlobInto(undefined4 param_1,undefined4 *param_2);
void db_storeBlobVec(undefined4 param_1,int *param_2);
undefined4 db_storeBlob(undefined4 *param_1,undefined4 param_2,undefined4 param_3);
void swapElem_0x11c(undefined4 *param_1,undefined4 *param_2);
void ctor_ObjWithListMap(void);
void refcount_initTo1(undefined4 param_1);
void copyCtor_ObjWithVec(int param_1);
void copyCtor_EntityLike(undefined4 *param_1);
void allocNode_0x120(undefined4 *param_1,undefined4 *param_2);
void deserialize_struct_0x28(int param_1);
void deserialize_struct_small(undefined4 *param_1);
void stream_readBytes(void *param_1,size_t param_2);
void GameWorld_serialize_state(int param_1);
void buffer_append_bytes(void *param_1,size_t param_2);
int GameController_getSelectedCount(void);
void GameController_isInFrontRange(void);
undefined4 GameController_isHoveredTileType0e(void);
void releaseTwoRefPtrs(void);
void spawnWorkerThread(undefined4 *param_1);
void bytesToUint2(byte *param_1);
void fixedToIntVec3(undefined4 *param_1);
void floatToIntVec3(int param_1);
int * adjustorThunkCall(int *param_1,undefined4 *param_2);
void storeShortViaAdjust(int *param_1,undefined2 *param_2);
bool memEqual_0040c520(int param_1,undefined4 *param_2);
bool wideMemCompare_ne(int param_1,undefined4 *param_2);
void vec3_scale(float *param_1,float param_2,float *param_3);
undefined4 * string_ctorAppend(undefined4 *param_1,int param_2,char *param_3);
void dtor_freePtrRange_0x128(undefined4 *param_1,undefined4 *param_2);
void GameController_interpTimeSum(longlong *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void GameController_lerpVec3(float *param_1,float *param_2,undefined4 param_3,undefined4 param_4);
undefined4 GameController_popbackAndFormat(undefined4 param_1,void *param_2);
void GameController_writeTwoStrings(undefined4 param_1,void *param_2);
void plasma::Widget::MemberFunctionConnection<cube::GameController>::ctor_0 (undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5);
void GameController_collectTextShapes(int *param_1);
void pair_assign_byteDword(undefined1 *param_1,undefined1 *param_2,undefined4 *param_3);
void stream_writeString(undefined4 *param_1);
void storeShort(undefined2 *param_1,undefined2 param_2);
void strcpy16(char *param_1,char *param_2);
void swapDword(undefined4 *param_1,undefined4 *param_2);
void storeDword(undefined4 param_1);
void storeRGBA(undefined1 param_1,undefined1 param_2,undefined1 param_3,undefined1 param_4);
void std_list_list_const(undefined4 param_1);
void noop(void);
void std_list_list_const_459070(undefined4 *param_1);
void Struct_reset_4Dwords(void);
void cube::GameController::ctor_0 (undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined8 *param_5,undefined4 param_6,undefined4 param_7,undefined4 param_8);
void T_T_const_T_465ae0(int param_1);
void Struct_reset_10Dwords(void);
void Struct_init_defaults_off2b(void);
void T_T_const_T_465ef0(undefined4 *param_1);
void T_T_465fd0(void);
void Struct_init_off4_defaults(void);
/* Library Function - Multiple Matches With Same Base Name public: __thiscall <lambda_0a97c9e57da7be065955385c79108ff2>::<lambda_0a97c9e57da7be065955385c79108ff2>(struct _iobuf * const &,struct __crt_locale_pointers * const &,unsigned __int64 const &,wchar_t const * const &,char * const &) public: __thiscall <lambda_0be4ab1c2a6918fda4e39227d83ea893>::<lambda_0be4ab1c2a6918fda4e39227d83ea893>(struct _iobuf * const &,struct __crt_locale_pointers * const &,unsigned __int64 const &,char const * const &,char * const &) public: __thiscall <lambda_21448eb78dd3c4a522ed7c65a98d88e6>::<lambda_21448eb78dd3c4a522ed7c65a98d88e6>(struct __crt_locale_pointers * const &,struct _iobuf * const &,unsigned __int64 const &,char const * const &,char * const &) public: __thiscall <lambda_2565fc715a641e539f44ad02d6823606>::<lambda_2565fc715a641e539f44ad02d6823606>(struct _iobuf * const &,struct __crt_locale_pointers * const &,unsigned __int64 const &,char const * const &,char * const &) 26 names - too many to list Libraries: Visual Studio 2015 Release, Visual Studio 2017 Release, Visual Studio 2019 Release */ void <>(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5);
void setQuadFaceFromNormal(undefined1 *param_1,int param_2,float *param_3);
void Struct_ctor_allocListHeads(void);
void cube::GameController::ctor_1(void);
void tree_dtor_free_unwind_467af0(void);
void Object_dtor_composite(int param_1);
void String_freeIfNotSelf(int param_1);
void Object_copyAssign_off118_vec(int param_1);
void Struct_copy_10Dwords_bytes(undefined4 *param_1);
void Struct_copy_skipIdx1_11(undefined4 *param_1);
void Object_copyCtor_withSubobjects(undefined4 *param_1);
int operator_eq_2ints(int param_1);
int operator_eq_3ints(int param_1);
int operator_ne_2ints(int param_1);
bool operator_ne_int(int *param_1);
int iterator_prev_0xc(void);
int iterator_at_0x10(void);
undefined8 * fixedMul_16_16(undefined8 *param_1,undefined4 param_2,undefined4 *param_3);
void iterator_postInc_2(int *param_1);
undefined4 * iterator_deref_advance(undefined4 *param_1);
void iterator_postInc_4(int *param_1);
void iterator_postInc_0xc(int *param_1);
void iterator_postDec_0xc(int *param_1);
void vec2_sub(float *param_1,float *param_2);
undefined4 * Struct_copy6_thenReset(undefined4 *param_1);
void fixed_sub_scaled_64(int *param_1,uint param_2,uint *param_3);
void vec4_add(float *param_1,float *param_2);
int * vec2i_divScalar(int *param_1,int param_2);
undefined8 * int64_divScalar_double(undefined8 *param_1,int param_2);
void cube::GameController::networkReceiveThread(void);
void vec3_mulInPlace(float *param_1);
void cube::GameController::vfunc_0(byte param_1);
void std_Tree_Buyheadnode(void);
void tree_setVisibilityFlagRecursive(undefined4 param_1);
void GameController_addItemToInventory(char *param_1,int param_2);
int iterator_backMinus4(void);
void deref_frontValue(undefined4 *param_1);
void GameController_reloadServerList(undefined4 param_1,int param_2);
void cube::GameController::connectToServer (undefined4 *param_1);
void GameController_onItemPickup(void);
void voxelRaycast_modelPick(int param_1,float *param_2);
undefined4 getter_field80015c(void);
void GameController_modifyBlockAtWorld(uint param_1,uint param_2,int param_3);
void GameController_disconnect(void);
void renderEntityLabelBillboard(char *param_1,float *param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5,undefined4 param_6);
void drawOrientedModelOrTrail(uint *param_1,float *param_2,int param_3,undefined8 *param_4,undefined4 param_5, undefined4 param_6,int param_7,undefined4 param_8,undefined4 param_9,float param_10 ,float param_11,float param_12,int param_13,char param_14);
bool isZero_off10(void);
bool isZero_off4(void);
void GameController_start_game_mode(void);
void findNearestEntityInGrid(int param_1,int param_2);
undefined4 getter_field800164(void);
void collectFilledInventorySlots(uint *param_1);
int getHoveredWorldItem(void);
int getEquipmentSlotPtr(void);
char * getTargetedItemName(void);
char * getInteractTargetName(void);
undefined4 * getSelectedSlotCoords(undefined4 *param_1);
int getSelectedItemPtr(void);
undefined4 getter_off4c(void);
void cube::GameController::vfunc_7(int param_1);
void cube::GameController::vfunc_8(int param_1);
void cube::GameController::handleKeyPress (uint param_1);
void cube::GameController::vfunc_3(undefined4 param_1);
void cube::GameController::vfunc_6(float param_1,float param_2);
void cube::GameController::vfunc_9(int param_1);
undefined1 getter_byte3c4(void);
uint cube::GameController::vfunc_1(void);
uint getter_flagBit0_f4(void);
void testAABBvsFrustum_fixed(uint *param_1,uint *param_2);
void testSphereVsFrustum_fixed(uint *param_1,float param_2,float param_3);
undefined1 isInteractableTileType(void);
bool hasActiveWorldChunk(void);
undefined4 getItemTypeCategory(undefined1 *param_1);
undefined4 getChunkCellAt(int param_1,int param_2);
void spawnItemAffixDrops(uint param_1);
void cube::GameController::loadStructureBlob (int param_1,int param_2);
float10 getVelocityX(void);
float10 getVelocityY(void);
void getPositionXY(undefined4 *param_1);
int getPtr_off94(void);
undefined2 * lookupNestedStringMap(undefined2 *param_1,int param_2,void *param_3);
void cube::GameController::enterEditMode(void);
void cube::GameController::loadWorldList(void);
void cube::GameController::vfunc_5(void);
void cube::GameController::vfunc_4(int param_1,int param_2);
void playSoundAtPlayer(undefined4 param_1);
void playHitSoundAtPos(undefined4 param_1,uint *param_2,float param_3,undefined4 param_4);
void std_list_push_back_4861f0(undefined4 param_1);
void std_list_push_back_4865b0(undefined4 param_1);
void GameController_saveKeyedString(undefined4 param_1,int param_2);
undefined4 GameController_getField_b4(void);
void cube::GameController::saveEntityBlob (int param_1,int param_2);
void cube::GameController::saveStructureBlob (int param_1,int param_2,char param_3);
int GameController_getVoxelColumn8(uint param_1,uint param_2);
undefined4 GameController_get_selected_char_ptr(void);
void GameController_getPair_18c_190(undefined4 *param_1);
void GameController_set_1ec(undefined4 param_1);
void GameController_set_b8(undefined4 param_1);
void GameController_emitFormattedString(undefined4 param_1,undefined4 *param_2,undefined4 param_3);
int vec2_lengthSquared_int(void);
int GameController_getSub_8000f0(void);
void GameController_interactSpecialObject(int *param_1,undefined4 param_2);
void GameController_interactNpc(int param_1,char param_2);
void GameController_updateSelectedEntity(void);
undefined4 GameController_get_8000bc(void);
int GameController_asType2Object(int param_1);
int GameController_asType3Object(int param_1);
void mat4_transformPointProjective(float *param_1);
void mat3_transformVector(float *param_1,float *param_2);
void cube::GameController::vfunc_10(int *param_1);
void GameController_buildCharacterList(void);
void GameController_loadInventoryItems(void);
void GameController_computeCraftPrices(int param_1,int *param_2);
void GameController_equipStarterGear(void);
void GameController_rebuildCraftState(void);
void GameController_buildWorldList(void);
void GameController_handleObjectAction(int *param_1);
undefined1 * GameController_voxelAt3D(int param_1,int param_2,int param_3);
void cube::GameController::drawItemTooltip (char *param_1,int param_2,int param_3,float param_4,int param_5,char param_6, char param_7);
int GameController_getField16(uint param_1,uint param_2);
void GameController_renderCreature(int param_1);
void vec3_floatToByte3(int param_1);
bool int_notEqual(int *param_1,int *param_2);
void vec4_scale_4a8f40(float *param_1,float param_2,float *param_3);
void float_lerp_smooth(float *param_1,float *param_2,undefined4 param_3,undefined4 param_4);
void pair_zeroInit(void);
int iter_prev_4(void);
void iter_postinc_188(int *param_1);
void iter_postinc_10(int *param_1);
void iter_postinc_30(int *param_1);
void iter_postdec_4(int *param_1);
float10 iterated_lerp_toward1(int param_1,float param_2);
void cube::GameController::vfunc_11(void);
void GameController_spawnRibbonEffect(uint *param_1,undefined8 *param_2,undefined8 *param_3,int param_4, undefined4 param_5,undefined4 param_6,float param_7,float param_8,int param_9);
void GameController_spawnRibbonEffect2(uint *param_1,undefined8 *param_2,undefined8 *param_3,int param_4, undefined4 param_5,undefined4 param_6,float param_7,float param_8,float param_9, int param_10);
void GameController_spawnEffectMesh(int *param_1,float param_2,float param_3,float param_4,int param_5, undefined4 param_6,undefined4 param_7,undefined4 *param_8);
void GameController_renderDroppedItem(float *param_1,float param_2,float param_3,float param_4,undefined4 param_5, undefined4 param_6,undefined4 *param_7);
byte GameController_getFlag30_bit0(void);
undefined1 GameController_isTimerZero_1cc(void);
float10 perlinNoise2D_cosInterp(undefined4 param_1,undefined4 param_2,double param_3);
void vec3_rotateTowardAngle(float *param_1,float *param_2);
void cube::GameController::drawCurrencyPanel(void);
void InventoryWidget_rebuildItemList(int *param_1);
void InventoryWidget_updateScroll(void);
void InventoryWidget_drawScrollbar(void);
void InventoryWidget_handleSlotHover(char param_1);
undefined4 GameController_itemCooldown(void);
void GameController_avgEquippedColor(float *param_1);
float10 item_computeValue(void);
void item_classifyRecursive(undefined4 param_1);
float10 item_computeStat_armor(void);
void item_glowColor(undefined4 *param_1);
float * material_toColor(float *param_1,undefined4 param_2,float *param_3,float param_4);
undefined4 Item_get_stack_or_grid_size(void);
int item_rarityScaled(void);
int item_valueByType(void);
float10 item_hasSpecialAbility(void);
float10 item_computeStat_variant3(void);
void Item_get_type_color(undefined4 *param_1);
float10 item_weaponDamage(void);
void GameController_pickSpawnPoint(undefined8 *param_1);
void GameController_copyEntityState(undefined4 *param_1);
void GameController_clearListLocked_3c(undefined4 *param_1);
void GameController_clearListLocked_44(undefined4 *param_1);
void GameController_clearListLocked_34(undefined4 *param_1);
void GameController_terrainStateChanged(void);
void GameController_questStateChanged(void);
int GameController_computeQuestScore(void);
void Container_ctor_default(undefined4 param_1);
void container_operation(int *param_1);
undefined4 * map_lower_bound_string(undefined4 *param_1);
void GameController_build_quest_text(undefined4 param_1,int *param_2,int *param_3);
void cube::GameController::generateQuestText (int param_1,int param_2,int *param_3,undefined4 param_4);
void GameController_show_region_name(undefined4 param_1,undefined4 param_2,uint param_3,uint param_4);
undefined4 GameController_show_object_name(undefined4 param_1,undefined4 param_2,int param_3,int param_4);
bool GameController_speech_text_fits(void);
int GameController_measure_speech_height(void);
undefined1 color_equals3(int param_1);
void GameController_draw_mesh(void);
undefined4 GameController_match_transparent_color(int param_1,char param_2);
void VoxelModel_allocate(undefined4 param_1,undefined4 param_2,int param_3);
void VoxelModel_set_data(undefined4 param_1,undefined4 param_2,int param_3,void *param_4,char param_5);
void VoxelModel_build_mesh(void);
float10 VoxelModel_compute_ao(int param_1,int param_2,int param_3,int *param_4);
undefined4 GameController_class_icon_id(undefined4 param_1);
undefined4 GameController_item_icon_id(undefined1 *param_1);
void GameController_load_game_assets(int param_1);
int GameController_item_name_string_id(undefined4 param_1,int param_2,int param_3,int param_4);
void abstr::Method0<cube::System,int>::ctor_0(undefined1 param_1);
void GameController_MatchInputBinding(void);
void cube::GameController::drawWeaponCustomization(void);
void GameController_ClearSelection(void);
void GameController_ToggleSelection(void);
undefined4 FUN_0058d730(undefined4 param_1,int param_2,int param_3);
void FUN_00593e20(void);
void FUN_00594c80(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, int param_5);
void FUN_00595010(undefined4 param_1,undefined1 *param_2,int param_3);
void FUN_005953a0(undefined4 param_1,int param_2,int param_3);
undefined4 World_findObjectById(undefined4 *param_1);
undefined1 World_areEntitiesHostile(int param_1,int param_2);
void cube::GameController::buildObjectName (int **param_1,char *param_2);
undefined2 * World_getObjectName(undefined2 *param_1,undefined4 *param_2);
void GameController_playItemActionSound(undefined1 *param_1,int param_2);
void Terrain_computeBiomeColor(undefined4 *param_1,float *param_2,float *param_3,float *param_4,float *param_5, float *param_6,float *param_7);
int World_getChunkEntity(undefined4 *param_1);
undefined2 * FUN_0059fbf0(undefined2 *param_1,int param_2,int param_3);
undefined4 FUN_0059ff60(undefined4 param_1,undefined4 param_2);
undefined * FUN_005a02d0(int param_1);
void World_findNearestSpawnPoint(uint *param_1,uint *param_2);
int resolveVectorElementByHandle(undefined4 *param_1);
void GameController_updateHeldObjectOnMove(int param_1);
void NameGen_initFirstNameTables(undefined4 param_1,uint param_2,undefined4 param_3);
void World_raycastVoxels(uint *param_1,float *param_2,float param_3,char param_4,char param_5);
int FUN_005a4710(int param_1,int param_2);
undefined2 * WorldMap_lookupTileValue(undefined2 *param_1,int param_2,int param_3);
void collectSolidBlocksInBox(int param_1,int *param_2,uint param_3,uint param_4);
void vec3ToFixed64(uint *param_1);
int allocObjectWithVec3(undefined4 param_1,undefined4 param_2,undefined4 *param_3);
void Creature_findPathToTarget(int param_1,int param_2);
void PathMap_findInOpenSet(int param_1,undefined4 param_2,undefined4 param_3);
void FUN_005c2270(int param_1,int param_2,int param_3,undefined4 param_4);
void FUN_005c24f0(int param_1,int param_2,int param_3,undefined4 param_4);
void FUN_005c2770(undefined4 *param_1,int param_2,undefined4 param_3);
void FUN_005c28e0(undefined4 *param_1,int param_2,undefined4 param_3);
void FUN_005c2a50(undefined4 *param_1,float *param_2,float *param_3,undefined4 param_4);
void FUN_005c3010(undefined4 *param_1,float *param_2,float *param_3,undefined4 param_4);
int * GameController_chunkMap2i_at(int *param_1);
void FUN_005c4230(uint param_1);
void GameController_sampleTemperatureGrid(float param_1,uint param_2);
void GameController_sampleHumidityGrid(int param_1,int param_2);
int * FUN_005d7a70(int param_1,int param_2);
void cube::GameController::generateRegion (int param_1,int param_2);
void assign_two_dwords(undefined4 *param_1,undefined4 *param_2);
void fixedpoint_vec_subtract(uint *param_1,uint param_2,int param_3,uint param_4,int param_5);
float * World_getColumnDataAt2(float *param_1,int param_2,int param_3);
void World_getRegionCellPtr2(int param_1,int param_2);
void FUN_005f4d10(undefined4 *param_1);
void GameController_buildDecalMesh(undefined4 param_1,undefined2 param_2,undefined1 param_3,int param_4);
void GameController_buildDecalMesh2(undefined4 param_1,undefined2 param_2,undefined1 param_3,int param_4);
float10 vec3_distanceSquared(uint *param_1,uint *param_2);
void FUN_005fb9f0(undefined4 *param_1);
void FUN_005fc0d0(int *param_1,undefined4 *param_2);
void GameController_tryLockAndProcess(undefined4 param_1,undefined4 param_2);
void GameController_processNetworkTick(int *param_1,int param_2,int param_3,int param_4,int param_5,float *param_6, float param_7,int param_8,uint *param_9,char param_10);
void enter_critical_section(void);
void locked_pair_update(int param_1,int param_2);
void leave_critical_section(void);
void cube::GameController::unloadZone(int param_1,int param_2);
int hash_or_index_compute(uint param_1,uint param_2);
void cube::GameController::loadLandscapeTile (int param_1,int param_2);
void cube::GameController::streamTileChunk (uint param_1,uint param_2);
void cube::GameController::drawWorldSelectEntry(void);
void object_release(void);
int get_int_stub(void);
void store_object_ref(undefined4 *param_1);
int get_int_stub_b(void);
void GameController_updateSubsystems(int param_1,undefined4 param_2,int param_3);
float10 exp_decay_factor(float param_1);
void GameController_updateWidgetLayout(void);
void Widget_layoutChildren(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void Widget_measureContentEntry(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void GameController_setWidgetBounds(float *param_1);
void GameController_setWidgetBounds2(float *param_1);
void GameController_getWidgetSize(void);
void GameController_getWidgetSize2(void);
void get_widget_child(int param_1);
void string_appendGrow(int param_1,undefined4 *param_2,undefined4 *param_3);
void object_buildWithRefcount(undefined4 *param_1);
void plasma::NamedObject::ctor_1 (undefined4 param_1,int param_2,undefined4 *param_3,int param_4,undefined4 param_5);
void object_alloc(void);
void compute_pair_field(int *param_1,uint *param_2);
void Widget_setPositionFloat(float param_1);
void AdaptionWidget_rebuildLayoutRecursive(undefined4 *param_1,int param_2,undefined4 param_3);
void Node_dtor_release_children(void);
int Node_find_child_by_name_recursive(undefined4 *param_1);
void Node_get_first_material_name(undefined4 *param_1);
void Node_find_child_name_by_string(undefined4 *param_1,undefined4 *param_2,char param_3);
void Node_propagate_resolved_value(void);
undefined4 Node_any_child_active(void);
void Node_hit_test_point_recursive(float *param_1,uint param_2);
void Node_remove_child_from_list(int param_1);
void Node_detach_from_parent(int param_1);
void Node_set_shape_slot(int param_1);
void Node_pick_link_by_name(undefined4 *param_1,undefined4 param_2,undefined4 param_3);
void Registry_foreach_node_locked(void);
int Node_make_vec3_node(undefined4 *param_1);
void FUN_0063de60(void);
void GameController_update_render_targets(void);
undefined4 * Registry_push_node_locked_0x94(undefined4 *param_1);
void Node_traverse_invoke_callback(int param_1,code *param_2,undefined4 param_3);
undefined4 NamedObject_create_with_defaults(int param_1,undefined4 param_2,int param_3,int param_4,undefined4 param_5);
undefined4 TextShape_new_instance(undefined4 param_1,undefined4 param_2);
void Node_destroy_and_unregister(undefined4 *param_1);
void ShapeNode_unregister_and_release(undefined4 *param_1);
void Widget_unregister_and_release(undefined4 *param_1);
int Widget_render_pass(void);
void GameController_hittest_if_no_capture(void);
void GameController_notify_all_widgets(void);
void GameController_on_mouse_down(void);
void GameController_on_mouse_up(void);
void GameController_on_button2_down(void);
void GameController_on_button2_up(void);
void GameController_set_hover_widget(undefined4 param_1,int param_2);
undefined4 GameController_get_tooltip_widget(void);
void GameController_position_popup(int param_1,float param_2);
void GameController_load_widget_file(undefined4 *param_1,undefined4 param_2,undefined4 param_3,int param_4, undefined4 param_5);
void GameController_deserialize_widget_tree(basic_istream<char,std::char_traits<char>_> *param_1,int param_2,byte param_3, float *param_4);
undefined4 ScrollButton_deserialize(basic_istream<char,std::char_traits<char>_> *param_1);
undefined4 ScrollButton_read_field(basic_istream<char,std::char_traits<char>_> *param_1,int param_2,int param_3);
undefined4 ScrollSlider_deserialize(basic_istream<char,std::char_traits<char>_> *param_1);
undefined4 ScrollSlider_read_field(basic_istream<char,std::char_traits<char>_> *param_1,int param_2,int param_3);
void SmoothMeshShape_deserialize_v2(basic_istream<char,std::char_traits<char>_> *param_1,undefined4 param_2, undefined4 param_3);
void istream_read_string(undefined1 *param_1,basic_istream<char,std::char_traits<char>_> *param_2);
void TextShape_deserialize(basic_istream<char,std::char_traits<char>_> *param_1,undefined4 param_2);
void Texture_load_from_file_freeimage(undefined4 *param_1);
void Texture_load_from_memory_freeimage(int param_1,int param_2,int param_3);
void ContinuousAttributeVec3_deserialize(basic_istream<char,std::char_traits<char>_> *param_1,undefined4 param_2);
undefined4 NamedObject_deserialize(basic_istream<char,std::char_traits<char>_> *param_1);
void Widget_deserialize_common_field(basic_istream<char,std::char_traits<char>_> *param_1,int param_2, undefined4 param_3);
void istream_skipRecordByLength(basic_istream<char,std::char_traits<char>_> *param_1);
void Font_advancePenX(int param_1);
void GameController_rebuildEntityLists(void);
void Image_reallocFromFields(undefined4 param_1);
void plasma::ScrollSlider::ctor_0(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void Widget_setAspectFitEnabled(undefined4 param_1);
void plasma::TextShape::ctor_0(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void list_pushFrontNode(void);
void plasma::Button::ctor_1 (undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void plasma::ContinuousAttribute<plasma::Vector<3,float>_>::ctor_1 (undefined4 param_1,undefined4 param_2);
void plasma::DiscreteAttribute<int>::ctor_0(undefined4 param_1,undefined4 param_2);
void plasma::ScrollButton::ctor_0(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void setField240(undefined4 param_1);
void SceneLoader_ctor(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5,undefined4 param_6);
void PlasmaGraphics_loadDisplay(void);
void Button_deserializeProperties(void);
void Display_deserializeProperties(void);
void deserializeWidgetOnlyObject_0064f200(void);
void GenericShape_deserializeProperties(void);
void deserializeWidgetOnlyObject_0064f300(void);
void Node_deserializeProperties(char param_1);
void Button_deserializeProperties_0065(void);
void ScrollButton_deserializeProperties(void);
void ScrollSlider_deserializeProperties(void);
void SmoothMeshShape_deserializeProperties(void);
void TextShape_deserializeProperties(void);
void Texture_deserializeProperties(void);
void Transformation_deserializeProperties(void);
void deserializeWidgetOnlyObject_006503e0(void);
void Widget_readProperty(int param_1,undefined4 *param_2);
void Widget_applyBindMatrix(undefined4 *param_1);
undefined8 hashString_FNV(undefined4 *param_1);
void plasma::Shape::ctor_0(undefined4 param_1,undefined4 param_2);
void StreamReaderCtx_init(undefined4 param_1);
void decodeScrambledBuffer(char *param_1,uint param_2,uint *param_3);
void StreamReader_readTaggedBlockAppend(void);
void StreamReader_readToken(undefined1 *param_1,char param_2);
uint StreamReader_endBlockCheckPos(void);
void StreamReader_readString(undefined1 *param_1);
void StreamReader_skipBlock(void);
ulonglong float_to_uint64_round_guarded(void);

#endif
