// World (world) — cube. 8 functions. Bodies = Ghidra pseudo-C.
#include "World.h"

/* [AUDIT] proposed: World::map_find_or_insert_int  (confidence: med)
 * purpose: RB-tree lower_bound by int key *param_1; if absent builds 7-cap string value and inserts new node
 * vars: in_ECX=map; key +4; value string cap at +0x18/0x24
 */
/* Global::World_map_find_or_insert_int @ 004e2df0 */

void World_map_find_or_insert_int(int *key)

{
  undefined4 *root;
  int node;
  int *in_ECX;
  undefined4 *cur;
  undefined4 *child;
  undefined4 *insertPos;
  undefined1 local_4c [4];
  void *local_48 [4];
  undefined4 local_38;
  uint local_34;
  int local_30;
  void *local_2c;
  undefined4 local_1c;
  uint local_18;
  uint local_14;
  void *local_10;
  undefined1 *puStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  puStack_c = &LAB_006e9940;
  local_10 = ExceptionList;
  local_14 = DAT_0076aa78 ^ (uint)&stack0xfffffffc;
  ExceptionList = &local_10;
  root = (undefined4 *)*in_ECX;
  insertPos = root;
  if (*(char *)((int)root[1] + 0xd) == '\0') {
    cur = (undefined4 *)root[1];
    do {
      if ((int)cur[4] < *key) {
        child = (undefined4 *)cur[2];
      }
      else {
        child = (undefined4 *)*cur;
        insertPos = cur;
      }
      cur = child;
    } while (*(char *)((int)child + 0xd) == '\0');
  }
  if ((insertPos == root) || (*key < (int)insertPos[4])) {
    local_30 = *key;
    local_34 = 7;
    local_38 = 0;
    local_48[0] = (void *)((uint)local_48[0] & 0xffff0000);
    local_8 = 0;
    u16string_moveConstruct(local_48);
    local_8 = CONCAT31(local_8._1_3_,1);
    node = rbtree_allocNode_copyStr(&local_30);
    rbtree_insertHint_int(local_4c,insertPos,node + 0x10,node);
    if (7 < local_18) {
      operator_delete(local_2c);
    }
    local_18 = 7;
    local_1c = 0;
    local_2c = (void *)((uint)local_2c & 0xffff0000);
    if (7 < local_34) {
      operator_delete(local_48[0]);
    }
  }
  ExceptionList = local_10;
  __security_check_cookie(local_14 ^ (uint)&stack0xfffffffc);
  return;
}




/* [AUDIT] proposed: Pair_CopyFromRefs  (confidence: high)
 * purpose: Game: copies two dword values dereferenced from key/param_2 into a 2-field pair at in_ECX
 * vars: in_ECX=pair out
 */
/* Global::Pair_CopyFromRefs @ 0058d6f0 */

void Pair_CopyFromRefs(undefined4 *srcA,undefined4 *srcB)

{
  undefined4 *dst;
  
  *dst = *srcA;
  dst[1] = *srcB;
  return;
}




/* [AUDIT] proposed: Identity_ReturnArg  (confidence: high)
 * purpose: Game: identity accessor returning its argument unchanged
 * vars: -
 */
/* Global::Identity_ReturnArg @ 0058e9e0 */

undefined4 Identity_ReturnArg(undefined4 param_1)

{
  return param_1;
}




/* cube::World::ctor_1 @ 0058eb00 */

void cube::World::ctor_1(undefined4 world,undefined1 isServer)

{
  char cVar1;
  undefined4 obj;
  undefined4 *selfBase;
  undefined4 *puVar4;
  float *pfVar5;
  undefined4 *self;
  int iVar6;
  int iVar7;
  float10 fVar8;
  wchar_t *pwVar9;
  undefined4 uVar10;
  undefined *puVar11;
  undefined1 local_138 [8];
  undefined1 local_130 [8];
  undefined1 local_128 [8];
  undefined1 local_120 [8];
  undefined1 local_118 [8];
  undefined1 local_110 [8];
  undefined1 local_108 [8];
  undefined1 local_100 [8];
  undefined1 local_f8 [8];
  undefined1 local_f0 [8];
  undefined1 local_e8 [8];
  undefined1 local_e0 [12];
  undefined1 local_d4 [8];
  undefined1 local_cc [8];
  undefined1 local_c4 [8];
  undefined1 local_bc [8];
  undefined1 local_b4 [8];
  undefined1 local_ac [8];
  undefined1 local_a4 [8];
  undefined4 local_9c;
  undefined4 local_98;
  undefined4 local_94;
  undefined4 local_90;
  undefined4 local_8c;
  undefined1 local_88 [4];
  undefined4 *local_84;
  undefined4 *local_80;
  undefined4 *local_7c;
  undefined4 *local_78;
  undefined4 *local_74;
  undefined4 *local_70;
  undefined4 *local_6c;
  undefined4 local_68;
  undefined1 local_64 [4];
  undefined4 local_60;
  undefined4 *local_5c;
  undefined4 *local_58;
  undefined4 *local_54;
  undefined1 local_50 [8];
  undefined4 *local_48;
  undefined4 local_44;
  undefined4 *local_40;
  undefined4 local_3c;
  int local_38;
  undefined4 local_34;
  undefined4 *local_30;
  void *local_2c [4];
  undefined4 local_1c;
  uint local_18;
  uint local_14;
  void *local_10;
  undefined1 *puStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  puStack_c = &LAB_006f1930;
  local_10 = ExceptionList;
  local_14 = DAT_0076aa78 ^ (uint)&stack0xfffffffc;
  ExceptionList = &local_10;
  *self = vftable;
  local_68 = world;
  self[1] = 0;
  self[2] = 0;
  local_6c = self;
  obj = RBTree_allocSentinelNode(local_14);
  self[1] = obj;
  local_8 = 0;
  self[3] = 0;
  self[4] = 0;
  obj = RBTree_allocSentinelNode();
  self[3] = obj;
  local_8._0_1_ = 1;
  self[5] = 0;
  self[6] = 0;
  obj = list_buyNode_78(0,0);
  self[5] = obj;
  local_8._0_1_ = 2;
  SpriteManager::ctor_0(world);
  local_8._0_1_ = 3;
  cube::Speech::ctor_1();
  local_70 = self + 0x22;
  self[0x21] = 0;
  *local_70 = 0;
  self[0x23] = 0;
  self[0x24] = 0;
  self[0x2a] = 0xf;
  self[0x29] = 0;
  *(undefined1 *)(self + 0x25) = 0;
  local_8._0_1_ = 6;
  Database::ctor_1();
  *(undefined1 *)(self + 0x2d) = isServer;
  self[0x2e] = 0;
  self[0x20002f] = 0;
  puVar4 = self + 0x200041;
  local_8._0_1_ = 7;
  *puVar4 = 0;
  self[0x200042] = 0;
  local_40 = puVar4;
  obj = std_list_alloc_sentinel_0x2c();
  selfBase = local_6c;
  *puVar4 = obj;
  local_8._0_1_ = 8;
  local_7c = local_6c + 0x200043;
  *local_7c = 0;
  local_6c[0x200044] = 0;
  obj = std_list_alloc_sentinel_0x2c();
  selfBase[0x200043] = obj;
  local_5c = selfBase + 0x200045;
  local_8._0_1_ = 9;
  *local_5c = 0;
  selfBase[0x200046] = 0;
  obj = std_list_alloc_sentinel_0x2c();
  selfBase[0x200045] = obj;
  local_58 = selfBase + 0x200047;
  local_8._0_1_ = 10;
  *local_58 = 0;
  selfBase[0x200048] = 0;
  obj = std_list_alloc_sentinel_0x2c();
  selfBase[0x200047] = obj;
  puVar4 = selfBase + 0x200049;
  local_8._0_1_ = 0xb;
  *puVar4 = 0;
  selfBase[0x20004a] = 0;
  local_84 = puVar4;
  obj = Map_AllocSentinelNode();
  *puVar4 = obj;
  local_80 = local_6c + 0x20004b;
  local_8._0_1_ = 0xc;
  *local_80 = 0;
  local_6c[0x20004c] = 0;
  obj = Map_AllocSentinelNode();
  *local_80 = obj;
  local_48 = local_6c + 0x20004d;
  local_8._0_1_ = 0xd;
  *local_48 = 0;
  local_6c[0x20004e] = 0;
  obj = Map_AllocSentinelNode();
  *local_48 = obj;
  local_78 = local_6c + 0x20004f;
  local_8._0_1_ = 0xe;
  *local_78 = 0;
  local_6c[0x200050] = 0;
  obj = std_list_alloc_sentinel_0x2c();
  *local_78 = obj;
  local_74 = local_6c + 0x200051;
  local_8._0_1_ = 0xf;
  *local_74 = 0;
  local_6c[0x200052] = 0;
  obj = std_list_alloc_sentinel_0x2c();
  *local_74 = obj;
  local_54 = local_6c + 0x200053;
  local_8._0_1_ = 0x10;
  *local_54 = 0;
  local_6c[0x200054] = 0;
  obj = Map_AllocSentinelNode();
  *local_54 = obj;
  local_30 = local_6c + 0x200055;
  local_8._0_1_ = 0x11;
  *local_30 = 0;
  local_6c[0x200056] = 0;
  obj = rbtree_allocHead24();
  *local_30 = obj;
  local_8._0_1_ = 0x12;
  local_6c[0x200057] = 43200000;
  local_6c[0x200058] = 0;
  local_18 = 0xf;
  local_1c = 0;
  local_2c[0] = (void *)((uint)local_2c[0] & 0xffffff00);
  string_assignPtrLen(&DAT_006fc918,0);
  local_8._0_1_ = 0x13;
  std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_15(0x7b,local_2c);
  local_8 = CONCAT31(local_8._1_3_,0x12);
  if (0xf < local_18) {
    operator_delete(local_2c[0]);
  }
  local_30 = (undefined4 *)0x0;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"ElfMale",7);
  local_30 = (undefined4 *)0x1;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"ElfFemale",9);
  local_30 = (undefined4 *)0x2;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"HumanMale",9);
  local_30 = (undefined4 *)0x3;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"HumanFemale",0xb);
  local_30 = (undefined4 *)0x4;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"GoblinMale",10);
  local_30 = (undefined4 *)0x5;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"GoblinFemale",0xc);
  local_30 = (undefined4 *)0x6;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Bullterrier",0xb);
  local_30 = (undefined4 *)0x7;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"LizardmanMale",0xd);
  local_30 = (undefined4 *)0x8;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"LizardmanFemale",0xf);
  local_30 = (undefined4 *)0xd;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"FrogmanMale",0xb);
  local_30 = (undefined4 *)0xe;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"FrogmanFemale",0xd);
  local_30 = (undefined4 *)0x60;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Zombie",6);
  local_30 = (undefined4 *)0x2c;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Bandit",6);
  local_30 = (undefined4 *)0x12;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"OldMan",6);
  local_30 = (undefined4 *)0x2b;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Wizard",6);
  local_30 = (undefined4 *)0x6c;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Troll",5);
  local_30 = (undefined4 *)0x6e;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"HellDemon",9);
  local_30 = (undefined4 *)0x6f;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Golem",5);
  local_30 = (undefined4 *)0x70;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"EmberGolem",10);
  local_30 = (undefined4 *)0x71;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"SnowGolem",9);
  local_30 = (undefined4 *)0x5e;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Werewolf",8);
  local_30 = (undefined4 *)0x6d;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"DarkTroll",9);
  local_30 = (undefined4 *)0x72;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Yeti",4);
  local_30 = (undefined4 *)0x2e;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Ogre",4);
  local_30 = (undefined4 *)0x2f;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Rockling",8);
  local_30 = (undefined4 *)0x61;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Vampire",7);
  local_30 = (undefined4 *)0x56;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Spitter",7);
  local_30 = (undefined4 *)0x4c;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"SpikeCreature",0xd);
  local_30 = (undefined4 *)0x4d;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Anubis",6);
  local_30 = (undefined4 *)0x4e;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Horus",5);
  local_30 = (undefined4 *)0x4f;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Jester",6);
  local_30 = (undefined4 *)0x50;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Spectrino",9);
  local_30 = (undefined4 *)0x51;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Djinn",5);
  local_30 = (undefined4 *)0x52;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Minotaur",8);
  local_30 = (undefined4 *)0x55;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(&DAT_0071aa44,3);
  local_30 = (undefined4 *)0x65;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Dragon",6);
  local_30 = (undefined4 *)0x75;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Lich",4);
  local_30 = (undefined4 *)0x9;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"DwarfMale",9);
  local_30 = (undefined4 *)0xa;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"DwarfFemale",0xb);
  local_30 = (undefined4 *)0x35;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Hornet",6);
  local_30 = (undefined4 *)0x36;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"InsectGuard",0xb);
  local_30 = (undefined4 *)0x7f;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Ginseng",7);
  local_30 = (undefined4 *)0x3c;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(&DAT_0071aacc,3);
  local_30 = (undefined4 *)0x3d;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Midge",5);
  local_30 = (undefined4 *)0x3e;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Mosquito",8);
  local_30 = (undefined4 *)0x39;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Seagull",7);
  local_30 = (undefined4 *)0x46;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"RadishCreature",0xe);
  local_30 = (undefined4 *)0x45;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"PlantCreature",0xd);
  local_30 = (undefined4 *)0x47;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Onionling",9);
  local_30 = (undefined4 *)0x48;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"DesertOnionling",0xf);
  local_30 = (undefined4 *)0x49;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Devourer",8);
  local_30 = (undefined4 *)0x6a;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Crab",4);
  local_30 = (undefined4 *)0x6b;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"SeaCrab",7);
  local_30 = (undefined4 *)0x66;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"BarkBeetle",10);
  local_30 = (undefined4 *)0x67;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"FireBeetle",10);
  local_30 = (undefined4 *)0x68;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"SnoutBeetle",0xb);
  local_30 = (undefined4 *)0x69;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"LemonBeetle",0xb);
  local_30 = (undefined4 *)0x92;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"LemonFish",9);
  local_30 = (undefined4 *)0x91;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"SapphireFish",0xc);
  local_30 = (undefined4 *)0x96;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Shark",5);
  local_30 = (undefined4 *)0x98;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"LanternFish",0xb);
  local_30 = (undefined4 *)0x99;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"MawFish",7);
  local_30 = (undefined4 *)0x9a;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Piranha",7);
  local_30 = (undefined4 *)0x9b;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Blowfish",8);
  local_30 = (undefined4 *)0x93;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Seahorse",8);
  local_30 = (undefined4 *)0x44;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Frog",4);
  local_30 = (undefined4 *)0x57;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Mole",4);
  local_30 = (undefined4 *)0x58;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Biter",5);
  local_30 = (undefined4 *)0x5a;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Squirrel",8);
  local_30 = (undefined4 *)0x5b;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Raccoon",7);
  local_30 = (undefined4 *)0x4a;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Duckbill",8);
  local_30 = (undefined4 *)0x4b;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Crocodile",9);
  local_30 = (undefined4 *)0x5c;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(&DAT_0071ad10,3);
  local_30 = (undefined4 *)0x5d;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Penguin",7);
  local_30 = (undefined4 *)0x37;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Crow",4);
  local_30 = (undefined4 *)0x3a;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Parrot",6);
  local_30 = (undefined4 *)0x77;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Saurian",7);
  local_30 = (undefined4 *)0x76;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"RuneGiant",9);
  local_30 = (undefined4 *)0x73;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Cyclops",7);
  local_30 = (undefined4 *)0x74;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Mammoth",7);
  local_30 = (undefined4 *)0x2d;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Witch",5);
  local_30 = (undefined4 *)0x33;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Gnobold",7);
  local_30 = (undefined4 *)0x34;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Insectoid",9);
  local_30 = (undefined4 *)0x30;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Gnoll",5);
  local_30 = (undefined4 *)0x31;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"PolarGnoll",10);
  local_30 = (undefined4 *)0x94;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Mermaid",7);
  local_30 = (undefined4 *)0x95;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Merman",6);
  local_30 = (undefined4 *)0x3b;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(&DAT_0071adfc,3);
  local_30 = (undefined4 *)0xb;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"OrcMale",7);
  local_30 = (undefined4 *)0xc;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"OrcFemale",9);
  local_30 = (undefined4 *)0x25;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"GreenSlime",10);
  local_30 = (undefined4 *)0x26;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"PinkSlime",9);
  local_30 = (undefined4 *)0x27;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"YellowSlime",0xb);
  local_30 = (undefined4 *)0x28;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"BlueSlime",9);
  local_30 = (undefined4 *)0x29;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Frightener",10);
  local_30 = (undefined4 *)0x2a;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"SandHorror",10);
  local_30 = (undefined4 *)0x78;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Bush",4);
  local_30 = (undefined4 *)0x79;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"SnowBush",8);
  local_30 = (undefined4 *)0x7a;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"SnowBerryBush",0xd);
  local_30 = (undefined4 *)0x82;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"ThornTree",9);
  local_30 = (undefined4 *)0x80;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Cactus",6);
  local_30 = (undefined4 *)0x8e;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Dummy",5);
  local_30 = (undefined4 *)0x8d;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(&DAT_0071af1c,3);
  local_30 = (undefined4 *)0x7b;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"CottonPlant",0xb);
  local_30 = (undefined4 *)0x7c;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Scrub",5);
  local_30 = (undefined4 *)0x7d;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"CobwebScrub",0xb);
  local_30 = (undefined4 *)0x7e;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"FireScrub",9);
  local_30 = (undefined4 *)0x90;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Bomb",4);
  local_30 = (undefined4 *)0xf;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"UndeadMale",10);
  local_30 = (undefined4 *)0x10;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"UndeadFemale",0xc);
  local_30 = (undefined4 *)0x11;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Skeleton",8);
  local_30 = (undefined4 *)0x3f;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"PlainRunner",0xb);
  local_30 = (undefined4 *)0x40;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"LeafRunner",10);
  local_30 = (undefined4 *)0x41;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"SnowRunner",10);
  local_30 = (undefined4 *)0x42;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"DesertRunner",0xc);
  local_30 = (undefined4 *)0x43;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Peacock",7);
  local_30 = (undefined4 *)0x23;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Bunny",5);
  local_30 = (undefined4 *)0x24;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Porcupine",9);
  local_30 = (undefined4 *)0x13;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Collie",6);
  local_30 = (undefined4 *)0x14;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"ShepherdDog",0xb);
  local_30 = (undefined4 *)0x16;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Alpaca",6);
  local_30 = (undefined4 *)0x17;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"BrownAlpaca",0xb);
  local_30 = (undefined4 *)0x15;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"SkullBull",9);
  local_30 = (undefined4 *)0x18;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(&DAT_0071b0c0,3);
  local_30 = (undefined4 *)0x19;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Turtle",6);
  local_30 = (undefined4 *)0x1a;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Terrier",7);
  local_30 = (undefined4 *)0x1b;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"ScottishTerrier",0xf);
  local_30 = (undefined4 *)0x1d;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Panther",7);
  local_30 = (undefined4 *)0x1e;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(&DAT_0071b118,3);
  local_30 = (undefined4 *)0x1f;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"BrownCat",8);
  local_30 = (undefined4 *)0x20;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"WhiteCat",8);
  local_30 = (undefined4 *)0x1c;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Wolf",4);
  local_30 = (undefined4 *)0x21;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(&DAT_0071b154,3);
  local_30 = (undefined4 *)0x22;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Sheep",5);
  local_30 = (undefined4 *)0x62;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Horse",5);
  local_30 = (undefined4 *)0x64;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(&DAT_0071b174,3);
  local_30 = (undefined4 *)0x63;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Camel",5);
  local_30 = (undefined4 *)0x32;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Monkey",6);
  local_30 = (undefined4 *)0x38;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Chicken",7);
  local_30 = (undefined4 *)0x3e;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Mosquito",8);
  local_30 = (undefined4 *)0x24;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Porcupine",9);
  local_30 = (undefined4 *)0x8f;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Vase",4);
  local_30 = (undefined4 *)0x84;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"IronDeposit",0xb);
  local_30 = (undefined4 *)0x83;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"GoldDeposit",0xb);
  local_30 = (undefined4 *)0x87;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"EmeraldDeposit",0xe);
  local_30 = (undefined4 *)0x88;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"SapphireDeposit",0xf);
  local_30 = (undefined4 *)0x89;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"RubyDeposit",0xb);
  local_30 = (undefined4 *)0x8a;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"DiamondDeposit",0xe);
  local_30 = (undefined4 *)0x85;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"SilverDeposit",0xd);
  local_30 = (undefined4 *)0x86;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"SandstoneDeposit",0x10);
  local_30 = (undefined4 *)0x8b;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"IceCrystalDeposit",0x11);
  local_30 = (undefined4 *)0x8c;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Scarecrow",9);
  local_30 = (undefined4 *)0x53;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"NomadMale",9);
  local_30 = (undefined4 *)0x54;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"NomadFemale",0xb);
  local_30 = (undefined4 *)0x97;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Bumblebee",9);
  local_30 = (undefined4 *)0x59;
  World_map_find_or_insert_int(&local_30);
  u16string_assignPtrLen(L"Koala",5);
  local_3c = 6;
  local_38 = 0;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"Boots",5);
  local_3c = 5;
  local_38 = 0;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"Gloves",6);
  local_3c = 4;
  local_38 = 0;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"ChestArmor",10);
  local_3c = 7;
  local_38 = 0;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"ShoulderArmor",0xd);
  local_3c = 0x13;
  local_38 = 0;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(&DAT_00700a30,3);
  local_3c = 8;
  local_38 = 0;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"Amulet",6);
  local_3c = 9;
  local_38 = 0;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"Ring",4);
  local_3c = 2;
  local_38 = 0;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"Formula",7);
  local_3c = 3;
  local_38 = 0;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"Sword",5);
  local_3c = 3;
  local_38 = 3;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"Dagger",6);
  local_3c = 3;
  local_38 = 4;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"Fist",4);
  local_3c = 3;
  local_38 = 2;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"Mace",4);
  local_3c = 3;
  local_38 = 1;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(&DAT_0071b3d0,3);
  local_3c = 3;
  local_38 = 6;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(&DAT_0071b3d8,3);
  local_3c = 3;
  local_38 = 7;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"Crossbow",8);
  local_3c = 3;
  local_38 = 8;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"Boomerang",9);
  local_3c = 3;
  local_38 = 0xe;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"Arrows",6);
  pwVar9 = L"Arrow";
  local_3c = 3;
  local_38 = 9;
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Torch";
  local_3c = 3;
  local_38 = 0x14;
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Staff";
  local_3c = 3;
  local_38 = 10;
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Wand";
  local_3c = 3;
  local_38 = 0xb;
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Bracelet";
  local_3c = 3;
  local_38 = 0xc;
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Shield";
  local_3c = 3;
  local_38 = 0xd;
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Greatsword";
  local_3c = 3;
  local_38 = 0xf;
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Greataxe";
  local_3c = 3;
  local_38 = 0x10;
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Greatmace";
  local_3c = 3;
  local_38 = 0x11;
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Longsword";
  local_3c = 3;
  local_38 = 5;
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Coin";
  local_3c = 0xc;
  local_38 = 0;
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"PlatinumCoin";
  local_3c = 0xd;
  local_38 = 0;
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Candle";
  local_3c = 0x12;
  local_38 = 0;
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Candle";
  local_3c = 0x12;
  local_38 = 1;
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"HangGlider";
  local_3c = 0x17;
  local_38 = 0;
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Boat";
  local_3c = 0x17;
  local_38 = 1;
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Lamp";
  local_3c = 0x18;
  local_38 = 0;
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"ManaCube";
  local_3c = 0x19;
  local_38 = 0;
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  iVar7 = 0;
  local_3c = 0x14;
  do {
    local_38 = iVar7;
    World_MapInsertChunk(&local_3c);
    u16string_assignPtrLen(L"Bait",4);
    iVar7 = iVar7 + 1;
  } while (iVar7 < 0x9c);
  local_3c = 0x14;
  local_38 = 0x28;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"BlueJelly",9);
  local_3c = 0x14;
  local_38 = 0x25;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"GreenJelly",10);
  local_3c = 0x14;
  local_38 = 0x26;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"PinkJelly",9);
  local_3c = 0x14;
  local_38 = 0x27;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"YellowJelly",0xb);
  local_3c = 0x14;
  local_38 = 0x23;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"Carrot",6);
  local_3c = 0x14;
  local_38 = 0x21;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"PumpkinMash",0xb);
  local_3c = 0x14;
  local_38 = 0x1e;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"Candy",5);
  local_3c = 0x14;
  local_38 = 0x5c;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"Lollipop",8);
  local_3c = 0x14;
  local_38 = 0x5d;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"Softice",7);
  local_3c = 0x14;
  local_38 = 0x57;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"ChocolateDonut",0xe);
  local_3c = 0x14;
  local_38 = 0x22;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"CottonCandy",0xb);
  local_3c = 0x14;
  local_38 = 0x35;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"Popcorn",7);
  local_3c = 0x14;
  local_38 = 0x38;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"CerealBar",9);
  local_3c = 0x14;
  local_38 = 0x5a;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"StrawberryCake",0xe);
  local_3c = 0x14;
  local_38 = 0x5b;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"ChocolateCake",0xd);
  local_3c = 0x14;
  local_38 = 0x17;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"ChocolateCupcake",0x10);
  local_3c = 0x14;
  local_38 = 0x16;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"VanillaCupcake",0xe);
  local_3c = 0x14;
  local_38 = 0x32;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"BananaSplit",0xb);
  local_3c = 0x14;
  local_38 = 0x1b;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"Croissant",9);
  local_3c = 0x14;
  local_38 = 0x66;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"Bread",5);
  local_3c = 0x14;
  local_38 = 0x68;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"Lolly",5);
  local_3c = 0x14;
  local_38 = 0x69;
  World_MapInsertChunk(&local_3c);
  u16string_assignPtrLen(L"LemonTart",9);
  local_30 = (undefined4 *)0x14;
  local_44 = 0x43;
  selfBase = (undefined4 *)Identity_ReturnArg(&local_30);
  local_34 = *selfBase;
  uVar10 = 0;
  obj = Pair_CopyFromRefs(&local_34,&local_44,0);
  Pair_Copy2(obj,uVar10);
  Pair_Copy2(&local_3c,0);
  pwVar9 = L"ChocolateCookie";
  World_MapInsertChunk(local_64);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x13;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"BubbleGum";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x37;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"LicoriceCandy";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x19;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"CinnamonRole";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x4b;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"AppleRing";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x1a;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Waffle";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x56;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"WaterIce";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 99;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"DateCookie";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x62;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"CandiedApple";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x6a;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"StrawberryCocktail";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x3f;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"MilkChocolateBar";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x42;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"CaramelChocolateBar";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  local_34 = 0x40;
  local_44 = 0x14;
  uVar10 = 0;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"MintChocolateBar";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x41;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"WhiteChocolateBar";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x4a;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"SugarCandy";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x24;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"BlackberryMarmelade";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  local_34 = 0x39;
  uVar10 = 0;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"SaltedCaramel";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x3a;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"GingerTartlet";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x3b;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"MangoJuice";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x3c;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"FruitBasket";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x3d;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"MelonIceCream";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x3e;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"BloodOrangeJuice";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x58;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Pancakes";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x67;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Curry";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x97;
  local_44 = 0x14;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"BiscuitRole";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 1;
  local_44 = 1;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"LifePotion";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 2;
  local_44 = 1;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"CactusPotion";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 3;
  local_44 = 1;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"ManaPotion";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 4;
  local_44 = 1;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"GinsengSoup";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 5;
  local_44 = 1;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"SnowBerryMash";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 6;
  local_44 = 1;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"MushroomSpit";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 8;
  local_44 = 1;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"PineappleSlice";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 9;
  local_44 = 1;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"PumpkinMuffin";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0;
  local_44 = 1;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Cookie";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 7;
  local_44 = 1;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Bomb";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Nugget";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 1;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  puVar11 = &DAT_0071bad8;
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(puVar11);
  uVar10 = 0;
  local_34 = 2;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Feather";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 3;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Horn";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  local_34 = 4;
  local_44 = 0xb;
  uVar10 = 0;
  obj = pair_assign_2dword(local_50,&local_44,&local_34,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Claw";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 5;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Fiber";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 7;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Hair";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 8;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Crystal";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  local_34 = 9;
  uVar10 = 0;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Yarn";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 6;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Cobweb";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 10;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Cube";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0xb;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Capsule";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0xd;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  puVar11 = &DAT_0071bb5c;
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(puVar11);
  uVar10 = 0;
  local_34 = 0xc;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Flask";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0xe;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Spirit";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0xf;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Mushroom";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x13;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"ShimmerMushroom";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x14;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"GinsengRoot";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x10;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Pumpkin";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x11;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Pineapple";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x16;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Heartflower";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x17;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"PricklyPear";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x18;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"FrozenHeartflower";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x19;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Soulflower";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x12;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"RadishSlice";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x15;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"OnionSlice";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x1a;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"WaterFlask";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0x1b;
  local_44 = 0xb;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"SnowBerry";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0;
  local_44 = 0xf;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Beak";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0;
  local_44 = 0x15;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Amulet1";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 1;
  local_44 = 0x15;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Amulet2";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  local_34 = 2;
  local_44 = 0x15;
  uVar10 = 0;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"JewelCase";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 3;
  local_44 = 0x15;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  puVar11 = &DAT_0071bcf8;
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(puVar11);
  uVar10 = 0;
  local_34 = 4;
  local_44 = 0x15;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Medicine";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 5;
  local_44 = 0x15;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Antivenom";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  local_34 = 6;
  uVar10 = 0;
  local_44 = 0x15;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"BandAid";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 7;
  local_44 = 0x15;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Crutch";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 8;
  local_44 = 0x15;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Bandage";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 9;
  local_44 = 0x15;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Salve";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0;
  local_44 = 0xe;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Leftovers";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_34 = 0;
  local_44 = 0x10;
  obj = pair_assign_2dword(local_50,&local_44,&local_34);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Painting";
  World_MapInsertChunk(&local_3c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Statue";
  local_34 = 0;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Door";
  local_34 = 1;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"BigDoor";
  local_34 = 2;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Window";
  local_34 = 3;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"CastleWindow";
  local_34 = 4;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Gate";
  local_34 = 5;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"FireTrap";
  local_34 = 6;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"SpikeTrap";
  local_34 = 7;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"StompTrap";
  local_34 = 8;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Lever";
  local_34 = 9;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Chest";
  local_34 = 10;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Table";
  local_34 = 0xc;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Table";
  local_34 = 0xe;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Table";
  local_34 = 0xd;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Stool";
  local_34 = 0x10;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Stool";
  local_34 = 0xf;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Stool";
  local_34 = 0x11;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Bench";
  local_34 = 0x12;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  puVar11 = &DAT_0071be5c;
  local_34 = 0x13;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(puVar11);
  pwVar9 = L"BedTable";
  local_34 = 0x14;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"MarketStand1";
  local_34 = 0x15;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"MarketStand2";
  local_34 = 0x16;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"MarketStand3";
  local_34 = 0x17;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Barrel";
  local_34 = 0x18;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Crate";
  local_34 = 0x19;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"OpenCrate";
  local_34 = 0x1a;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Sack";
  local_34 = 0x1b;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Shelter";
  local_34 = 0x1c;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Cupboard";
  local_34 = 0x1d;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Desktop";
  local_34 = 0x1e;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Counter";
  local_34 = 0x1f;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Shelf1";
  local_34 = 0x20;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Shelf2";
  local_34 = 0x21;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Shelf3";
  local_34 = 0x22;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Corpse";
  local_34 = 0x2c;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"RuneStone";
  local_34 = 0x2d;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Artifact";
  local_34 = 0x2e;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"FlowerBox1";
  local_34 = 0x2f;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"FlowerBox2";
  local_34 = 0x30;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"FlowerBox3";
  local_34 = 0x31;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"StreetLight";
  local_34 = 0x32;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"FireStreetLight";
  local_34 = 0x33;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Fence1";
  local_34 = 0x34;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Fence2";
  local_34 = 0x35;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Fence3";
  local_34 = 0x36;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Fence4";
  local_34 = 0x37;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Vase1";
  local_34 = 0x38;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Vase2";
  local_34 = 0x39;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Vase3";
  local_34 = 0x3a;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Vase4";
  local_34 = 0x3b;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Vase5";
  local_34 = 0x3c;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Vase6";
  local_34 = 0x3d;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Vase7";
  local_34 = 0x3e;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Vase8";
  local_34 = 0x3f;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Vase9";
  local_34 = 0x40;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  local_34 = 0x41;
  pwVar9 = L"Campfire";
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Tent";
  local_34 = 0x42;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"BeachUmbrella";
  local_34 = 0x43;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"BeachTowel";
  local_34 = 0x44;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"SleepingMat";
  local_34 = 0x45;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Furnace";
  local_34 = 0x47;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Anvil";
  local_34 = 0x48;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"SpinningWheel";
  local_34 = 0x49;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"Loom";
  local_34 = 0x4a;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"SawBench";
  local_34 = 0x4b;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  local_34 = 0x4c;
  pwVar9 = L"Workbench";
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"CustomizationBench";
  local_34 = 0x4d;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"SkillAbility1";
  local_34 = 6;
  World_map_find_or_insert_int(&local_34);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"SkillAbility2";
  local_5c = (undefined4 *)0x7;
  World_map_find_or_insert_int(&local_5c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"SkillAbility3";
  local_5c = (undefined4 *)0x8;
  World_map_find_or_insert_int(&local_5c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"SkillAbility4";
  local_5c = (undefined4 *)0x9;
  World_map_find_or_insert_int(&local_5c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"SkillAbility5";
  local_5c = (undefined4 *)0xa;
  World_map_find_or_insert_int(&local_5c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"SkillPetTaming";
  local_5c = (undefined4 *)0x0;
  World_map_find_or_insert_int(&local_5c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"SkillPetRiding";
  local_5c = (undefined4 *)0x1;
  World_map_find_or_insert_int(&local_5c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"SkillClimbing";
  local_5c = (undefined4 *)0x2;
  World_map_find_or_insert_int(&local_5c);
  u16string_assignFromWide(pwVar9);
  local_5c = (undefined4 *)0x3;
  pwVar9 = L"SkillHangGliding";
  World_map_find_or_insert_int(&local_5c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"SkillSwimming";
  local_5c = (undefined4 *)0x4;
  World_map_find_or_insert_int(&local_5c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"SkillBoatDriving";
  local_5c = (undefined4 *)0x5;
  World_map_find_or_insert_int(&local_5c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"AbilitySmash";
  local_5c = (undefined4 *)0x36;
  World_map_find_or_insert_int(&local_5c);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"AbilityCyclone";
  local_58 = (undefined4 *)0x56;
  World_map_find_or_insert_int(&local_58);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"AbilityBulwark";
  local_58 = (undefined4 *)0x65;
  World_map_find_or_insert_int(&local_58);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"AbilityWarFrenzy";
  local_58 = (undefined4 *)0x66;
  World_map_find_or_insert_int(&local_58);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"AbilityRangerKick";
  local_58 = (undefined4 *)0x15;
  World_map_find_or_insert_int(&local_58);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"AbilityRetreat";
  local_58 = (undefined4 *)0x32;
  World_map_find_or_insert_int(&local_58);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"AbilityAim";
  local_58 = (undefined4 *)0x63;
  World_map_find_or_insert_int(&local_58);
  u16string_assignFromWide(pwVar9);
  local_58 = (undefined4 *)0x64;
  pwVar9 = L"AbilitySwiftness";
  World_map_find_or_insert_int(&local_58);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"AbilityFireExplosion";
  local_58 = (undefined4 *)0x58;
  World_map_find_or_insert_int(&local_58);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"AbilityManaShield";
  local_58 = (undefined4 *)0x67;
  World_map_find_or_insert_int(&local_58);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"AbilityTeleport";
  local_58 = (undefined4 *)0x31;
  World_map_find_or_insert_int(&local_58);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"AbilityHealingStream";
  local_58 = (undefined4 *)0x22;
  World_map_find_or_insert_int(&local_58);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"AbilityIntercept";
  local_58 = (undefined4 *)0x30;
  World_map_find_or_insert_int(&local_58);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"AbilityShuriken";
  local_58 = (undefined4 *)0x60;
  World_map_find_or_insert_int(&local_58);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"AbilityCamouflage";
  local_58 = (undefined4 *)0x61;
  World_map_find_or_insert_int(&local_58);
  u16string_assignFromWide(pwVar9);
  pwVar9 = L"AbilitySneak";
  local_58 = (undefined4 *)0x4f;
  World_map_find_or_insert_int(&local_58);
  u16string_assignFromWide(pwVar9);
  local_30 = (undefined4 *)0x0;
  local_58 = (undefined4 *)0x1;
  local_5c = (undefined4 *)0x2;
  local_34 = 3;
  local_44 = 4;
  local_90 = 6;
  local_98 = 0xb;
  local_8c = 0xc;
  local_94 = 7;
  local_9c = 8;
  local_60 = 0xd;
  local_38 = 0xf;
  do {
    selfBase = local_30;
    uVar10 = 0;
    obj = pair_assign_2dword(local_138,&local_58,&local_30,0);
    Pair_Copy2(obj,uVar10);
    pwVar9 = L"Village";
    World_MapInsertChunk(local_88);
    u16string_assignFromWide(pwVar9);
    uVar10 = 0;
    obj = pair_assign_2dword(local_f0,&local_5c,&local_30,0);
    Pair_Copy2(obj,uVar10);
    pwVar9 = L"Mountain";
    World_MapInsertChunk(local_a4);
    u16string_assignFromWide(pwVar9);
    uVar10 = 0;
    obj = pair_assign_2dword(local_100,&local_34,&local_30,0);
    Pair_Copy2(obj,uVar10);
    pwVar9 = L"Forest";
    World_MapInsertChunk(local_b4);
    u16string_assignFromWide(pwVar9);
    uVar10 = 0;
    obj = pair_assign_2dword(local_120,&local_44,&local_30,0);
    Pair_Copy2(obj,uVar10);
    pwVar9 = L"Lake";
    World_MapInsertChunk(local_e8);
    u16string_assignFromWide(pwVar9);
    uVar10 = 0;
    obj = pair_assign_2dword(local_110,&local_90,&local_30,0);
    Pair_Copy2(obj,uVar10);
    pwVar9 = L"Canyon";
    World_MapInsertChunk(local_d4);
    u16string_assignFromWide(pwVar9);
    uVar10 = 0;
    obj = pair_assign_2dword(local_130,&local_98,&local_30,0);
    Pair_Copy2(obj,uVar10);
    pwVar9 = L"Rock";
    World_MapInsertChunk(local_c4);
    u16string_assignFromWide(pwVar9);
    uVar10 = 0;
    obj = pair_assign_2dword(local_f8,&local_8c,&local_30,0);
    Pair_Copy2(obj,uVar10);
    pwVar9 = L"Tree";
    World_MapInsertChunk(local_e0);
    u16string_assignFromWide(pwVar9);
    uVar10 = 0;
    obj = pair_assign_2dword(local_108,&local_94,&local_30,0);
    Pair_Copy2(obj,uVar10);
    pwVar9 = L"Valley";
    World_MapInsertChunk(local_ac);
    u16string_assignFromWide(pwVar9);
    uVar10 = 0;
    obj = pair_assign_2dword(local_118,&local_9c,&local_30,0);
    Pair_Copy2(obj,uVar10);
    pwVar9 = L"Crater";
    World_MapInsertChunk(local_bc);
    u16string_assignFromWide(pwVar9);
    uVar10 = 0;
    obj = pair_assign_2dword(local_128,&local_60,&local_30,0);
    Pair_Copy2(obj,uVar10);
    pwVar9 = L"Peak";
    World_MapInsertChunk(local_cc);
    u16string_assignFromWide(pwVar9);
    uVar10 = 0;
    obj = pair_assign_2dword(&local_1c,&local_38,&local_30);
    Pair_Copy2(obj,uVar10);
    pwVar9 = L"Island";
    World_MapInsertChunk(local_50);
    u16string_assignFromWide(pwVar9);
    local_30 = (undefined4 *)((int)selfBase + 1);
  } while ((int)local_30 < 10);
  uVar10 = 0;
  local_38 = 0;
  local_60 = 5;
  obj = pair_assign_2dword(&local_1c,&local_60,&local_38,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Ruins";
  World_MapInsertChunk(local_50);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_38 = 1;
  local_60 = 5;
  obj = pair_assign_2dword(&local_1c,&local_60,&local_38,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Ruins";
  World_MapInsertChunk(local_50);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_38 = 2;
  local_60 = 5;
  obj = pair_assign_2dword(&local_1c,&local_60,&local_38,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Ruins";
  World_MapInsertChunk(local_50);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_38 = 3;
  local_60 = 5;
  obj = pair_assign_2dword(&local_1c,&local_60,&local_38,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Ruins";
  World_MapInsertChunk(local_50);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_38 = 4;
  local_60 = 5;
  obj = pair_assign_2dword(&local_1c,&local_60,&local_38,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Gravesite";
  World_MapInsertChunk(local_50);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_38 = 0;
  local_60 = 0xe;
  obj = pair_assign_2dword(&local_1c,&local_60,&local_38,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Castle";
  World_MapInsertChunk(local_50);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_38 = 1;
  local_60 = 0xe;
  obj = pair_assign_2dword(&local_1c,&local_60,&local_38,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Ruins";
  World_MapInsertChunk(local_50);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_38 = 2;
  local_60 = 0xe;
  obj = pair_assign_2dword(&local_1c,&local_60,&local_38,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Catacombs";
  World_MapInsertChunk(local_50);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_38 = 3;
  local_60 = 0xe;
  obj = pair_assign_2dword(&local_1c,&local_60,&local_38,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Palace";
  World_MapInsertChunk(local_50);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_38 = 4;
  local_60 = 0xe;
  obj = pair_assign_2dword(&local_1c,&local_60,&local_38,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Temple";
  World_MapInsertChunk(local_50);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_38 = 5;
  local_60 = 0xe;
  obj = pair_assign_2dword(&local_1c,&local_60,&local_38,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Pyramid";
  World_MapInsertChunk(local_50);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_38 = 0;
  local_60 = 9;
  obj = pair_assign_2dword(&local_1c,&local_60,&local_38,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Cave";
  World_MapInsertChunk(local_50);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_38 = 0;
  local_60 = 10;
  obj = pair_assign_2dword(&local_1c,&local_60,&local_38,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Portal";
  World_MapInsertChunk(local_50);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_38 = 1;
  local_60 = 1;
  obj = pair_assign_2dword(&local_1c,&local_60,&local_38,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Trade Quarter";
  World_MapInsertChunk(local_50);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_38 = 2;
  local_60 = 1;
  obj = pair_assign_2dword(&local_1c,&local_60,&local_38);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Crafting Quarter";
  World_MapInsertChunk(local_50);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_38 = 3;
  local_60 = 1;
  obj = pair_assign_2dword(&local_1c,&local_60,&local_38,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Class Quarter";
  World_MapInsertChunk(local_50);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_38 = 4;
  local_60 = 1;
  obj = pair_assign_2dword(&local_1c,&local_60,&local_38,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Pet Quarter";
  World_MapInsertChunk(local_50);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_38 = 0;
  local_60 = 4;
  obj = pair_assign_2dword(&local_1c,&local_60,&local_38,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Portal";
  World_MapInsertChunk(local_50);
  u16string_assignFromWide(pwVar9);
  uVar10 = 0;
  local_38 = 0;
  local_60 = 5;
  obj = pair_assign_2dword(&local_1c,&local_60,&local_38,0);
  Pair_Copy2(obj,uVar10);
  pwVar9 = L"Palace";
  World_MapInsertChunk(local_50);
  u16string_assignFromWide(pwVar9);
  deref_frontValue(&local_30);
  obj = store_object_ref(&local_40);
  cVar1 = operator_ne_int(obj);
  while (cVar1 != '\0') {
    selfBase = (undefined4 *)iterator_at_0x10();
    puVar4 = (undefined4 *)std_map_getOrInsertByKey(selfBase + 1);
    *puVar4 = *selfBase;
    iterator_deref_advance(&local_38,0);
    obj = store_object_ref(&local_40);
    cVar1 = operator_ne_int(obj);
  }
  deref_frontValue(&local_30);
  obj = store_object_ref(&local_40);
  cVar1 = operator_ne_int(obj);
  while (cVar1 != '\0') {
    selfBase = (undefined4 *)iterator_at_0x10();
    puVar4 = (undefined4 *)std_map_getOrInsertByKey(selfBase + 1);
    *puVar4 = *selfBase;
    iterator_deref_advance(&local_38,0);
    obj = store_object_ref(&local_40);
    cVar1 = operator_ne_int(obj);
  }
  deref_frontValue(&local_30);
  obj = store_object_ref(&local_40);
  cVar1 = operator_ne_int(obj);
  selfBase = local_6c;
  while (cVar1 != '\0') {
    local_6c = selfBase;
    iVar7 = iterator_at_0x10();
    World_MapInsertKeyed(iVar7 + 8);
    vec2_copy(iVar7);
    iterator_deref_advance(&local_38,0);
    obj = store_object_ref(&local_40);
    cVar1 = operator_ne_int(obj);
    selfBase = local_6c;
  }
  iVar7 = 0x400;
  puVar4 = selfBase + 0x10002f;
  do {
    iVar6 = 0x400;
    do {
      puVar4[-0x100000] = 0;
      *puVar4 = 0;
      puVar4 = puVar4 + 1;
      iVar6 = iVar6 + -1;
    } while (iVar6 != 0);
    iVar7 = iVar7 + -1;
  } while (iVar7 != 0);
  InitializeCriticalSectionAndSpinCount((LPCRITICAL_SECTION)(selfBase + 0x200030),0x80000400);
  InitializeCriticalSectionAndSpinCount((LPCRITICAL_SECTION)(selfBase + 0x200036),0x80000400);
  local_40 = operator_new(0x60);
  local_8._0_1_ = 0x14;
  if (local_40 == (undefined4 *)0x0) {
    local_54 = (undefined4 *)0x0;
  }
  else {
    local_54 = (undefined4 *)Sprite::ctor_0(local_68,0);
  }
  local_8._0_1_ = 0x12;
  local_40 = (undefined4 *)0x0;
  puVar4 = (undefined4 *)rbtree_findOrInsert_intKey(&local_40);
  *puVar4 = local_54;
  string_assignCStr("framework-floor-wood.cub");
  local_8._0_1_ = 0x15;
  local_40 = (undefined4 *)0x0;
  rbtree_findOrInsert_intKey(&local_40);
  VoxelModel_load_from_file_or_buffer(local_2c,0,1);
  local_8._0_1_ = 0x12;
  string_dtor();
  local_40 = operator_new(0x60);
  local_8._0_1_ = 0x16;
  if (local_40 == (undefined4 *)0x0) {
    local_54 = (undefined4 *)0x0;
  }
  else {
    local_54 = (undefined4 *)Sprite::ctor_0(local_68,0);
  }
  local_8._0_1_ = 0x12;
  local_40 = (undefined4 *)0x1;
  puVar4 = (undefined4 *)rbtree_findOrInsert_intKey(&local_40);
  *puVar4 = local_54;
  string_assignCStr("framework-wall-window.cub");
  local_8._0_1_ = 0x17;
  local_40 = (undefined4 *)0x1;
  rbtree_findOrInsert_intKey(&local_40);
  VoxelModel_load_from_file_or_buffer(local_2c,0,1);
  local_8._0_1_ = 0x12;
  string_dtor();
  local_40 = operator_new(0x60);
  local_8._0_1_ = 0x18;
  if (local_40 == (undefined4 *)0x0) {
    local_54 = (undefined4 *)0x0;
  }
  else {
    local_54 = (undefined4 *)Sprite::ctor_0(local_68,0);
  }
  local_8._0_1_ = 0x12;
  local_40 = (undefined4 *)0x2;
  puVar4 = (undefined4 *)rbtree_findOrInsert_intKey(&local_40);
  *puVar4 = local_54;
  string_assignCStr("framework-wall-door.cub");
  local_8._0_1_ = 0x19;
  local_40 = (undefined4 *)0x2;
  rbtree_findOrInsert_intKey(&local_40);
  VoxelModel_load_from_file_or_buffer(local_2c,0,1);
  local_8._0_1_ = 0x12;
  string_dtor();
  local_40 = operator_new(0x60);
  local_8._0_1_ = 0x1a;
  if (local_40 == (undefined4 *)0x0) {
    local_54 = (undefined4 *)0x0;
  }
  else {
    local_54 = (undefined4 *)Sprite::ctor_0(local_68,0);
  }
  local_8._0_1_ = 0x12;
  local_40 = (undefined4 *)0x3;
  puVar4 = (undefined4 *)rbtree_findOrInsert_intKey(&local_40);
  *puVar4 = local_54;
  string_assignCStr("framework-roof1.cub");
  local_8._0_1_ = 0x1b;
  local_40 = (undefined4 *)0x3;
  rbtree_findOrInsert_intKey(&local_40);
  VoxelModel_load_from_file_or_buffer(local_2c,0,1);
  local_8._0_1_ = 0x12;
  string_dtor();
  local_40 = operator_new(0x60);
  local_8._0_1_ = 0x1c;
  if (local_40 == (undefined4 *)0x0) {
    local_54 = (undefined4 *)0x0;
  }
  else {
    local_54 = (undefined4 *)Sprite::ctor_0(local_68,0);
  }
  local_8._0_1_ = 0x12;
  local_40 = (undefined4 *)0x4;
  puVar4 = (undefined4 *)rbtree_findOrInsert_intKey(&local_40);
  *puVar4 = local_54;
  string_assignCStr("framework-entrance.cub");
  local_8._0_1_ = 0x1d;
  local_40 = (undefined4 *)0x4;
  rbtree_findOrInsert_intKey(&local_40);
  VoxelModel_load_from_file_or_buffer(local_2c,0,1);
  local_8._0_1_ = 0x12;
  string_dtor();
  local_40 = operator_new(0x60);
  local_8._0_1_ = 0x1e;
  if (local_40 == (undefined4 *)0x0) {
    local_54 = (undefined4 *)0x0;
  }
  else {
    local_54 = (undefined4 *)Sprite::ctor_0(local_68,0);
  }
  local_8._0_1_ = 0x12;
  local_40 = (undefined4 *)0x5;
  puVar4 = (undefined4 *)rbtree_findOrInsert_intKey(&local_40);
  *puVar4 = local_54;
  string_assignCStr("framework-wall.cub");
  local_8._0_1_ = 0x1f;
  local_40 = (undefined4 *)0x5;
  rbtree_findOrInsert_intKey(&local_40);
  VoxelModel_load_from_file_or_buffer(local_2c,0,1);
  local_8._0_1_ = 0x12;
  string_dtor();
  local_40 = operator_new(0x60);
  local_8._0_1_ = 0x20;
  if (local_40 == (undefined4 *)0x0) {
    local_54 = (undefined4 *)0x0;
  }
  else {
    local_54 = (undefined4 *)Sprite::ctor_0(local_68,0);
  }
  local_8._0_1_ = 0x12;
  local_40 = (undefined4 *)0x6;
  puVar4 = (undefined4 *)rbtree_findOrInsert_intKey(&local_40);
  *puVar4 = local_54;
  string_assignCStr("framework-roof2.cub");
  local_8._0_1_ = 0x21;
  local_40 = (undefined4 *)0x6;
  rbtree_findOrInsert_intKey(&local_40);
  VoxelModel_load_from_file_or_buffer(local_2c,0,1);
  local_8._0_1_ = 0x12;
  string_dtor();
  local_40 = operator_new(0x60);
  local_8._0_1_ = 0x22;
  if (local_40 == (undefined4 *)0x0) {
    local_54 = (undefined4 *)0x0;
  }
  else {
    local_54 = (undefined4 *)Sprite::ctor_0(local_68,0);
  }
  local_8._0_1_ = 0x12;
  local_40 = (undefined4 *)0x7;
  puVar4 = (undefined4 *)rbtree_findOrInsert_intKey(&local_40);
  *puVar4 = local_54;
  string_assignCStr("framework-roof3.cub");
  local_8._0_1_ = 0x23;
  local_40 = (undefined4 *)0x7;
  rbtree_findOrInsert_intKey(&local_40);
  VoxelModel_load_from_file_or_buffer(local_2c,0,1);
  local_8._0_1_ = 0x12;
  string_dtor();
  local_40 = operator_new(0x60);
  local_8._0_1_ = 0x24;
  if (local_40 == (undefined4 *)0x0) {
    local_54 = (undefined4 *)0x0;
  }
  else {
    local_54 = (undefined4 *)Sprite::ctor_0(local_68,0);
  }
  local_8._0_1_ = 0x12;
  local_40 = (undefined4 *)0x8;
  puVar4 = (undefined4 *)rbtree_findOrInsert_intKey(&local_40);
  *puVar4 = local_54;
  string_assignCStr("framework-wall-balcony.cub");
  local_8._0_1_ = 0x25;
  local_40 = (undefined4 *)0x8;
  rbtree_findOrInsert_intKey(&local_40);
  VoxelModel_load_from_file_or_buffer(local_2c,0,1);
  local_8._0_1_ = 0x12;
  string_dtor();
  local_40 = operator_new(0x60);
  local_8._0_1_ = 0x26;
  if (local_40 == (undefined4 *)0x0) {
    local_54 = (undefined4 *)0x0;
  }
  else {
    local_54 = (undefined4 *)Sprite::ctor_0(local_68,0);
  }
  local_8._0_1_ = 0x12;
  local_40 = (undefined4 *)0x9;
  puVar4 = (undefined4 *)rbtree_findOrInsert_intKey(&local_40);
  *puVar4 = local_54;
  string_assignCStr("framework-roof-wall2.cub");
  local_8._0_1_ = 0x27;
  local_40 = (undefined4 *)0x9;
  rbtree_findOrInsert_intKey(&local_40);
  VoxelModel_load_from_file_or_buffer(local_2c,0,1);
  local_8._0_1_ = 0x12;
  string_dtor();
  local_40 = operator_new(0x60);
  local_8._0_1_ = 0x28;
  if (local_40 == (undefined4 *)0x0) {
    local_54 = (undefined4 *)0x0;
  }
  else {
    local_54 = (undefined4 *)Sprite::ctor_0(local_68,0);
  }
  local_8._0_1_ = 0x12;
  local_40 = (undefined4 *)0xa;
  puVar4 = (undefined4 *)rbtree_findOrInsert_intKey(&local_40);
  *puVar4 = local_54;
  string_assignCStr("building-stone-well.cub");
  local_8._0_1_ = 0x29;
  local_40 = (undefined4 *)0xa;
  rbtree_findOrInsert_intKey(&local_40);
  VoxelModel_load_from_file_or_buffer(local_2c,0,1);
  local_8._0_1_ = 0x12;
  string_dtor();
  local_40 = operator_new(0x60);
  local_8._0_1_ = 0x2a;
  if (local_40 == (undefined4 *)0x0) {
    local_54 = (undefined4 *)0x0;
  }
  else {
    local_54 = (undefined4 *)Sprite::ctor_0(local_68,0);
  }
  local_8._0_1_ = 0x12;
  local_40 = (undefined4 *)0xb;
  puVar4 = (undefined4 *)rbtree_findOrInsert_intKey(&local_40);
  *puVar4 = local_54;
  string_assignCStr("building-stone-stairs2.cub");
  local_8._0_1_ = 0x2b;
  local_40 = (undefined4 *)0xb;
  rbtree_findOrInsert_intKey(&local_40);
  VoxelModel_load_from_file_or_buffer(local_2c,0,1);
  local_8 = CONCAT31(local_8._1_3_,0x12);
  string_dtor();
  obj = setVec3(0x4b002080,0x4b002080,0x42c80000);
  vec3_copy(obj);
  obj = 0;
  pfVar5 = (float *)arrayElem_stride4(1);
  iVar7 = (int)*pfVar5;
  pfVar5 = (float *)arrayElem_stride4(0);
  fVar8 = (float10)terrain_generateColumnColor((int)*pfVar5,iVar7,obj);
  local_40 = (undefined4 *)(float)fVar8;
  pfVar5 = (float *)arrayElem_stride4(2);
  *pfVar5 = (float)local_40;
  obj = setPair_a(0x8000,0x8000);
  vec2_copy(obj);
  selfBase[0x2e] = 0;
  local_40 = (undefined4 *)0x23;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x57;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x3c;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x37;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x22;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x17;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x16;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x1e;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x21;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x62;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x19;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x35;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x43;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x66;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x68;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x69;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x13;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x28;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x25;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x26;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x27;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x5c;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x5d;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x38;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x5a;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x5b;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x32;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x1b;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x4b;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x1a;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x56;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x63;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x6a;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x3f;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x42;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x40;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x41;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x4a;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x24;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x39;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x3a;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x3b;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x3d;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x3e;
  std_vector_push_back_4byte(&local_40);
  local_40 = (undefined4 *)0x58;
  std_vector_push_back_4byte(&local_40);
  ExceptionList = local_10;
  __security_check_cookie(local_14 ^ (uint)&stack0xfffffffc);
  return;
}




/* cube::World::ctor_0 @ 00593ed0 */

void cube::World::ctor_0(void)

{
  undefined4 *puVar1;
  char isLeaf;
  int *node;
  undefined4 *puVar4;
  int *parent;
  uint uVar6;
  undefined4 *self;
  int *chunkCol;
  int iVar8;
  int iVar9;
  int chunkX;
  int iVar11;
  int colY;
  int colX;
  undefined4 *selfBase;
  void *local_10;
  undefined1 *puStack_c;
  undefined4 local_8;
  
  puStack_c = &LAB_006f1a5b;
  local_10 = ExceptionList;
  uVar6 = DAT_0076aa78 ^ (uint)&stack0xfffffffc;
  ExceptionList = &local_10;
  *self = vftable;
  chunkX = 0;
  local_8 = 0x12;
  colY = 0;
  chunkCol = self + 0x2f;
  colX = 0;
  selfBase = self;
  while( true ) {
    iVar9 = colX;
    if (*chunkCol != 0) {
      if (*(char *)(selfBase + 0x2d) == '\0') {
        iVar8 = 0x10018;
        do {
          iVar11 = 0x40;
          do {
            std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_13
                      (*(undefined4 *)(*chunkCol + iVar8));
            iVar9 = colX;
            chunkX = colY;
            iVar8 = iVar8 + 4;
            iVar11 = iVar11 + -1;
          } while (iVar11 != 0);
        } while (iVar8 < 0x14018);
        std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_17
                  (colY,colX);
      }
      if ((undefined4 *)*chunkCol != (undefined4 *)0x0) {
        (*(code *)**(undefined4 **)*chunkCol)(1,uVar6);
      }
    }
    if ((void *)chunkCol[0x100000] != (void *)0x0) break;
    colX = iVar9 + 1;
    chunkCol = chunkCol + 1;
    if (0x3ff < colX) {
      chunkX = chunkX + 1;
      colY = chunkX;
      if (0x3ff < chunkX) {
        chunkCol = *(int **)selfBase[1];
        if (chunkCol != (int *)selfBase[1]) {
          do {
            if ((undefined4 *)chunkCol[6] != (undefined4 *)0x0) {
              (*(code *)**(undefined4 **)chunkCol[6])(1);
            }
            if (*(char *)((int)chunkCol + 0xd) == '\0') {
              node = (int *)chunkCol[2];
              if (*(char *)((int)node + 0xd) == '\0') {
                isLeaf = *(char *)(*node + 0xd);
                chunkCol = node;
                node = (int *)*node;
                while (isLeaf == '\0') {
                  isLeaf = *(char *)(*node + 0xd);
                  chunkCol = node;
                  node = (int *)*node;
                }
              }
              else {
                isLeaf = *(char *)(chunkCol[1] + 0xd);
                parent = (int *)chunkCol[1];
                node = chunkCol;
                while ((chunkCol = parent, isLeaf == '\0' && (node == (int *)chunkCol[2]))) {
                  isLeaf = *(char *)(chunkCol[1] + 0xd);
                  parent = (int *)chunkCol[1];
                  node = chunkCol;
                }
              }
            }
          } while (chunkCol != (int *)selfBase[1]);
        }
        chunkCol = *(int **)selfBase[3];
        if (chunkCol != (int *)selfBase[3]) {
          do {
            colY = chunkCol[6];
            if (colY != 0) {
              puVar1 = (undefined4 *)(colY + 0x78);
              puVar4 = (undefined4 *)*puVar1;
              std_Tree_eraseRange(&colX,*puVar4,puVar4);
              operator_delete((void *)*puVar1);
            }
            if (*(char *)((int)chunkCol + 0xd) == '\0') {
              node = (int *)chunkCol[2];
              if (*(char *)((int)node + 0xd) == '\0') {
                isLeaf = *(char *)(*node + 0xd);
                chunkCol = node;
                node = (int *)*node;
                while (isLeaf == '\0') {
                  isLeaf = *(char *)(*node + 0xd);
                  chunkCol = node;
                  node = (int *)*node;
                }
              }
              else {
                isLeaf = *(char *)(chunkCol[1] + 0xd);
                parent = (int *)chunkCol[1];
                node = chunkCol;
                while ((chunkCol = parent, isLeaf == '\0' && (node == (int *)chunkCol[2]))) {
                  isLeaf = *(char *)(chunkCol[1] + 0xd);
                  parent = (int *)chunkCol[1];
                  node = chunkCol;
                }
              }
            }
            colY = 0;
          } while (chunkCol != (int *)selfBase[3]);
        }
        DeleteCriticalSection((LPCRITICAL_SECTION)(selfBase + 0x200030));
        DeleteCriticalSection((LPCRITICAL_SECTION)(selfBase + 0x200036));
        local_8 = CONCAT31(local_8._1_3_,0x11);
        std_Tree_eraseRange(&colY,*(undefined4 *)selfBase[0x200055],(undefined4 *)selfBase[0x200055]);
        operator_delete((void *)selfBase[0x200055]);
      }
      colX = 0;
    }
  }
  operator_delete((void *)chunkCol[0x100000]);
}




/* [AUDIT] proposed: World_MapInsertChunk  (confidence: low)
 * purpose: Game/STL: inserts a chunk record into a World map keyed by (x,y), building the node and rebalancing (SEH)
 * vars: self=map; local key x/y
 */
/* Global::World_MapInsertChunk @ 005943b0 */

void World_MapInsertChunk(int *coords)

{
  int existing;
  int node;
  int *in_ECX;
  undefined1 local_50 [4];
  void *local_4c [4];
  undefined4 local_3c;
  uint local_38;
  int x;
  int y;
  void *local_2c;
  undefined4 local_1c;
  uint local_18;
  uint local_14;
  void *local_10;
  undefined1 *puStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  puStack_c = &LAB_006f1a90;
  local_10 = ExceptionList;
  local_14 = DAT_0076aa78 ^ (uint)&stack0xfffffffc;
  ExceptionList = &local_10;
  existing = std_Tree_lower_bound_xy(coords);
  if (existing != *in_ECX) {
    if ((*(int *)(existing + 0x10) <= *coords) &&
       ((*(int *)(existing + 0x10) < *coords || (*(int *)(existing + 0x14) <= coords[1]))))
    goto LAB_00594490;
  }
  local_38 = 7;
  local_3c = 0;
  local_4c[0] = (void *)((uint)local_4c[0] & 0xffff0000);
  local_8 = 0;
  x = *coords;
  y = coords[1];
  u16string_moveConstruct(local_4c);
  local_8 = CONCAT31(local_8._1_3_,1);
  node = MapNode_CreateXY(&x);
  RBTree_InsertHintXY(local_50,existing,node + 0x10,node);
  if (7 < local_18) {
    operator_delete(local_2c);
  }
  local_18 = 7;
  local_1c = 0;
  local_2c = (void *)((uint)local_2c & 0xffff0000);
  if (7 < local_38) {
    operator_delete(local_4c[0]);
  }
LAB_00594490:
  ExceptionList = local_10;
  __security_check_cookie(local_14 ^ (uint)&stack0xfffffffc);
  return;
}




/* [AUDIT] proposed: World_MapInsertKeyed  (confidence: low)
 * purpose: Game/STL: inserts a keyed record into a World map using string/blob comparison (u16string_compare)
 * vars: in_ECX=map; coords=key src
 */
/* Global::World_MapInsertKeyed @ 005944c0 */

void World_MapInsertKeyed(int key)

{
  int existing;
  int *keyPtr;
  int cmp;
  int *in_ECX;
  undefined1 local_38 [4];
  void *local_34 [4];
  undefined4 local_24;
  uint local_20;
  undefined4 local_1c;
  undefined4 local_18;
  uint local_14;
  void *local_10;
  undefined1 *puStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  puStack_c = &LAB_006f1ac8;
  local_10 = ExceptionList;
  local_14 = DAT_0076aa78 ^ (uint)&stack0xfffffffc;
  ExceptionList = &local_10;
  existing = map_lower_bound_string(key);
  if (existing != *in_ECX) {
    keyPtr = (int *)(existing + 0x10);
    if (7 < *(uint *)(existing + 0x24)) {
      keyPtr = (int *)*keyPtr;
    }
    cmp = u16string_compare(0,*(undefined4 *)(key + 0x10),keyPtr,*(undefined4 *)(existing + 0x20));
    if (-1 < cmp) goto LAB_00594581;
  }
  local_20 = 7;
  local_24 = 0;
  local_34[0] = (void *)((uint)local_34[0] & 0xffff0000);
  u16string_replaceRange(key,0,0xffffffff);
  local_1c = 0;
  local_18 = 0;
  local_8 = 0;
  cmp = MapNode_CreateB(local_34);
  RBTree_InsertHintKeyed(local_38,existing,cmp + 0x10,cmp);
  if (7 < local_20) {
    operator_delete(local_34[0]);
  }
LAB_00594581:
  ExceptionList = local_10;
  __security_check_cookie(local_14 ^ (uint)&stack0xfffffffc);
  return;
}




/* cube::World::vfunc_0 @ 005946c0 */

void cube::World::vfunc_0(byte param_1)

{
  void *in_ECX;
  
  ctor_0();
  if ((param_1 & 1) != 0) {
    operator_delete(in_ECX);
  }
  return;
}




