// audit (server) — reconstructed declarations.
#ifndef SERVER__LIBRARY_AUDIT_H
#define SERVER__LIBRARY_AUDIT_H
#include "../include/cube_types.h"

undefined4 * __thiscall RBNode_allocSetKey(void *this,undefined4 *param_1);
undefined4 * __thiscall RBTree_insertNode(void *this,undefined4 *param_1,int *param_2,uint *param_3,int *param_4);
void __thiscall RBTree_insertRebalance(void *this,undefined4 *param_1,char param_2,uint *param_3,int *param_4);
uint * __thiscall RBTree_findOrInsert(void *this,uint *param_1);
void RBTree_destroyRec(int *param_1);
void __cdecl Vector_destroyTriples(undefined4 *param_1,undefined4 *param_2);
int * __thiscall RBTree_copyBeginThenInc(void *this,int *param_1);
int * __fastcall RBTree_iterIncrement(int *param_1);
void List_allocSentinel0x34(void);
void List_allocSentinel0x20(void);
void List_allocSentinel0x18(void);
void List_allocNode0x134(undefined4 *param_1,undefined4 *param_2);
void List_allocNode0x30(undefined4 *param_1,undefined4 *param_2);
void List_allocNode0x14(undefined4 *param_1,undefined4 *param_2);
void RBTree_destroyRecursive(int *param_1);
void __thiscall RBTree_eraseNode_plain(void *this,undefined4 *param_1,int *param_2);
void __thiscall vector_reallocate(void *this,uint param_1);
void __thiscall vector_growToFit(void *this,uint param_1);
void __thiscall vector_resizeZero(void *this,uint param_1);
undefined4 * __thiscall u16string_moveConstruct(void *this,undefined4 *param_1);
undefined2 * __thiscall U16String_ctorFromCStr(void *this,int *param_1);
void __thiscall U16String_assignFromCStr(void *this,int *param_1);
void __thiscall U16String_reallocGrow(void *this,uint param_1,int param_2);
int * __thiscall U16String_appendFill(void *this,uint param_1,undefined2 param_2);
int * __thiscall U16String_assignSubstr(void *this,int *param_1,uint param_2,uint param_3);
int * __thiscall U16String_assignPtrCount(void *this,int *param_1,uint param_2);
int * __thiscall U16String_erase(void *this,uint param_1,uint param_2);
uint __thiscall wstring_compareSubstr(void *this,uint param_1,uint param_2,ushort *param_3,uint param_4);
undefined2 * __thiscall wstring_ctorFromSubstr(void *this,undefined2 *param_1,uint param_2,uint param_3);
void MapNode_allocSentinel40(void);
void __thiscall RBTree_eraseNode(void *this,undefined4 *param_1,int *param_2);
undefined4 * __thiscall RBTree_buyNodeStr(void *this,int *param_1);
undefined4 * __thiscall RBTree_copyRec(void *this,undefined4 *param_1,undefined4 param_2,undefined4 param_3);
void __thiscall RBTree_insertRebalance_41a7b0(void *this,undefined4 *param_1,char param_2,undefined4 *param_3,int *param_4);
bool wstring_lessCompare(void *param_1,ushort *param_2);
undefined4 * __fastcall RBTree_buyNode40(undefined4 *param_1);
void list_emplaceCopy40(undefined4 *param_1,undefined4 *param_2,undefined8 *param_3);
void list_emplaceCopy24(undefined4 *param_1,undefined4 *param_2,undefined8 *param_3);
void __fastcall list_destroyWstrings(int *param_1);
undefined4 * __thiscall std_map_Speech_allocPairNode(void *this,int *param_1);
int std_list_Speech_makeStrNode(undefined4 *param_1,undefined4 *param_2,int *param_3);
undefined4 * __thiscall std_map_allocNode_intKeyStr(void *this,undefined4 *param_1);
undefined4 * __thiscall std_map_Speech_allocEntryNode(void *this,undefined4 *param_1);
undefined4 * __thiscall std_map_allocNode_str2(void *this,undefined4 *param_1);
void __thiscall std_map_copyAssign(void *this,int *param_1,undefined4 param_2);
undefined4 * __thiscall rbtree_cloneSubtree(void *this,undefined4 *param_1,undefined4 param_2,undefined4 param_3);
void __thiscall std_map_insertRebalance_str2(void *this,undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
void __thiscall std_map_insertRebalance_SpeechNode(void *this,undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
void __thiscall std_map_insertRebalance_variantC(void *this,undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
void __thiscall std_map_insertRebalance_QuestText(void *this,undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
undefined4 * __thiscall std_map_insertHint_intKey(void *this,undefined4 *param_1,int *param_2,int *param_3,int *param_4);
undefined4 * __thiscall std_map_insertHint_strKey(void *this,undefined4 *param_1,ushort *param_2,ushort *param_3,int *param_4);
undefined4 * __thiscall std_map_insertHint_strKey_Speech(void *this,undefined4 *param_1,ushort *param_2,ushort *param_3,int *param_4);
undefined4 * __thiscall std_map_insertHint_strKey_variantC(void *this,undefined4 *param_1,ushort *param_2,ushort *param_3,int *param_4);
undefined4 * __thiscall std_map_insertHint_strKey_QuestText(void *this,undefined4 *param_1,ushort *param_2,ushort *param_3,int *param_4);
void __thiscall std_map_insertLowerBound_intKey(void *this,undefined4 *param_1,char param_2,int *param_3,int *param_4);
void __thiscall std_map_insertLowerBound_strKey_Speech(void *this,undefined4 *param_1,undefined4 *param_2,ushort *param_3,int *param_4);
void __thiscall std_map_insertLowerBound_strKey_variantC(void *this,undefined4 *param_1,undefined4 *param_2,ushort *param_3,int *param_4);
void __thiscall std_map_insertLowerBound_strKey_QuestText(void *this,undefined4 *param_1,undefined4 *param_2,ushort *param_3,int *param_4);
void __thiscall std_list_appendCopy_strNodes(void *this,undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void __thiscall std_list_assignCopy_Speech(void *this,undefined4 *param_1,undefined4 *param_2);
facet * __cdecl std_use_facet_ctype_wchar(locale *param_1);
undefined4 * __thiscall std_list_copyCtor(void *this,int *param_1);
undefined4 * __thiscall std_list_copyCtor_strList(void *this,undefined4 *param_1);
bool __thiscall std_iterator_notEqual(void *this,int *param_1);
void __thiscall std_map_subscript_intKey(void *this,int *param_1);
void __thiscall std_map_insert_strToStr(void *this,ushort *param_1);
void __thiscall std_map_insert_strToStr_v2(void *this,ushort *param_1);
void std_map_makeHeader_0x2c(void);
void std_map_makeHeader_0x38(void);
undefined4 * __fastcall std_map_allocRawNode_0x2c(undefined4 *param_1);
undefined4 * __fastcall std_map_allocRawNode_0x38(undefined4 *param_1);
undefined4 * __fastcall std_map_allocRawNode_0x40(undefined4 *param_1);
void rbtree_destroyRecursive_strNode(int *param_1);
void * __thiscall rbtree_destroyRecursive_SpeechNode(void *this,int *param_1);
uint __thiscall rbtree_destroyRecursive_QuestText(undefined4 param_1,int *param_2);
void __thiscall std_strstreambuf_init(void *this,void *param_1,uint param_2,undefined4 param_3);
undefined4 * __thiscall std_map_lowerBound_strKey(void *this,ushort *param_1);
int __cdecl rbtree_max(int param_1);
int * __cdecl rbtree_min(int *param_1);
void __thiscall rbtree_rotateLeft(void *this,int *param_1);
void __fastcall std_list_clear(int *param_1);
undefined4 * __thiscall std_map_eraseRange_strNode(void *this,undefined4 *param_1,int *param_2,int *param_3);
void __thiscall std_map_eraseNode_strNode(void *this,undefined4 *param_1,int *param_2);
undefined4 * __thiscall std_map_eraseRange_SpeechNode(void *this,undefined4 *param_1,int *param_2,int *param_3);
void std_map_eraseNode_SpeechNode(undefined4 *param_1,int *param_2);
undefined4 * __thiscall std_map_eraseRange_QuestText(void *this,undefined4 *param_1,int *param_2,int *param_3);
void __thiscall std_map_eraseNode_QuestText(void *this,undefined4 *param_1,int *param_2);
int * __thiscall std_list_eraseRange(void *this,int *param_1,int *param_2,int *param_3);
void std_map_makeHeader_0x1c(void);
undefined4 __thiscall rbtree_destroyRecursive_SpriteNode(undefined4 param_1,int *param_2);
void __fastcall std_vector_free(undefined4 *param_1);
undefined4 * __thiscall std_map_eraseRange_SpriteNode(void *this,undefined4 *param_1,int *param_2,int *param_3);
void __thiscall std_map_eraseNode_SpriteNode(void *this,undefined4 *param_1,int *param_2);
void __cdecl sqlite3_close(int *param_1);
uint __cdecl sqlite3_exec(int param_1,byte *param_2,undefined *param_3,undefined4 param_4,int *param_5);
uint __cdecl sqlite3_overloadFunction(int param_1,byte *param_2,int param_3);
int __cdecl sqlite3_vfs_find(byte *param_1);
void __cdecl sqlite3_mutex_enter_ind(int param_1);
void __cdecl sqlite3_mutex_leave_ind(int param_1);
undefined4 __cdecl sqlite3_snprintf_guarded(byte *param_1);
void __cdecl sqlite3_vxprintf_toBuf(byte *param_1,double *param_2);
void __cdecl sqlite3_snprintf_impl(int param_1,undefined4 param_2,byte *param_3);
void __cdecl sqlite3_free(int param_1);
void __cdecl sqlite3_randomness(int param_1,undefined1 *param_2);
void __cdecl sqlite3_open(int *param_1,undefined4 *param_2);
void __cdecl sqlite3_log(undefined4 param_1,undefined4 param_2);
uint __cdecl sqlite3_errcode(int param_1);
void __cdecl sqlite3_prepare(int param_1,void *param_2,size_t param_3,undefined4 *param_4,int *param_5);
void __cdecl sqlite3_bind_text(int *param_1,int param_2,void *param_3,size_t param_4,undefined *param_5);
int __cdecl sqlite3_column_value(int *param_1,int param_2);
uint __cdecl sqlite3_step_469cb0(uint *param_1);
int __cdecl sqlite3_column_int(int *param_1,int param_2);
int __cdecl sqlite3_column_bytes(int *param_1,int param_2);
uint __cdecl sqlite3_clear_bindings_46aa30(int *param_1);
uint __cdecl sqlite3_reset(int *param_1);
uint __cdecl btree_accessPayload(int param_1,uint param_2,size_t param_3,void *param_4,int param_5);
uint __cdecl pager_setInAllSavepoints(int param_1,uint param_2);
uint __cdecl btree_moveToNext(int *param_1,int *param_2,uint *param_3,undefined4 *param_4,char param_5);
uint __cdecl btree_balanceCleanup(int *param_1);
/* WARNING: Removing unreachable block (ram,0x0046e41a) */ uint __cdecl btree_writeOverflow(int param_1,undefined4 *param_2,int param_3);
uint __cdecl sqlite3_bindValue(int *param_1,int param_2,void *param_3,size_t param_4,undefined *param_5,char param_6);
void __cdecl btree_closeCursor(int *param_1);
int __cdecl btree_getAndInitPage(int *param_1,uint param_2,int *param_3,int param_4);
undefined4 __cdecl btree_initPage(char *param_1);
void __cdecl btree_parseCellPtr(int param_1,uint param_2,uint *param_3);
void __cdecl btree_unlinkCursorOverflow(int param_1);
void __cdecl sqlite3_exprDelete(int param_1,undefined4 *param_2);
void __cdecl sqlite3_column_apiExit(int *param_1);
undefined * __cdecl sqlite3_columnMem(int *param_1,int param_2);
undefined4 __cdecl sqlite3_txnActive(int param_1);
uint __cdecl btree_copyPayload(void *param_1,void *param_2,size_t param_3,int param_4,undefined4 *param_5);
undefined4 __cdecl sqlite3_createCollation(int param_1,byte *param_2,byte param_3,int param_4,int param_5,int param_6);
undefined4 __cdecl btree_decodeFlags(int param_1,uint param_2);
char * __cdecl vdbe_displayP4(int param_1,char *param_2,int param_3);
int __cdecl vdbe_runVtabCommit(int param_1);
int * __cdecl sqlite3_findCollSeq(int param_1,byte *param_2,int param_3);
void __cdecl vdbe_freeP4(int param_1,undefined4 param_2,int *param_3);
void __cdecl pager_freeSavepointBitvec(int param_1);
void __cdecl vdbe_freeAuxRef(int param_1,int param_2);
void __cdecl btree_cacheCellSize(int param_1);
int __cdecl btree_getOverflowPage(int *param_1,undefined4 *param_2,int *param_3,undefined4 *param_4);
int __cdecl pager_hasHotJournal(int *param_1,uint *param_2);
uint __cdecl btree_clearDbPage(int *param_1,undefined4 *param_2,char *param_3);
void __cdecl pcache_pageInsert(int param_1,int *param_2,int *param_3);
longlong __cdecl pager_journalHdrOffset(int param_1);
uint __cdecl btree_readPage1(int *param_1);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ uint __cdecl sqlite3_mallocRaw(int param_1,int *param_2);
undefined4 __cdecl btree_putCellPtr(char *param_1,int param_2,undefined4 param_3,char param_4);
undefined8 __cdecl pager_pageToOffset(int param_1);
uint __cdecl sqlite3_openDatabase(int *param_1,undefined4 *param_2,uint param_3,byte *param_4);
undefined4 __cdecl vdbe_initPseudoCursor(int *param_1);
int __cdecl pager_walCheckpointCheck(int param_1);
int __cdecl pager_lockDbDefault(int param_1);
int __cdecl pager_lockDb(int param_1,int param_2);
void __cdecl pager_unlockAndRollback(int *param_1);
void __cdecl pager_endTransactionCheck(int *param_1);
int __cdecl pager_pageCount(int param_1,uint *param_2);
uint __cdecl pager_playbackSavepoint(undefined4 *param_1,uint *param_2);
int __cdecl pager_playbackAllPages(int param_1);
void __cdecl pager_syncJournal(int param_1);
int __cdecl pager_playbackOnePage(int param_1,int param_2);
void __cdecl pcache_releasePage(uint *param_1);
undefined4 __cdecl pager_unlockDb(int param_1,undefined4 param_2);
int __cdecl pager_writeDirtyList(int param_1,uint *param_2,uint param_3,int param_4);
int __cdecl pager_cksum(int param_1,int param_2);
int __cdecl pager_deleteMasterJournal(int *param_1,byte *param_2);
int __cdecl pager_endTransaction(int *param_1,int param_2);
uint __cdecl pager_error(int param_1,uint param_2);
uint __cdecl pager_incrChangeCounter(uint *param_1);
undefined4 __cdecl pager_getSavepointPtr(int param_1,int param_2);
int __cdecl pager_openJournal(int *param_1);
uint __cdecl pager_playback(uint *param_1,int param_2);
uint __cdecl pager_playbackOnePageJournal(undefined4 *param_1,uint *param_2,uint *param_3,int param_4,int param_5);
void __cdecl btree_invalidateAllCursors(int param_1);
/* WARNING: Removing unreachable block (ram,0x00485304) */ /* WARNING: Removing unreachable block (ram,0x00485331) */ int __cdecl pager_truncateImage(int param_1,uint param_2);
void __cdecl pcache_freePage(int param_1);
int __cdecl pager_lockWithRetry(int param_1,int param_2);
uint __cdecl pager_writePage(int param_1);
void __cdecl pager_writeChangeCounter(int param_1);
int __cdecl pager_commitPhaseOne(int *param_1,int param_2);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ undefined4 * __cdecl pcache_allocPage(int param_1);
int __cdecl pcache_freePageMem(undefined4 *param_1);
void __cdecl pcache_removeFromDirty(int param_1);
int __cdecl btree_readCellPtrByte(int *param_1,undefined4 *param_2,byte *param_3,undefined4 *param_4);
int __cdecl btree_ptrmapPageno(int param_1,uint param_2);
void __cdecl btree_ptrmapPut(int *param_1,uint param_2,char param_3,int param_4,uint *param_5);
int __cdecl pager_read32be(int *param_1,undefined4 param_2,undefined4 param_3,uint *param_4);
int __cdecl pager_readDbPage(int param_1);
void __cdecl pager_readJournalHeader(int param_1,int param_2,uint param_3,int param_4,uint *param_5,uint *param_6);
void __cdecl pager_readMasterJournal(int *param_1,undefined1 *param_2,uint param_3);
void __cdecl pager_freeSavepointArray(int param_1);
void __cdecl vdbe_releaseMemArray(int *param_1,int param_2);
void __cdecl btree_releasePage(int param_1);
uint __cdecl btree_updateOverflowCell(int *param_1,char *param_2,undefined4 param_3,uint param_4,uint param_5,int param_6);
undefined4 __cdecl btree_unrefSharedCache(int param_1);
void __cdecl sqlite3_logCallback(undefined4 param_1,byte *param_2,double *param_3);
uint __cdecl btree_saveCursorPages(uint param_1);
void __cdecl vdbe_commitAllBtrees(int *param_1);
uint __cdecl btree_clearCell(char *param_1);
void __cdecl pager_setSectorSize(int param_1);
undefined4 __cdecl sqlite3_setupLookaside(int param_1,undefined4 *param_2,uint param_3,int param_4);
uint __cdecl sqlite3_apiExit(int param_1,uint param_2);
void __cdecl sqlite3_autoExtensions(int param_1);
void __cdecl btree_writeOverflowCursors(int *param_1,undefined4 *param_2,int param_3);
undefined4 __cdecl btree_closeConnection(int *param_1);
undefined4 __cdecl btree_dropCursor(undefined4 *param_1);
uint __cdecl btree_rollback(undefined4 *param_1,char *param_2);
int __cdecl btree_commitPhaseTwo(int *param_1,int param_2);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ void __cdecl btree_enter(undefined4 *param_1);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ void __cdecl btree_enterAll(int param_1);
void __cdecl sqlite3BtreeLeave(int param_1);
void __cdecl sqlite3BtreeLeaveAll(int param_1);
void __cdecl sqlite3BtreeOpen(undefined *param_1,byte *param_2,int param_3,undefined4 *param_4,byte param_5, uint param_6);
uint __cdecl sqlite3BtreeCommitPhaseOne(int *param_1,uint param_2);
undefined4 __cdecl btreeCheckReadConflicts(undefined4 *param_1);
void __cdecl sqlite3BtreeTripAllCursors(undefined4 *param_1,undefined4 param_2);
undefined4 sqlite3CantopenError(void);
void __cdecl pcacheCleanupCursorSpace(int *param_1);
void __cdecl pcacheClearOverflowList(int param_1);
void __cdecl pcacheCompactPageArray(int param_1);
undefined4 sqlite3CorruptError(void);
int __cdecl sqlite3CreateFunc(int param_1,byte *param_2,int param_3,uint param_4,undefined4 param_5,int param_6, int param_7,int param_8,int *param_9);
void __cdecl sqlite3PageFree(int param_1,undefined4 *param_2);
undefined4 * __cdecl sqlite3PageMalloc(int param_1,int param_2);
undefined4 * __cdecl sqlite3PageRealloc(int param_1,undefined4 *param_2,int param_3);
undefined4 * __cdecl sqlite3PageStrdup(int param_1,char *param_2);
void __cdecl sqlite3DeleteTable(int param_1,undefined4 *param_2);
void __cdecl sqlite3SelectDelete(int param_1,undefined4 *param_2);
void __cdecl sqlite3ErrorWithMsg(int param_1,undefined4 param_2,byte *param_3);
void __cdecl sqlite3ExpirePreparedStatements(int param_1);
void __cdecl sqlite3ExprDelete(int param_1,undefined4 *param_2);
void __cdecl sqlite3ExprListDelete(int param_1,int *param_2);
int * __cdecl sqlite3FindDbFunction(int param_1,byte param_2,byte *param_3,int param_4);
short * __cdecl sqlite3FindFunction(int param_1,byte *param_2,size_t param_3,int param_4,byte param_5,char param_6);
void __cdecl sqlite3DeleteTableAux(int param_1,int param_2);
void __cdecl sqlite3HashInsertElement(int param_1,int param_2);
undefined4 __cdecl sqlite3Get4byte(undefined1 *param_1);
undefined4 __cdecl sqlite3GetVarint(byte *param_1,uint *param_2);
uint __cdecl sqlite3GetVarint32(byte *param_1,uint *param_2);
void __cdecl sqlite3PageFreeList(undefined4 *param_1);
undefined4 __cdecl sqlite3HashFind(uint *param_1,byte *param_2,int param_3);
uint __cdecl sqlite3HashInsert(uint *param_1,byte *param_2,uint param_3,uint param_4);
void __cdecl sqlite3IdListDelete(int param_1,int *param_2);
void __cdecl sqlite3Close(int *param_1);
uint __cdecl sqlite3LockAndPrepare(int param_1,void *param_2,size_t param_3,byte param_4,int param_5,undefined4 *param_6, int *param_7);
int __cdecl sqlite3Malloc(int param_1);
void __cdecl sqlite3MallocAlarm(undefined4 param_1);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ void __cdecl pcache1Initialize(undefined4 param_1);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ void sqlite3MutexInit(void);
undefined4 __cdecl sqlite3OsClose(int *param_1);
undefined4 __cdecl sqlite3OsCurrentTimeInt64(int *param_1,ulonglong *param_2);
void __cdecl sqlite3OsFileControl(int *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5);
void __cdecl sqlite3OsShmMap_or_v10(int *param_1,undefined4 param_2,undefined4 param_3);
void __cdecl sqlite3OsWrite(int *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5);
void __cdecl sqlite3PcacheBufferSetup(undefined4 *param_1,uint param_2,int param_3);
undefined4 __cdecl sqlite3PagerClose(uint *param_1);
uint __cdecl sqlite3PagerCommitPhaseOne(uint *param_1,char *param_2,int param_3);
void __cdecl pager_playback_or_reset(int *param_1);
uint __cdecl sqlite3PagerMovepage(undefined4 *param_1,undefined4 *param_2,int param_3,int param_4);
int __cdecl sqlite3PagerOpen(undefined *param_1,undefined4 *param_2,char *param_3,int param_4,byte param_5, uint param_6,uint param_7);
int __cdecl pager_write_dirty_or_openWal(int *param_1,undefined4 *param_2);
int __cdecl pagerReadFileheader(int param_1,size_t param_2,void *param_3);
uint __cdecl sqlite3PagerCommitPhaseTwo_or_sync(uint *param_1);
uint __cdecl sqlite3PagerReleaseSavepoints(undefined4 *param_1,int param_2,int param_3);
void __cdecl sqlite3PagerSetBusyhandler(int param_1,undefined4 param_2,undefined4 param_3);
int __cdecl sqlite3PagerSetPagesize(int param_1,uint *param_2,int param_3);
void __cdecl pager_playback_4a2980(uint *param_1);
int __cdecl pagerSyncHotJournal(int param_1);
void __cdecl sqlite3PagerUnrefNotNull(undefined4 *param_1);
uint __cdecl pagerPlaybackSavepoint(undefined4 *param_1);
undefined4 __cdecl sqlite3ParseUri(byte *param_1,int *param_2,uint *param_3,int *param_4,undefined4 *param_5, undefined4 *param_6);
void __cdecl pagerReleaseAllSavepoints_flush(undefined4 *param_1);
undefined1 * __cdecl pcacheSortDirtyList(int *param_1);
void __cdecl pcacheRelease_writeSubj(undefined4 *param_1);
int __cdecl sqlite3PcacheFetch(int *param_1,int param_2,int param_3,undefined4 *param_4);
void __cdecl pcacheMakeClean(undefined4 *param_1);
void __cdecl pcacheManageDirtyList_add(int param_1);
void __cdecl sqlite3PcacheMove(undefined4 *param_1,undefined4 param_2);
undefined4 __cdecl pagerFileSync(int param_1);
void __cdecl sqlite3PcacheRelease(undefined4 *param_1);
void __cdecl pcacheTruncate(undefined4 *param_1,uint param_2);
uint __cdecl sqlite3Prepare(int param_1,void *param_2,size_t param_3,byte param_4,int param_5,undefined4 *param_6, int *param_7);
void __cdecl sqlite3Put4byte(undefined1 *param_1,undefined4 param_2);
int __cdecl sqlite3Realloc(int param_1,int param_2);
void sqlite3RegisterBuiltinFunctions(void);
void __cdecl sqlite3ExprListClearList(undefined4 *param_1);
undefined4 __cdecl sqlite3SafetyCheckOk(int param_1);
void __cdecl sqlite3SchemaClear(int param_1);
void * __cdecl sqlite3SchemaGet(int param_1,undefined4 *param_2);
void __cdecl pcache1Free(undefined4 *param_1);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ undefined4 * __cdecl pcache1Alloc(int param_1);
void __cdecl sqlite3WindowListDelete_or_Cte(int param_1,undefined4 *param_2);
void __cdecl sqlite3SetString(int *param_1,int param_2,byte *param_3);
void __cdecl sqlite3SrcListDelete(int param_1,short *param_2);
void __cdecl sqlite3StatusUp(int param_1,int param_2);
void __cdecl sqlite3StatusSet(int param_1,int param_2);
uint __cdecl sqlite3Step(uint *param_1);
void __cdecl sqlite3StrAccumAppend(int *param_1,char *param_2,size_t param_3);
int __cdecl sqlite3StrAccumFinish(int *param_1);
void __cdecl sqlite3StrAccumReset(int *param_1);
uint __cdecl sqlite3Strlen30(char *param_1);
undefined4 __thiscall sqlite3VdbeFrameRestore(void *this,int param_1,int *param_2);
void __cdecl sqlite3VXPrintf_toAccum(int param_1,byte *param_2,double *param_3);
/* WARNING: Removing unreachable block (ram,0x004ad973) */ void __cdecl sqlite3VXPrintf(int *param_1,int param_2,byte *param_3,double *param_4);
void __cdecl sqlite3VdbeMemRelease_free(int *param_1);
void __cdecl sqlite3ValueNew(int param_1);
int __cdecl sqlite3ValueApplyAffinity(int *param_1,byte param_2);
undefined4 __cdecl sqlite3VdbeChangeEncoding(int *param_1,uint param_2);
void __cdecl sqlite3VdbeFreeCursorsAndProgram(int param_1,int param_2);
void __cdecl sqlite3VdbeDeleteAuxData(int *param_1,uint param_2);
uint __cdecl sqlite3VdbeDelete(int *param_1);
undefined4 __cdecl sqlite3VdbeList(int *param_1);
undefined4 __cdecl sqlite3VdbeMemExpandBlob(int *param_1);
undefined4 __cdecl sqlite3VdbeMemFinalize(int *param_1,int param_2);
undefined4 __cdecl sqlite3VdbeMemGrow(int *param_1,int param_2,int param_3);
int __cdecl sqlite3VdbeMemHandleBom(int *param_1);
undefined4 __cdecl sqlite3VdbeMemMakeWriteable(int *param_1);
undefined4 __cdecl sqlite3VdbeMemNulTerminate(int *param_1);
void __cdecl sqlite3VdbeMemRelease(int *param_1);
void __cdecl sqlite3VdbeMemReleaseExternal(int *param_1);
void __cdecl sqlite3VdbeMemClearExternAndSetNull(int param_1);
undefined4 __cdecl sqlite3VdbeMemSetStr(int *param_1,void *param_2,size_t param_3,char param_4,undefined *param_5);
undefined4 __cdecl sqlite3VdbeMemStringify(int *param_1,int param_2);
undefined4 __cdecl sqlite3VdbeMemTranslate(int *param_1,char param_2);
uint __cdecl sqlite3VdbeHalt(int *param_1);
void __cdecl sqlite3VdbeResizeMemArray(int *param_1,int param_2);
int __cdecl sqlite3VdbeTransferError(int *param_1);
void __cdecl sqlite3AggInfoDelete_or_columns(int param_1,int param_2);
void __cdecl sqlite3KeyInfoUnref(int *param_1);
void __cdecl sqlite3VtabUnlockList(int param_1);
int __cdecl walTryBeginRead(int *param_1,undefined4 *param_2);
int __cdecl sqlite3WalFrames(int param_1,int param_2,undefined *param_3,undefined4 param_4,int param_5,int param_6, undefined4 param_7,undefined4 *param_8,undefined4 *param_9);
int __cdecl sqlite3WalClose(int *param_1,int param_2,int param_3,undefined4 param_4);
void __cdecl walIteratorFree_or_restart(int param_1);
/* WARNING: Removing unreachable block (ram,0x004babbb) */ /* WARNING: Removing unreachable block (ram,0x004baad0) */ void __cdecl walWriteFrames_inner(int *param_1,uint param_2,uint *param_3,int param_4,int param_5,uint param_6);
int __cdecl sqlite3WalOpen(int param_1,int param_2,int param_3,int param_4,int param_5,int param_6, undefined4 *param_7);
int __cdecl walFindFrame(int param_1,int param_2,undefined4 *param_3,int param_4,undefined4 param_5);
int __cdecl sqlite3WalUndo_or_iterate(int param_1,undefined *param_2,undefined4 param_3);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ undefined4 __cdecl sqlite3_config(undefined4 param_1,undefined8 *param_2,undefined4 param_3,undefined4 param_4);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ int sqlite3_initialize(void);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ undefined4 pcache1_init_systeminfo(void);
void __cdecl sqlite3WithDelete_or_AggFree(int param_1,int param_2);
uint __cdecl sqlite3StrHash_wal(byte *param_1,int param_2);
undefined4 __cdecl walDirtyPagesPresent_or_bitTest(int param_1);
void __cdecl pager_incr_changecounter(uint param_1,int param_2);
undefined4 __cdecl vdbeUnbind(int *param_1,int param_2);
void __cdecl pcache1RemoveFromList(int param_1);
int * __cdecl sqlite3VtabMoveToList(int param_1,int param_2);
int __cdecl walBusyLock(int param_1,undefined *param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5 );
int __cdecl walCheckpoint(int param_1,int param_2,undefined *param_3,undefined4 param_4,int param_5, undefined4 param_6);
void __cdecl walChecksumBytes(int param_1,uint *param_2,int param_3,int *param_4,int *param_5);
void __cdecl walCleanupHash(int param_1);
undefined4 __cdecl walDecodeFrame(int param_1,int *param_2,undefined4 *param_3,uint *param_4,uint *param_5);
void __cdecl walEncodeFrame(int param_1,undefined4 param_2,undefined4 param_3,uint *param_4,uint *param_5);
int __cdecl walIndexAppend(int param_1,void *param_2,int param_3);
void __cdecl walIndexClose(int param_1);
int __cdecl walIndexPage(int param_1,int param_2,undefined4 *param_3);
int __cdecl walIndexReadHdr(int param_1,undefined4 *param_2);
void __cdecl walIndexRecover(int param_1);
void __cdecl walIndexTryHdr(int param_1,undefined4 *param_2);
void __cdecl walIndexWriteHdr(int param_1);
int __cdecl walIteratorInit(int param_1,undefined4 *param_2);
bool __cdecl walIteratorNext(uint *param_1,uint *param_2,int *param_3);
void __cdecl sqlite3WalLimitSize(int param_1,uint param_2,int param_3);
void __cdecl walMerge(int param_1,void *param_2,int param_3,int *param_4,int *param_5,void *param_6);
void __cdecl walMergesort(int param_1,void *param_2,void *param_3,uint *param_4);
void __cdecl walRestartHdr(int *param_1);
int __cdecl walTryBeginRead_4c1ad0(int *param_1,undefined4 *param_2,int param_3,int param_4);
void __cdecl walUnlockShared(int param_1,undefined4 param_2);
void __cdecl walWriteToLog(int param_1,int param_2,uint param_3,uint param_4,int param_5);
int __cdecl pagerWriteWalHeader(uint param_1);
int __cdecl walWriteWalFrames_journal(int param_1,char *param_2);
int __cdecl pagerWalSyncTruncate(int param_1,int param_2);
void __cdecl std_vector_Ucopy_4c5c10(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
undefined4 * __thiscall std_vector_copy_ctor(void *this,int *param_1);
undefined4 __thiscall std_vector_Reserve_4c5d90(void *this,uint param_1);
undefined4 * __thiscall std_pair_ctor2(void *this,undefined4 *param_1,undefined4 *param_2);
undefined4 * __thiscall std_pair_copy_ctor(void *this,undefined4 *param_1);
undefined4 * __thiscall std_Tree_Buynode_int2(void *this,undefined4 *param_1);
undefined4 * __thiscall std_Tree_Buynode_str(void *this,undefined4 *param_1);
undefined4 * __thiscall std_Tree_Buynode_str2(void *this,undefined4 *param_1);
void __cdecl std_vector_of_vector_dtor(undefined4 *param_1,undefined4 *param_2);
void __thiscall std_Tree_Rebalance_int(void *this,undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
void __thiscall std_Tree_Rebalance_strkey(void *this,undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
void __thiscall std_Tree_Rebalance_strkey2(void *this,undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
void __thiscall std_Tree_Rebalance_strkey3(void *this,undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
void __thiscall std_Tree_Rebalance_buynode(void *this,undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 *param_4);
undefined4 * __thiscall std_Tree_Insert_hint_int(void *this,undefined4 *param_1,int *param_2,int *param_3,int *param_4);
undefined4 * __thiscall std_Tree_Insert_hint_pair(void *this,undefined4 *param_1,int *param_2,int *param_3,int *param_4);
undefined4 * __thiscall std_Tree_Insert_hint_str(void *this,undefined4 *param_1,ushort *param_2,ushort *param_3,int *param_4);
void __thiscall std_Tree_Insert_nohint_int(void *this,undefined4 *param_1,char param_2,int *param_3,int *param_4);
void __thiscall std_Tree_Insert_nohint_pair(void *this,undefined4 *param_1,char param_2,int *param_3,int *param_4);
void __thiscall std_Tree_Insert_nohint_str(void *this,undefined4 *param_1,undefined4 *param_2,ushort *param_3,int *param_4);
void __thiscall std_Tree_Insert_nohint_str2(void *this,undefined4 *param_1,undefined4 *param_2,ushort *param_3,int *param_4);
void __cdecl std_pair_ctor_swap(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
undefined4 * __thiscall std_pair_copy_ctor2(void *this,undefined4 *param_1);
int * __thiscall std_map_operator_int(void *this,int *param_1);
void __thiscall std_map_insert_pair(void *this,int *param_1);
void __thiscall std_map_insert_str(void *this,ushort *param_1);
void __thiscall std_map_insert_str2(void *this,ushort *param_1);
uint __thiscall std_pair_less(void *this,uint *param_1);
uint __thiscall std_pair_lessequal(void *this,uint *param_1);
uint std_pair_less_2(int *param_1,int *param_2);
void std_Tree_ctor_sentinel(void);
void std_List_node_alloc_0x48(undefined4 *param_1,undefined4 *param_2);
void std_List_node_alloc_0xc(undefined4 *param_1,undefined4 *param_2);
undefined4 * __fastcall std_Tree_node_alloc_0x30(undefined4 *param_1);
void std_Rb_tree_destroy_recursive(int *param_1);
void __thiscall std_Rb_tree_rotate(void *this,int param_1);
undefined4 * __thiscall std_map_erase_range(void *this,undefined4 *param_1,int *param_2,int *param_3);
void __thiscall std_Rb_tree_erase_node(void *this,undefined4 *param_1,int *param_2);
void __thiscall std_Rb_tree_erase_node_variant(void *this,undefined4 *param_1,int *param_2);
/* WARNING: Removing unreachable block (ram,0x004d5645) */ /* WARNING: Removing unreachable block (ram,0x004d558a) */ /* WARNING: Removing unreachable block (ram,0x004d56ea) */ void __thiscall WalkPathBehavior_checkPathClear(void *this,uint *param_1,float *param_2,char param_3);
undefined4 * __thiscall std_Tree_node_construct_seh(void *this,int *param_1);
int std_list_insertNode3(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
undefined4 * __thiscall std_Tree_node_move_construct(void *this,undefined4 *param_1);
void __thiscall std_Rb_tree_insert_rebalance_A(void *this,undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
void __thiscall std_Rb_tree_insert_rebalance_B(void *this,undefined4 *param_1,char param_2,undefined4 *param_3,int *param_4);
undefined4 * __thiscall std_map_insert_hint_4da210(void *this,undefined4 *param_1,int *param_2,undefined4 *param_3,int *param_4);
void __thiscall std_map_insert_unique(void *this,undefined4 *param_1,char param_2,undefined4 *param_3,int *param_4);
undefined4 * __thiscall std_map_insert_scalarKey(void *this,undefined4 *param_1,char param_2,uint *param_3,undefined4 param_4);
void __thiscall std_map_insert_vectorKey(void *this,undefined4 *param_1,char param_2,int *param_3,undefined4 param_4);
undefined4 __cdecl std_lexicographical_less(int *param_1,int *param_2,int *param_3,int *param_4);
void __cdecl std_copy_ints(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
undefined4 * __thiscall std_vector_copyConstruct(void *this,int *param_1);
void __thiscall std_map_insertOrAssign(void *this,int *param_1);
int * __fastcall std_Rb_tree_increment(int *param_1);
undefined4 __thiscall std_vector_reserve_4dae20(void *this,uint param_1);
undefined4 * __fastcall std_Tree_node_alloc_0x14(undefined4 *param_1);
undefined4 * __fastcall std_Tree_node_alloc_0x34(undefined4 *param_1);
undefined4 * __thiscall std_map_lower_bound_vecKey(void *this,undefined4 *param_1);
void __thiscall std_vector_push_back_int(void *this,undefined4 *param_1);
void __thiscall std_Rb_tree_insert_rebalance_C(void *this,undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
void std_List_node_alloc_0x20(undefined4 *param_1,undefined4 *param_2);
undefined4 * __fastcall std_Tree_node_alloc_0x1c(undefined4 *param_1);
undefined4 * __fastcall std_Tree_node_alloc_0x20b(undefined4 *param_1);
void std_Rb_tree_destroy_recursive_B(int *param_1);
undefined4 * __thiscall std_map_lower_bound_2key(void *this,int *param_1);
void __fastcall std_map_clear(int *param_1);
undefined4 * __thiscall std_map_erase_range_B(void *this,undefined4 *param_1,int *param_2,int *param_3);
undefined4 * __thiscall std_Tree_node_alloc_assign2(void *this,undefined4 *param_1);
void std_list_insertNode1(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void std_List_init_sentinel(void);
undefined4 * __fastcall std_Tree_node_alloc_0x18(undefined4 *param_1);
void __thiscall std_map_lower_bound_yx(void *this,int *param_1,uint *param_2);
void __cdecl operator_new_wrapper(uint param_1);
ulonglong ftol2_round(void);
void eh_vector_ctor_iter_unwind(void);
void eh_vector_dtor_iter_unwind(void);

#endif
