// crt_stl (server) — reconstructed declarations.
#ifndef SERVER__LIBRARY_CRT_STL_H
#define SERVER__LIBRARY_CRT_STL_H
#include "../include/cube_types.h"

undefined8 * __thiscall assign_two_qwords(void *this,undefined8 param_1,undefined8 param_2);
undefined1 * __thiscall copy_3_bytes(void *this,undefined1 *param_1);
undefined1 * __thiscall set_3_bytes(void *this,undefined1 param_1,undefined1 param_2,undefined1 param_3);
undefined4 * __thiscall store_4_dwords(void *this,undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined1 * __thiscall copy_4_bytes(void *this,undefined1 *param_1,undefined1 param_2);
int __thiscall ptr_add_offset(void *this,int param_1);
undefined4 __thiscall std_vector_int_at(void *this,int param_1);
float10 __fastcall fixedpoint16_to_float(longlong *param_1);
void __thiscall vec3_sub(void *this,float *param_1,float *param_2);
void __thiscall int64_sub(void *this,int *param_1,uint *param_2);
void __thiscall int64_sub_timecall(void *this,int *param_1);
void __thiscall vec3_add(void *this,float *param_1,float *param_2);
void __thiscall int64_add_timecall(void *this,int *param_1);
float10 __thiscall vec2_dot(float *param_1,float *param_2);
float10 __thiscall vec3_dot(float *param_1,float *param_2);
float * __thiscall vec2_scale(void *this,float param_1);
float * __thiscall vec3_scale(void *this,float param_1);
float * __thiscall vec3_add_inplace(void *this,float *param_1);
undefined4 * __thiscall std::error_category::vfunc_0(error_category *this,byte param_1);
void call_ptr_n_times(undefined4 param_1,undefined4 param_2,int param_3,undefined *param_4);
undefined * Catch_All_00401786(void);
void Catch_All_004017c3(void);
bool __thiscall std_string_grow(void *this,uint param_1,char param_2);
void * std_allocate(uint param_1);
void std::_System_error_category::vfunc_3(int *param_1,int param_2);
void __thiscall std::error_category::vfunc_3(error_category *this,undefined4 *param_1,undefined4 param_2);
uint __thiscall std::error_category::vfunc_4(error_category *this,int *param_1,int param_2);
uint __thiscall std::error_category::vfunc_5(error_category *this,undefined4 param_1,int *param_2);
float10 __cdecl std_fabsf(float param_1);
float10 __fastcall vec2_length(float *param_1);
float10 __fastcall vec3_length(float *param_1);
undefined1 * std::_Generic_error_category::vfunc_2(undefined1 *param_1,int param_2);
undefined1 * std::_Iostream_error_category::vfunc_2(undefined1 *param_1,int param_2);
undefined1 * std::_System_error_category::vfunc_2(undefined1 *param_1,int param_2);
char * std::_Generic_error_category::vfunc_1(void);
char * std::_Iostream_error_category::vfunc_1(void);
char * std::_System_error_category::vfunc_1(void);
float * __fastcall vec2_normalize(float *param_1);
float * __fastcall vec3_normalize(float *param_1);
void __thiscall matrix_rotate_columns(void *this,float param_1);
undefined4 __fastcall get_field_0x44(int param_1);
undefined4 __fastcall get_field_0x48(int param_1);
undefined4 __fastcall get_field_0x4c(int param_1);
float10 __fastcall vec2_length_sq(float *param_1);
float10 __fastcall vec3_length_sq(float *param_1);
float * __thiscall mat4_transform_point(void *this,float *param_1,float *param_2);
void __thiscall mat4_translate_vec(void *this,float *param_1);
void __thiscall mat4_translate(void *this,float param_1,float param_2,float param_3);
float10 __cdecl std_asinf(float param_1);
float10 __cdecl std_cosf(float param_1);
float10 __cdecl std_sinf(float param_1);
float10 __cdecl std_sqrtf(float param_1);
void Catch_All_004027ef(void);
void Catch_All_00402954(void);
undefined4 * __thiscall vec3_store(void *this,undefined4 param_1,undefined4 param_2,undefined4 param_3);
ulonglong * __fastcall int64_assign_timecall(ulonglong *param_1);
int __thiscall ptr_index_dword(void *this,int param_1);
void __thiscall iterator_advance_0x11c(void *this,int *param_1);
void __thiscall iterator_advance_0xc(void *this,int *param_1);
int __thiscall fixedpoint_greater(void *this,uint param_1);
undefined4 __fastcall fixedpoint_greater_call(uint *param_1);
uint Int64_lessThan(uint *param_1,uint *param_2);
uint * __thiscall int64x3_add(void *this,uint *param_1);
uint * __thiscall int64_add(void *this,uint *param_1);
uint * __thiscall int64x3_sub(void *this,uint *param_1);
uint * __thiscall int64_sub2(void *this,uint *param_1);
uint __thiscall std_map_find_value(void *this,uint *param_1);
ulonglong __cdecl fixedpoint_to_int_floor(uint *param_1);
void __thiscall set_flag_bits_0x114(void *this,ushort param_1,char param_2);
float10 __cdecl std_powf(float param_1);
undefined1 * __thiscall copy_4_bytes_b(void *this,undefined1 *param_1);
/* Library Function - Single Match public: long __thiscall CRefTime::Millisecs(void) Libraries: Visual Studio 2012 Release, Visual Studio 2015 Release, Visual Studio 2017 Release, Visual Studio 2019 Release */ long __thiscall CRefTime::Millisecs(CRefTime *this);
void __thiscall int64_sub_shifted(void *this,int *param_1,uint param_2);
void __thiscall int64_add_shifted(void *this,int *param_1,uint param_2);
int __thiscall fixedpoint_less(void *this,uint param_1);
undefined4 __fastcall get_field_0x10(int param_1);
byte __fastcall get_bit6_of_byte3(int param_1);
undefined4 __fastcall check_type_low5_active(int param_1);
undefined4 __fastcall get_field_0x1c(int param_1);
uint * __thiscall vec_op_self_wrapper(void *this,uint *param_1);
byte __fastcall get_low5bits_byte3(int param_1);
void free_string_buffer(undefined4 *param_1);
undefined4 * __thiscall store_6_dwords(void *this,undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5,undefined4 param_6);
undefined4 * __fastcall std_list_construct(undefined4 *param_1);
int __fastcall init_struct_fields_a(int param_1);
undefined4 * __fastcall init_buffer_256_a(undefined4 *param_1);
undefined2 * __fastcall init_buffer_256_b(undefined2 *param_1);
bool __thiscall compare_int_eq(void *this,int *param_1);
uint __thiscall item_struct_equals(void *this,char *param_1);
undefined1 __thiscall compare_3_bytes_ne(void *this,int param_1);
void __thiscall vec3_scale_to(void *this,float *param_1,float param_2);
float10 __cdecl formula_diminishing_int(int param_1);
float10 __cdecl formula_diminishing_float(float param_1);
void __thiscall creature_spawn_projectile(void *this,int param_1);
float10 __fastcall calc_attack_power(int param_1);
float10 __fastcall calc_damage_value(void *param_1);
float10 __fastcall calc_stat_variant(int param_1);
float10 __cdecl formula_scaled_a(int param_1);
uint __fastcall check_weapon_kind(int param_1);
float10 __cdecl formula_curve_b(int param_1);
int __thiscall get_ability_cast_duration(void *this,undefined4 param_1,int param_2);
float10 __fastcall calc_regen_total(int param_1);
float10 __cdecl formula_scaled_b(int param_1);
/* WARNING: Removing unreachable block (ram,0x0040a935) */ /* WARNING: Removing unreachable block (ram,0x0040a95c) */ /* WARNING: Removing unreachable block (ram,0x0040a986) */ /* WARNING: Removing unreachable block (ram,0x0040a99b) */ /* WARNING: Removing unreachable block (ram,0x0040a971) */ /* WARNING: Removing unreachable block (ram,0x0040a947) */ /* WARNING: Removing unreachable block (ram,0x0040a919) */ /* WARNING: Removing unreachable block (ram,0x0040a9b0) */ void __cdecl generate_entity_appearance(uint *param_1,int param_2,undefined4 *param_3);
undefined4 * __thiscall list_find_by_id_byte(void *this,uint param_1);
void __cdecl get_value_range_a(undefined4 param_1,undefined4 *param_2,undefined4 *param_3);
void __cdecl get_value_range_b(undefined4 param_1,undefined4 *param_2,undefined4 *param_3);
bool __thiscall roll_probability(void *this,float param_1);
bool __fastcall check_proc_chance(int param_1);
undefined1 __fastcall check_ability_state(int param_1);
undefined1 stub_return_zero(void);
undefined1 __fastcall check_falling_state(int param_1);
uint __cdecl is_ranged_ability_id(int param_1);
undefined1 __fastcall is_consumable_effect(char *param_1);
int __fastcall get_cast_time(int param_1);
void __fastcall rbtree_inorder_walk(int param_1);
void __thiscall std_list_push_back(void *this,undefined8 *param_1);
void __fastcall creature_reset_state(int param_1);
void __fastcall creature_init_fields(int param_1);
float10 __fastcall calc_attack_power_b(int param_1);
float10 __cdecl formula_curve_c(int param_1);
float10 __cdecl formula_curve_d(int param_1);
void __fastcall process_regen_tick(int param_1);
float * __thiscall vec3_normalize_to(void *this,float *param_1);
undefined * Catch_All_004128ba(void);
int * __thiscall std_vector_assign(void *this,int *param_1);
/* WARNING: Removing unreachable block (ram,0x00412b2f) */ uint __thiscall std_vector_allocate(void *this,uint param_1);
void __fastcall delete_member_object(int param_1);
void __fastcall zlib_compress_to_vector(int *param_1);
void __cdecl zlib_compress_buffer(int *param_1,undefined4 *param_2);
void __fastcall zlib_uncompress_to_vector(int *param_1);
/* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ void __cdecl zlib_inflate_stream(int *param_1,int *param_2);
bool __fastcall is_field4_nonzero(int param_1);
int __fastcall std_vector_size(int *param_1);
void __thiscall db_store_blob_wrapper(void *this,undefined4 *param_1,int *param_2);
uint __thiscall db_upsert_blob(void *this,undefined4 *param_1,void *param_2,uint *param_3);
void __thiscall resize_dword_array(void *this,uint param_1,int param_2);
void __cdecl std_thread_start(undefined4 *param_1);
void * __cdecl uninitialized_copy_items(undefined1 *param_1,undefined1 *param_2,void *param_3);
uint __thiscall vector_calc_growth_0x118(void *this,uint param_1);
void __thiscall std_vector_reallocate_0x118(void *this,uint param_1);
void Catch_All_0041391e(void);
int __thiscall std_vector_reserve_0x118(void *this,uint param_1);
float10 __fastcall calc_defense_value(char *param_1);
undefined4 __fastcall get_effect_duration_a(char *param_1);
float10 __fastcall calc_dot_tick_value(char *param_1);
float10 __fastcall calc_heal_value(char *param_1);
float * __cdecl get_material_color(float *param_1,undefined4 param_2,float *param_3,float param_4);
float10 __fastcall calc_value_ranged(char *param_1);
float10 __fastcall calc_defense_value_b(char *param_1);
uint __thiscall roll_random_level(void *this,float param_1,char param_2);
undefined1 __cdecl net_encode_field_u8(undefined4 *param_1,uint *param_2,uint *param_3,char *param_4,char *param_5, char param_6);
undefined1 __cdecl net_encode_field_u16(undefined4 *param_1,uint *param_2,uint *param_3,short *param_4,short *param_5, char param_6);
undefined1 __cdecl net_encode_field_u32(undefined4 *param_1,uint *param_2,uint *param_3,int *param_4,int *param_5,char param_6);
undefined1 __cdecl net_encode_field_f32(undefined4 *param_1,uint *param_2,uint *param_3,float *param_4,float *param_5, char param_6);
int __cdecl net_encode_field_vec5(undefined4 *param_1,uint *param_2,uint *param_3,float *param_4,float *param_5, char param_6);
undefined1 __cdecl net_encode_field_struct0xac(undefined4 *param_1,uint *param_2,uint *param_3,void *param_4,int param_5,char param_6);
undefined1 __cdecl net_encode_field_creature(undefined4 *param_1,uint *param_2,uint *param_3,void *param_4,char *param_5, char param_6);
undefined1 __cdecl net_encode_field_item0x118(undefined4 *param_1,uint *param_2,uint *param_3,void *param_4,char *param_5, char param_6);
uint __cdecl net_encode_field_int3(undefined4 *param_1,uint *param_2,uint *param_3,int param_4,int *param_5,char param_6);
uint __cdecl net_encode_field_f32x3(undefined4 *param_1,uint *param_2,uint *param_3,int param_4,float *param_5,char param_6 );
uint __cdecl net_encode_field_2int_0x18(undefined4 *param_1,uint *param_2,uint *param_3,int param_4,int *param_5,char param_6);
undefined1 __cdecl net_encode_field_int2(undefined4 *param_1,uint *param_2,uint *param_3,int *param_4,int *param_5,char param_6);
undefined4 __cdecl net_decode_field_u8(int *param_1,uint *param_2,uint *param_3,undefined1 *param_4);
undefined4 __cdecl net_decode_field_u16(int *param_1,uint *param_2,uint *param_3,undefined2 *param_4);
undefined4 __cdecl net_decode_field_u32(int *param_1,uint *param_2,uint *param_3,undefined4 *param_4);
undefined4 __cdecl net_decode_field_vec5(int *param_1,uint *param_2,uint *param_3,undefined8 *param_4);
undefined4 __cdecl net_decode_field_struct0xac(int *param_1,uint *param_2,uint *param_3,void *param_4);
undefined4 __cdecl net_decode_field_creature(int *param_1,uint *param_2,uint *param_3,void *param_4);
undefined4 __cdecl net_decode_field_item0x118(int *param_1,uint *param_2,uint *param_3,void *param_4);
undefined4 __cdecl net_decode_field_int3(int *param_1,uint *param_2,uint *param_3,undefined8 *param_4);
undefined4 __cdecl net_decode_field_struct0x18(int *param_1,uint *param_2,uint *param_3,undefined8 *param_4);
undefined4 __cdecl net_decode_field_int2(int *param_1,uint *param_2,uint *param_3,undefined8 *param_4);
int __thiscall compare_3dword_eq_b(void *this,int param_1);
undefined1 __thiscall compare_3float_ne(void *this,float *param_1);
undefined1 __thiscall item_struct_equals_full(void *this,int param_1);
uint __thiscall creature_items_equal(void *this,char *param_1);
bool __thiscall item_not_equals(void *this,char *param_1);
undefined1 __cdecl net_encode_field_string(undefined4 *param_1,uint *param_2,uint *param_3,byte *param_4,byte *param_5, char param_6);
uint __cdecl net_encode_field_struct0x2c(undefined4 *param_1,uint *param_2,uint *param_3,int param_4,int *param_5,char param_6);
void __thiscall buffer_read_bounded(void *this,void *param_1,size_t param_2);
undefined4 __cdecl net_decode_field_struct0x10(int *param_1,uint *param_2,uint *param_3,undefined8 *param_4);
undefined4 __cdecl net_decode_field_struct0x2c(int *param_1,uint *param_2,uint *param_3,void *param_4);
int __cdecl EntityData_serializeToStream(int *param_1,undefined8 *param_2);
int __cdecl EntityData_writeDelta(int *param_1,int param_2,int *param_3,char param_4);
void __thiscall WriteBuffer_appendRaw(void *this,void *param_1,size_t param_2);
void __cdecl free(void *_Memory);
void __fastcall thunk_FUN_00417cc0(int *param_1);
int __thiscall std_wstring_operator(void *this,int param_1);
void __thiscall std_string_Assign_rv(void *this,undefined4 *param_1);
void __thiscall std_string_Chassign(void *this,int param_1,size_t param_2,char param_3);
void __thiscall CharTraits_assignFill(void *this,int param_1,uint param_2,undefined2 param_3);
undefined * Catch_All_00416dff(void);
void Catch_All_00416e3c(void);
void * std_wstring_Allocate(uint param_1);
int * __thiscall std_string_append_count_char(void *this,uint param_1,char param_2);
bool __fastcall std_string_empty(int param_1);
void Catch_All_0041a657(void);
void Catch_All_0041a78f(void);
void Catch_All_0041aaef(void);
int __thiscall std_vector_operator(void *this,int param_1);
void Catch_All_0041bb5f(void);
int __thiscall World_getVoxelField(void *this,uint param_1,uint param_2,int param_3);
undefined4 __fastcall getFieldAtFixedOffset(int param_1);
void __thiscall std_list_push_back_41caf0(void *this,undefined1 *param_1);
int __fastcall std_vector_size_41cb40(int *param_1);
/* Library Function - Single Match public: struct std::pair<unsigned __int64,unsigned __int64> & __thiscall std::pair<unsigned __int64,unsigned __int64>::operator=<struct std::pair<unsigned __int64,unsigned __int64>,0>(struct std::pair<unsigned __int64,unsigned __int64> &&) Library: Visual Studio 2019 Release */ pair<unsigned___int64,unsigned___int64> * __thiscall std::pair<unsigned___int64,unsigned___int64>:: operator=<std::pair<unsigned___int64,unsigned___int64>,0> (pair<unsigned___int64,unsigned___int64> *this, pair<unsigned___int64,unsigned___int64> *param_1);
uint * __thiscall computeLengthSquared_16_16(void *this,uint *param_1);
int __thiscall floatVec3_to_byte3(void *this,int param_1);
void * __cdecl std_vector_Umove(int param_1,int param_2,void *param_3);
void * __cdecl std_vector_Ucopy(int *param_1,int *param_2,void *param_3);
undefined4 __cdecl std_equal_Chunk_range(void *param_1,void *param_2,char *param_3);
undefined4 * __cdecl std_vector_Ucopy_41d340(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
undefined4 * __cdecl std_vector_Move_backward(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
undefined4 * __cdecl std_vector_Ucopy_41d410(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void * __cdecl std_vector_Ucopy_guarded(int *param_1,int *param_2,void *param_3);
void Catch_All_0041d4c6(void);
undefined4 * __cdecl std_vector_Ucopy_41d500(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void __cdecl std_vector_Ufill_default(int param_1,int param_2);
void __cdecl std_vector_Ufill_default_41d5d0(undefined4 *param_1,int param_2);
undefined4 * __cdecl std_vector_Ucopy_41d600(undefined1 *param_1,undefined1 *param_2,undefined4 *param_3);
void * __cdecl std_vector_Ucopy_41d680(undefined1 *param_1,undefined1 *param_2,void *param_3);
void __cdecl std_vector_Umove_41d6c0(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
undefined4 * __thiscall std_vector_vector_copy(void *this,int *param_1);
void Catch_All_0041d7bf(void);
int __fastcall struct_clear_fields_c_10(int param_1);
void * __thiscall Chunk_copyAssign(void *this,undefined1 *param_1);
undefined2 * __fastcall VoxelColumn_init(undefined2 *param_1);
int * __thiscall std_vector_operator_41d950(void *this,int *param_1);
void Catch_All_0041dac0(void);
int * __thiscall std_vector_operator_41dae0(void *this,int *param_1);
void Catch_All_0041dc43(void);
int * __thiscall std_vector_operator_41dc60(void *this,int *param_1);
void Catch_All_0041de13(void);
void * __thiscall QuestText_copyStrings13(void *this,undefined1 *param_1);
void * __thiscall struct_copyAssign_vec_str(void *this,int *param_1);
undefined4 * __thiscall EntityData_copyAssign(void *this,undefined4 *param_1);
int __thiscall std_vector_operator_41e2e0(void *this,int param_1);
void __thiscall std_vector_back_slot(void *this,int *param_1);
uint __thiscall std_vector_Reserve(void *this,uint param_1);
uint __thiscall std_vector_Reserve_41e390(void *this,uint param_1);
uint __thiscall std_vector_Grow_calc(void *this,uint param_1);
void __thiscall std_vector_Reallocate(void *this,uint param_1);
void Catch_All_0041e520(void);
void __thiscall std_vector_Reallocate_41e540(void *this,uint param_1);
void Catch_All_0041e61e(void);
void __thiscall std_vector_Reallocate_41e640(void *this,uint param_1);
void Catch_All_0041e71c(void);
void __thiscall std_vector_Reallocate_41e740(void *this,uint param_1);
void Catch_All_0041e820(void);
void __thiscall std_vector_reserve(void *this,uint param_1);
int __thiscall std_vector_Grow_by(void *this,uint param_1);
void __thiscall std_vector_reserve_41e960(void *this,uint param_1);
void __thiscall std_vector_reserve_41ea10(void *this,uint param_1);
uint __cdecl std_char_traits_compare(byte *param_1,byte *param_2,uint param_3);
undefined4 * __thiscall std_vector_erase(void *this,undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
byte __fastcall rbtree_node_isRed(int param_1);
void __thiscall World_deserializeZonePacket(void *this,void *param_1,int param_2);
void __thiscall std_vector_push_back(void *this,undefined4 *param_1);
void __thiscall std_vector_push_back_41f5b0(void *this,undefined1 *param_1);
undefined4 * __thiscall std_vector_resize(void *this,uint param_1);
void Catch_All_0041f75d(void);
undefined4 * __thiscall std_vector_resize_41f770(void *this,uint param_1);
void Catch_All_0041f860(void);
void __thiscall writeCombatActionToStream(void *this,int param_1);
void __thiscall writeHitToStream(void *this,undefined4 *param_1);
void __thiscall World_serializeZoneSaveData(void *this,int param_1);
void __thiscall VoxelColumn_setBlock(void *this,int param_1,undefined1 *param_2);
void __thiscall World_fillVoxelColumn(void *this,float param_1,uint param_2,int param_3,undefined1 *param_4,int param_5);
int __fastcall std_vector_size_41fff0(int *param_1);
int __fastcall std_vector_size_420020(int *param_1);
int std_map_insert_node_0x70(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
int std_map_insert_node_0x1c(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
int std_map_insert_node_string(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_004201e2(void);
int std_map_insert_node_wstring(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_00420299(void);
int std_map_insert_node_0x47a(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
int std_map_insert_node_list(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_00420362(void);
int std_map_insert_node_0x28b(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
int std_map_insert_node_0x48(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
int std_map_insert_node_0x40(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
int std_map_insert_node_Chunk(undefined4 *param_1,undefined4 *param_2,undefined1 *param_3);
void __thiscall std_list_assign(void *this,undefined1 *param_1,undefined1 *param_2);
void Catch_All_0042052c(void);
void Catch_All_004205df(void);
void __thiscall std_map_Insert_rebalance(void *this,undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
undefined4 * __thiscall std_map_insert_hint(void *this,undefined4 *param_1,int *param_2,uint *param_3,int *param_4);
void Catch_All_00420a0f(void);
void __thiscall std_map_Insert_unique(void *this,undefined4 *param_1,char param_2,uint *param_3,int *param_4);
void Catch_All_00420b74(void);
void __thiscall std_list_Assign_0x28(void *this,undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_00420c39(void);
void __thiscall std_list_Assign_str(void *this,undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_00420d09(void);
void __thiscall std_list_Assign_str2(void *this,undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_00420dd9(void);
void __thiscall std_list_Assign_0x1c(void *this,undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_00420ea9(void);
void __thiscall std_list_Assign_0x47a(void *this,undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_00420f79(void);
void __thiscall std_list_Assign_list(void *this,undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_00421049(void);
void __thiscall std_list_Assign_str3(void *this,undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_00421119(void);
void __thiscall std_list_Assign_0x18(void *this,undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_004211e9(void);
void __thiscall std_list_Assign_0x28b(void *this,undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_004212b9(void);
void __thiscall std_list_Assign_0x48(void *this,undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_00421389(void);
void __thiscall std_list_Assign_0x40(void *this,undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_00421459(void);
void __thiscall std_list_Assign_0x08b(void *this,undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_00421529(void);
void __thiscall std_list_Assign(void *this,undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_004215f9(void);
void __thiscall std_list_Assign_0x14b(void *this,undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_004216c9(void);
void __thiscall std_list_Assign_0x70(void *this,undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_00421799(void);
void __thiscall std_list_Assign_arr_0x1c(void *this,undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_00421867(void);
void __thiscall std_list_Assign_arr(void *this,undefined4 *param_1,undefined1 *param_2,undefined1 *param_3);
void Catch_All_00421939(void);
void * __cdecl std_vector_Ucopy_421980(undefined4 *param_1,undefined4 *param_2,void *param_3);
void __cdecl serializeList_records_0x28(int *param_1,int *param_2);
void __cdecl serializeList_records_0x10(int *param_1,int *param_2);
void __cdecl serializeList_records_0x70(int *param_1,int *param_2);
void __cdecl serializeList_records_0x14(int *param_1,int *param_2);
void __cdecl serializeList_records_0x48(int *param_1,int *param_2);
void __cdecl serializeList_records_0x120(int *param_1,int *param_2);
void __cdecl serializeList_records_0x18(int *param_1,int *param_2);
void __cdecl serializeList_records_0x38(int *param_1,int *param_2);
void __cdecl serializeList_records_0x58(int *param_1,int *param_2);
void __cdecl serializeList_Chunk_0x148(int *param_1,int *param_2);
undefined2 * __thiscall std_wstring_basic_string_count_wch(void *this,uint param_1,undefined2 param_2);
undefined4 * __thiscall std_list_list_copy_0x28(void *this,undefined4 *param_1);
void Catch_All_00421eff(void);
undefined4 * __thiscall std_list_list_copy_str(void *this,undefined4 *param_1);
void Catch_All_00421f9f(void);
undefined4 * __thiscall std_list_list_copy_str2(void *this,undefined4 *param_1);
void Catch_All_0042203f(void);
undefined4 * __thiscall std_list_list_copy_0x70(void *this,undefined4 *param_1);
void Catch_All_004220df(void);
undefined4 * __thiscall std_list_list_copy_0x1c(void *this,undefined4 *param_1);
void Catch_All_0042217f(void);
undefined4 * __thiscall std_list_list_copy_0x47a(void *this,undefined4 *param_1);
void Catch_All_0042221f(void);
undefined4 * __thiscall std_list_list_copy_list(void *this,undefined4 *param_1);
void Catch_All_004222bf(void);
undefined4 * __thiscall std_list_list_copy_str3(void *this,undefined4 *param_1);
void Catch_All_0042235f(void);
undefined4 * __thiscall std_list_list_copy_0x18(void *this,undefined4 *param_1);
void Catch_All_004223ff(void);
undefined4 * __thiscall std_list_list_copy_0x28b(void *this,undefined4 *param_1);
void Catch_All_0042249f(void);
undefined4 * __thiscall std_list_list_copy_0x48(void *this,undefined4 *param_1);
void Catch_All_0042253f(void);
undefined4 * __thiscall std_list_list_copy_0x40(void *this,undefined4 *param_1);
void Catch_All_004225df(void);
undefined4 * __thiscall std_list_list_copy_0x08b(void *this,undefined4 *param_1);
void Catch_All_0042267f(void);
undefined4 * __thiscall std_list_list_copy(void *this,undefined4 *param_1);
void Catch_All_0042271f(void);
undefined4 * __thiscall std_list_list_copy_0x14b(void *this,undefined4 *param_1);
void Catch_All_004227bf(void);
undefined4 * __thiscall copyStruct_0x70(void *this,undefined4 *param_1);
undefined4 * __fastcall initStruct_0x70_defaults(undefined4 *param_1);
undefined4 * __thiscall copyStruct_0x47(void *this,undefined4 *param_1);
int __fastcall initStruct_0x47_zero(int param_1);
undefined4 * __fastcall initStruct_0x10_zero(undefined4 *param_1);
undefined4 * __thiscall Zone_extractChunkList(void *this,int param_1);
undefined4 * __thiscall copyStruct_0x38(void *this,undefined4 *param_1);
undefined4 * __fastcall initStruct_0x38_zero(undefined4 *param_1);
undefined4 * __thiscall copyStruct_head_plus_0x48(void *this,undefined4 *param_1,undefined4 *param_2);
undefined4 * __thiscall copyStruct_0x48(void *this,undefined4 *param_1);
undefined4 * __thiscall copyStruct_0x44(void *this,undefined4 *param_1);
undefined4 * __thiscall copyStruct_0x74(void *this,undefined4 *param_1);
void * __thiscall Zone_copyStateContainer(void *this,undefined4 *param_1);
undefined4 * __thiscall copyStruct_0x28(void *this,undefined4 *param_1);
/* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ void __thiscall std_map_insert(void *this,uint *param_1);
void __fastcall Server_worldUpdateSendLoop(int *param_1);
void __fastcall std:: _Func_impl<std::_Callable_obj<<lambda_ab9fa502c78db4b4288c2bfaac953e1a>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::ctor_0(int *param_1);
/* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ void __fastcall Connection_receiveDispatch(int *param_1);
void std_list_Buyheadnode_0x1180(void);
void std_list_Buynode_0x150(undefined4 *param_1,undefined4 *param_2);
void __thiscall std:: _Func_impl<std::_Callable_obj<<lambda_ab9fa502c78db4b4288c2bfaac953e1a>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_0(_Func_impl<std::_Callable_obj<<lambda_ab9fa502c78db4b4288c2bfaac953e1a>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> *this,undefined4 *param_1);
void __thiscall scalar_deleting_destructor(void *this,char param_1);
void __fastcall std:: _Func_impl<std::_Callable_obj<<lambda_38361316b522edf94308fdf9d1a2954a>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_2(int param_1);
void __fastcall std:: _Func_impl<std::_Callable_obj<<lambda_8ac7a930af6f0ab005bd27e10d1330ab>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_2(int param_1);
void __fastcall std:: _Func_impl<std::_Callable_obj<<lambda_ab9fa502c78db4b4288c2bfaac953e1a>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_2(int param_1);
void __thiscall std_Tree_equal_range(void *this,int *param_1,uint *param_2);
void node_dtor_free_list_0x10(void *param_1);
void __thiscall std:: _Func_impl<std::_Callable_obj<<lambda_38361316b522edf94308fdf9d1a2954a>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_0(_Func_impl<std::_Callable_obj<<lambda_38361316b522edf94308fdf9d1a2954a>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> *this,undefined4 *param_1);
void __thiscall std:: _Func_impl<std::_Callable_obj<<lambda_8ac7a930af6f0ab005bd27e10d1330ab>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_0(_Func_impl<std::_Callable_obj<<lambda_8ac7a930af6f0ab005bd27e10d1330ab>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> *this,undefined4 *param_1);
void __thiscall std_vector_Reallocate_426db0(void *this,uint param_1);
void Catch_All_00426e8e(void);
TypeDescriptor * std:: _Func_impl<std::_Callable_obj<<lambda_38361316b522edf94308fdf9d1a2954a>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_3(void);
TypeDescriptor * std:: _Func_impl<std::_Callable_obj<<lambda_8ac7a930af6f0ab005bd27e10d1330ab>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_3(void);
TypeDescriptor * std:: _Func_impl<std::_Callable_obj<<lambda_ab9fa502c78db4b4288c2bfaac953e1a>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_3(void);
void __fastcall std_list_Tidy_no_size(int *param_1);
void __thiscall std_list_erase(void *this,int *param_1);
void __thiscall std_list_erase_embedded_list(void *this,int *param_1);
void __thiscall game_inventoryAccumulateCount(void *this,char *param_1,int param_2);
void __thiscall game_buildItemDefinition(void *this,undefined4 *param_1);
int * __thiscall std_basic_string_resize(void *this,uint param_1,undefined2 param_2);
int __fastcall std_list_front_or_null(int *param_1);
void __thiscall std_list_operator(void *this,undefined4 *param_1);
void __thiscall std_list_operator_4281d0(void *this,undefined4 *param_1);
void __thiscall std_list_operator_428230(void *this,undefined4 *param_1);
undefined1 __fastcall game_isEntityTypeSolid(char *param_1);
undefined1 __fastcall game_isItemTypeStackable(char *param_1);
undefined4 game_itemTypeCategory(undefined1 *param_1);
void __thiscall std_list_push_back_428360(void *this,undefined4 *param_1);
void __thiscall std_list_push_back_4283b0(void *this,undefined4 *param_1);
void __thiscall std_list_push_back_428400(void *this,undefined4 *param_1);
void __thiscall std_list_push_back_428450(void *this,undefined4 *param_1);
void __thiscall std_list_push_back_4284a0(void *this,undefined4 *param_1);
void __thiscall std_list_push_back_4284f0(void *this,undefined4 *param_1);
void __thiscall std_list_push_back_428540(void *this,undefined4 *param_1);
void __thiscall std_list_push_back_428590(void *this,undefined4 *param_1);
void __thiscall std_list_push_back_4285e0(void *this,undefined4 *param_1);
void __thiscall game_appendItemEntry(void *this,undefined4 *param_1);
int __cdecl ws2_32_send_all(undefined4 param_1,int param_2,int param_3,undefined4 param_4);
undefined4 __fastcall accessor_dword_at_4(int param_1);
void __fastcall std:: _Func_impl<std::_Callable_obj<<lambda_8ac7a930af6f0ab005bd27e10d1330ab>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::ctor_0(int param_1);
int __thiscall array_index_stride32(void *this,int param_1);
int __fastcall std_vector_size_428ee0(int *param_1);
undefined * Catch_All_00429040(void);
void Catch_All_00429180(void);
void Catch_All_00429227(void);
void Catch_All_0042931d(void);
void Catch_All_00429415(void);
void Catch_All_0042954f(void);
void Catch_All_0042a018(void);
void Catch_All_0042a244(void);
void Catch_All_0042a434(void);
void Catch_All_0042a624(void);
void Catch_All_0042a814(void);
void Catch_All_0042a908(void);
void Catch_All_0042aac0(void);
void Catch_All_0042ac24(void);
void Catch_All_0042ad84(void);
void Catch_All_0042ae29(void);
void Catch_All_0042af1d(void);
void Catch_All_0042b0b6(void);
void Catch_All_0042b156(void);
void Catch_All_0042b1ff(void);
void __fastcall std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::ctor_0 (int *param_1);
void __thiscall std::basic_stringstream<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::vfunc_0 (basic_stringstream<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_> *this, byte param_1);
basic_streambuf<wchar_t,std::char_traits<wchar_t>_> * __thiscall std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::vfunc_0 (basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_> *this, byte param_1);
ios_base * __thiscall std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::ctor_1 (basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_> *this, byte param_1);
void __fastcall std::basic_stringstream<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::vfunc_1 (int param_1);
void __fastcall std::basic_stringstream<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::vfunc_2 (int param_1);
void Catch_operator_delete(void *param_1);
void Catch_operator_delete_42d000(void *param_1);
void Catch_cleanup_thunk(void *param_1);
void node_free_twoStrings(void *param_1);
void QuestText_node_free(void *param_1);
void __thiscall Catch_operator_delete_42d4c0(void *this,int *param_1);
undefined4 __thiscall game_gridLookup1024(void *this,int param_1,int param_2);
wchar_t __thiscall std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::vfunc_3 (basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_> *this, wchar_t param_1);
uint __thiscall std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::vfunc_4 (basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_> *this, ushort param_1);
void __thiscall std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::vfunc_10 (basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_> *this, uint *param_1,uint param_2,uint param_3,int param_4,uint param_5);
void __thiscall std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::vfunc_11 (basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_> *this, uint *param_1,uint param_2,int param_3,uint param_4,int param_5,undefined4 param_6, undefined4 param_7,uint param_8);
undefined2 __fastcall std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::vfunc_6 (int param_1);
int __thiscall game_blockLookup(void *this,uint param_1,uint param_2);
bool __cdecl std_Fputc(char param_1,FILE *param_2);
facet * __cdecl std_use_facet(locale *param_1);
basic_istream<char,std::char_traits<char>_> * __thiscall std::basic_filebuf<char,std::char_traits<char>_>::ctor_3 (basic_filebuf<char,std::char_traits<char>_> *this,char *param_1,uint param_2,int *param_3 ,int param_4);
void __fastcall std::basic_filebuf<char,std::char_traits<char>_>::ctor_5 (basic_streambuf<char,std::char_traits<char>_> *param_1);
void __fastcall std::basic_filebuf<char,std::char_traits<char>_>::ctor_4(int param_1);
void __fastcall std::basic_filebuf<char,std::char_traits<char>_>::ctor_6(int param_1);
undefined1 __thiscall memcmp3_equal(void *this,int param_1);
int * __thiscall vec3_div_scalar(void *this,int *param_1,int param_2);
void __thiscall std::basic_ifstream<char,std::char_traits<char>_>::vfunc_0 (basic_ifstream<char,std::char_traits<char>_> *this,byte param_1);
void __thiscall std::basic_ofstream<char,std::char_traits<char>_>::vfunc_0 (basic_ofstream<char,std::char_traits<char>_> *this,byte param_1);
basic_streambuf<char,std::char_traits<char>_> * __thiscall std::basic_filebuf<char,std::char_traits<char>_>::vfunc_0 (basic_filebuf<char,std::char_traits<char>_> *this,byte param_1);
ios_base * __thiscall std_basic_streambuf_scalar_deleting_dtor(void *this,byte param_1);
ios_base * __thiscall std_basic_streambuf_scalar_deleting_dtor_42ef30(void *this,byte param_1);
void __fastcall std::basic_ifstream<char,std::char_traits<char>_>::vfunc_1(int param_1);
void __fastcall std::basic_ofstream<char,std::char_traits<char>_>::vfunc_2(int param_1);
/* WARNING: Removing unreachable block (ram,0x0042f0db) */ void __fastcall std_basic_filebuf_Endwrite(int *param_1);
void __fastcall std::basic_filebuf<char,std::char_traits<char>_>::vfunc_1(int param_1);
void Catch_All_0042f318(void);
/* Library Function - Single Match private: void __thiscall std::basic_filebuf<char,struct std::char_traits<char> >::_Reset_back(void) Library: Visual Studio 2012 Release */ void __thiscall std::basic_filebuf<char,std::char_traits<char>_>::_Reset_back (basic_filebuf<char,std::char_traits<char>_> *this);
/* Library Function - Single Match private: void __thiscall std::basic_filebuf<char,struct std::char_traits<char> >::_Set_back(void) Library: Visual Studio 2012 Release */ void __thiscall std::basic_filebuf<char,std::char_traits<char>_>::_Set_back (basic_filebuf<char,std::char_traits<char>_> *this);
void __fastcall std::basic_filebuf<char,std::char_traits<char>_>::vfunc_2(int param_1);
basic_streambuf<char,std::char_traits<char>_> * __fastcall std_basic_filebuf_close(basic_streambuf<char,std::char_traits<char>_> *param_1);
void __thiscall std::basic_filebuf<char,std::char_traits<char>_>::vfunc_14 (basic_filebuf<char,std::char_traits<char>_> *this,locale *param_1);
basic_streambuf<char,std::char_traits<char>_> * __thiscall std_basic_filebuf_open(void *this,char *param_1,int param_2,int *param_3);
/* WARNING: Removing unreachable block (ram,0x0042fcfd) */ void __thiscall std::basic_filebuf<char,std::char_traits<char>_>::vfunc_3 (basic_filebuf<char,std::char_traits<char>_> *this,int param_1);
uint __thiscall std::basic_filebuf<char,std::char_traits<char>_>::vfunc_4 (basic_filebuf<char,std::char_traits<char>_> *this,uint param_1);
void Catch_All_00430033(void);
void __thiscall std::basic_filebuf<char,std::char_traits<char>_>::vfunc_10 (basic_filebuf<char,std::char_traits<char>_> *this,undefined4 *param_1,int param_2, int param_3,int param_4);
void __thiscall std::basic_filebuf<char,std::char_traits<char>_>::vfunc_11 (basic_filebuf<char,std::char_traits<char>_> *this,undefined4 *param_1,int param_2, int param_3,undefined4 param_4,undefined4 param_5,undefined4 param_6);
basic_streambuf<char,std::char_traits<char>_> * __thiscall std::basic_filebuf<char,std::char_traits<char>_>::vfunc_12 (basic_filebuf<char,std::char_traits<char>_> *this,char *param_1,size_t param_2, int param_3);
undefined4 __fastcall std::basic_filebuf<char,std::char_traits<char>_>::vfunc_13(int *param_1);
void __fastcall std::basic_filebuf<char,std::char_traits<char>_>::vfunc_7 (basic_streambuf<char,std::char_traits<char>_> *param_1);
uint __fastcall std::basic_filebuf<char,std::char_traits<char>_>::vfunc_6(int *param_1);
undefined1 * __thiscall game_voxelColorAt(void *this,int param_1,int param_2,int param_3);
undefined4 * __cdecl std_basic_string_assign(undefined4 *param_1,undefined4 *param_2,int *param_3);
undefined4 * __thiscall std_Tree_Buynode(void *this,undefined4 *param_1);
void Catch_All_00430911(void);
void __thiscall std_Tree_Insert(void *this,undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
undefined4 * __thiscall std_map_insert_430b40(void *this,undefined4 *param_1,int *param_2,int *param_3,int *param_4);
void Catch_All_00430d18(void);
void __thiscall std_Tree_Insert_430d70(void *this,undefined4 *param_1,char param_2,int *param_3,int *param_4);
void Catch_All_00430e4d(void);
undefined4 * __thiscall std_basic_string_assign_430fa0(void *this,undefined4 *param_1);
void __thiscall std_basic_string_assign_cstr(void *this,int *param_1);
int * __thiscall std_map_operator(void *this,int *param_1);
void std_Tree_Erase_node_with_list(void *param_1);
int * __thiscall std_basic_string_replace(void *this,undefined4 *param_1,uint param_2,uint param_3);
int * __thiscall std_basic_string_append(void *this,int *param_1,uint param_2);
/* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ void __thiscall game_loadVoxelModelsFromDb(void *this,undefined4 *param_1);
void __thiscall std_list_Insert(void *this,undefined4 *param_1);
void __cdecl sqlite3_bind_blob(int *param_1,int param_2,void *param_3,size_t param_4,undefined *param_5);
/* Library Function - Single Match void * __cdecl operator new[](unsigned int,enum FILL) Library: Visual Studio 2017 Release */ void * __cdecl operator_new__(uint param_1,FILL param_2);
void Catch_All_004c5cfd(void);
float * __thiscall lib_fn_4c6470(void *this,byte *param_1);
float * __thiscall lib_fn_4c64b0(void *this,int *param_1);
basic_ostream<char,std::char_traits<char>_> * lib_fn_4c6580(basic_ostream<char,std::char_traits<char>_> *param_1,char *param_2);
undefined * Catch_All_004c66ee(void);
void lib_fn_4c670e(void);
int lib_fn_4c6770(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_004c7527(void);
void Catch_All_004c776f(void);
void Catch_All_004c7994(void);
void Catch_All_004c7a8a(void);
void Catch_All_004c7c38(void);
void Catch_All_004c7dbd(void);
void Catch_All_004c7f4d(void);
void * __cdecl lib_fn_4c7f70(int *param_1,int *param_2,void *param_3);
void Catch_All_004c7fdd(void);
void * __cdecl lib_fn_4c8020(undefined4 *param_1,undefined4 *param_2,void *param_3);
void Catch_All_004c808c(void);
void lib_fn_4c80d0(int param_1);
void __cdecl lib_fn_4c8150(undefined4 *param_1,undefined4 *param_2);
void __cdecl lib_fn_4c8170(undefined4 *param_1,undefined4 *param_2);
basic_iostream<char,std::char_traits<char>_> * __thiscall std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_2 (basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_> *this,uint param_1, int param_2);
undefined4 * __fastcall lib_fn_4c8280(undefined4 *param_1);
undefined4 * __thiscall lib_fn_4c82a0(void *this,int *param_1);
void Catch_All_004c833c(void);
undefined4 * __thiscall lib_fn_4c8350(void *this,undefined4 *param_1);
int __fastcall lib_fn_4c83b0(int param_1);
void * __thiscall lib_fn_4c8420(void *this,undefined4 *param_1);
int __fastcall lib_fn_4c84b0(int param_1);
int __fastcall lib_fn_4c8510(int param_1);
int __fastcall lib_fn_4c8530(int param_1);
int * __thiscall lib_fn_4cde40(void *this,uint param_1);
undefined4 __fastcall lib_fn_4ce1f0(undefined4 *param_1);
void __thiscall lib_fn_4ce200(void *this,int *param_1);
void __thiscall lib_fn_4ce220(void *this,int *param_1,int *param_2);
void __thiscall lib_fn_4ce270(void *this,int *param_1,int param_2);
void __thiscall lib_fn_4ce290(void *this,int *param_1);
ulonglong * lib_fn_4ce2d0(ulonglong *param_1);
ulonglong * lib_fn_4ce310(ulonglong *param_1);
void __fastcall std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_4(int *param_1);
void __thiscall std::basic_stringstream<char,std::char_traits<char>,std::allocator<char>_>::vfunc_0 (basic_stringstream<char,std::char_traits<char>,std::allocator<char>_> *this,byte param_1);
basic_streambuf<char,std::char_traits<char>_> * __thiscall std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::vfunc_0 (basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_> *this,byte param_1);
ios_base * __thiscall std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_6 (basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_> *this,byte param_1);
void * __thiscall lib_fn_4ce500(void *this,byte param_1);
void __fastcall std::basic_stringstream<char,std::char_traits<char>,std::allocator<char>_>::vfunc_1(int param_1);
void __fastcall std::basic_stringstream<char,std::char_traits<char>,std::allocator<char>_>::vfunc_2(int param_1);
undefined4 __thiscall lib_fn_4ce580(void *this,uint param_1);
void lib_fn_4ce6e0(void *param_1);
void __thiscall lib_fn_4ce7e0(void *this,uint param_1);
void Catch_All_004ce8c7(void);
void __thiscall lib_fn_4ce8e0(void *this,uint param_1);
void __thiscall lib_fn_4cea80(void *this,uint *param_1,void *param_2,undefined4 *param_3);
void __thiscall stl_fn_4cfd50(void *this,float param_1,void *param_2,float param_3,char param_4,char param_5, float param_6,undefined4 param_7,float *param_8,undefined4 *param_9,undefined4 *param_10 ,char param_11,int param_12,undefined4 param_13,char param_14);
int lib_fn_4d18c0(int param_1,int param_2);
/* WARNING: Removing unreachable block (ram,0x004d1fdd) */ void __thiscall lib_fn_4d1a70(void *this,uint param_1,uint param_2,int param_3,int param_4,int param_5,int param_6);
void lib_fn_4d2190(undefined8 *param_1,undefined8 *param_2,float param_3,char param_4,int param_5, int param_6);
uint __thiscall lib_fn_4d2340(void *this,uint param_1,uint param_2,undefined8 param_3);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ undefined * __thiscall lib_fn_4d23f0(void *this,int param_1);
byte __thiscall lib_fn_4d24a0(void *this,uint param_1,uint param_2,int param_3,int param_4,int param_5);
void __thiscall lib_fn_4d2500(void *this,int param_1,int param_2,int param_3,int *param_4,int param_5,char param_6);
void lib_fn_4d2810(undefined1 *param_1,uint *param_2,float param_3,float param_4,void *param_5);
void __thiscall lib_fn_4d2ae0(void *this,int param_1,void *param_2);
void __thiscall lib_fn_4d3de0(void *this,undefined4 *param_1);
void __fastcall lib_fn_4d3df0(int param_1);
void __fastcall lib_fn_4d3e00(int param_1);
void __thiscall lib_fn_4d4430(void *this,undefined4 *param_1,void *param_2);
int * __thiscall lib_fn_4d4470(void *this,int *param_1,int param_2);
void __thiscall lib_fn_4d44c0(void *this,int param_1,int param_2,int param_3,float param_4,byte *param_5,int param_6, char param_7,char param_8);
void __thiscall lib_fn_4d4820(void *this,int param_1,int param_2,int param_3,float param_4,byte *param_5,int param_6, char param_7,char param_8);
void __thiscall lib_fn_4d4f60(void *this,undefined4 *param_1,uint *param_2);
void __thiscall lib_fn_4d5740(void *this,uint *param_1,float *param_2);
void __fastcall lib_fn_4d5c60(int param_1);
void __fastcall lib_fn_4d5c70(int param_1);
float10 __thiscall lib_fn_4d5c80(void *param_1,uint *param_2);
void __thiscall lib_fn_4d61c0(void *this,uint *param_1);
int __thiscall std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::vfunc_3 (basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_> *this,int param_1);
int __thiscall std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::vfunc_4 (basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_> *this,int param_1);
void ** __thiscall lib_fn_4d6670(void *this,void **param_1);
void __thiscall lib_fn_4d78e0(void *this,int param_1,int param_2);
void __thiscall lib_fn_4d7960(void *this,int param_1,int param_2);
void __thiscall lib_fn_4d79f0(void *this,uint param_1,uint param_2);
void __thiscall std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_0 (basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_> *this,int param_1, int param_2);
void __thiscall std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_3 (basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_> *this,int param_1);
void __thiscall std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_5 (basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_> *this,uint param_1, int *param_2);
void __thiscall std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::vfunc_10 (basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_> *this,uint *param_1, uint param_2,uint param_3,int param_4,uint param_5);
void __thiscall std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::vfunc_11 (basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_> *this,uint *param_1, uint param_2,int param_3,uint param_4,int param_5,undefined4 param_6,undefined4 param_7, uint param_8);
void lib_fn_4d8c90(int *param_1,int param_2,char param_3);
undefined4 __fastcall lib_fn_4d8dc0(int param_1);
undefined4 __fastcall lib_fn_4d8de0(int param_1);
undefined4 __fastcall lib_fn_4d8e00(int param_1);
float10 __fastcall lib_fn_4d8e30(double *param_1);
float10 __thiscall lib_fn_4d9010(void *param_1,float param_2,float param_3,int param_4);
uint __fastcall std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::vfunc_6(int param_1);
void __thiscall lib_fn_4d9160(void *this,int param_1,int *param_2,uint param_3,uint param_4);
float * lib_fn_4d9720(float *param_1);
int * __thiscall lib_fn_4d99d0(void *this,uint *param_1);
void Catch_All_004d9aa8(void);
void Catch_All_004d9b31(void);
void __thiscall lib_fn_4d9be0(void *this,int *param_1,undefined4 param_2);
void Catch_All_004d9cff(void);
void Catch_All_004d9dbf(void);
void Catch_All_004da44c(void);
void Catch_All_004da611(void);
void Catch_All_004da75f(void);
void Catch_All_004da906(void);
void * lib_fn_4da990(void *param_1,int param_2,void *param_3);
void __thiscall lib_fn_4da9f0(void *this,int *param_1,int *param_2);
void Catch_All_004dab0f(void);
ulonglong * __fastcall lib_fn_4dab30(ulonglong *param_1);
int * __thiscall lib_fn_4dab90(void *this,int *param_1);
undefined4 __fastcall lib_fn_4dade0(uint *param_1);
void lib_fn_4daf10(void *param_1);
void __thiscall lib_fn_4db1b0(void *this,int *param_1,uint *param_2);
void lib_fn_4db200(void *param_1,int param_2);
void __thiscall lib_fn_4dde00(void *this,float *param_1,float *param_2);
void __thiscall lib_fn_4e0700(void *this,int *param_1);
void __thiscall lib_fn_4e0740(void *this,int param_1,uint *param_2);
int * __thiscall lib_fn_4e1200(void *this,int param_1);
undefined4 * __cdecl lib_fn_4e1230(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void __thiscall lib_fn_4e1280(void *this,uint param_1);
void Catch_All_004e1350(void);
void __thiscall lib_fn_4e1370(void *this,uint param_1);
void __thiscall lib_fn_4e1420(void *this,undefined4 *param_1);
undefined4 * __thiscall lib_fn_4e14e0(void *this,uint *param_1);
void __cdecl lib_fn_4e1520(float *param_1,float param_2,float *param_3);
void __cdecl lib_fn_4e1910(undefined8 *param_1,undefined8 *param_2,undefined8 *param_3);
void __cdecl lib_fn_4e1d70(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void __cdecl lib_fn_4e1db0(int param_1,int param_2);
void __cdecl lib_fn_4e1e00(undefined8 *param_1,undefined8 *param_2,undefined8 *param_3);
undefined4 * __thiscall lib_fn_4e1e90(void *this,undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 * __fastcall lib_fn_4e1eb0(undefined4 *param_1);
undefined4 * __thiscall lib_fn_4e1ed0(void *this,int *param_1);
void Catch_All_004e1f6c(void);
undefined4 * __thiscall lib_fn_4e20d0(void *this,undefined4 *param_1,undefined4 param_2);
undefined4 * __fastcall lib_fn_4e2110(undefined4 *param_1);
undefined4 * __fastcall lib_fn_4e2190(undefined4 *param_1);
int __thiscall lib_fn_4e2320(void *this,int param_1);
int __thiscall lib_fn_4e2330(void *this,int param_1);
int __thiscall lib_fn_4e2350(void *this,int param_1);
int * __thiscall lib_fn_4e2360(void *this,int *param_1,int param_2);
uint __thiscall lib_fn_4e23b0(void *this,uint param_1);
void __thiscall lib_fn_4e2400(void *this,uint param_1);
void Catch_All_004e24e4(void);
void __thiscall lib_fn_4e2500(void *this,uint param_1);
void Catch_All_004e25bc(void);
void Catch_All_004e269d(void);
int __thiscall lib_fn_4e26c0(void *this,uint param_1);
void __thiscall lib_fn_4e2730(void *this,uint param_1);
void __thiscall lib_fn_4e27b0(void *this,uint param_1);
int __fastcall lib_fn_4e2830(int param_1);
float * __cdecl lib_fn_4e2840(float *param_1,float *param_2);
bool __fastcall lib_fn_4e28d0(int *param_1);
/* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ /* WARNING: Removing unreachable block (ram,0x004e9862) */ /* WARNING: Removing unreachable block (ram,0x004e5295) */ /* WARNING: Removing unreachable block (ram,0x004e5269) */ /* WARNING: Removing unreachable block (ram,0x004e99b8) */ /* WARNING: Removing unreachable block (ram,0x004e9ab5) */ /* WARNING: Removing unreachable block (ram,0x004e9d1b) */ /* WARNING: Removing unreachable block (ram,0x004e9be8) */ /* WARNING: Removing unreachable block (ram,0x004e9932) */ /* WARNING: Removing unreachable block (ram,0x004e995b) */ /* WARNING: Removing unreachable block (ram,0x004e9ade) */ /* WARNING: Removing unreachable block (ram,0x004e9d44) */ /* WARNING: Removing unreachable block (ram,0x004e9c11) */ /* WARNING: Removing unreachable block (ram,0x004e99e1) */ /* WARNING: Removing unreachable block (ram,0x004e9db6) */ /* WARNING: Removing unreachable block (ram,0x004e9ddf) */ /* WARNING: Removing unreachable block (ram,0x004e9efa) */ void lib_fn_4e28e0(int param_1,uint *param_2);
void __thiscall lib_fn_4f2c50(void *this,undefined4 *param_1);
undefined4 * __cdecl lib_fn_4f2cd0(undefined4 *param_1,undefined4 *param_2,undefined4 param_3);
void __cdecl lib_fn_4f2ee0(void *param_1,uint *param_2,undefined4 param_3,int param_4);
undefined4 * __cdecl lib_fn_4f3490(undefined4 *param_1,undefined4 *param_2,undefined4 param_3);
int * __cdecl lib_fn_4f3630(int *param_1,int *param_2,int param_3);
undefined8 * __thiscall lib_fn_4f36f0(void *this,uint param_1);
void Catch_All_004f3803(void);
int __fastcall lib_fn_4f3820(int *param_1);
int __fastcall lib_fn_4f3840(int *param_1);
undefined8 __cdecl lib_fn_4f3850(uint param_1,uint param_2,uint param_3);
uint * __thiscall lib_fn_4f3880(void *this,byte *param_1);
undefined4 * __thiscall lib_fn_4f3b20(void *this,undefined4 *param_1);
undefined4 * __thiscall lib_fn_4f3b60(void *this,undefined4 *param_1);
int lib_fn_4f3ba0(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void __thiscall stl_fn_4f3c60(void *this,undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
undefined4 * __thiscall lib_fn_4f4080(void *this,undefined4 *param_1,int *param_2,int *param_3,int *param_4);
void Catch_All_004f427f(void);
undefined4 * __thiscall lib_fn_4f42d0(void *this,undefined4 *param_1,int *param_2,int *param_3,int *param_4);
void Catch_All_004f4505(void);
void __thiscall lib_fn_4f4560(void *this,undefined4 *param_1,char param_2,int *param_3,int *param_4);
void Catch_All_004f469e(void);
void __thiscall lib_fn_4f46c0(void *this,undefined4 *param_1,char param_2,int *param_3,int *param_4);
void Catch_All_004f483e(void);
undefined1 * __cdecl lib_fn_4f59f0(undefined4 *param_1,undefined4 *param_2,undefined1 *param_3);
void * __cdecl lib_fn_4f70f0(undefined4 *param_1,undefined4 *param_2,void *param_3);
void * __cdecl lib_fn_4f7130(int *param_1,int *param_2,void *param_3);
void Catch_All_004f71a6(void);
undefined4 * __cdecl lib_fn_4f7230(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void lib_fn_4f7270(undefined4 *param_1);
void __cdecl lib_fn_4f72d0(undefined1 *param_1,undefined1 *param_2,undefined1 *param_3);
void __cdecl lib_fn_4f72f0(undefined1 *param_1,undefined1 *param_2,undefined1 *param_3);
undefined4 * __fastcall lib_fn_4f7310(undefined4 *param_1);
undefined4 * __fastcall lib_fn_4f7330(undefined4 *param_1);
void __thiscall lib_fn_4f7350(void *this,undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
undefined4 * __thiscall lib_fn_4f7400(void *this,undefined4 *param_1);
undefined4 * __fastcall lib_fn_4f7490(undefined4 *param_1);
undefined4 * __fastcall lib_fn_4f7540(undefined4 *param_1);
undefined4 * __thiscall lib_fn_4f7620(void *this,undefined4 *param_1,undefined4 *param_2);
int * __thiscall lib_fn_4f7890(void *this,int *param_1);
int * __thiscall lib_fn_4f7910(void *this,int *param_1);
int __thiscall lib_fn_4f79b0(void *this,int param_1);
void __thiscall lib_fn_4f79d0(void *this,int *param_1);
uint * __thiscall lib_fn_4f79f0(void *this,uint *param_1,uint *param_2);
void __cdecl lib_fn_4f7a30(int *param_1,undefined4 param_2,uint *param_3);
void __thiscall lib_fn_4f7a70(void *this,float *param_1,float param_2);
uint lib_fn_4f7ab0(int *param_1,int *param_2);
undefined4 * __thiscall lib_fn_4f7ca0(void *this,int *param_1);
void __thiscall lib_fn_4f7d00(void *this,uint param_1);
void Catch_All_004f7dd4(void);
void __thiscall lib_fn_4f7df0(void *this,uint param_1);
void Catch_All_004f7ed1(void);
void Catch_All_004f7fbf(void);
void __thiscall lib_fn_4f7fe0(void *this,uint param_1);
void Catch_All_004f80af(void);
void __thiscall lib_fn_4f80d0(void *this,uint param_1);
void __thiscall lib_fn_4f8180(void *this,uint param_1);
float * __thiscall lib_fn_4f82d0(void *this,float *param_1,int param_2,int param_3);
undefined1 * __thiscall lib_fn_4f84a0(void *this,int param_1,int param_2,int param_3);
void __thiscall lib_fn_4f9010(void *this,int *param_1,int *param_2,int *param_3,int *param_4);
void __thiscall lib_fn_4f9450(void *this,undefined4 *param_1,float param_2,float param_3,int param_4,float param_5, float param_6,int param_7);
void __thiscall World_rockGroundBaseColor(void *this,float *param_1,float param_2,uint param_3,int param_4,int param_5);
void ** lib_fn_4fb480(int param_1,undefined4 param_2);
float10 __thiscall lib_fn_4fc100(void *param_1,float param_2,uint param_3,int param_4);
float10 __thiscall lib_fn_4fc140(void *param_1,uint param_2,uint param_3,int param_4);
void lib_fn_4fc180(int param_1);
void lib_fn_4fd920(int param_1);
void __cdecl lib_fn_4fdd80(int *param_1,undefined2 param_2);
void lib_fn_4fde90(int param_1);
void __thiscall lib_fn_4feec0(void *this,int param_1,int param_2);
void __cdecl lib_fn_4ff1a0(int param_1,uint *param_2,uint param_3,int param_4,int param_5,int param_6,int param_7);
void __thiscall lib_fn_4ff340(void *this,int param_1,int param_2,int param_3,int *param_4,undefined3 *param_5, int param_6);
void __thiscall lib_fn_4ff3f0(void *this,int param_1,int param_2,int param_3,int param_4,int param_5,int param_6, int param_7);
void __thiscall lib_fn_4ffbf0(void *this,int param_1,int param_2,int param_3,int param_4,int param_5,int param_6, int param_7);
/* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ void lib_fn_500300(uint param_1,undefined4 param_2,uint *param_3,uint *param_4,uint param_5, char param_6);
/* WARNING: Type propagation algorithm not settling */ void __thiscall stl_fn_509e40(void *this,int param_1,int param_2);
void lib_fn_50bd60(int param_1,int param_2,int param_3,float param_4,float param_5,undefined8 param_6 ,float param_7,undefined8 param_8,float param_9,int param_10,int param_11);
/* WARNING: Type propagation algorithm not settling */ void __thiscall lib_fn_50c550(void *this,uint param_1,uint param_2,int param_3);
void __thiscall lib_fn_50d260(void *this,int param_1);
void __thiscall stl_fn_50d8d0(void *this,int param_1,int param_2,int param_3);
void __thiscall lib_fn_5104e0(void *this,int param_1,uint *param_2,int *param_3);
void __thiscall lib_fn_513400(void *this,int param_1,int param_2,int param_3,int *param_4,byte *param_5,float param_6 ,int param_7,byte param_8);
/* WARNING: Removing unreachable block (ram,0x00516958) */ /* WARNING: Removing unreachable block (ram,0x005169f1) */ void lib_fn_513760(float param_1,uint param_2,float param_3,int param_4,int param_5,int param_6, int param_7);
/* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ void __thiscall World_buildVoxelColumn(void *this,float param_1,uint param_2);
int __cdecl lib_fn_521ed0(int param_1,int param_2,int param_3,int param_4,uint param_5,int *param_6,int *param_7);
float * lib_fn_522320(float *param_1,int param_2,int param_3);
void __thiscall lib_fn_522580(void *this,uint param_1,undefined4 param_2,int param_3);
undefined1 __fastcall lib_fn_522820(char *param_1);
void __thiscall lib_fn_5234b0(void *this,int *param_1,int *param_2);
void __thiscall lib_fn_5236d0(void *this,int *param_1,int *param_2,char param_3);
float10 __thiscall lib_fn_523b90(void *param_1,float param_2,uint param_3,int param_4,int param_5);
void World_landMask(uint param_1,float param_2,float param_3);
void __fastcall lib_fn_524500(int param_1);
/* WARNING: Type propagation algorithm not settling */ void __thiscall lib_fn_524540(void *this,void *param_1,uint *param_2,uint param_3,undefined4 param_4,int param_5, int param_6,char param_7,int *param_8,int param_9);
void __thiscall lib_fn_5283b0(void *this,undefined4 *param_1);
void __thiscall lib_fn_528400(void *this,undefined4 *param_1);
void __thiscall lib_fn_528450(void *this,undefined4 *param_1);
void __thiscall lib_fn_5284a0(void *this,undefined4 *param_1);
void __thiscall lib_fn_528530(void *this,undefined1 *param_1);
void __thiscall lib_fn_5285c0(void *this,int *param_1);
void __thiscall lib_fn_528730(void *this,undefined4 *param_1);
void __thiscall lib_fn_5287b0(void *this,int param_1,int param_2,char param_3);
void lib_fn_528bf0(void *param_1,undefined2 param_2,undefined1 param_3,int param_4);
/* WARNING: Type propagation algorithm not settling */ void * __thiscall lib_fn_5290d0(void *this,float param_1,float param_2,int param_3,undefined4 param_4);
void lib_fn_52a760(byte *param_1,undefined2 param_2,undefined1 param_3);
void __cdecl lib_fn_52a830(void *param_1,uint *param_2,uint param_3,int param_4);
/* WARNING: Type propagation algorithm not settling */ void * lib_fn_52ae10(void);
undefined1 * lib_fn_52b1c0(undefined1 *param_1);
undefined4 __thiscall lib_fn_52b230(void *this,int param_1,int param_2,int param_3);
undefined1 * __thiscall lib_fn_52b3f0(void *this,undefined1 *param_1);
void lib_fn_52b470(void *param_1,undefined2 param_2,int param_3);
int lib_fn_52bf40(int param_1,char param_2);
uint lib_fn_52bfa0(void);
undefined2 * __cdecl lib_fn_52c160(undefined2 *param_1,undefined2 param_2);
int * __cdecl lib_fn_52c370(int *param_1,undefined4 param_2,int *param_3,int param_4);
void lib_fn_52c4e0(void *param_1,undefined2 param_2,undefined1 param_3,int param_4);
float * __thiscall lib_fn_52d030(void *this,float *param_1,float param_2,uint param_3,int param_4,int param_5);
float * __thiscall lib_fn_52d5d0(void *this,float *param_1,int param_2,int param_3);
undefined4 __fastcall lib_fn_52d820(int param_1);
undefined4 __fastcall lib_fn_52d840(int param_1);
undefined4 __fastcall lib_fn_52d860(int param_1);
float * lib_fn_52d870(float *param_1,int param_2,int param_3);
float * __thiscall lib_fn_52db90(void *this,float *param_1,int param_2,int param_3,int param_4);
void __thiscall lib_fn_52dde0(void *this,int *param_1,int *param_2);
void __thiscall lib_fn_52de60(void *this,int *param_1,int *param_2);
bool __cdecl lib_fn_52df20(int *param_1,int *param_2);
int lib_fn_52df40(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void __thiscall lib_fn_52dfd0(void *this,undefined4 *param_1,undefined4 *param_2);
void Catch_All_0052e02c(void);
void __thiscall lib_fn_52e040(void *this,int *param_1,undefined4 param_2);
undefined4 * __cdecl lib_fn_52e0c0(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_0052e1bf(void);
void __cdecl lib_fn_52e1e0(int *param_1,int *param_2,int *param_3);
void __thiscall stl_fn_52e250(void *this,undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 *param_4);
undefined4 * __thiscall lib_fn_52e450(void *this,undefined4 *param_1,char param_2,uint *param_3,undefined4 param_4);
void Catch_All_0052e567(void);
void __thiscall lib_fn_52e590(void *this,undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_0052e617(void);
void __cdecl lib_fn_52e660(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void __cdecl lib_fn_52e710(float *param_1,float *param_2,int param_3,float param_4);
void __cdecl lib_fn_52e7c0(float *param_1,undefined8 *param_2,int param_3,float param_4);
undefined4 * __thiscall lib_fn_52e890(void *this,int *param_1);
void Catch_All_0052e906(void);
undefined4 * __fastcall lib_fn_52e930(undefined4 *param_1);
undefined4 * __thiscall lib_fn_52e950(void *this,int param_1);
void * __thiscall lib_fn_52e9e0(void *this,undefined4 *param_1);
int * __thiscall lib_fn_52ea70(void *this,int *param_1);
void Catch_All_0052eb79(void);
int __fastcall lib_fn_52eb90(int *param_1);
int __fastcall lib_fn_52eba0(int *param_1);
ulonglong * lib_fn_52ebb0(ulonglong *param_1);
void __thiscall lib_fn_52ebf0(void *this,undefined4 *param_1);
void __thiscall lib_fn_52ec10(void *this,int *param_1);
float * __thiscall lib_fn_52ec30(void *this,float *param_1);
undefined4 __fastcall lib_fn_52ec80(uint *param_1);
uint __thiscall lib_fn_52ecc0(void *this,uint param_1);
void Catch_All_0052ee5c(void);
void __thiscall lib_fn_530470(void *this,uint param_1,uint param_2,int param_3);
bool __fastcall lib_fn_530540(int param_1);
int __thiscall lib_fn_530560(void *this,uint *param_1);
void __thiscall lib_fn_5305b0(void *this,int *param_1,int *param_2);
int __fastcall lib_fn_530680(undefined4 *param_1);
void __thiscall lib_fn_530690(void *this,undefined4 *param_1,uint *param_2);
byte __fastcall lib_fn_5306c0(int param_1);
float10 __cdecl lib_fn_5306d0(float param_1,float param_2,float param_3);
void __thiscall lib_fn_5307f0(void *this,undefined4 *param_1);
void __thiscall lib_fn_5308b0(void *this,int param_1);
/* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ void GameController_updateSubsystems(uint param_1,int *param_2,void *param_3);
float10 __cdecl lib_fn_548b00(float param_1);
float10 __cdecl lib_fn_548b20(float param_1);
basic_istream<char,std::char_traits<char>_> * lib_fn_549200(basic_istream<char,std::char_traits<char>_> *param_1,undefined1 *param_2);
undefined * Catch_All_0054928d(void);
void lib_fn_5492ad(void);
void lib_fn_549300(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
basic_istream<char,std::char_traits<char>_> * __thiscall std::basic_filebuf<char,std::char_traits<char>_>::ctor_1 (basic_filebuf<char,std::char_traits<char>_> *this,char *param_1,uint param_2,int *param_3 ,int param_4);
basic_ostream<char,std::char_traits<char>_> * __thiscall std::basic_filebuf<char,std::char_traits<char>_>::ctor_2 (basic_filebuf<char,std::char_traits<char>_> *this,char *param_1,uint param_2,int *param_3 ,int param_4);
void __fastcall lib_fn_549550(int *param_1);
undefined4 * __thiscall std::_Func_base<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>::vfunc_5 (_Func_base<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> *this,byte param_1);
void __fastcall std:: _Func_impl<std::_Callable_obj<<lambda_00ca7a589ff1e281ef3a7159f4e6a134>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_2(int param_1);
void __fastcall std:: _Func_impl<std::_Callable_obj<<lambda_90aea85a8928b722e251ae835df30be1>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_2(int param_1);
void __thiscall std:: _Func_impl<std::_Callable_obj<<lambda_00ca7a589ff1e281ef3a7159f4e6a134>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_0(_Func_impl<std::_Callable_obj<<lambda_00ca7a589ff1e281ef3a7159f4e6a134>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> *this,undefined4 *param_1);
void __thiscall std:: _Func_impl<std::_Callable_obj<<lambda_90aea85a8928b722e251ae835df30be1>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_0(_Func_impl<std::_Callable_obj<<lambda_90aea85a8928b722e251ae835df30be1>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> *this,undefined4 *param_1);
TypeDescriptor * std:: _Func_impl<std::_Callable_obj<<lambda_00ca7a589ff1e281ef3a7159f4e6a134>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_3(void);
TypeDescriptor * std:: _Func_impl<std::_Callable_obj<<lambda_90aea85a8928b722e251ae835df30be1>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_3(void);
void std::basic_filebuf<char,std::char_traits<char>_>::ctor_0(void);
void inflate(void);
void inflateEnd(void);
void compress(void);
void inflateInit_(void);
void Ordinal_16(void);
void Ordinal_19(void);
void Ordinal_1(void);
void Ordinal_2(void);
void Ordinal_3(void);
void Ordinal_9(void);
void Ordinal_13(void);
void Ordinal_23(void);
void Ordinal_115(void);
void Ordinal_116(void);
void Sleep(DWORD dwMilliseconds);
BOOL DeleteFileA(LPCSTR lpFileName);
BOOL AreFileApisANSI(void);
void GetSystemTime(LPSYSTEMTIME lpSystemTime);
HLOCAL LocalFree(HLOCAL hMem);
DWORD GetTempPathA(DWORD nBufferLength,LPSTR lpBuffer);
DWORD GetCurrentProcessId(void);
BOOL DeleteFileW(LPCWSTR lpFileName);
BOOL CloseHandle(HANDLE hObject);
BOOL GetVersionExA(LPOSVERSIONINFOA lpVersionInformation);
BOOL GetFileAttributesExW (LPCWSTR lpFileName,GET_FILEEX_INFO_LEVELS fInfoLevelId,LPVOID lpFileInformation);
void GetSystemInfo(LPSYSTEM_INFO lpSystemInfo);
HANDLE CreateFileMappingW(HANDLE hFile,LPSECURITY_ATTRIBUTES lpFileMappingAttributes,DWORD flProtect ,DWORD dwMaximumSizeHigh,DWORD dwMaximumSizeLow,LPCWSTR lpName);
HMODULE LoadLibraryA(LPCSTR lpLibFileName);
BOOL LockFileEx(HANDLE hFile,DWORD dwFlags,DWORD dwReserved,DWORD nNumberOfBytesToLockLow, DWORD nNumberOfBytesToLockHigh,LPOVERLAPPED lpOverlapped);
FARPROC GetProcAddress(HMODULE hModule,LPCSTR lpProcName);
DWORD GetLastError(void);
DWORD GetTempPathW(DWORD nBufferLength,LPWSTR lpBuffer);
BOOL FlushFileBuffers(HANDLE hFile);
int MultiByteToWideChar(UINT CodePage,DWORD dwFlags,LPCSTR lpMultiByteStr,int cbMultiByte, LPWSTR lpWideCharStr,int cchWideChar);
HANDLE CreateFileW(LPCWSTR lpFileName,DWORD dwDesiredAccess,DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes,DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes,HANDLE hTemplateFile);
BOOL ReadFile(HANDLE hFile,LPVOID lpBuffer,DWORD nNumberOfBytesToRead,LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped);
DWORD GetFileAttributesW(LPCWSTR lpFileName);
DWORD GetFileAttributesA(LPCSTR lpFileName);
DWORD FormatMessageW(DWORD dwFlags,LPCVOID lpSource,DWORD dwMessageId,DWORD dwLanguageId, LPWSTR lpBuffer,DWORD nSize,va_list *Arguments);
HMODULE LoadLibraryW(LPCWSTR lpLibFileName);
int WideCharToMultiByte(UINT CodePage,DWORD dwFlags,LPCWSTR lpWideCharStr,int cchWideChar, LPSTR lpMultiByteStr,int cbMultiByte,LPCSTR lpDefaultChar, LPBOOL lpUsedDefaultChar);
BOOL WriteFile(HANDLE hFile,LPCVOID lpBuffer,DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten,LPOVERLAPPED lpOverlapped);
DWORD FormatMessageA(DWORD dwFlags,LPCVOID lpSource,DWORD dwMessageId,DWORD dwLanguageId, LPSTR lpBuffer,DWORD nSize,va_list *Arguments);
void GetSystemTimeAsFileTime(LPFILETIME lpSystemTimeAsFileTime);
BOOL UnlockFileEx(HANDLE hFile,DWORD dwReserved,DWORD nNumberOfBytesToUnlockLow, DWORD nNumberOfBytesToUnlockHigh,LPOVERLAPPED lpOverlapped);
DWORD GetTickCount(void);
BOOL LockFile(HANDLE hFile,DWORD dwFileOffsetLow,DWORD dwFileOffsetHigh, DWORD nNumberOfBytesToLockLow,DWORD nNumberOfBytesToLockHigh);
BOOL UnlockFile(HANDLE hFile,DWORD dwFileOffsetLow,DWORD dwFileOffsetHigh, DWORD nNumberOfBytesToUnlockLow,DWORD nNumberOfBytesToUnlockHigh);
BOOL QueryPerformanceCounter(LARGE_INTEGER *lpPerformanceCount);
BOOL FreeLibrary(HMODULE hLibModule);
BOOL SetEndOfFile(HANDLE hFile);
BOOL UnmapViewOfFile(LPCVOID lpBaseAddress);
LPVOID MapViewOfFile(HANDLE hFileMappingObject,DWORD dwDesiredAccess,DWORD dwFileOffsetHigh, DWORD dwFileOffsetLow,SIZE_T dwNumberOfBytesToMap);
DWORD SetFilePointer(HANDLE hFile,LONG lDistanceToMove,PLONG lpDistanceToMoveHigh,DWORD dwMoveMethod );
DWORD GetFileSize(HANDLE hFile,LPDWORD lpFileSizeHigh);
HANDLE CreateFileA(LPCSTR lpFileName,DWORD dwDesiredAccess,DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes,DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes,HANDLE hTemplateFile);
DWORD GetFullPathNameA(LPCSTR lpFileName,DWORD nBufferLength,LPSTR lpBuffer,LPSTR *lpFilePart);
DWORD GetFullPathNameW(LPCWSTR lpFileName,DWORD nBufferLength,LPWSTR lpBuffer,LPWSTR *lpFilePart);
/* Library Function - Multiple Matches With Same Base Name private: static void __cdecl std::locale::facet::_Facet_Register(class std::locale::facet *) void __cdecl std::_Facet_Register(class std::_Facet_base *) Libraries: Visual Studio 2010 Release, Visual Studio 2012 Release */ void __cdecl Facet_Register(undefined4 param_1);
void __thiscall std::basic_streambuf<wchar_t,std::char_traits<wchar_t>_>::_Lock (basic_streambuf<wchar_t,std::char_traits<wchar_t>_> *this);
void __thiscall std::basic_streambuf<wchar_t,std::char_traits<wchar_t>_>::_Unlock (basic_streambuf<wchar_t,std::char_traits<wchar_t>_> *this);
void __thiscall std::basic_streambuf<wchar_t,std::char_traits<wchar_t>_>::imbue (basic_streambuf<wchar_t,std::char_traits<wchar_t>_> *this,locale *param_1);
basic_streambuf<wchar_t,struct_std::char_traits<wchar_t>_> * __thiscall std::basic_streambuf<wchar_t,std::char_traits<wchar_t>_>::setbuf (basic_streambuf<wchar_t,std::char_traits<wchar_t>_> *this,wchar_t *param_1, __int64 param_2);
__int64 __thiscall std::basic_streambuf<wchar_t,std::char_traits<wchar_t>_>::showmanyc (basic_streambuf<wchar_t,std::char_traits<wchar_t>_> *this);
int __thiscall std::basic_streambuf<wchar_t,std::char_traits<wchar_t>_>::sync (basic_streambuf<wchar_t,std::char_traits<wchar_t>_> *this);
ushort __thiscall std::basic_streambuf<wchar_t,std::char_traits<wchar_t>_>::uflow (basic_streambuf<wchar_t,std::char_traits<wchar_t>_> *this);
__int64 __thiscall std::basic_streambuf<wchar_t,std::char_traits<wchar_t>_>::xsgetn (basic_streambuf<wchar_t,std::char_traits<wchar_t>_> *this,wchar_t *param_1, __int64 param_2);
__int64 __thiscall std::basic_streambuf<wchar_t,std::char_traits<wchar_t>_>::xsputn (basic_streambuf<wchar_t,std::char_traits<wchar_t>_> *this,wchar_t *param_1, __int64 param_2);
void __thiscall std::basic_ios<char,std::char_traits<char>_>::_Add_vtordisp1 (basic_ios<char,std::char_traits<char>_> *this);
void __thiscall std::basic_ios<char,std::char_traits<char>_>::_Add_vtordisp2 (basic_ios<char,std::char_traits<char>_> *this);
__int64 __thiscall std::basic_streambuf<char,std::char_traits<char>_>::showmanyc (basic_streambuf<char,std::char_traits<char>_> *this);
__int64 __thiscall std::basic_streambuf<char,std::char_traits<char>_>::xsgetn (basic_streambuf<char,std::char_traits<char>_> *this,char *param_1,__int64 param_2);
__int64 __thiscall std::basic_streambuf<char,std::char_traits<char>_>::xsputn (basic_streambuf<char,std::char_traits<char>_> *this,char *param_1,__int64 param_2);
void __thiscall std::basic_streambuf<char,std::char_traits<char>_>::_Lock (basic_streambuf<char,std::char_traits<char>_> *this);
void __thiscall std::basic_streambuf<char,std::char_traits<char>_>::_Unlock (basic_streambuf<char,std::char_traits<char>_> *this);
void __thiscall std::basic_streambuf<char,std::char_traits<char>_>::imbue (basic_streambuf<char,std::char_traits<char>_> *this,locale *param_1);
basic_streambuf<char,struct_std::char_traits<char>_> * __thiscall std::basic_streambuf<char,std::char_traits<char>_>::setbuf (basic_streambuf<char,std::char_traits<char>_> *this,char *param_1,__int64 param_2);
int __thiscall std::basic_streambuf<char,std::char_traits<char>_>::sync (basic_streambuf<char,std::char_traits<char>_> *this);
int __thiscall std::basic_streambuf<char,std::char_traits<char>_>::uflow (basic_streambuf<char,std::char_traits<char>_> *this);
void __cdecl purecall(void);
void * __cdecl operator_new(uint param_1);
void __cdecl operator_delete(void *param_1);
/* WARNING: Function: __SEH_prolog4 replaced with injection: SEH_prolog4 */ /* WARNING: Function: __SEH_epilog4 replaced with injection: EH_epilog3 */ /* Library Function - Single Match __onexit Library: Visual Studio 2012 Release */ _onexit_t __cdecl __onexit(_onexit_t param_1);
void lib_fn_54a89a(void);
/* Library Function - Single Match _atexit Library: Visual Studio 2012 Release */ int __cdecl _atexit(_func_4879 *param_1);
/* Library Function - Single Match @eh_security_check_cookie_4 Library: Visual Studio 2012 Release __fastcall __security_check_cookie,4 */ void __fastcall __security_check_cookie(int param_1);
void _CxxThrowException(void *pExceptionObject,ThrowInfo *pThrowInfo);
/* WARNING: This is an inlined function */ void __alloca_probe(void);
void __cdecl libm_sse2_asin_precise(void);
void __cdecl libm_sse2_cos_precise(void);
void __cdecl libm_sse2_sin_precise(void);
void __cdecl libm_sse2_sqrt_precise(void);
void * __cdecl memcpy(void *_Dst,void *_Src,size_t _Size);
/* Library Function - Multiple Matches With Different Base Names public: virtual void * __thiscall CDaoRelationFieldInfo::`vector deleting destructor'(unsigned int) public: virtual void * __thiscall type_info::`vector deleting destructor'(unsigned int) Library: Visual Studio 2012 Release */ type_info * __thiscall FID_conflict__vector_deleting_destructor_(void *this,byte param_1);
/* Library Function - Single Match __alldiv Libraries: Visual Studio 2012 Release, Visual Studio 2015 Release, Visual Studio 2017 Release, Visual Studio 2019 Release */ undefined8 __alldiv(uint param_1,uint param_2,uint param_3,uint param_4);
/* Library Function - Single Match __allmul Library: Visual Studio */ longlong __allmul(uint param_1,int param_2,uint param_3,int param_4);
void __cdecl libm_sse2_pow_precise(void);
void * __cdecl memset(void *_Dst,int _Val,size_t _Size);
void __cdecl setjmp3(void);
/* Library Function - Single Match ___raise_securityfailure Library: Visual Studio 2012 Release */ void __cdecl ___raise_securityfailure(EXCEPTION_POINTERS *param_1);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ /* Library Function - Single Match ___report_gsfailure Library: Visual Studio 2012 Release */ void __cdecl ___report_gsfailure(void);
/* Library Function - Single Match ___report_rangecheckfailure Libraries: Visual Studio 2012 Release, Visual Studio 2017 Release, Visual Studio 2019 Release */ void ___report_rangecheckfailure(void);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ /* Library Function - Single Match ___report_securityfailure Library: Visual Studio 2012 Release */ void __cdecl ___report_securityfailure(undefined4 param_1);
void __cdecl operator_delete__(void *param_1);
/* WARNING: Function: __SEH_prolog4 replaced with injection: SEH_prolog4 */ /* WARNING: Function: __SEH_epilog4 replaced with injection: EH_epilog3 */ /* Library Function - Single Match void __stdcall __ArrayUnwind(void *,unsigned int,int,void (__thiscall*)(void *)) Library: Visual Studio 2012 Release */ void __ArrayUnwind(void *param_1,uint param_2,int param_3,_func_void_void_ptr *param_4);
/* Library Function - Single Match __alldvrm Library: Visual Studio */ undefined8 __alldvrm(uint param_1,uint param_2,uint param_3,uint param_4);
/* Library Function - Single Match __allrem Library: Visual Studio */ undefined8 __allrem(uint param_1,uint param_2,uint param_3,uint param_4);
/* Library Function - Single Match __allshl Library: Visual Studio */ longlong __fastcall __allshl(byte param_1,int param_2);
/* Library Function - Single Match __aulldiv Library: Visual Studio */ undefined8 __aulldiv(uint param_1,uint param_2,uint param_3,uint param_4);
/* Library Function - Single Match __aulldvrm Library: Visual Studio */ undefined8 __aulldvrm(uint param_1,uint param_2,uint param_3,uint param_4);
/* Library Function - Single Match __aullrem Library: Visual Studio */ undefined8 __aullrem(uint param_1,uint param_2,uint param_3,uint param_4);
void __cdecl libm_sse2_acos_precise(void);
void __cdecl libm_sse2_exp_precise(void);
/* WARNING: Function: __SEH_prolog4 replaced with injection: SEH_prolog4 */ /* WARNING: Function: __SEH_epilog4 replaced with injection: EH_epilog3 */ /* Library Function - Single Match ___tmainCRTStartup Library: Visual Studio 2012 Release */ int ___tmainCRTStartup(void);
void __cdecl _lock(int _File);
void __cdecl _unlock(int _File);
void __dllonexit(void);
/* WARNING: This is an inlined function */ /* WARNING: Unable to track spacebase fully for stack */ /* WARNING: Variable defined which should be unmapped: param_2 */ /* Library Function - Single Match __SEH_prolog4 Library: Visual Studio */ void __cdecl __SEH_prolog4(undefined4 param_1,int param_2);
/* WARNING: This is an inlined function */ /* Library Function - Single Match __SEH_epilog4 Library: Visual Studio */ void __SEH_epilog4(void);
/* WARNING: Removing unreachable block (ram,0x0054b5d6) */ /* WARNING: Removing unreachable block (ram,0x0054b5a6) */ /* WARNING: Removing unreachable block (ram,0x0054b51c) */ /* WARNING: Removing unreachable block (ram,0x0054b57a) */ /* Library Function - Single Match ___isa_available_init Library: Visual Studio 2012 Release */ undefined4 ___isa_available_init(void);
void __thiscall type_info::~type_info(type_info *this);
void __cdecl _crt_debugger_hook(int param_1);
LONG __cdecl __crtUnhandledException(EXCEPTION_POINTERS *exceptionInfo);
void __cdecl __crtTerminateProcess(UINT uExitCode);
void __cdecl terminate(void);
int __cdecl _XcptFilter(ulong _ExceptionNum,_EXCEPTION_POINTERS *_ExceptionPtr);
void __cdecl _amsg_exit(int param_1);
/* Library Function - Single Match __FindPESection Library: Visual Studio 2012 Release */ PIMAGE_SECTION_HEADER __cdecl __FindPESection(PBYTE pImageBase,DWORD_PTR rva);
/* Library Function - Single Match __IsNonwritableInCurrentImage Library: Visual Studio 2012 Release */ BOOL __cdecl __IsNonwritableInCurrentImage(PBYTE pTarget);
/* Library Function - Single Match __ValidateImageBase Libraries: Visual Studio 2012 Release, Visual Studio 2015 Release */ BOOL __cdecl __ValidateImageBase(PBYTE pImageBase);
/* Library Function - Single Match ___security_init_cookie Library: Visual Studio 2012 Release */ void __cdecl ___security_init_cookie(void);
void __cdecl initterm_e(void);
void __cdecl initterm(void);
void __cdecl except_handler4_common(void);
void __cdecl __crtSetUnhandledExceptionFilter(LPTOP_LEVEL_EXCEPTION_FILTER exceptionFilter);
void __cdecl _invoke_watson(wchar_t *param_1,wchar_t *param_2,wchar_t *param_3,uint param_4,uintptr_t param_5);
errno_t __cdecl _controlfp_s(uint *_CurrentState,uint _NewValue,uint _Mask);
BOOL IsProcessorFeaturePresent(DWORD ProcessorFeature);
void std::error_category::ctor_0(void);
void std::error_category::ctor_1(void);
void std::error_category::ctor_2(void);

#endif
