// audit (cube) — reconstructed declarations.
#ifndef CUBE__LIBRARY_AUDIT_H
#define CUBE__LIBRARY_AUDIT_H
#include "../include/cube_types.h"

byte OggPage_continued(int *param_1);
byte OggPage_bos(int *param_1);
byte OggPage_eos(int *param_1);
undefined8 OggPage_granulepos(int *param_1);
undefined4 OggPage_serialno(int *param_1);
undefined4 OggStream_init(undefined4 *param_1,undefined4 param_2);
undefined4 OggStream_clear(undefined4 *param_1);
undefined4 OggStream_lacingExpand(void);
void OggPage_checksumSet(void);
undefined4 OggSync_reset(undefined8 *param_1);
undefined4 OggBuffer_free(undefined8 *param_1);
int OggSync_buffer(int *param_1,int param_2);
undefined4 OggSync_wrote(int param_1,int param_2);
int OggSync_pageseek(int *param_1,int *param_2);
undefined4 OggStream_pagein(int *param_1,int *param_2);
undefined4 OggSync_reset2(int param_1);
undefined4 OggStream_reset(int *param_1);
undefined4 OggStream_resetSerialno(int *param_1,int param_2);
undefined4 OggStream_packetOut_impl(int param_1);
undefined4 OggStream_packetout(int *param_1);
undefined4 OggStream_packetpeek(int *param_1,int *param_2);
int RBTreeNode_createString(undefined4 param_1);
void RBTree_insertRebalance(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
undefined4 * map_insertUnique(undefined4 *param_1,int *param_2,undefined4 *param_3,undefined4 param_4);
void map_insertHint(undefined4 *param_1,char param_2,byte *param_3,void *param_4);
void map_insertOrAssignStr(uint *param_1);
void map_findOrInsertEmpty(int param_1);
undefined4 * RBTreeNode_alloc(void);
void vector_fillN(int param_1,undefined4 *param_2);
void RBTree_eraseRecursive(void *param_1);
undefined4 * map_lowerBound(byte *param_1);
void strstreambuf_tidy(void);
void map_insertNode(int param_1,int param_2);
undefined4 * map_eraseRange(undefined4 *param_1,int *param_2,int *param_3);
/* WARNING: Removing unreachable block (ram,0x0040c91d) */ /* WARNING: Removing unreachable block (ram,0x0040c92d) */ /* WARNING: Removing unreachable block (ram,0x0040c936) */ /* WARNING: Removing unreachable block (ram,0x0040c939) */ /* WARNING: Removing unreachable block (ram,0x0040c929) */ /* WARNING: Removing unreachable block (ram,0x0040c947) */ /* WARNING: Removing unreachable block (ram,0x0040c956) */ /* WARNING: Removing unreachable block (ram,0x0040c961) */ /* WARNING: Removing unreachable block (ram,0x0040c95d) */ /* WARNING: Removing unreachable block (ram,0x0040c951) */ /* WARNING: Removing unreachable block (ram,0x0040c964) */ void RBTree_eraseNode(undefined4 param_1,int *param_2);
undefined4 wostream_insertNarrow_unwind(void);
int wostream_insertWide_unwind(void);
void u16string_moveConstruct(undefined4 *param_1);
void u16string_assignCStr(short *param_1);
void u16string_defaultInit(void);
void u16string_move(undefined4 *param_1);
void u16string_grow(uint param_1,int param_2);
void u16string_setEos(int param_1);
bool u16string_resize(uint param_1,char param_2);
void strstreambuf_init(void *param_1,uint param_2,undefined4 param_3);
undefined4 * u16string_data(void);
void u16string_replaceRange(int *param_1,uint param_2,uint param_3);
void u16string_assignPtrLen(int *param_1,uint param_2);
void u16string_erase(uint param_1,uint param_2);
void strstreambuf_initWrap(undefined4 *param_1);
basic_ostream<wchar_t,std::char_traits<wchar_t>_> * wostream_insertU16string(basic_ostream<wchar_t,std::char_traits<wchar_t>_> *param_1,wchar_t *param_2);
void wostream_insertU16string_unwind(void);
void u16string_assignCharRange(char *param_1,char *param_2);
void u16string_fillAssign(int param_1,uint param_2,undefined2 param_3);
void u16string_append(uint param_1,undefined4 param_2);
bool u16string_equals(int param_1,undefined4 *param_2);
int RBTree_next(int param_1);
uint u16string_compare(uint param_1,uint param_2,ushort *param_3,uint param_4);
void resizeChildBuffers_type16(undefined4 param_1);
void std_vector_resize(uint param_1);
void std_vector_resize_42bf80(uint param_1);
int std_vector_size(void);
void rbtree_iteratorIncrement(void);
void rbtree_destroyRec_buf(void *param_1);
void rbtree_destroyRec_simple(void *param_1);
void rbtree_rotate(int *param_1);
bool wstring_equalsCI(int param_1,short *param_2);
bool wstring_notEquals(int param_1,short *param_2);
void rbtree_allocNode24(undefined4 *param_1,undefined4 *param_2);
void wstring_dataPtr(undefined4 *param_1);
void wstring_replace(undefined4 *param_1,undefined4 *param_2,uint param_3,uint param_4);
undefined2 * wstring_ctorFromRange(undefined2 *param_1,undefined4 param_2,undefined4 param_3);
void rbtree_allocHead24(void);
void rbtree_destroyRec_str(void *param_1);
/* WARNING: Removing unreachable block (ram,0x0043eea2) */ /* WARNING: Removing unreachable block (ram,0x0043eeb2) */ /* WARNING: Removing unreachable block (ram,0x0043eebb) */ /* WARNING: Removing unreachable block (ram,0x0043eebe) */ /* WARNING: Removing unreachable block (ram,0x0043eeae) */ /* WARNING: Removing unreachable block (ram,0x0043eecc) */ /* WARNING: Removing unreachable block (ram,0x0043eed8) */ /* WARNING: Removing unreachable block (ram,0x0043eee3) */ /* WARNING: Removing unreachable block (ram,0x0043eedf) */ /* WARNING: Removing unreachable block (ram,0x0043eed3) */ /* WARNING: Removing unreachable block (ram,0x0043eee6) */ void rbtree_eraseNode(undefined4 param_1,int *param_2);
undefined4 * rbtree_eraseRange_str(undefined4 *param_1,int *param_2,int *param_3);
/* WARNING: Removing unreachable block (ram,0x0043f1cd) */ /* WARNING: Removing unreachable block (ram,0x0043f1dd) */ /* WARNING: Removing unreachable block (ram,0x0043f1e6) */ /* WARNING: Removing unreachable block (ram,0x0043f1e9) */ /* WARNING: Removing unreachable block (ram,0x0043f1d9) */ /* WARNING: Removing unreachable block (ram,0x0043f1f7) */ /* WARNING: Removing unreachable block (ram,0x0043f206) */ /* WARNING: Removing unreachable block (ram,0x0043f211) */ /* WARNING: Removing unreachable block (ram,0x0043f20d) */ /* WARNING: Removing unreachable block (ram,0x0043f201) */ /* WARNING: Removing unreachable block (ram,0x0043f214) */ void rbtree_eraseNode_str(undefined4 param_1,int *param_2);
undefined4 * rbtree_eraseRange_buf(undefined4 *param_1,int *param_2,int *param_3);
/* WARNING: Removing unreachable block (ram,0x0043f53d) */ /* WARNING: Removing unreachable block (ram,0x0043f54d) */ /* WARNING: Removing unreachable block (ram,0x0043f556) */ /* WARNING: Removing unreachable block (ram,0x0043f559) */ /* WARNING: Removing unreachable block (ram,0x0043f549) */ /* WARNING: Removing unreachable block (ram,0x0043f567) */ /* WARNING: Removing unreachable block (ram,0x0043f576) */ /* WARNING: Removing unreachable block (ram,0x0043f581) */ /* WARNING: Removing unreachable block (ram,0x0043f57d) */ /* WARNING: Removing unreachable block (ram,0x0043f571) */ /* WARNING: Removing unreachable block (ram,0x0043f584) */ void rbtree_eraseNode_buf(undefined4 param_1,int *param_2);
void rbtree_lowerBound(int *param_1,int *param_2);
void rbtree_traverseInorder(void);
/* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ void zlib_inflateBuffer(int *param_1,int *param_2);
int vector_uninitCopy_0x148(int param_1,int param_2,int param_3);
int vector_destroyRange_0xc(int param_1,int param_2,int param_3);
undefined4 vector_equal_0x148(int param_1,int param_2,int param_3);
void rbtree_insertRebalance_0x148node(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
undefined4 * map_insertUnique_findPos(undefined4 *param_1,int *param_2,undefined4 param_3,undefined4 param_4);
void map_lowerBoundInsert_strKey(undefined4 *param_1,int *param_2,int *param_3,void *param_4);
undefined4 * vector_uninitCopy_0x11c(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
int vector_destroyRange_0xc_seh(int param_1,int param_2,int param_3);
undefined4 * vector_uninitCopy_0x11c_ee70(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void vector_defaultInit_0x11c(int param_1,int param_2);
undefined4 * vector_uninitCopy_0x14(undefined1 *param_1,undefined1 *param_2,undefined4 *param_3);
undefined4 * vector_uninitCopy_0x11c_ee70b(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
int vector_uninitCopy_0x148_a8c0(int param_1,int param_2,int param_3);
void vector_copyAssign_0x11c(int *param_1);
void vector_assignFrom_0x11c(int *param_1);
void vector_assignFrom_0x148(int *param_1);
int * vector_assignFrom_0xc(int *param_1);
int vector_at_0x188(int param_1);
void vector_pushBackSlot_0x148(int *param_1);
uint vector_buyAlloc_0x11c(uint param_1);
uint vector_buyAlloc_0x148(uint param_1);
undefined4 vector_buyAlloc_0xc(uint param_1);
void list_allocSentinel_0x48(void);
uint vector_growCap_0x148(uint param_1);
void vector_reallocInsert_0x14(uint param_1);
void vector_reallocInsert_0x11c(void *param_1);
void vector_reallocInsert_0x148(void *param_1);
void vector_reserveGrow_0x14(uint param_1);
int vector_reserveGrow_0x11c(uint param_1);
void vector_reserveGrow_0x148(uint param_1);
void vector_clear(void);
void list_pushBack_0x48(undefined4 param_1);
void vector_insertSelfaware_0x14(undefined4 *param_1);
void vector_pushBack_0x148(uint param_1);
int vector_resize_0x11c(uint param_1);
void tilemap_writeGlyphColumn(undefined4 param_1,undefined4 param_2,int param_3,undefined *param_4, undefined4 param_5);
int vector_size_0x188(void);
undefined4 wstring_assign(undefined4 param_1,undefined4 param_2,short *param_3);
undefined4 * wstring_ctorAppend(undefined4 *param_1,int param_2,short *param_3);
void map_insertVal_5x64payload(undefined4 param_1,undefined4 param_2,undefined8 *param_3);
int map_insertVal_strPayload(undefined4 param_1,undefined4 param_2,undefined4 *param_3);
void map_insertVal_3x64payload(undefined4 param_1,undefined4 param_2,undefined8 *param_3);
int map_insertVal_465c00(undefined4 param_1,undefined4 param_2,undefined4 param_3);
int map_insertVal_4594c0(undefined4 param_1,undefined4 param_2,undefined4 param_3);
int map_insertVal_4595b0(undefined4 param_1,undefined4 param_2,undefined4 param_3);
int map_insertVal_0x18payload(undefined4 param_1,undefined4 param_2,undefined4 *param_3);
int map_insertVal_4599a0(undefined4 param_1,undefined4 param_2,undefined4 param_3);
int map_insertVal_1val(undefined4 param_1,undefined4 param_2,undefined4 *param_3);
int map_insertVal_4591b0(undefined4 param_1,undefined4 param_2,undefined4 *param_3);
int map_insertVal_12dword(undefined4 param_1,undefined4 param_2,undefined4 *param_3);
int map_insertVal_00468670(undefined4 param_1,undefined4 param_2,undefined4 *param_3);
int map_insertVal_00465ce0(undefined4 param_1,undefined4 param_2,undefined4 param_3);
int map_insertVal_00465e60(undefined4 param_1,undefined4 param_2,undefined4 param_3);
int map_insertVal_00466410(undefined4 param_1,undefined4 param_2,undefined4 param_3);
int map_insertVal_0044a8c0(undefined4 param_1,undefined4 param_2,undefined4 param_3);
int map_insertVal_strKey(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void wstring_assignFromShortRange(undefined1 *param_1,undefined1 *param_2);
void map_copyAssignTree(int *param_1,undefined4 param_2);
int vector_uninitCopy_0x11c_5e0(int param_1,int param_2,int param_3);
undefined4 * list_copyRange_004572c0(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
undefined4 * rbtree_copyRecursive(undefined4 *param_1,undefined4 param_2,undefined4 param_3);
void vector_insertRangeFromList_0x10(int param_1,int *param_2,int *param_3);
void vector_insertRangeFromList_0x148(int param_1,int *param_2,int *param_3);
void rbtree_insertRebalance_A(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
void rbtree_insertRebalance_mapset(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
undefined4 * map_insertHint_intKey(undefined4 *param_1,int *param_2,int *param_3,undefined4 param_4);
undefined4 * map_insertHint_strKey(undefined4 *param_1,int *param_2,undefined4 *param_3,undefined4 param_4);
undefined4 * map_insertHint_2intKey(undefined4 *param_1,int *param_2,uint *param_3,undefined4 param_4);
void map_lowerBoundInsert_intKey(undefined4 *param_1,char param_2,int *param_3,void *param_4);
void map_lowerBoundInsert_strKey_4539e0(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3,undefined4 param_4);
void map_lowerBoundInsert_2intKey(undefined4 *param_1,char param_2,uint *param_3,void *param_4);
undefined4 * map_findOrInsert_2intKey(undefined4 *param_1,char param_2,uint *param_3,undefined4 param_4);
void list_assignRange_00608a20(int param_1,undefined4 *param_2,undefined4 *param_3);
void list_assignRange_00451da0(int param_1,undefined4 *param_2,undefined4 *param_3);
void list_assignRange_00451ee0(int param_1,undefined4 *param_2,undefined4 *param_3);
void list_assignRange_004e0300(int param_1,undefined4 *param_2,undefined4 *param_3);
void list_assignRange_00452190(int param_1,undefined4 *param_2,undefined4 *param_3);
void list_assignRange_004cb5a0(int param_1,undefined4 *param_2,undefined4 *param_3);
void list_assignRange_00451c70(int param_1,undefined4 *param_2,undefined4 *param_3);
void list_assignRange_00451e80(int param_1,undefined4 *param_2,undefined4 *param_3);
void list_assignRange_00451f50(int param_1,undefined4 *param_2,undefined4 *param_3);
void list_assignRange_00451cc0(int param_1,undefined4 *param_2,undefined4 *param_3);
void list_assignRange_00451d40(int param_1,undefined4 *param_2,undefined4 *param_3);
void list_assignRange_00452060(int param_1,undefined4 *param_2,undefined4 *param_3);
void list_assignRange_004520d0(int param_1,undefined4 *param_2,undefined4 *param_3);
void list_assignRange_0058d860(int param_1,undefined4 *param_2,undefined4 *param_3);
void introsort_insertionPass_0x128(byte *param_1,byte *param_2);
void introsort_0x128(int param_1,int param_2,int param_3,undefined4 param_4);
void introsort_0xc(int param_1,int param_2,int param_3,undefined4 param_4);
void heapSort_0x128(int param_1,int param_2,undefined4 param_3);
void heapSort_0xc(undefined8 *param_1,int param_2,undefined4 param_3);
int vector_uninitCopy_0x11c_guarded(int param_1,int param_2,int param_3);
int vector_destroyRange_8_seh(int param_1,int param_2,int param_3);
void list_copyNodesToArray_0x10(int *param_1,int *param_2,int *param_3);
int vector_destroyListRange_0x148(int *param_1,int *param_2,int param_3);
int vector_uninitCopy_0x11c_g2(int param_1,int param_2,int param_3);
int vector_destroyRange_0xc_seh2(int param_1,int param_2,int param_3);
undefined4 * list_copyNodesToVector_0x10(int param_1,int param_2,undefined4 *param_3);
int vector_destroyRange_0x128_seh(int param_1,int param_2,int param_3);
void list_assignReuse_005c03f0(undefined4 *param_1,undefined4 *param_2);
void list_assignReuse_00449b70(undefined4 *param_1,undefined4 *param_2);
void list_assignReuse_004e0300(undefined4 *param_1,undefined4 *param_2);
void map_eraseNode_004dc5b0(undefined4 *param_1,int param_2,undefined4 param_3,undefined4 param_4);
void map_eraseNode_004544d0(undefined4 *param_1,int param_2,undefined4 param_3,undefined4 param_4);
void vector_eraseElem_0x10(int *param_1,int param_2,undefined4 param_3,undefined4 param_4);
void map_eraseNode_004dc4e0(undefined4 *param_1,int param_2,undefined4 param_3,undefined4 param_4);
void map_eraseNode_004545a0(undefined4 *param_1,int param_2,undefined4 param_3,undefined4 param_4);
void map_eraseNode_00454670(undefined4 *param_1,int param_2,undefined4 param_3,undefined4 param_4);
void map_eraseNode_00454740(undefined4 *param_1,int param_2,undefined4 param_3,undefined4 param_4);
void map_eraseNode_00454810(undefined4 *param_1,int param_2,undefined4 param_3,undefined4 param_4);
void map_eraseNode_004548e0(undefined4 *param_1,int param_2,undefined4 param_3,undefined4 param_4);
void map_eraseNode_004549b0(undefined4 *param_1,int param_2,undefined4 param_3,undefined4 param_4);
void map_eraseNode_00454a80(undefined4 *param_1,int param_2,undefined4 param_3,undefined4 param_4);
void vector_eraseElem_0x148(int *param_1,int param_2,undefined4 param_3,undefined4 param_4);
void sortEntry_introsort_0xc(int param_1,int param_2,undefined4 param_3);
void std_list_copyConstruct_nodeSz18(undefined4 *param_1);
void std_list_copyConstruct_nodeSz30(undefined4 *param_1);
void std_list_copyConstruct_nodeSz150(undefined4 *param_1);
void std_list_copyConstruct_nodeSz_ccbf0(undefined4 *param_1);
void std_vector_assign_stride11c(int *param_1);
void std_vector_assign_stride0c(int *param_1);
void std_vector_ctor_fillFrom(undefined4 param_1,undefined4 param_2);
void Store_ftol64_result(void);
void list_dtor_freeHeadAt8(void);
void list_dtor_freeHeadAt51a0(void);
void u16string_clear_off38(void);
void list_dtor_freeHeadAt60(void);
int Vector_storeElementAt20(undefined4 *param_1);
int Vector_end_stride18_freeStr(int param_1);
void u16string_moveClear(undefined4 *param_1);
void u16string_assignFromWide(short *param_1);
void std_vector_copyAssign_stride11c(int *param_1);
void std_vector_copyAssign_vecElem8(int *param_1);
void std_vector_copyAssign_elem8_b(int *param_1);
void std_vector_copyAssign_stride18(int *param_1);
int * rbtree_findOrInsert_intKey(int *param_1);
void rbtree_eraseByStringKey(int param_1);
uint * rbtree_findOrInsert_pairKey(uint *param_1);
int vector_at_stride4(int param_1);
int vector_at_stride8(int param_1);
void list_popFront_node(undefined4 *param_1);
void fixed_sub_ftol_64(int *param_1,undefined4 param_2,uint *param_3);
void fixed_sub_ftol_rev64(int *param_1);
undefined4 std_vector_reserveAlloc_stride8(uint param_1);
void rbtree_allocHeaderNode_1c(void);
void rbtree_allocHeaderNode_28(void);
void list_buyNode_0c(undefined4 *param_1,undefined4 *param_2);
void list_buyNode_18(undefined4 *param_1,undefined4 *param_2);
void list_buyNode_78(undefined4 *param_1,undefined4 *param_2);
void list_buyNode_28(undefined4 *param_1,undefined4 *param_2);
void list_buyNode_1c(undefined4 *param_1,undefined4 *param_2);
void list_buyNode_124(undefined4 *param_1,undefined4 *param_2);
void list_buyNode_128(undefined4 *param_1,undefined4 *param_2);
void list_buyNode_38(undefined4 *param_1,undefined4 *param_2);
void list_buyNode_40(undefined4 *param_1,undefined4 *param_2);
void list_buyNode_60(undefined4 *param_1,undefined4 *param_2);
void list_buyNode_c0(undefined4 *param_1,undefined4 *param_2);
void list_buyNode_50(undefined4 *param_1,undefined4 *param_2);
void list_buyNode_30(undefined4 *param_1,undefined4 *param_2);
void list_buyNode_68(undefined4 *param_1,undefined4 *param_2);
void list_buyNode_150(undefined4 *param_1,undefined4 *param_2);
undefined4 * rbtree_buyNode_copyKey20(void);
undefined4 * rbtree_buyNode_copyKey18(void);
int Node_alloc_thenInit(undefined4 param_1,undefined4 param_2);
void vector_fill_pairElem(int param_1,undefined4 *param_2);
void vector_destroyRange_strings(undefined4 *param_1,undefined4 *param_2);
void rbtree_destroyRecursive(void *param_1);
uint vector_growCap_stride4(uint param_1);
uint vector_growCap_stride16(uint param_1);
uint vector_growCap_stride128(uint param_1);
uint vector_growCap_stride18(uint param_1);
void vector_insertN_stride4(int *param_1,undefined4 *param_2,void *param_3,undefined4 *param_4);
void vector_reallocInsert_stride128(uint param_1);
void vector_reallocInsert_strElem8(uint param_1);
void vector_reallocInsert_stride8(uint param_1);
int vector_resizeGrow_stride128(uint param_1);
void vector_reserve_stride8(uint param_1);
void vector_reserve_stride8_b(uint param_1);
void vector_destroy_stringElems(void);
void std_string_replace_char(undefined4 *param_1,uint param_2,uint param_3);
void std_string_append_char(int *param_1,uint param_2);
void std_u16string_replace(undefined4 *param_1,uint param_2,uint param_3);
void std_u16string_append(int *param_1,uint param_2);
void list_clearSingleNode(void);
void list_clearNestedList(void);
void list_eraseTail_stringNode(void);
byte map_getTileLightOrHeight(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, int param_5);
bool vector_empty(void);
void u16string_endIterator(int *param_1);
int * list_eraseNode_front(int *param_1,int *param_2);
undefined4 * list_eraseRange(undefined4 *param_1,int *param_2,int *param_3);
void list_eraseNode(int *param_1,int *param_2);
int * list_eraseNode_stringField(int *param_1,int *param_2);
void rbtree_lowerBound_pairKey(int *param_1,uint *param_2);
void map_getPairValue(undefined4 *param_1,undefined4 param_2);
void list_popFront(void);
void list_clearFrontNode(void);
void list_pushBack_via583cb0(undefined4 param_1);
void list_pushBack_via451d70(undefined4 param_1);
void list_pushBack_via451d00(undefined4 param_1);
void list_pushBack_via451da0(undefined4 param_1);
void list_pushBack_via451e80(undefined4 param_1);
void list_pushBack_via451ee0(undefined4 param_1);
void list_pushBack_via5c03f0(undefined4 param_1);
void list_pushBack_via451f50(undefined4 param_1);
void list_pushBack_via451ff0(undefined4 param_1);
void list_pushBack_via451d40(undefined4 param_1);
void list_pushBack_via4520d0(undefined4 param_1);
void std_list_insert_node_32(undefined4 param_1);
void std_list_insert_node_a(undefined4 param_1);
void std_list_insert_node_b(undefined4 param_1);
void ** std_vector_insert_one_296(void **param_1);
void std_vector_insert_one_284(undefined4 *param_1);
void std_vector_insert_one_8_seh(uint param_1);
void std_vector_insert_one_8b(undefined4 *param_1);
void std_list_insert_node_c(undefined4 param_1);
void std_wstring_replace(uint param_1,uint param_2,int *param_3,uint param_4,uint param_5);
void std_list_resize(uint param_1);
void std_vector_resize_erase_4(uint param_1,undefined4 param_2);
int std_vector_resize_12(uint param_1);
int std_vector_size_4(void);
int std_vector_size_8(void);
undefined1 * std_string_ctor_wrap(undefined1 *param_1,undefined4 param_2,undefined4 param_3);
void push_heap_ptr_key6c(int param_1,int param_2,int param_3,int *param_4);
void push_heap_12_key4(int param_1,int param_2,int param_3,undefined8 *param_4);
void push_heap_16_key8(int param_1,int param_2,int param_3,undefined8 *param_4);
void adjust_heap_48_key28(int param_1,int param_2,int param_3,undefined4 param_4,undefined4 param_5);
void make_heap_ptr_key6c(int param_1,int param_2);
void make_heap_12_key4(int param_1,int param_2);
void make_heap_16_key8(int param_1,int param_2);
void make_heap_48_key28(int param_1,int param_2,undefined4 param_3);
void push_heap_up_48(int param_1,int param_2,int param_3,undefined4 *param_4);
void introsort_ptr_key6c(int param_1,int param_2,int param_3,undefined4 param_4);
void introsort_12_key4(int param_1,int param_2,int param_3,undefined4 param_4);
void introsort_16_key8(int param_1,int param_2,int param_3,undefined4 param_4);
void introsort_48_key2c(int param_1,int param_2,int param_3,undefined4 param_4);
void heapsort_finish_ptr(undefined4 *param_1,int param_2,undefined4 param_3);
void heapsort_finish_12(undefined8 *param_1,int param_2,undefined4 param_3);
void heapsort_finish_16(undefined8 *param_1,int param_2,undefined4 param_3);
void heapsort_finish_48(undefined4 *param_1,int param_2,undefined4 param_3);
void uninitialized_copy_16(undefined8 *param_1,undefined8 *param_2,undefined8 *param_3);
undefined4 * uninitialized_copy_48(int param_1,int param_2,undefined4 *param_3);
void std_list_assign(undefined4 *param_1,undefined4 *param_2);
void std_sort_ptr_key6c(int param_1,int param_2,undefined4 param_3);
void std_sort_12_key4(int param_1,int param_2,undefined4 param_3);
void std_sort_16_key8(int param_1,int param_2,undefined4 param_3);
void std_sort_48_key2c(int param_1,int param_2,undefined4 param_3);
int vector_at_48(int param_1);
void std_vector_realloc_12(uint param_1);
void std_vector_realloc_16(uint param_1);
void std_vector_realloc_48(uint param_1);
void std_vector_reserve_12(uint param_1);
void std_vector_reserve_16(uint param_1);
void std_vector_reserve_48(uint param_1);
void std_vector_pushback_12(undefined8 *param_1);
void std_vector_pushback_16(undefined8 *param_1);
void std_vector_pushback_48(undefined4 *param_1);
int std_vector_size_48(void);
int uninitialized_fill_copy_280(int param_1,int param_2,int param_3);
uint vector_growCapacity_280(uint param_1);
void std_vector_realloc_280(void *param_1);
int std_vector_reserveGrow_280(uint param_1);
void std_vector_eraseResize_280(uint param_1);
void rbtree_insertValueNode(undefined4 *param_1);
undefined4 * rbtree_allocNode_14(void);
undefined1 * uninitialized_copy_3(undefined1 *param_1,undefined1 *param_2,undefined1 *param_3);
void std_vector_realloc_3(uint param_1);
void std_vector_reserve_3(uint param_1);
void rbtree_insertPairNode(undefined4 param_1,undefined4 param_2,undefined4 *param_3);
void rbtree_allocNode_10(undefined4 *param_1,undefined4 *param_2);
uint std_wstring_findSubstr(ushort *param_1,uint param_2,uint param_3);
void std_list_clear_4da480(void);
undefined4 * rbtree_allocNode_28(void);
int vector_at_12(int param_1);
void list_copyAll_328(undefined4 param_1,undefined4 param_2);
void list_appendRange_a(int param_1,undefined4 *param_2,undefined4 *param_3);
void list_appendRange_b(int param_1,undefined4 *param_2,undefined4 *param_3);
void list_appendRange_20(int param_1,int param_2,int param_3);
void list_appendRange_328(int param_1,int param_2,int param_3);
void std_list_insert_node_d(undefined4 param_1);
int vector_at_32(int param_1);
int std_vector_size_32(void);
int rbtree_allocNode_copyStr(undefined4 *param_1);
int rbtree_allocNode_strKey(int param_1);
int rbtree_allocNode_strVec(undefined4 param_1,undefined4 param_2,int param_3);
undefined4 * rbtree_copyTreeNode_b(undefined4 *param_1,undefined4 param_2,undefined4 param_3);
void rbtree_insertRebalance_int(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
void rbtree_insertRebalance_b(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
undefined4 * rbtree_insertHint_int(undefined4 *param_1,int *param_2,int *param_3,undefined4 param_4);
undefined4 * rbtree_insertHint_str(undefined4 *param_1,int *param_2,undefined4 *param_3,undefined4 param_4);
void rbtree_insertUnique_int(undefined4 *param_1,char param_2,int *param_3,void *param_4);
void rbtree_insertUnique_str(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3,void *param_4);
void std_list_assign_range(int param_1,undefined4 *param_2,undefined4 *param_3);
void std_list_copy_ctor(undefined4 *param_1);
void unwind_delete_member(void);
undefined4 * rbtree_alloc_node(void);
void rbtree_destroy_recursive(void *param_1);
void rbtree_destroy_recursive_qt(void *param_1);
void rbtree_rotate_left(int param_1);
undefined4 * std_list_erase_range(undefined4 *param_1,int *param_2,int *param_3);
void rbtree_destroy_recursive_list(int param_1);
int * rbtree_min_node(int *param_1);
void vector_u16_reallocate(uint param_1);
void vector_u16_grow_to(uint param_1);
void vector_u16_resize(uint param_1);
void sqlite3_close(undefined4 param_1);
uint sqlite3_exec(int param_1,byte *param_2,code *param_3,undefined4 param_4,int *param_5);
uint sqlite3_exec_single(int param_1,char *param_2,undefined4 param_3);
int sqlite3_vfs_find(byte *param_1);
void sqlite3_mutex_enter_maybe(int param_1);
void sqlite3_mutex_leave_maybe(int param_1);
undefined4 sqlite3_log(undefined4 param_1);
void sqlite3_log_impl(undefined4 param_1,undefined4 param_2);
void sqlite3_str_appendf(int param_1,undefined4 param_2,undefined4 param_3);
void sqlite3_free(int param_1);
void sqlite3_randomness(int param_1,undefined1 *param_2);
void sqlite3_open(undefined4 param_1,undefined4 param_2);
void sqlite3_error_log(undefined4 param_1,undefined4 param_2);
uint sqlite3SafetyCheckOk(int param_1);
void sqlite3_prepare_v2_526480(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5);
void sqlite3_bind_text(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5);
void sqlite3_bind_blob_526b60(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5);
undefined4 sqlite3_column_value_527080(int *param_1,int param_2);
uint sqlite3_step(int *param_1);
undefined4 sqlite3_column_int(undefined4 param_1,undefined4 param_2);
int sqlite3_column_int_offset(undefined4 param_1,undefined4 param_2);
undefined4 sqlite3_finalize(int *param_1);
uint sqlite3_reset(int *param_1);
int btree_access_payload(int param_1,uint param_2,int param_3,int param_4,undefined4 param_5);
uint pager_add_to_savepoint_bitvecs(int param_1,uint param_2);
int btree_allocate_page(undefined4 *param_1,int *param_2,uint *param_3,uint param_4,char param_5);
int btree_incr_vacuum_truncate(int *param_1);
/* WARNING: Removing unreachable block (ram,0x0052baaa) */ int btree_copy_overflow_pages(int param_1,int param_2,int param_3);
int sqlite3_bind_impl(int *param_1,int param_2,int param_3,undefined4 param_4,code *param_5, undefined4 param_6);
void btree_release_cursor_page(int *param_1);
int btree_get_and_init_page(undefined4 *param_1,int param_2,int *param_3,undefined4 param_4);
undefined4 btree_init_page(char *param_1);
void btree_parse_cell_ptr(int param_1,uint param_2,uint *param_3);
void btree_unlink_cursor(int param_1);
void sqlite3_stmt_api_exit(int *param_1);
undefined * sqlite3_column_mem(int *param_1,int param_2);
undefined4 sqlite3_pager_has_content(int param_1);
undefined4 sqlite3_create_collation(int param_1,char *param_2,byte param_3,undefined4 param_4,undefined4 param_5, undefined4 param_6);
undefined4 btree_decode_page_flags(int param_1,uint param_2);
char * vdbe_display_p4(int param_1,char *param_2,int param_3);
int sqlite3_call_collation_needed(int param_1);
int * sqlite3_find_coll_seq(int param_1,char *param_2,int param_3);
undefined4 * sqlite3_hash_find(int param_1,byte *param_2,int param_3,int param_4);
void vdbe_release_p4_value(int param_1,undefined4 param_2,int *param_3);
void pager_free_tmp_space(int param_1);
int sqlite3_hash_find_ci(int param_1,int param_2,byte *param_3,int param_4);
void btree_get_cell_info(int param_1);
int btree_next_overflow_page(undefined4 *param_1,uint param_2,int *param_3,uint *param_4);
int pager_commit_phase_one(int *param_1,uint *param_2);
int btree_free_page(int *param_1,undefined4 *param_2,uint param_3);
void pcache_manage_dirty_list(int param_1,int *param_2,int *param_3);
int btree_lock_and_read_page1(int *param_1);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ uint sqlite3_mem_malloc(int param_1,int *param_2);
undefined4 btree_modify_page_pointer(undefined1 *param_1,int param_2,undefined4 param_3,char param_4);
int pager_pagecount_from_size(int param_1);
uint sqlite3_open_database(undefined4 param_1,undefined4 *param_2,uint param_3,undefined4 param_4);
undefined4 pager_zero_journal_header(int *param_1);
int pager_flush_wal_frames(int param_1);
int pager_lock_exclusive(int param_1);
int pager_lock_db(int param_1,int param_2);
void pager_write_journal_hdr(undefined4 *param_1);
void pager_unlock_if_unused(int *param_1);
int pager_pagecount(int param_1,uint *param_2);
int pager_playback_journal(int param_1,uint *param_2);
int pager_undo_all_dirty(int param_1);
void pager_sync_file_size(int param_1);
int pager_playback_one_page(int param_1,undefined4 param_2);
void pcache_release_page(int param_1);
undefined4 pager_unlock_db_vfs(int param_1,undefined4 param_2);
int pager_wal_frames(int param_1,int param_2,uint param_3,int param_4);
int pager_cksum(int param_1,int param_2);
int pager_delete_master_journal(int *param_1,byte *param_2);
int pager_end_transaction(int *param_1,undefined4 param_2);
uint pager_set_error_state(int param_1,uint param_2);
int pager_acquire_page1(undefined4 *param_1);
undefined4 pcache_fetch_no_create(int param_1,undefined4 param_2);
int pager_open_journal(int *param_1);
int pager_playback_savepoint(uint *param_1,int param_2);
int pager_playback_or_backup_page(int param_1,uint *param_2,int param_3,int param_4,int param_5);
void pager_invalidate_cursors(int param_1);
/* WARNING: Removing unreachable block (ram,0x005429a4) */ /* WARNING: Removing unreachable block (ram,0x005429d1) */ int pager_truncate_file(int param_1,undefined4 param_2);
void pager_unlock(int param_1);
int pager_lock_db_busy(int param_1,int param_2);
uint pager_write_page(int param_1);
void pager_incr_change_counter(int param_1);
int pager_write_dirty_to_wal(int *param_1,int param_2);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ undefined4 * pcache1_alloc(int param_1);
int pcache1_free(undefined4 *param_1);
void pcache_remove_from_hash(int param_1);
int btree_ptrmap_get(undefined4 *param_1,uint param_2,byte *param_3,undefined4 *param_4);
int btree_ptrmap_pageno(int param_1,uint param_2);
void btree_ptrmap_put(undefined4 *param_1,int param_2,char param_3,int param_4,int *param_5);
int pager_read_db_page(int param_1);
void pager_read_master_journal_name(int *param_1,undefined1 *param_2,uint param_3);
void pager_reset_pcache(int param_1);
void vdbe_release_mem_array(int *param_1,int param_2);
void btree_release_page(int param_1);
int btree_overwrite_cell(undefined4 *param_1,int param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5,undefined4 param_6);
void pcache1_remove_page(int param_1,int *param_2,int param_3);
undefined4 btree_shared_cache_unref(int param_1);
void sqlite3_log_message(undefined4 param_1,undefined4 param_2,undefined4 param_3);
int btree_save_cursor_position(int param_1);
void vdbe_commit_all_btrees(int *param_1);
int btree_free_cell_overflows(undefined1 *param_1);
void pager_set_sector_size(int param_1);
undefined4 sqlite3_setup_lookaside(int param_1,undefined4 *param_2,uint param_3,int param_4);
void sqlite3_register_builtin_functions(void);
uint sqlite3ApiExit(int param_1,uint param_2);
void sqlite3_run_auto_extensions(undefined4 param_1);
void btree_update_cursors_after_move(int *param_1,uint param_2,undefined4 param_3);
undefined4 btree_close(int param_1);
undefined4 btree_close_cursor(int *param_1);
int btree_commit_phase_two(int param_1,undefined4 param_2);
int btree_rollback(int param_1,int param_2);
void btree_enter(undefined4 *param_1);
void btree_enter_all(int param_1);
void btree_leave_lock(int param_1);
void btree_leave_all(int param_1);
void btree_open(int param_1,byte *param_2,int param_3,undefined4 *param_4,uint param_5, uint param_6);
int btree_begin_trans(int param_1,int param_2);
undefined4 btree_check_read_conflicts(int param_1);
void btree_trip_all_cursors(int param_1,undefined4 param_2);
undefined4 pager_report_cantopen(undefined4 param_1);
void vdbe_delete_aux_data(int *param_1);
void vdbe_free_cursor_list(int param_1);
undefined4 sqlite3_report_corrupt(undefined4 param_1);
int sqlite3_create_function_5515c0(int param_1,int param_2,int param_3,uint param_4,undefined4 param_5,int param_6, int param_7,int param_8,int *param_9);
void sqlite3DbFree(int param_1,undefined4 *param_2);
undefined4 * sqlite3DbMallocRaw(int param_1,int param_2);
void * sqlite3DbRealloc(int param_1,void *param_2,int param_3);
void * sqlite3_DbStrDup(undefined4 param_1,char *param_2);
void sqlite3_DeleteTrigger(int param_1,undefined4 *param_2);
void sqlite3_DeleteIndexList(undefined4 param_1,int param_2);
void sqlite3_ErrorWithMsg(int param_1,undefined4 param_2,int param_3);
void sqlite3_MarkAllCursorsInvalid(int param_1);
void sqlite3_ExprDelete(undefined4 param_1,int param_2);
void sqlite3_ExprListDelete(int param_1,int *param_2);
int sqlite3_ColumnDefault(int param_1,byte param_2,int param_3,undefined4 param_4);
short * sqlite3_FindCollSeq(int param_1,byte *param_2,size_t param_3,int param_4,byte param_5,char param_6);
void sqlite3_DeleteColumnNames(int param_1,int param_2);
void sqlite3_HashInsertNoResize(int param_1,int param_2);
undefined4 sqlite3_Get4byte(undefined1 *param_1);
undefined4 sqlite3_GetVarint(byte *param_1,uint *param_2);
undefined1 sqlite3_GetVarint32(byte *param_1,uint *param_2);
void sqlite3_HashClear(undefined4 *param_1);
undefined4 sqlite3_HashFind(uint *param_1,undefined4 param_2,undefined4 param_3);
uint sqlite3_HashInsert(uint *param_1,uint param_2,uint param_3,uint param_4);
void sqlite3_KeyInfoOrIdListFree(int param_1,int *param_2);
void sqlite3_LeaveSchemaAndClose(int param_1);
int sqlite3_LockAndPrepare(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5,undefined4 *param_6,undefined4 param_7);
int sqlite3_Malloc(int param_1);
void sqlite3_MallocAlarm(undefined4 param_1);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ void sqlite3_PcacheBufferSetup(void);
void sqlite3_StrAccumInitStatic(undefined8 *param_1);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ void sqlite3_MutexInit(void);
undefined4 sqlite3_OsClose(int *param_1);
undefined4 sqlite3_OsCurrentTimeInt64(int *param_1,undefined8 *param_2);
void sqlite3_OsSectorSizeCall(int *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5);
void sqlite3_OsMethod0x10(int *param_1,undefined4 param_2,undefined4 param_3);
void sqlite3_OsMethod0xc(int *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5);
void sqlite3_Pcache1BufferInit(undefined4 *param_1,uint param_2,int param_3);
int sqlite3_PagerGet(int param_1,uint param_2,int *param_3,int param_4);
undefined4 sqlite3_PagerClose(int param_1);
int sqlite3_PagerCommitPhaseOne(uint param_1,undefined4 param_2,int param_3);
void sqlite3_PagerSync(int param_1);
int sqlite3_PagerWrite(int param_1,int param_2,undefined4 param_3,int param_4);
int sqlite3_PagerOpen(code *param_1,undefined4 *param_2,char *param_3,int param_4,byte param_5, uint param_6,uint param_7);
int sqlite3_PagerBegin(int param_1,undefined4 *param_2);
int sqlite3_PagerReadFileHeader(int param_1,size_t param_2,void *param_3);
uint sqlite3_PagerSyncJournal(int param_1);
int sqlite3_PagerSavepoint(int param_1,int param_2,int param_3);
void sqlite3_PagerSetBusyhandler(int param_1,undefined4 param_2,undefined4 param_3);
int sqlite3_PagerSetPagesize(int param_1,uint *param_2,int param_3);
void sqlite3_PagerPlaybackOrCommit(int *param_1);
int sqlite3_PagerFileSync(int param_1);
void sqlite3_PagerUnrefPageOne(int param_1);
int sqlite3_PagerWritePagelist(int param_1);
undefined4 sqlite3_ParseUri(int *param_1,int *param_2,uint *param_3,int *param_4,undefined4 *param_5, undefined4 *param_6);
void sqlite3_PcacheCleanAll(undefined4 *param_1);
undefined1 * sqlite3_PcacheSortDirtyList(int *param_1);
void sqlite3_PcacheMakeClean(undefined4 *param_1);
int sqlite3_PcacheFetch(int *param_1,int param_2,int param_3,undefined4 *param_4);
void sqlite3_PcacheMakeCleanB(undefined4 *param_1);
void sqlite3_PcacheMakeDirty(int param_1);
void sqlite3_PcacheMove(undefined4 *param_1,undefined4 param_2);
undefined4 sqlite3_PcacheErrorCallback(int param_1);
void sqlite3_PcacheRelease(undefined4 *param_1);
void sqlite3_PcacheTruncate(undefined4 *param_1,uint param_2);
uint sqlite3_Prepare(int param_1,void *param_2,size_t param_3,byte param_4,int param_5,int *param_6, int *param_7);
void sqlite3_Put4byte(undefined1 *param_1,undefined4 param_2);
int sqlite3_Realloc(int param_1,int param_2);
void sqlite3_RegisterDateTimeFuncs(void);
void sqlite3_RegisterBuiltinFuncs(void);
void sqlite3_VdbeMemReleaseChain(undefined4 *param_1);
undefined4 sqlite3_SafetyCheckOk(int param_1);
void sqlite3_SchemaClear(int param_1);
void * sqlite3_SchemaGet(int param_1,int param_2);
void sqlite3_ScratchFree(undefined4 *param_1);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ undefined4 * sqlite3_ScratchMalloc(int param_1);
void sqlite3_SelectDelete(undefined4 param_1,int param_2);
void sqlite3_MPrintf(undefined4 *param_1,int param_2,undefined4 param_3);
void sqlite3_SrcListDelete(undefined4 param_1,short *param_2);
void sqlite3_StatusAdd(int param_1,int param_2);
void sqlite3_StatusSet(int param_1,int param_2);
uint sqlite3_Step(int *param_1);
void sqlite3_StrAccumAppend(undefined4 *param_1,char *param_2,size_t param_3);
int sqlite3_StrAccumFinish(undefined4 *param_1);
void sqlite3_StrAccumReset(undefined4 *param_1);
uint sqlite3_Strlen30(char *param_1);
undefined4 sqlite3_VdbeReprepareSwap(int param_1,int *param_2);
void sqlite3_VMPrintfInto(int param_1,undefined4 param_2,undefined4 param_3);
/* WARNING: Removing unreachable block (ram,0x0056b033) */ void sqlite3_VXPrintf(int param_1,int param_2,byte *param_3,double *param_4);
void sqlite3_VdbeMemFreeAndDestroy(undefined4 *param_1);
void sqlite3_VdbeAllocErrMem(undefined4 param_1);
undefined4 sqlite3_ValueText(int param_1,byte param_2);
undefined4 sqlite3_VdbeChangeEncoding(int param_1,uint param_2);
void sqlite3_VdbeFreeResources(undefined4 param_1,int param_2);
void sqlite3_VdbeDeleteAuxData(int *param_1,uint param_2);
undefined4 sqlite3_VdbeDelete(int *param_1);
undefined4 sqlite3_VdbeListExec(int *param_1);
undefined4 sqlite3_VdbeMemExpandBlob(int param_1);
undefined4 sqlite3_VdbeMemFinalize(undefined8 *param_1,int param_2);
undefined4 sqlite3_VdbeMemGrow(int *param_1,int param_2,int param_3);
int sqlite3_VdbeMemHandleBom(int param_1);
undefined4 sqlite3_VdbeMemNulTerminate(int param_1);
undefined4 sqlite3_VdbeMemMakeWriteable(int param_1);
void sqlite3_VdbeMemReleaseExternal(undefined4 *param_1);
void sqlite3_VdbeMemRelease(int param_1);
void sqlite3_VdbeFrameRelease(int param_1);
undefined4 sqlite3_VdbeMemSetStr(int *param_1,void *param_2,size_t param_3,char param_4,code *param_5);
undefined4 sqlite3_VdbeMemStringify(int param_1,int param_2);
undefined4 sqlite3_VdbeMemTranslate(undefined4 *param_1,char param_2);
uint sqlite3_VdbeHalt(int *param_1);
void sqlite3_VdbeSetNumCols(undefined4 *param_1,int param_2);
int sqlite3_VdbeTransferError(int *param_1);
void sqlite3_DeleteTriggerAux(int param_1,int param_2);
void sqlite3_KeyInfoUnref(undefined4 *param_1);
void sqlite3_SchemaResetCursors(int param_1);
int sqlite3_WalTryBeginRead(int *param_1,undefined4 param_2);
int sqlite3_WalCheckpoint(int param_1,int param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5, int param_6,undefined4 param_7,undefined4 *param_8,undefined4 *param_9);
int sqlite3_WalClose(int *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void sqlite3_WalEndReadTransaction(int param_1);
/* WARNING: Removing unreachable block (ram,0x00578130) */ /* WARNING: Removing unreachable block (ram,0x0057821b) */ void sqlite3_WalFrames(int param_1,int param_2,int param_3,undefined4 param_4,int param_5,uint param_6);
int sqlite3_WalOpen(int param_1,int param_2,int param_3,int param_4,int param_5,int param_6, undefined4 *param_7);
int sqlite3_WalFindFrame(int param_1,int param_2,undefined4 *param_3,int param_4,undefined4 param_5);
int sqlite3_WalUndo(int param_1,code *param_2,undefined4 param_3);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ undefined4 sqlite3_Config(undefined4 param_1,undefined8 *param_2,undefined4 param_3,undefined4 param_4);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ int sqlite3_Initialize(void);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ undefined4 sqlite3_PcacheInitialize(void);
void sqlite3_DeleteTriggerStepList(int param_1,int param_2);
uint sqlite3_StrHash(byte *param_1,int param_2);
undefined4 sqlite3_PagerPageInJournal(int param_1);
void sqlite3_SubjournalPage(int param_1);
void sqlite3_PagerOpenJournal(int param_1,int param_2);
undefined4 sqlite3_VdbeUnbind(int *param_1,int param_2);
void sqlite3_PcacheGroupUnlink(int param_1);
int * sqlite3_WalDetachPagers(int param_1,int param_2);
int sqlite3_WalBusyLock(int param_1,code *param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5);
/* WARNING: Removing unreachable block (ram,0x0057da59) */ int sqlite3_WalCheckpointCopy(int param_1,int param_2,undefined4 param_3,undefined4 param_4,int param_5, undefined4 param_6);
void sqlite3_WalChecksumBytes(int param_1,uint *param_2,int param_3,int *param_4,int *param_5);
void sqlite3_WalCleanupHash(int param_1);
undefined4 sqlite3_WalDecodeFrame(int param_1,int *param_2,undefined4 *param_3,undefined4 param_4,undefined1 *param_5);
void sqlite3_WalEncodeFrame(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined1 *param_5);
int sqlite3_WalIndexAppend(undefined4 param_1,void *param_2,int param_3);
void sqlite3_WalIndexClose(int param_1);
int sqlite3_WalIndexPage(int param_1,int param_2,undefined4 *param_3);
int sqlite3_WalIndexReadHdr(int param_1,undefined4 *param_2);
void sqlite3_WalIndexRecover(int param_1);
void sqlite3_WalIndexTryHdr(int param_1,undefined4 *param_2);
void sqlite3_WalIndexWriteHdr(int param_1);
int sqlite3_WalIteratorInit(int param_1,undefined4 *param_2);
bool sqlite3_WalIteratorNext(uint *param_1,uint *param_2,int *param_3);
void sqlite3_WalLimitSize(int param_1,uint param_2,int param_3);
void sqlite3_WalMerge(int param_1,void *param_2,int param_3,int *param_4,int *param_5,void *param_6);
void sqlite3_WalMergesort(int param_1,void *param_2,void *param_3,uint *param_4);
void sqlite3_WalRestartLog(int param_1);
int sqlite3_WalTryBeginReadB(int *param_1,undefined4 param_2,int param_3,int param_4);
void sqlite3_WalUnlockShared(int param_1,undefined4 param_2);
void sqlite3_WalWriteToLog(int param_1,int param_2,uint param_3,uint param_4,int param_5);
void sqlite3_PagerWrite32(int *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
int sqlite3_WriteJournalHdr(uint param_1);
int sqlite3_WriteMasterJournal(int param_1,char *param_2);
int sqlite3_PagerTruncateFile(int param_1,int param_2);
void std_string_AssignRange(undefined1 *param_1,undefined1 *param_2);
void Vector_ConstructResize(undefined4 param_1);
void Vector_Reallocate(uint param_1);
void Vector_Reserve(uint param_1);
void Vector_Resize(uint param_1);
void WalkPath_CopyNodes(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void WalkPath_CopyConstructVector(int *param_1);
undefined4 Vector_AllocCapacity18(uint param_1);
undefined4 * WString_Concat(undefined4 *param_1,int param_2,int param_3);
int Map_InsertVec6(undefined4 param_1,undefined4 param_2,undefined4 *param_3);
void RBTree_InsertRebalance(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
void RBTree_InsertRebalanceB(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
void RBTree_InsertRebalanceC(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
undefined4 * RBTree_InsertHintXY(undefined4 *param_1,int *param_2,int *param_3,undefined4 param_4);
undefined4 * RBTree_InsertHintKeyed(undefined4 *param_1,int *param_2,undefined4 *param_3,undefined4 param_4);
void RBTree_InsertUniqueXY(undefined4 *param_1,char param_2,int *param_3,void *param_4);
void RBTree_InsertUniqueKeyed(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3,void *param_4);
undefined4 * RBTree_LowerBoundInsertUint(undefined4 *param_1,char param_2,uint *param_3,undefined4 param_4);
void std_string_FreeMember(void);
void Map_AllocSentinelNode(void);
undefined4 * MapNode_Alloc30(void);
uint std_vector_Calculate_growth_594840(uint param_1);
undefined4 * std_Tree_lower_bound_xy(int *param_1);
void std_vector_Reallocate_grow_11c(void *param_1);
void std_vector_Reallocate_grow_188(uint param_1);
int std_vector_Emplace_reallocate_11c(uint param_1);
void std_vector_Reserve_grow_188(uint param_1);
void std_list_eraseNode_148(int *param_1,int param_2);
int * std_vector_eraseShift_c(int *param_1,int param_2);
/* WARNING: Removing unreachable block (ram,0x0059f755) */ /* WARNING: Removing unreachable block (ram,0x0059f69a) */ /* WARNING: Removing unreachable block (ram,0x0059f7fa) */ void WalkPathBehavior_isAreaWalkable(uint *param_1,float *param_2,char param_3);
void WalkPathBehavior_sampleStepCollision(uint *param_1,float *param_2);
void std_vector_pushBack_0x11c(uint param_1);
void ** std_vector_pushBack_0x188(void **param_1);
int rbTree_cloneNode(int param_1);
int rbTree_cloneNodeVariant(undefined4 param_1);
void rbTree_copyAssign(int *param_1,undefined4 param_2);
undefined4 * rbTree_copyRecursive(undefined4 *param_1,undefined4 param_2,undefined4 param_3);
undefined4 * rbTree_copyRecursiveVariant(undefined4 *param_1,undefined4 param_2,undefined4 param_3);
void rbTree_insertFixup(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
void rbTree_insertFixup_setKey(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4);
undefined4 * map_insertUniqueWithHint(undefined4 *param_1,int *param_2,undefined4 *param_3,undefined4 param_4);
void map_findInsertPos(undefined4 *param_1,char param_2,undefined4 *param_3,void *param_4);
void map_insertUnique_5a7700(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4);
void map_copyRange(int *param_1,int *param_2);
void std_vector_copyConstruct(int *param_1);
undefined4 * std_Tree_lowerBound_vecKey(undefined4 *param_1);
void std_Tree_lowerBound_u32(int *param_1,uint *param_2);
undefined4 * std_uninitializedCopy_T24(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void std_vector_reallocate(uint param_1);
void std_vector_reserveGrow(uint param_1);
void std_AdjustHeap_siftDown(int param_1,int param_2,int param_3,undefined4 param_4,int *param_5);
void std_destroyRange_T24(undefined4 *param_1,undefined4 *param_2);
void std_InsertionSort_byKey(int *param_1,int *param_2,int *param_3);
void std_MakeHeap_byKey(int param_1,int param_2,int *param_3);
void std_Med3_byKey(int *param_1,int *param_2,int *param_3,int *param_4);
void std_MedianGuess(int param_1,int param_2,int param_3,undefined4 param_4);
void std_uninitializedCopy_T28(undefined8 *param_1,undefined8 *param_2,undefined8 *param_3);
void std_PushHeap_byIndex(int param_1,int param_2,int param_3,int *param_4,int *param_5);
void std_introSort(int param_1,int param_2,int param_3,undefined4 param_4);
void std_SortHeap(undefined4 *param_1,int param_2,undefined4 param_3);
void std_PartitionByMedian(uint *param_1,int *param_2,int *param_3,int *param_4);
void std_uninitializedCopy_T12(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void std_uninitializedCopy_T28_guarded(undefined8 *param_1,undefined8 *param_2,undefined8 *param_3);
void std_uninitializedCopy_T32(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void std_vector_initEmpty(void);
void std_vector_assignCopy(int *param_1);
void std_vector_destructor(void);
int std_vector_elementAt(int param_1);
uint std_vector_Calculate_growth_5aee40(uint param_1);
void std_vector_Reallocate_grow(uint param_1);
void std_vector_Reallocate_grow_5aef90(uint param_1);
int std_vector_Reserve_grow_5af070(uint param_1);
void std_vector_Reserve_grow_5af0e0(uint param_1);
int std_vector_Last_minus_one(void);
void std_vector_push_back(undefined4 *param_1);
void std_vector_push_back_5bf4f0(undefined4 *param_1);
int std_vector_resize_5bffd0(uint param_1);
int std_vector_size_5c0100(void);
void rbtree_insert_rebalance_3key(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
undefined4 * rbtree_insert_hint_2key(undefined4 *param_1,int *param_2,int *param_3,undefined4 param_4);
undefined4 * rbtree_insert_hint_3key(undefined4 *param_1,int *param_2,int *param_3,undefined4 param_4);
void rbtree_lower_bound_insert_2key(undefined4 *param_1,char param_2,int *param_3,void *param_4);
void rbtree_lower_bound_insert_3key(undefined4 *param_1,char param_2,int *param_3,void *param_4);
void make_heap_int(int param_1,int param_2,undefined4 param_3);
void make_heap_float(int param_1,int param_2,undefined4 param_3);
undefined1 * uninitialized_copy_280(undefined4 *param_1,undefined4 *param_2,undefined1 *param_3);
void push_heap_int(int param_1,int param_2,int param_3,undefined4 *param_4);
void push_heap_float(int param_1,int param_2,int param_3,undefined4 *param_4);
void introsort_int(int param_1,int param_2,int param_3,undefined4 param_4);
void introsort_float(int param_1,int param_2,int param_3,undefined4 param_4);
void sort_heap_int(undefined4 *param_1,undefined4 *param_2,undefined4 param_3);
void sort_heap_float(undefined4 *param_1,undefined4 *param_2,undefined4 param_3);
void std_sort_unguarded_partition_vec3i(undefined4 *param_1,int *param_2,int *param_3,undefined4 param_4);
void std_sort_unguarded_partition_vec3f(undefined4 *param_1,float *param_2,float *param_3,undefined4 param_4);
int std_uninitialized_copy_stride0x140(int param_1,int param_2,int param_3);
int std_uninitialized_copy_stride0x18_eh(int param_1,int param_2,int param_3);
undefined4 * std_uninitialized_copy_vec3i(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void rbtree_iterator_increment(void);
undefined4 * rbtree_lower_bound_vec3i(int *param_1);
void std_vector_reallocate_stride0x140(uint param_1);
void std_vector_reallocate_stride0x18(uint param_1);
void std_vector_reserve_grow_stride0x140(uint param_1);
void std_vector_reserve_grow_stride0x18(uint param_1);
void vector_assign_range(int *param_1,int *param_2,char param_3);
undefined1 * init_struct_memset(undefined1 *param_1);
undefined1 * init_struct_memset2(undefined1 *param_1);
int * vector_insert_element(int *param_1,undefined4 param_2,int *param_3,int param_4);
void unwind_free_object(void);
void vector_reallocate(uint param_1);
void vector_reserveGrow(uint param_1);
void list_pushBack_601eb0(undefined4 param_1);
void vector_pushWithGrow(undefined4 *param_1);
int map_insertVec4Node(undefined4 param_1,undefined4 param_2,undefined4 *param_3);
int map_insertPairNode(undefined4 *param_1);
int map_insertNodeSEH(undefined4 param_1,undefined4 param_2,undefined4 *param_3);
void map_insertFromField(undefined4 param_1,undefined4 param_2);
undefined4 * list_copyNode(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void map_insertVec4(int param_1,int param_2,int param_3);
void list_buildAndFree(int *param_1);
void map_insertViaSub(undefined4 param_1);
longlong codec_decodeCodebook(void);
longlong codec_decodeResidueA(int *param_1,int *param_2,int param_3,int *param_4,undefined8 *param_5);
longlong codec_decodeResidueB(undefined4 param_1);
void security_cookie_guard_a(void);
void security_cookie_guard_b(void);
void map_insertRebalance(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
void map_insertUnique_62fbc0(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4);
undefined4 * map_findOrInsert(undefined4 *param_1,int *param_2,undefined4 *param_3,undefined4 param_4);
void map_lowerBoundInsert(undefined4 *param_1,char param_2,byte *param_3,undefined4 param_4);
void std_list_clear_nodes(void);
undefined4 * std_list_erase_range_633ce0(undefined4 *param_1,int *param_2,int *param_3);
void Node_select_glyph_by_name(undefined4 *param_1);
void std_list_insert_unique_sorted(byte *param_1,int param_2);
undefined4 * std_map_insert_hint_string(undefined4 *param_1,int *param_2,undefined4 *param_3,undefined4 param_4);
void std_list_alloc_sentinel_0x34(void);
void std_map_equal_range_string(int *param_1,undefined4 *param_2);
uint std_string_rfind_substr(ushort *param_1,uint param_2,uint param_3);
void std_uninitialized_copy_pair(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
undefined4 * std_uninitialized_copy_triple(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
int std_destroy_relocate_0xc(int param_1,int param_2,int param_3);
void std_vector_destroy_ptr_elems_stride3(undefined4 *param_1,undefined4 *param_2);
void std_map_rb_insert_rebalance_vec2(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
undefined4 * std_map_insert_unique_hint_uint2(undefined4 *param_1,int *param_2,uint *param_3,undefined4 param_4);
undefined4 * std_set_insert_unique_hint_uint(undefined4 *param_1,int *param_2,uint *param_3,undefined4 param_4);
void std_map_insert_at_pos_vec2(undefined4 *param_1,char param_2,uint *param_3,void *param_4);
void std_set_insert_at_pos_uint(undefined4 *param_1,char param_2,uint *param_3,void *param_4);
undefined4 * std_uninitialized_copy_records_0xd(int param_1,int param_2,undefined4 *param_3);
undefined4 * std_vector_move_assign_stride3(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void * std_copy_int_range(void *param_1,int param_2,void *param_3);
void std_uninitialized_copy_matrix(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
int std_uninitialized_copy_0xc_guarded(int param_1,int param_2,int param_3);
undefined4 * std_uninitialized_copy_dword(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
undefined4 * std_uninitialized_copy_2dword(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
undefined4 * std_uninitialized_copy_4dword(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
undefined4 * std_uninitialized_copy_records_0xd_v2(int param_1,int param_2,undefined4 *param_3);
void std_vector_assign_range_stride1(int *param_1);
void std_vector_assign_range_stride2(int *param_1);
void std_vector_assign_range_stride4(int *param_1);
int * std_vector_assign_range_stride0xc(int *param_1);
uint * std_map_subscript(uint *param_1);
uint std_vector_allocate_stride0x10(uint param_1);
void std_vector_grow_realloc_stride4(uint param_1);
void std_vector_grow_realloc_stride0x34(void *param_1);
void std_vector_grow_realloc_stride0xc(uint param_1);
void std_vector_reserve_stride4(uint param_1);
void std_vector_reserve_stride0x34(uint param_1);
void std_vector_reserve_stride0xc(uint param_1);
void * std_allocator_allocate_stride0xc(uint param_1);
int * std_vector_erase_range_stride0xc(int *param_1,int param_2,int param_3);
void std_vector_insert_one_stride0xc(uint param_1);
void std_vector_default_construct_range4(undefined4 param_1);
int std_vector_resize_stride0x34(uint param_1);
int std_vector_size_stride0xc(void);
int std_list_make_node_copy_pair(undefined4 param_1,undefined4 param_2,undefined4 param_3);
int std_list_make_node_worldinfo(undefined4 param_1);
int std_list_make_node_copy_pair_v2(undefined4 param_1,undefined4 param_2,undefined4 param_3);
undefined4 * std_move_backward_stride4(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void std_map_rb_insert_rebalance_int(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
undefined4 * std_map_insert_unique_hint_int(undefined4 *param_1,int *param_2,int *param_3,undefined4 param_4);
void std_map_insert_at_pos_int(undefined4 *param_1,char param_2,int *param_3,void *param_4);
void std_transform_toupper_u16(undefined4 *param_1,undefined2 *param_2,undefined2 *param_3,undefined2 *param_4, code *param_5);
void std_uninitialized_fill_n_stride4(int param_1,int param_2,undefined4 *param_3);
void std_uninitialized_fill_stride4(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void std_vector_init_fill(undefined4 param_1,undefined4 param_2);
void std_map_ensure_key(int *param_1);
void std_map_ensure_key_v2(int *param_1);
/* WARNING: Removing unreachable block (ram,0x0064e33f) */ uint std_vector_allocate(uint param_1);
void std_list_alloc_sentinel_0x2c(void);
void std_list_alloc_sentinel_0x44(undefined4 *param_1,undefined4 *param_2);
void std_vector_assign_fill(size_t param_1,byte *param_2);
void std_vector_insert_n_stride0x10(int *param_1,int param_2,uint param_3,undefined4 *param_4);
void std_list_append_node_pair(undefined4 param_1);
void std_list_append_node_worldinfo(undefined4 param_1);
void Widget_deserialize_children_tree(basic_istream<char,std::char_traits<char>_> *param_1,undefined4 param_2, undefined4 param_3);
void istream_read_wstring(undefined4 param_1,basic_istream<char,std::char_traits<char>_> *param_2);
undefined4 std_map_findValue(undefined4 *param_1);
undefined1 * std_string_assignFromString(undefined1 *param_1,undefined4 *param_2);
void std_map_storeGlyphAt(undefined4 param_1,undefined4 param_2,undefined8 *param_3);
int std_map_insertOrAssignGuardedValue(undefined4 param_1,undefined4 param_2,undefined4 *param_3);
int std_map_createNode16(undefined4 *param_1);
int std_map_createNodeMoveVector(undefined4 *param_1);
void RBTree_insertNodeRebalance(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
undefined4 * std_map_insertWithHint(undefined4 *param_1,int *param_2,undefined4 param_3,undefined4 param_4);
void std_map_insertUnique(undefined4 *param_1,int *param_2,int *param_3,void *param_4);
void std_copyRange(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void std_list_initSentinel(void);
int * std_map_insertOrAssignMoveVal(int *param_1);
undefined4 std_vector_allocateN(uint param_1);
void RBTree_allocSentinelNode(void);
void std_map_equalRange3Key(int *param_1,int *param_2);
void std_map_equalRangeVectorKey(int *param_1,int *param_2);
void RBTree_destroyRecursive(void *param_1);
undefined4 * std_map_findLowerBoundVecKey(int *param_1);
void std_list_clearNodes(void);
/* WARNING: Type propagation algorithm not settling */ void Font_layoutAndDrawGlyphs(undefined4 *param_1,float param_2,float param_3,undefined4 *param_4, undefined4 *param_5,undefined4 *param_6,uint param_7);
undefined4 * std_map_eraseRange(undefined4 *param_1,int *param_2,int *param_3);
/* WARNING: Removing unreachable block (ram,0x0065d1ed) */ /* WARNING: Removing unreachable block (ram,0x0065d1fd) */ /* WARNING: Removing unreachable block (ram,0x0065d206) */ /* WARNING: Removing unreachable block (ram,0x0065d209) */ /* WARNING: Removing unreachable block (ram,0x0065d1f9) */ /* WARNING: Removing unreachable block (ram,0x0065d217) */ /* WARNING: Removing unreachable block (ram,0x0065d226) */ /* WARNING: Removing unreachable block (ram,0x0065d231) */ /* WARNING: Removing unreachable block (ram,0x0065d22d) */ /* WARNING: Removing unreachable block (ram,0x0065d221) */ /* WARNING: Removing unreachable block (ram,0x0065d234) */ void RBTree_eraseNodeRebalance(undefined4 param_1,int *param_2);
void std_map_find3KeyNode(int *param_1,int *param_2);
void std_map_findVecKeyNode(int *param_1,int *param_2);
void std_map_findStringKeyNode(int *param_1,int param_2);
void Font_rasterizeGlyphBitmap(int *param_1,ushort param_2,char param_3);
undefined4 Font_findCachedGlyph3D(ushort param_1);
void Font_rasterizeGlyph3D(undefined4 *param_1,ushort param_2,char param_3);
void Font_setPixelSizeAndCacheGlyphs(undefined4 *param_1,undefined4 *param_2,void *param_3);
void std_map_lowerBoundInsertHint(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3,void *param_4);
void std_map_copyAssign(int param_1);
void std_map_getOrInsertByKey(int param_1);
void std_map_eraseTreeRec(void *param_1);
undefined4 * std_map_eraseRange_661a20(undefined4 *param_1,int *param_2,int *param_3);
/* WARNING: Removing unreachable block (ram,0x00661bad) */ /* WARNING: Removing unreachable block (ram,0x00661bbd) */ /* WARNING: Removing unreachable block (ram,0x00661bc6) */ /* WARNING: Removing unreachable block (ram,0x00661bc9) */ /* WARNING: Removing unreachable block (ram,0x00661bb9) */ /* WARNING: Removing unreachable block (ram,0x00661bd7) */ /* WARNING: Removing unreachable block (ram,0x00661be6) */ /* WARNING: Removing unreachable block (ram,0x00661bf1) */ /* WARNING: Removing unreachable block (ram,0x00661bed) */ /* WARNING: Removing unreachable block (ram,0x00661be1) */ /* WARNING: Removing unreachable block (ram,0x00661bf4) */ void std_rbtree_eraseNode(undefined4 param_1,int *param_2);
int std_list_Buynode_splice(undefined4 *param_1);
void std_Move_backward_0x40(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void std_Move_backward_8byte(int param_1,int param_2,undefined4 *param_3);
void std_Move_backward_0xc(int param_1,int param_2,undefined4 *param_3);
void std_Rb_tree_Insert_rebalance(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4);
undefined4 * std_map_Insert_hint(undefined4 *param_1,char param_2,int *param_3,undefined4 param_4);
void std_Uninitialized_fill_n_0x40(undefined4 *param_1,int param_2,undefined4 *param_3);
void std_Uninitialized_fill_n_8byte(undefined4 *param_1,int param_2,undefined4 *param_3);
void std_Uninitialized_fill_n_0xc(undefined4 *param_1,int param_2,undefined4 *param_3);
undefined4 * std_Uninitialized_copy_0xc(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void std_Fill_0x40(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void std_Fill_0xc(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
undefined4 * std_map_operator_667a90(int *param_1);
void std_map_equal_range(int *param_1,int *param_2);
uint std_vector_Calc_growth_0x40(uint param_1);
uint std_vector_Calc_growth_0xc(uint param_1);
void std_vector_Insert_n_4byte(int *param_1,undefined4 *param_2,void *param_3,undefined4 *param_4);
void std_vector_Insert_n_0x40(int *param_1,int param_2,uint param_3,undefined4 *param_4);
void std_vector_Insert_n_8byte(int *param_1,undefined8 *param_2,uint param_3,undefined4 *param_4);
void std_vector_Insert_n_0xc(int *param_1,int param_2,uint param_3,undefined4 *param_4);
void std_vector_Reallocate_0xc(uint param_1);
void std_vector_Move_range_0x40(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void std_vector_push_back_4byte(undefined4 *param_1);
void std_vector_push_back_move_0xc(undefined4 *param_1);
void std_vector_resize_4byte(uint param_1,undefined4 param_2);
void std_vector_resize_0xc(uint param_1,undefined4 param_2);
void std_vector_Reallocate_0xc_v2(uint param_1);
void std_vector_Reserve_0xc(uint param_1);
void std_vector_push_back_0xc(undefined4 *param_1);
void std_Uninitialized_copy_0xc_v2(undefined8 *param_1,undefined8 *param_2,undefined8 *param_3);
int std_Rotate_0xc(undefined8 *param_1,int param_2,undefined8 *param_3);
void std_Uninitialized_copy_0xc_v3(undefined8 *param_1,undefined8 *param_2,undefined8 *param_3);
void std_vector_Copy_assign_ctor(int param_1);
void std_vector_Assign_range_0xc(int *param_1);
void std_vector_assign_0xc(int param_1);
void std_vector_Erase_shift_0xc(int param_1);
int std_vector_insertSortedKeyframe(undefined4 param_1,int param_2,undefined4 param_3);
void std_vector_destroyRange(undefined4 *param_1,undefined4 *param_2);
undefined2 * std_vector_uninitializedCopy(int param_1,int param_2,undefined2 *param_3);
void std_vector_reallocate_677d10(uint param_1);
int std_vector_growIfNeeded(uint param_1);
void std_vector_findOrAppendNamed(undefined4 *param_1,int param_2);
void std_vector_insertAt(uint param_1);
void std_Tree_allocHeadSentinel(void);
int * std_vector_assignRange(int *param_1);
void std_list_clear_67e480(void);
undefined4 * std_Tree_eraseRange(undefined4 *param_1,int *param_2,int *param_3);
undefined4 * std_map_insertWithHint_67fa60(undefined4 *param_1,int *param_2,uint *param_3,undefined4 param_4);
void std_map_insertUnique_67fc90(undefined4 *param_1,char param_2,uint *param_3,undefined4 param_4);
void std_vector_copyConstructPairs(int *param_1);
undefined4 * std_map_findOrInsert(uint *param_1);
undefined4 * std_list_allocNode(void);
void std_Tree_destroyHead(int param_1);
void std_vector_reallocate8byte(uint param_1);
void std_vector_growIfNeeded8byte(uint param_1);
void std_list_clearNodesWithStrings(void);
void std_vector_pushBack8byte(undefined4 *param_1);
void StreamReader_readWString(void);
void list_allocNode(undefined4 *param_1,undefined4 *param_2);
void operator_new_wrapper(uint param_1);
void eh_vector_dtor_iterator_helper(void);
void eh_vector_ctor_iterator_helper(void);
undefined4 FT_Face_FindUnicodeCharmap(int param_1);
undefined4 FT_Match_BitmapStrike(int param_1,int *param_2,char param_3,int *param_4);
void ft_recompute_scaled_metrics(void);
void ft_select_bitmap_strike_metrics(int param_1,int param_2);
void FT_Request_Metrics(int param_1,int *param_2);
undefined4 ft_size_reset_bitmap(int param_1,int param_2);
int FT_Request_Size_internal(int param_1,int *param_2);
void FT_Set_Pixel_Sizes(undefined4 param_1,int param_2,int param_3,int param_4,int param_5);
int FT_Get_Kerning(int param_1,undefined4 param_2,undefined4 param_3,int param_4,uint *param_5);
undefined4 FT_Get_Char_Index(int param_1);
undefined4 FT_Get_Postscript_Name(int param_1);
int ft_find_charmap_by_encoding(int param_1,int param_2,int *param_3);
void ft_reset_active_charmap_cache(void);
undefined4 FT_Get_Module_By_Name(int param_1,byte *param_2);
undefined4 ft_validate_outline_contours(short *param_1);
void FT_Outline_Translate(int param_1,int param_2,int param_3);
void FT_Vector_Transform(int *param_1,undefined4 *param_2);
void FT_Outline_Transform(int param_1,int param_2);
void ft_glyphloader_node_init(undefined4 *param_1,undefined4 param_2,undefined4 param_3);
void ft_call_done_hook(int param_1);
undefined4 FT_Stream_Seek(int param_1,uint param_2);
undefined4 FT_Stream_Skip_checked(undefined4 param_1,int param_2);
undefined4 FT_Stream_Pos(int param_1);
undefined4 FT_Stream_Read_buffer(int *param_1,uint param_2,void *param_3,uint param_4);
undefined2 FT_Stream_ReadUShort(int *param_1,undefined4 *param_2);
undefined4 FT_Stream_ReadULong(int *param_1,undefined4 *param_2);
int ft_trig_downscale(void);
int ft_trig_prenorm(uint *param_1);
void ft_trig_pseudo_rotate(int *param_1);
void ft_trig_pseudo_polarize(int *param_1);
int FT_Cos(void);
void FT_Sin(void);
int FT_Atan2(int param_1,int param_2);
void FT_Vector_Length_or_Rotate(int *param_1,int param_2);
void FT_Vector_From_Angle(undefined4 *param_1,undefined4 param_2,undefined4 param_3);
int FT_Angle_Diff(int param_1,int param_2);
int ft_mem_alloc_raw(int param_1,int param_2,undefined4 *param_3);
void FT_Mem_Free(int param_1,int param_2);
int ft_list_find_by_data(int *param_1,int param_2);
void FT_List_Add(undefined4 *param_1,int *param_2);
void FT_List_Remove(undefined4 *param_1,int *param_2);
void FT_List_Up(int *param_1,int *param_2);
void FT_List_Finalize(int *param_1,code *param_2,undefined4 param_3,undefined4 param_4);
void ft_glyphslot_free_internal(undefined4 *param_1);
void ft_glyphslot_done(undefined4 *param_1);
void ft_size_destroy(int param_1,int param_2);
void ft_glyphslot_clear_bitmap(int param_1);
void ft_glyphslot_clear_fields(void);
void ft_size_done_inner(void);
void FT_Done_Size(int param_1);
void ft_charmap_node_done(void);
int FT_CMap_Activate(int param_1,int param_2,int param_3,undefined4 *param_4);
int FT_Render_Glyph_Internal(int param_1,int param_2,undefined4 param_3);
undefined4 FT_Render_Glyph(int param_1,undefined4 param_2);
undefined4 FT_Bitmap_Free(int param_1,undefined4 *param_2);
undefined4 FT_Bitmap_Done(int param_1);
void FT_Stream_Read_current(int param_1,undefined4 param_2,undefined4 param_3);
void * FT_Mem_QAlloc_Clear(undefined4 param_1,size_t param_2,int *param_3);
int FT_Mem_QRealloc(int param_1,int param_2,int param_3,int param_4,int param_5,undefined4 *param_6);
void ft_alloc_charmap_obj(undefined4 param_1,undefined4 *param_2);
undefined4 * ft_glyphloader_add_glyph(undefined4 *param_1,uint *param_2,uint *param_3);
void ft_glyphslot_internal_init(void);
int FT_New_GlyphSlot(int param_1,int *param_2);
int FT_Load_Glyph(int param_1,undefined4 param_2,uint param_3);
undefined4 FT_Load_Char(int param_1,undefined4 param_2,undefined4 param_3);
void ft_free_charmap_array(undefined4 param_1);
void ft_face_destroy_inner(undefined4 param_1,int param_2,int param_3);
int ft_open_face_object(undefined4 param_1,undefined4 param_2,int param_3,int param_4,int *param_5);
int ft_new_charmap_node(int param_1,undefined4 param_2,undefined4 param_3);
int ft_open_face_from_stream(undefined4 param_1,int param_2,int *param_3);
undefined4 FT_Remove_GlyphSlot(int param_1);
int FT_New_Size(int param_1,int *param_2);
void TT_Load_TTC_SubHeader(undefined4 param_1,undefined4 param_2,int param_3,int *param_4,int *param_5);
int FT_Mem_QRenew_Clear(undefined4 param_1,int param_2,int param_3,int param_4,undefined4 param_5, int *param_6);
undefined4 * FT_New_BitmapGlyph_Buffers(int param_1,undefined4 param_2,undefined4 param_3,undefined4 *param_4);
undefined4 FT_BitmapGlyph_Init_wrapper(int param_1);
undefined4 * TT_Load_CMap_Subtable(undefined4 *param_1,undefined4 param_2,int param_3,int param_4,int param_5,int *param_6 ,size_t *param_7);
int ft_open_font_format_dispatch(undefined4 param_1,undefined4 param_2,undefined4 *param_3);
void ft_probe_type1_header(undefined4 param_1);
void ft_probe_font_drivers_table(undefined4 param_1,int param_2,undefined4 param_3,int param_4,int param_5, int *param_6);
void ft_try_open_all_formats(undefined4 param_1,undefined4 param_2,int param_3);
void ft_probe_and_open_font(undefined4 param_1,byte *param_2);
uint FT_Open_Face(undefined4 *param_1,uint *param_2,int param_3,int *param_4);
undefined4 FT_New_Memory_Face(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4);
undefined4 FT_New_Face(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5 );
undefined4 ft_bitmapglyph_copy_from_slot(undefined4 *param_1,int param_2);
int ft_new_glyph_obj(void);
undefined4 FT_Glyph_Transform(int param_1,int param_2,undefined4 param_3);
void FT_Done_Glyph(undefined4 *param_1);
int FT_Glyph_Copy(int param_1,int *param_2);
int FT_Get_Glyph(undefined4 *param_1,undefined4 *param_2);
void FT_Glyph_To_Bitmap(int *param_1,undefined4 param_2,int *param_3,char param_4);
int ft_int_abs(void);
void ft_outline_grow_arrays(int param_1);
uint ft_outline_close_contour(char param_1);
void ft_outline_line_to(undefined1 param_1);
void ft_outline_conic_to(undefined4 *param_1);
void ft_outline_cubic_to(undefined4 *param_1,undefined4 *param_2);
void ft_stroke_move_to(void);
void ft_outline_builder_init(void);
void ft_outline_builder_reset(void);
void ft_outline_builder_done(void);
undefined4 ft_outline_count_contours(int *param_1,int *param_2,int *param_3);
void ft_outline_merge_points(void);
undefined4 * ft_new_outline_obj(undefined4 *param_1,int *param_2);
void ft_stroker_reset_two(int param_1);
void ft_free_outline_obj(int param_1);
void ft_stroke_arc_both_sides(void);
void ft_stroke_conic_to(int *param_1,int *param_2);
void ft_stroke_conic_recursive(int *param_1,undefined4 *param_2,int *param_3);
void ft_stroke_cubic_recursive(int *param_1,undefined4 *param_2,undefined4 *param_3,int *param_4);
undefined4 ft_stroke_move_to_record(int param_1,undefined4 *param_2,undefined1 param_3);
int ft_stroke_reverse_subpath(char param_1);
int ft_stroke_end_subpath(undefined4 *param_1);
void ft_outline_get_counts(int param_1,int *param_2,int *param_3);
void ft_stroke_export_border(int param_1,int param_2);
void ft_stroke_export_both(undefined4 param_1,undefined4 param_2);
int TT_Decompose_Glyph_Outline(int param_1,short *param_2,undefined4 param_3);
int FT_Glyph_Stroke(int *param_1,undefined4 param_2,char param_3);
void ft_stroker_set_params(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5);
undefined4 FT_Stream_Open_File(int param_1,char *param_2);
void FT_Bitmap_Init(undefined4 *param_1);
int FT_Bitmap_Copy(undefined4 *param_1,int *param_2,int *param_3);
/* WARNING: Removing unreachable block (ram,0x006cf948) */ /* WARNING: Removing unreachable block (ram,0x006cf950) */ /* WARNING: Removing unreachable block (ram,0x006cf995) */ /* WARNING: Removing unreachable block (ram,0x006cf99b) */ /* WARNING: Removing unreachable block (ram,0x006cf9af) */ /* WARNING: Removing unreachable block (ram,0x006cf953) */ /* WARNING: Removing unreachable block (ram,0x006cf97b) */ /* WARNING: Removing unreachable block (ram,0x006cf984) */ /* WARNING: Removing unreachable block (ram,0x006cf958) */ /* WARNING: Removing unreachable block (ram,0x006cf95d) */ /* WARNING: Removing unreachable block (ram,0x006cf965) */ /* WARNING: Removing unreachable block (ram,0x006cf96d) */ /* WARNING: Removing unreachable block (ram,0x006cf9a4) */ undefined4 vorbis_read_setup_header(undefined4 param_1,undefined4 param_2,int param_3);
/* WARNING: Removing unreachable block (ram,0x006cfa4b) */ /* WARNING: Removing unreachable block (ram,0x006cfa53) */ undefined4 vorbis_validate_packet_crc(undefined4 *param_1);
undefined4 vorbis_read_setup_maps_modes(void);
undefined4 vorbis_read_residue_config(void);
undefined4 vorbis_read_info_header(void);
void vorbis_free_setup(undefined8 *param_1);
void vorbis_alloc_state(undefined8 *param_1);
undefined4 vorbis_get_serial_or_index(int param_1,int param_2);
void vorbis_free_residue_arrays(int *param_1);
void vorbis_init_pcm_struct(undefined8 *param_1);
void vorbis_read_bits_to_bytes(int param_1);
undefined4 vorbis_get_codebook_dim_log(int param_1);
undefined4 vorbis_decode_mode_mapping(int param_1);
undefined4 vorbis_start_packet_decode(undefined4 *param_1,undefined4 *param_2);
undefined4 vorbis_decode_packet_full(int *param_1,int *param_2);
undefined4 vorbis_advance_read_pos(int param_1,int param_2);
int vorbis_get_channel_ptrs(int param_1,undefined4 *param_2);
undefined4 vorbis_apply_window_overlap(int param_1,int *param_2);
undefined4 vorbis_init_decoder(undefined4 param_1);
undefined4 vorbis_reset_decode_state(int param_1);
void vorbis_free_channel_state(void *param_1);
undefined4 vorbis_alloc_decode_buffers(void);
undefined4 vorbis_free_bitreader_state(void *param_1);
undefined4 vorbis_init_bitreader_state(int *param_1,void *param_2);
int vorbis_temp_bump_alloc(void);
void vorbis_temp_arena_flush(void);
void * vorbis_floor0_synth_curve(int *param_1);
int vorbis_lookup1_values(void);
uint * vorbis_compute_huffman_codes(int param_1);
/* WARNING: Function: __alloca_probe_16 replaced with injection: alloca_probe */ /* WARNING: Unable to track spacebase fully for stack */ /* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ undefined4 vorbis_build_codebook_table(void);
void vorbis_free_codebook_buf(void);
uint * vorbis_read_codebook(void);
void vorbis_free_mapping(void);
void vorbis_free_floor(void);
void vorbis_free_residue_book(void);
void vorbis_imdct_setup_twiddles(void);

#endif
