// crt_stl (cube) — reconstructed declarations.
#ifndef CUBE__LIBRARY_CRT_STL_H
#define CUBE__LIBRARY_CRT_STL_H
#include "../include/cube_types.h"

basic_ostream<char,std::char_traits<char>_> * std_ostream_insert_string(basic_ostream<char,std::char_traits<char>_> *param_1,char *param_2);
undefined * Catch_All_0040215e(void);
void std_ostream_insert_cleanup(void);
void Catch_All_00402269(void);
void Catch_All_004022d9(void);
bool std_fputc_nofail(char param_1,FILE *param_2);
void Catch_All_0040249e(void);
void Catch_All_00402633(void);
void Catch_All_00402aa4(void);
void Catch_All_00402d3b(void);
facet * std_locale_getfacet(locale *param_1);
void std::basic_filebuf<char,std::char_traits<char>_>::ctor_3 (undefined4 param_1,uint param_2,undefined4 param_3,int param_4);
void std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_4 (uint param_1,int param_2);
void Catch_All_0040354c(void);
void std::basic_filebuf<char,std::char_traits<char>_>::ctor_0(void);
void std::basic_filebuf<char,std::char_traits<char>_>::ctor_1(void);
void std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_18(void);
void std::basic_ifstream<char,std::char_traits<char>_>::vfunc_0(void);
void std::basic_stringstream<char,std::char_traits<char>,std::allocator<char>_>::vfunc_0(void);
void std::basic_filebuf<char,std::char_traits<char>_>::vfunc_0(byte param_1);
ios_base * std_filebuf_deleting_dtor(byte param_1);
void std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::vfunc_0(byte param_1);
ios_base * std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_19(byte param_1);
void std::error_category::vfunc_0(byte param_1);
void std::basic_stringstream<char,std::char_traits<char>,std::allocator<char>_>::vfunc_1(void);
void std::basic_ifstream<char,std::char_traits<char>_>::vfunc_1(void);
void std::basic_stringstream<char,std::char_traits<char>,std::allocator<char>_>::vfunc_2(void);
undefined * Catch_All_00405586(void);
void Catch_All_004055c3(void);
void std_string_deleting_dtor(void *param_1);
void std::basic_filebuf<char,std::char_traits<char>_>::vfunc_1(void);
/* Library Function - Single Match private: void __thiscall std::basic_filebuf<char,struct std::char_traits<char> >::_Reset_back(void) Library: Visual Studio 2012 Release */ void __thiscall std::basic_filebuf<char,std::char_traits<char>_>::_Reset_back (basic_filebuf<char,std::char_traits<char>_> *this);
/* Library Function - Single Match private: void __thiscall std::basic_filebuf<char,struct std::char_traits<char> >::_Set_back(void) Library: Visual Studio 2012 Release */ void __thiscall std::basic_filebuf<char,std::char_traits<char>_>::_Set_back (basic_filebuf<char,std::char_traits<char>_> *this);
void std::basic_filebuf<char,std::char_traits<char>_>::vfunc_2(void);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ void std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_0 (undefined4 param_1,float param_2);
void * std_allocate(uint param_1);
void std::_System_error_category::vfunc_3(int *param_1,int param_2);
void std::error_category::vfunc_3(undefined4 *param_1,undefined4 param_2);
uint std::error_category::vfunc_4(int *param_1,int param_2);
uint std::error_category::vfunc_5(undefined4 param_1,int *param_2);
void std::basic_filebuf<char,std::char_traits<char>_>::vfunc_14(undefined4 param_1);
undefined1 * std::_Generic_error_category::vfunc_2(undefined1 *param_1,int param_2);
undefined1 * std::_Iostream_error_category::vfunc_2(undefined1 *param_1,int param_2);
undefined1 * std::_System_error_category::vfunc_2(undefined1 *param_1,int param_2);
char * std::_Generic_error_category::vfunc_1(void);
char * std::_Iostream_error_category::vfunc_1(void);
char * std::_System_error_category::vfunc_1(void);
basic_streambuf<char,std::char_traits<char>_> * std_filebuf_open(char *param_1,int param_2,int *param_3);
/* WARNING: Removing unreachable block (ram,0x0040d41d) */ void std::basic_filebuf<char,std::char_traits<char>_>::vfunc_3(int param_1);
int std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::vfunc_3(int param_1);
uint std::basic_filebuf<char,std::char_traits<char>_>::vfunc_4(uint param_1);
int std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::vfunc_4(int param_1);
void std::basic_filebuf<char,std::char_traits<char>_>::vfunc_10 (undefined4 *param_1,int param_2,int param_3,int param_4);
void std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::vfunc_10 (uint *param_1,uint param_2,uint param_3,int param_4,uint param_5);
void std::basic_filebuf<char,std::char_traits<char>_>::vfunc_11 (undefined4 *param_1,int param_2,int param_3,undefined4 param_4,undefined4 param_5, undefined4 param_6);
void std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::vfunc_11 (uint *param_1,uint param_2,int param_3,uint param_4,int param_5,undefined4 param_6, undefined4 param_7,uint param_8);
basic_streambuf<char,std::char_traits<char>_> * std::basic_filebuf<char,std::char_traits<char>_>::vfunc_12(char *param_1,size_t param_2,int param_3);
undefined4 std::basic_filebuf<char,std::char_traits<char>_>::vfunc_13(void);
void std::basic_filebuf<char,std::char_traits<char>_>::vfunc_7(void);
uint std::basic_filebuf<char,std::char_traits<char>_>::vfunc_6(void);
uint std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::vfunc_6(void);
undefined * Catch_All_0040e676(void);
undefined * Catch_All_0040e8b6(void);
void std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::ctor_17 (uint param_1,int param_2);
void std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::ctor_18(void);
void std::basic_stringstream<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::vfunc_0 (void);
void std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::vfunc_0 (byte param_1);
ios_base * std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::ctor_14 (byte param_1);
void std::basic_stringstream<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::vfunc_1 (void);
void std::basic_stringstream<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::vfunc_2 (void);
undefined * Catch_All_0040f20f(void);
void Catch_All_0040f24c(void);
void std_wstring_Tidy(char param_1,int param_2);
void * std_wstring_Allocate(uint param_1);
void std_char_traits_assign(undefined2 *param_1,undefined2 *param_2);
void std_wstring_operator_delete_wrapper(void *param_1);
wchar_t std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::vfunc_3 (wchar_t param_1);
uint std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::vfunc_4 (ushort param_1);
undefined4 GameController_get_field_0x8006d0(void);
int GameController_get_field_ptr_0x800a1c(void);
void std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::vfunc_10 (uint *param_1,uint param_2,uint param_3,int param_4,uint param_5);
void std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::vfunc_11 (uint *param_1,uint param_2,int param_3,uint param_4,int param_5,undefined4 param_6, undefined4 param_7,uint param_8);
undefined2 std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::vfunc_6(void);
undefined * Catch_All_00424d20(void);
void Catch_All_00424e30(void);
void cube::Interface::drawCharacterCreation(void);
void math_vec4_sub(float *param_1,float *param_2);
void Catch_All_00428b7d(void);
void Catch_All_00428c5c(void);
void cube::GameController::drawCharacterAppearancePanel(void);
void Catch_All_0042bf63(void);
void Catch_All_0042c04f(void);
float10 get_float_field_0x1000e78(void);
void cube::GameController::drawQuestHud(void);
float10 get_float_field_0xd4(void);
float10 get_float_field_0xd8(void);
void cube::Interface::drawCharacterStatsPanel(void);
void Catch_All_004392af(void);
void Catch_All_00439398(void);
void NameInput_handle_key(short param_1);
void std_wstring_dtor_free(undefined4 *param_1);
float10 Creature_compute_scale_factor(void);
int stat_diminishing_returns_pct(void);
float10 Equipment_sum_slot_values(void);
undefined * Catch_All_004492fa(void);
void obj_init_and_load_a(void);
void obj_init_and_inflate(void);
undefined4 db_delete_blob(undefined4 param_1);
undefined4 db_update_blob_key(undefined4 param_1,undefined4 param_2);
void Catch_All_0044a17d(void);
void Catch_All_0044a39e(void);
void Catch_All_0044a476(void);
void Catch_All_0044a79f(void);
void Catch_All_0044ab90(void);
void Catch_All_0044ad13(void);
void Catch_All_0044aee3(void);
void std_Tree_Freenode_str(void *param_1);
void Catch_All_0044b9f0(void);
void Catch_All_0044baee(void);
void Catch_All_0044bbec(void);
/* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ void cube::Creature::deserializeState(int param_1);
void deserialize_struct_0x28(int param_1);
void deserialize_struct_small(undefined4 *param_1);
void Catch_All_0044d77d(void);
void GameWorld_serialize_state(int param_1);
void serialize_struct_0x28(int param_1);
void serialize_struct_small(undefined4 *param_1);
void serialize_struct_creatures(int param_1);
void buffer_append_bytes(void *param_1,size_t param_2);
void cube::Interface::drawMerchantDialog(void);
void std:: _Func_impl<std::_Callable_obj<<lambda_1ffef8671b5d330b7078b5ff273ee5fb>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::ctor_0(undefined4 *param_1);
void std:: _Func_impl<std::_Callable_obj<<lambda_29209b183b27224642a038ec1f3692c5>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::ctor_0(undefined4 *param_1);
void std:: _Func_impl<std::_Callable_obj<<lambda_864084cd43f09ea2a93402c86ee87b29>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::ctor_0(undefined4 *param_1);
void std:: _Func_impl<std::_Callable_obj<<lambda_fdf816e424f0da55b18915c89c349fdd>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::ctor_0(undefined4 *param_1);
void std:: _Func_impl<std::_Callable_obj<<lambda_ff38bf9ea15b41cb34bc5dae16af8ab3>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::ctor_0(undefined4 *param_1);
basic_istream<wchar_t,std::char_traits<wchar_t>_> * std_operator_wistream_wstring(basic_istream<wchar_t,std::char_traits<wchar_t>_> *param_1,undefined4 *param_2);
undefined * Catch_All_00451360(void);
void std_operator_wstring_unwind(void);
void Catch_All_00451c57(void);
int std_map_insert_val_wstr(undefined4 param_1,undefined4 param_2,undefined4 *param_3);
void Catch_All_00451e69(void);
void Catch_All_00451fd2(void);
void Catch_All_00452171(void);
void Catch_All_00452247(void);
int node_ctor_2strings(int param_1);
void Catch_All_004523ae(void);
void Catch_All_004525df(void);
void Catch_All_004527d4(void);
void Catch_All_0045299d(void);
void Catch_All_004531e7(void);
void Catch_All_00453404(void);
void Catch_All_0045361f(void);
void Catch_All_0045386f(void);
void Catch_All_0045399a(void);
void Catch_All_00453b24(void);
void Catch_All_00453c54(void);
void Catch_All_00453da4(void);
void Catch_All_00453ef7(void);
void Catch_All_00453fa9(void);
void Catch_All_00454079(void);
void Catch_All_00454149(void);
void std_list_Insert_range(int param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_00454219(void);
void Catch_All_004542e9(void);
void Catch_All_004543b9(void);
void Catch_All_00454489(void);
void Catch_All_00454559(void);
void Catch_All_00454629(void);
void Catch_All_004546f9(void);
void Catch_All_004547c9(void);
void Catch_All_00454899(void);
void Catch_All_00454969(void);
void Catch_All_00454a39(void);
void Catch_All_00454b09(void);
void Catch_All_00456aa6(void);
void Catch_All_00456b5c(void);
void Catch_All_00456ced(void);
void Catch_All_00456e4a(void);
void std_Copy(int param_1,int param_2,undefined4 *param_3);
void Catch_All_004571be(void);
void Catch_All_004572a2(void);
void Catch_All_00457392(void);
void std_Tidy_deallocate_catch(int param_1);
void dtor_and_free_catch(undefined4 *param_1);
void std_basic_string_Tidy(undefined4 *param_1);
/* Library Function - Single Match public: struct std::pair<unsigned __int64,unsigned __int64> & __thiscall std::pair<unsigned __int64,unsigned __int64>::operator=<struct std::pair<unsigned __int64,unsigned __int64>,0>(struct std::pair<unsigned __int64,unsigned __int64> &&) Library: Visual Studio 2019 Release */ pair<unsigned___int64,unsigned___int64> * __thiscall std::pair<unsigned___int64,unsigned___int64>:: operator=<std::pair<unsigned___int64,unsigned___int64>,0> (pair<unsigned___int64,unsigned___int64> *this, pair<unsigned___int64,unsigned___int64> *param_1);
void std_list_list_const(undefined4 param_1);
void Catch_All_00458db6(void);
void std_list_list_const_458df0(undefined4 *param_1);
void Catch_All_00458e6f(void);
void Catch_All_00458f0f(void);
void std_list_list_const_458f30(undefined4 *param_1);
void Catch_All_00458faf(void);
void std_list_list_const_458fd0(undefined4 *param_1);
void Catch_All_0045904f(void);
void std_list_list_const_459070(undefined4 *param_1);
void Catch_All_004590ef(void);
void Catch_All_0045918f(void);
void Catch_All_0045922f(void);
void Catch_All_004592cf(void);
void Catch_All_0045938f(void);
void Catch_All_0045947c(void);
void T_T_const_T_465ae0(int param_1);
void T_T_const_T_465ef0(undefined4 *param_1);
void T_T_465fd0(void);
void thunk_FUN_0046ea70(void);
void Catch_All_004681c0(void);
void Catch_All_004682fe(void);
void Catch_All_00468419(void);
void Catch_All_004685c8(void);
/* WARNING: Removing unreachable block (ram,0x0046949b) */ /* WARNING: Removing unreachable block (ram,0x00469417) */ /* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ /* WARNING: Restarted to delay deadcode elimination for space: stack */ void cube::World::updateNearbyEntities(void);
void World_streamChunksAroundPlayer(void);
/* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ void cube::World::updateActiveChunks(void);
/* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ /* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ /* WARNING: Exceeded maximum restarts with more pending */ void cube::GameController::networkReceiveThread(void);
void std::_Func_base<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>:: vfunc_5(byte param_1);
void std_Tree_Buyheadnode(void);
void std:: _Func_impl<std::_Callable_obj<<lambda_29209b183b27224642a038ec1f3692c5>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_0(undefined4 *param_1);
void std:: _Func_impl<std::_Callable_obj<<lambda_1ffef8671b5d330b7078b5ff273ee5fb>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_4(char param_1);
void std_Destroy_range_catch(undefined4 param_1,undefined4 param_2);
void Node_dtor_2strings(void *param_1);
void std:: _Func_impl<std::_Callable_obj<<lambda_1ffef8671b5d330b7078b5ff273ee5fb>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_2(void);
void std:: _Func_impl<std::_Callable_obj<<lambda_29209b183b27224642a038ec1f3692c5>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_2(void);
void std:: _Func_impl<std::_Callable_obj<<lambda_864084cd43f09ea2a93402c86ee87b29>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_2(void);
void std:: _Func_impl<std::_Callable_obj<<lambda_fdf816e424f0da55b18915c89c349fdd>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_2(void);
void std:: _Func_impl<std::_Callable_obj<<lambda_ff38bf9ea15b41cb34bc5dae16af8ab3>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_2(void);
void std_list_Tidy(int param_1);
int std:: _Func_impl<std::_Callable_obj<<lambda_1ffef8671b5d330b7078b5ff273ee5fb>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_6(void);
void std:: _Func_impl<std::_Callable_obj<<lambda_1ffef8671b5d330b7078b5ff273ee5fb>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_0(undefined4 *param_1);
void std:: _Func_impl<std::_Callable_obj<<lambda_864084cd43f09ea2a93402c86ee87b29>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_0(undefined4 *param_1);
void std:: _Func_impl<std::_Callable_obj<<lambda_fdf816e424f0da55b18915c89c349fdd>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_0(undefined4 *param_1);
void std:: _Func_impl<std::_Callable_obj<<lambda_ff38bf9ea15b41cb34bc5dae16af8ab3>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_0(undefined4 *param_1);
void Catch_All_0046e239(void);
void std_vector_Reallocate(uint param_1);
void Catch_All_0046e30c(void);
void Catch_All_0046e40e(void);
void Catch_All_0046e50e(void);
void Catch_All_0046e5ed(void);
void Catch_All_0046e6f1(void);
void std_vector_reserve(uint param_1);
TypeDescriptor * std:: _Func_impl<std::_Callable_obj<<lambda_1ffef8671b5d330b7078b5ff273ee5fb>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_3(void);
TypeDescriptor * std:: _Func_impl<std::_Callable_obj<<lambda_29209b183b27224642a038ec1f3692c5>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_3(void);
TypeDescriptor * std:: _Func_impl<std::_Callable_obj<<lambda_864084cd43f09ea2a93402c86ee87b29>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_3(void);
TypeDescriptor * std:: _Func_impl<std::_Callable_obj<<lambda_fdf816e424f0da55b18915c89c349fdd>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_3(void);
TypeDescriptor * std:: _Func_impl<std::_Callable_obj<<lambda_ff38bf9ea15b41cb34bc5dae16af8ab3>,0>,std::allocator<std::_Func_class<void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil>_>,void,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil,std::_Nil> ::vfunc_3(void);
void std_list_Unlink(int *param_1);
void std_list_erase(int *param_1);
void std_list_erase_46eb20(int *param_1);
undefined4 GameController_check_tile_walkable(int param_1,int param_2);
/* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ void cube::GameController::connectToServer (undefined4 *param_1);
int * std_list_Erase_node(int *param_1,int *param_2);
void std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::ctor_13 (undefined4 param_1,int param_2);
void std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::ctor_5 (undefined4 param_1,int param_2);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ void cube::GameController::handleKeyPress (uint param_1);
void GameController_validate_selected_zone(void);
void std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_9 (int param_1,int param_2);
void cube::GameController::loadStructureBlob (int param_1,int param_2);
void std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::ctor_8 (char *param_1,int param_2);
void std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_7(void);
void cube::GameController::loadWorldList(void);
void std_list_pop_back(void);
void std_list_push_back_4861f0(undefined4 param_1);
void std_list_push_back_4865b0(undefined4 param_1);
void Catch_All_00487179(void);
void Catch_All_00487363(void);
void Catch_All_00487470(void);
void cube::GameController::saveEntityBlob (int param_1,int param_2);
void cube::GameController::saveStructureBlob (int param_1,int param_2,char param_3);
undefined4 GameController_get_selected_char_ptr(void);
void cube::GameController::drawItemTooltip (char *param_1,int param_2,int param_3,float param_4,int param_5,char param_6, char param_7);
void GameController_load_skill_tooltip(int param_1,int param_2,int param_3,int param_4,undefined4 param_5,int param_6);
void GameController_load_specialization_text(undefined4 param_1,int param_2,int param_3,int param_4,undefined4 param_5, int param_6);
void Catch_All_004aba0c(void);
void Catch_All_004abd8f(void);
void Catch_All_004abe6c(void);
void Catch_All_004abf64(void);
void cube::GameController::drawCurrencyPanel(void);
void Catch_All_004c691e(void);
undefined4 Item_get_stack_or_grid_size(void);
float10 Item_compute_value(void);
void Item_get_type_color(undefined4 *param_1);
void cube::World::updateObjectLabels(void);
void std::basic_filebuf<char,std::char_traits<char>_>::ctor_2 (undefined4 *param_1,uint param_2,undefined4 param_3,int param_4);
void std::basic_filebuf<char,std::char_traits<char>_>::ctor_4(void);
void std::basic_ofstream<char,std::char_traits<char>_>::vfunc_0(void);
ios_base * std_basic_filebuf_scalar_deleting_dtor(byte param_1);
void std::basic_ofstream<char,std::char_traits<char>_>::vfunc_2(void);
void Catch_All_004cb3d8(void);
void Catch_All_004cb583(void);
undefined1 net_Connection_write_delta_i8(int *param_1,uint *param_2,uint *param_3,char *param_4,char *param_5,char param_6);
undefined1 net_Connection_write_delta_i16(int *param_1,uint *param_2,uint *param_3,short *param_4,short *param_5,char param_6);
undefined1 net_Connection_write_delta_i32(int *param_1,uint *param_2,uint *param_3,int *param_4,int *param_5,char param_6);
undefined1 net_Connection_write_delta_f32(int *param_1,uint *param_2,uint *param_3,float *param_4,float *param_5,char param_6);
undefined4 net_Connection_write_delta_vec5f(int *param_1,uint *param_2,uint *param_3,float *param_4,float *param_5,char param_6);
undefined1 net_Connection_write_delta_struct_ac(int *param_1,uint *param_2,uint *param_3,undefined4 param_4,undefined4 param_5, char param_6);
undefined1 net_Connection_write_delta_struct_e38(int *param_1,uint *param_2,uint *param_3,undefined4 param_4,undefined4 param_5, char param_6);
undefined1 net_Connection_write_delta_creature(int *param_1,uint *param_2,uint *param_3,undefined4 param_4,undefined4 param_5, char param_6);
undefined4 net_Connection_write_delta_vec3i(int *param_1,uint *param_2,uint *param_3,int param_4,int *param_5,char param_6);
undefined4 net_Connection_write_delta_vec3f(int *param_1,uint *param_2,uint *param_3,int param_4,float *param_5,char param_6);
undefined4 net_Connection_write_delta_vec6i(int *param_1,uint *param_2,uint *param_3,int param_4,int *param_5,char param_6);
undefined1 net_Connection_write_delta_i64(int *param_1,uint *param_2,uint *param_3,int *param_4,int *param_5,char param_6);
undefined1 std_compare_float3_ne(float *param_1);
undefined1 EntityAppearance_compareEqual(int param_1);
undefined4 compareEqual_array13(int param_1);
undefined1 std_list_push_serializeField_string(int *param_1,uint *param_2,uint *param_3,byte *param_4,byte *param_5,char param_6);
undefined4 std_list_push_serializeField_0x2C(int *param_1,uint *param_2,uint *param_3,int param_4,int *param_5,char param_6);
void EntityState_serializeToBuffer(int *param_1,int param_2,int param_3,undefined4 param_4);
undefined * Catch_All_004ce3d9(void);
void std::basic_filebuf<char,std::char_traits<char>_>::ctor_8 (undefined4 param_1,uint param_2,undefined4 param_3,int param_4);
void cube::Interface::drawOptionsMenu(void);
void std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::ctor_22(void);
void xml_malloc_thunk(size_t param_1);
void __cdecl free(void *_Memory);
undefined4 utf32le_to_utf16_alloc(int *param_1,int *param_2,uint *param_3,uint param_4);
undefined4 utf32be_to_utf16_alloc(int *param_1,int *param_2,undefined4 param_3,uint param_4);
void xml_memoryPool_ctor(void);
void thunk_FUN_004d77d0(void);
uint xml_iterator_notEqual(uint *param_1);
int xml_iterator_isValid(void);
void xml_iterator_deref_advance(int *param_1);
int xml_memoryPool_allocateBlock(uint param_1,int *param_2);
uint * xml_node_allocate(int *param_1,uint param_2);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ void xml_memoryPool_allocateArena(int param_1);
int * xml_attribute_allocate(int param_1,int *param_2);
int xml_node_appendChild(int param_1,undefined4 param_2,undefined4 param_3);
void xml_node_findChildByName(int *param_1,ushort *param_2);
void xml_node_firstChild(undefined4 *param_1);
void xml_node_findAttributeByName(int *param_1,ushort *param_2);
undefined ** xml_document_firstElementNode(void);
uint xml_transcode_dispatch(undefined4 param_1,undefined4 param_2,uint param_3,undefined4 param_4, undefined4 param_5,undefined4 param_6);
undefined4 utf16_byteswapCopy(int *param_1,uint *param_2,int param_3,uint param_4,char param_5);
undefined4 utf8_to_utf16_alloc(int *param_1,int *param_2,undefined4 param_3,undefined4 param_4);
void xml_memoryPool_initArena(void);
int utf16_countUnits_fromUtf32be(uint *param_1,int param_2,int param_3);
ushort * utf32le_to_utf16_write(uint *param_1,int param_2,ushort *param_3);
ushort * utf32be_to_utf16_write(uint *param_1,int param_2,ushort *param_3);
int utf8_countCodepoints(uint *param_1,uint param_2,int param_3);
void utf8_to_utf16_write(uint *param_1,uint param_2,ushort *param_3);
void xml_memoryPool_freeAll(void);
void xml_node_ctor_setParent(undefined4 *param_1);
void xml_document_firstNode(undefined4 *param_1);
int xml_detectEncoding(int param_1,char *param_2,uint param_3);
undefined4 utf16_copy_passthrough(undefined4 *param_1,uint *param_2,void *param_3,uint param_4,char param_5);
code * xml_selectAttrValueScanner(uint param_1);
void xml_document_parseWithEncoding(undefined8 *param_1,int param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5);
undefined ** xml_document_root(void);
ushort * xml_parseText_entityAndNewlineNorm(ushort *param_1);
void xml_parseNodeTree(ushort *param_1,undefined4 *param_2,uint param_3,undefined4 param_4);
void xml_parse_setjmpWrapper(undefined8 *param_1,int param_2,int param_3,int param_4,undefined4 param_5);
void xml_parseBang_commentCData_doctype(int *param_1,int param_2,uint param_3,undefined4 param_4);
void xml_parsePI_or_xmlDecl(int *param_1,int *param_2,uint param_3,short param_4);
ushort * xml_scanCDATA_withEntities(ushort *param_1,short param_2);
ushort * xml_scanComment_withEntities(ushort *param_1,short param_2);
void Catch_All_004d9ac7(void);
int std_Tree_buynode(undefined4 param_1);
void Catch_All_004d9c2f(void);
void std_Tree_insert_rebalance_v2(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4);
void Catch_All_004da18f(void);
void std_map_insert_unique_v2(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3,undefined4 param_4);
void Catch_All_004da2df(void);
undefined2 QuestText_isPunctuation(short param_1);
/* WARNING: Type propagation algorithm not settling */ void cube::QuestText::parseTemplate(undefined4 *param_1);
void Catch_All_004dc4cc(void);
void Catch_All_004dc569(void);
void Catch_All_004dc639(void);
void Catch_All_004dc707(void);
void Catch_All_004dc7d9(void);
void std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::ctor_20(void);
void Catch_All_004e0130(void);
void Catch_All_004e022d(void);
void Catch_All_004e02e5(void);
void Catch_All_004e03a2(void);
void Catch_All_004e04df(void);
void Catch_All_004e0d98(void);
void Catch_All_004e0fc4(void);
void Catch_All_004e11b4(void);
void Catch_All_004e12a8(void);
void Catch_All_004e1460(void);
void Catch_All_004e15c4(void);
void Catch_All_004e1669(void);
void std_list_resize_insert(undefined4 *param_1,undefined4 *param_2);
void Catch_All_004e175d(void);
void Catch_All_004e1806(void);
void Catch_All_004e18a6(void);
void Catch_All_004e194f(void);
void cube::Speech::ctor_1(void);
void container_operation(int *param_1);
void map_string_operation(int param_1);
void node_alloc(void);
void node_free(void *param_1);
void node_release_free(void *param_1);
void cube::GameController::generateQuestText (int param_1,int param_2,int *param_3,undefined4 param_4);
void std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::ctor_24 (undefined4 *param_1);
void Catch_All_004ebb21(void);
void Catch_All_004ebf28(void);
void Catch_All_004ec05d(void);
/* Library Function - Single Match void * __cdecl operator new[](unsigned int,enum FILL) Library: Visual Studio 2017 Release */ void * __cdecl operator_new__(uint param_1,FILL param_2);
void Catch_All_00583d5b(void);
void std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_11 (undefined4 param_1);
void cube::GameController::drawWeaponCustomization(void);
void Catch_All_0058cf4d(void);
undefined4 lib_fn_58d730(undefined4 param_1,int param_2,int param_3);
void Catch_All_0058e27f(void);
void Catch_All_0058e4a4(void);
void Catch_All_0058e628(void);
void Catch_All_0058e7ad(void);
void Catch_All_0058e8af(void);
void Catch_All_0058e94c(void);
void lib_fn_58e990(int param_1);
void lib_fn_594760(void *param_1);
void lib_fn_5947a0(void *param_1);
void Catch_All_005949ae(void);
void Catch_All_00594ab7(void);
undefined2 * lib_fn_594bf0(undefined2 *param_1,undefined4 *param_2);
void lib_fn_594c80(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, int param_5);
void lib_fn_595010(undefined4 param_1,undefined1 *param_2,int param_3);
void lib_fn_5953a0(undefined4 param_1,int param_2,int param_3);
void cube::GameController::buildObjectName (int **param_1,char *param_2);
undefined2 * lib_fn_59fbf0(undefined2 *param_1,int param_2,int param_3);
undefined4 lib_fn_59ff60(undefined4 param_1,undefined4 param_2);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ undefined * lib_fn_5a02d0(int param_1);
int lib_fn_5a4710(int param_1,int param_2);
void std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_17 (int param_1,int param_2);
void std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_13(int param_1);
void std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_15 (uint param_1,int param_2);
undefined2 * lib_fn_5a5a60(undefined2 *param_1,undefined4 *param_2);
void Catch_All_005a6b48(void);
void Catch_All_005a6c11(void);
void Catch_All_005a6d7f(void);
void Catch_All_005a6e3f(void);
void Catch_All_005a74cc(void);
void Catch_All_005a7691(void);
void Catch_All_005a7876(void);
void Catch_All_005a7a1f(void);
void lib_fn_5a7bd0(void *param_1);
void Catch_All_005adf30(void);
void lib_fn_5ae9f0(undefined4 *param_1);
void Catch_All_005aeb2c(void);
void Catch_All_005aef74(void);
void Catch_All_005af04c(void);
void Catch_All_005c00e3(void);
void Catch_All_005c082f(void);
void Catch_All_005c0ab5(void);
void Catch_All_005c0c4e(void);
void Catch_All_005c0dee(void);
void Catch_All_005c3756(void);
undefined4 * lib_fn_5c37d0(int param_1,int param_2,undefined4 *param_3);
void Catch_All_005c4114(void);
void Catch_All_005c4211(void);
void lib_fn_5c4230(uint param_1);
void Catch_All_005c42ff(void);
void lib_fn_5c4480(uint param_1);
int * lib_fn_5d7a70(int param_1,int param_2);
/* WARNING: Removing unreachable block (ram,0x005dacc3) */ void cube::GameController::generateRegion (int param_1,int param_2);
void lib_fn_5f4d10(undefined4 *param_1);
void cube::Zone::constructTileGrid(void);
void lib_fn_5fb9f0(undefined4 *param_1);
void Catch_All_005fbbed(void);
void std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_2(void);
void lib_fn_5fbed0(int param_1,int param_2);
void lib_fn_5fc0d0(int *param_1,undefined4 *param_2);
void cube::GameController::unloadZone(int param_1,int param_2);
void lib_fn_6022d0(uint param_1,uint param_2);
int lib_fn_6023b0(uint param_1,uint param_2);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ void cube::GameController::loadLandscapeTile (int param_1,int param_2);
void std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_3 (int param_1,int param_2);
void cube::GameController::streamTileChunk (uint param_1,uint param_2);
void std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_14 (int param_1,int param_2);
void std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char>_>::ctor_16 (int param_1,int param_2);
void cube::GameController::drawWorldSelectEntry(void);
void Catch_All_00608b12(void);
void Catch_All_00608b8c(void);
void Catch_All_00608d1f(void);
void Catch_All_00608e37(void);
void Catch_All_00608ef6(void);
void Catch_All_00609189(void);
void Catch_All_006093dc(void);
void inflate(void);
void inflateEnd(void);
void compress(void);
void inflateInit_(void);
void DirectInput8Create(void);
void Direct3DCreate9(void);
void Ordinal_3(void);
void Ordinal_4(void);
void Ordinal_9(void);
void Ordinal_11(void);
void Ordinal_16(void);
void Ordinal_19(void);
void Ordinal_23(void);
void Ordinal_52(void);
void Ordinal_115(void);
void Ordinal_116(void);
void Catch_All_0062f7fe(void);
void Catch_All_0062f8a6(void);
void Catch_All_0062f98f(void);
void Catch_All_0062ff94(void);
void Catch_All_00630207(void);
void Catch_All_006302a9(void);
void Catch_All_0063039d(void);
void Catch_All_0063044f(void);
void tree_nodeFree(void *param_1);
void Catch_All_00638f84(void);
/* Library Function - Multiple Matches With Same Base Name struct `protected: int __thiscall GSI1::readHash(unsigned short,long,long)'::`2'::FileSymbolInfo * __cdecl std::_Uninitialized_move<struct `protected: int __thiscall GSI1::readHash(unsigned short,long,long)'::`2'::FileSymbolInfo *,class std::allocator<struct `protected: int __thiscall GSI1::readHash(unsigned short,long,long)'::`2'::FileSymbolInfo> >(struct `protected: int __thiscall GSI1::readHash(unsigned short,long,long)'::`2'::FileSymbolInfo * const,struct `protected: int __thiscall GSI1::readHash(unsigned short,long,long)'::`2'::FileSymbolInfo * const,struct `protected: int __thiscall GSI1::readHash(unsigned short,long,long)'::`2'::FileSymbolInfo *,class std::allocator<struct `protected: int __thiscall GSI1::readHash(unsigned short,long,long)'::`2'::FileSymbolInfo> &) struct GSISymbolEntry * __cdecl std::_Uninitialized_move<struct GSISymbolEntry *,class std::allocator<struct GSISymbolEntry> >(struct GSISymbolEntry * const,struct GSISymbolEntry * const,struct GSISymbolEntry *,class std::allocator<struct GSISymbolEntry> &) Library: Visual Studio 2019 Release */ void _Uninitialized_move<>(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Catch_All_0063a13f(void);
void Catch_All_0063a337(void);
void Catch_All_0063a4be(void);
void Catch_All_0063a5ba(void);
void Catch_All_0063a7e6(void);
void Catch_All_0063c08f(void);
void Catch_All_0063c13f(void);
void Catch_All_0063c1ef(void);
void Catch_All_0063d153(void);
void Catch_All_0063d279(void);
void Catch_All_0063d3ea(void);
void Catch_All_0063d509(void);
void Catch_All_0063d6d3(void);
void Catch_All_0063db73(void);
void Catch_All_0063dc70(void);
void lib_fn_642700(int param_1);
void lib_fn_642770(int param_1);
void lib_fn_6427e0(int param_1);
void Catch_All_00642a01(void);
basic_ostream<wchar_t,std::char_traits<wchar_t>_> * lib_fn_64b0d0(basic_ostream<wchar_t,std::char_traits<wchar_t>_> *param_1,wchar_t param_2);
undefined * Catch_All_0064b251(void);
undefined4 * lib_fn_64b2e0(undefined4 *param_1,short *param_2,int param_3);
void Catch_All_0064b441(void);
void Catch_All_0064bb48(void);
void Catch_All_0064bc78(void);
void Catch_All_0064bdc4(void);
void std::basic_filebuf<char,std::char_traits<char>_>::ctor_9 (undefined4 param_1,uint param_2,undefined4 param_3,int param_4);
void std::basic_filebuf<char,std::char_traits<char>_>::ctor_10(int param_1);
void Catch_All_0064e67d(void);
void lib_fn_64e850(undefined4 *param_1);
void lib_fn_64e8f0(undefined4 *param_1);
void lib_fn_64e9b0(undefined4 *param_1);
void std::basic_stringbuf<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>::ctor_15 (int param_1,int param_2,int param_3,undefined4 param_4);
undefined4 lib_fn_64fd30(undefined4 param_1);
void lib_fn_64fda0(int param_1,undefined4 param_2);
/* WARNING: Type propagation algorithm not settling */ void std::basic_filebuf<char,std::char_traits<char>_>::ctor_5 (undefined4 *param_1,undefined4 param_2,float param_3);
basic_streambuf<char,std::char_traits<char>_> * lib_fn_653210(wchar_t *param_1,int param_2,int *param_3);
void std::basic_filebuf<char,std::char_traits<char>_>::ctor_7 (undefined4 *param_1,undefined4 param_2);
void Catch_All_0065a0c2(void);
void Catch_All_0065a601(void);
void Catch_All_0065a83f(void);
void lib_fn_65aeb0(void *param_1);
void std::basic_filebuf<char,std::char_traits<char>_>::ctor_6(undefined4 *param_1);
void Catch_All_0066145d(void);
void Catch_All_0066311a(void);
void Catch_All_00663953(void);
void Catch_All_00663a79(void);
void Catch_All_00665c71(void);
void Catch_All_00666069(void);
void Catch_All_0066826a(void);
void Catch_All_006684b8(void);
void Catch_All_0066874c(void);
void Catch_All_0066892c(void);
void Catch_All_00668a1f(void);
/* WARNING: Function: __alloca_probe_16 replaced with injection: alloca_probe */ void std::bad_alloc::ctor_10(undefined4 param_1,uint param_2,int *param_3,undefined4 param_4);
/* WARNING: Function: __alloca_probe_16 replaced with injection: alloca_probe */ void std::bad_alloc::ctor_7(undefined4 param_1,uint param_2,int *param_3,undefined4 param_4);
/* WARNING: Function: __alloca_probe_16 replaced with injection: alloca_probe */ void std::bad_alloc::ctor_8(undefined4 param_1,uint param_2,int *param_3,undefined4 param_4);
/* WARNING: Function: __alloca_probe_16 replaced with injection: alloca_probe */ void std::bad_alloc::ctor_9(undefined4 param_1,uint param_2,int *param_3,undefined4 param_4);
/* WARNING: Function: __alloca_probe_16 replaced with injection: alloca_probe */ void std::bad_alloc::ctor_6(undefined4 param_1,uint param_2,int *param_3,undefined4 param_4);
void lib_fn_66e1b0(undefined4 param_1);
void Concurrency::details::_UnrealizedChore::ctor_0(void);
void std::bad_alloc::ctor_5(exception *param_1);
void Concurrency::missing_wait::ctor_0(exception *param_1);
void Concurrency::details::_Chore::ctor_14(void);
void Concurrency::details::_Chore::ctor_15(void);
void Concurrency::details::_Chore::ctor_16(void);
void Concurrency::details::_Chore::ctor_17(void);
void Concurrency::details::_Chore::ctor_18(void);
void Concurrency::details::_Chore::ctor_19(void);
void Concurrency::details::_Chore::ctor_20(void);
void Concurrency::details::_Chore::ctor_21(void);
void Concurrency::details::_Chore::ctor_6(void);
void Concurrency::details::_Chore::ctor_7(void);
void Concurrency::details::_Chore::ctor_8(void);
void Concurrency::details::_Chore::ctor_10(void);
void Concurrency::details::_Chore::ctor_9(void);
void Concurrency::details::_Chore::ctor_11(void);
void Concurrency::details::_Chore::ctor_12(void);
void Concurrency::details::_Chore::ctor_13(void);
/* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ void std::bad_alloc::ctor_4(void);
/* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ void std::bad_alloc::ctor_2(void);
/* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ void std::bad_alloc::ctor_3(void);
/* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ void std::bad_alloc::ctor_1(void);
/* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ void std::bad_alloc::ctor_0(void);
void Concurrency::details:: _MallocaArrayHolder<Concurrency::task_handle<Concurrency::_Parallel_chunk_helper<Concurrency::details::_Vector_iterator<Concurrency::concurrent_vector<plasma::QuadVertex*,std::allocator<plasma::QuadVertex*>_>,plasma::QuadVertex*>,int,<lambda_c31a3785b8ee29a1ce8445e019cbe6ee>,Concurrency::auto_partitioner,1>_>_> ::vfunc_0(byte param_1);
void Concurrency::details:: _MallocaArrayHolder<Concurrency::task_handle<Concurrency::_Parallel_chunk_helper<Concurrency::details::_Vector_iterator<Concurrency::concurrent_vector<plasma::QuadVertex*,std::allocator<plasma::QuadVertex*>_>,plasma::QuadVertex*>,int,<lambda_fe4ce4a6aaf0318c62c756eaccc0431b>,Concurrency::auto_partitioner,1>_>_> ::vfunc_0(byte param_1);
void Concurrency::details:: _MallocaArrayHolder<Concurrency::task_handle<Concurrency::_Parallel_chunk_helper<Concurrency::details::_Vector_iterator<Concurrency::concurrent_vector<plasma::QuadEdge,std::allocator<plasma::QuadEdge>_>,plasma::QuadEdge>,int,<lambda_9843e8019373a7557d3f3e498d32c258>,Concurrency::auto_partitioner,1>_>_> ::vfunc_0(byte param_1);
void Concurrency::details:: _MallocaArrayHolder<Concurrency::task_handle<Concurrency::_Parallel_chunk_helper<Concurrency::details::_Vector_iterator<Concurrency::concurrent_vector<plasma::QuadEdge,std::allocator<plasma::QuadEdge>_>,plasma::QuadEdge>,int,<lambda_e3fd6255bcf168381cb2d01c4cfc52ca>,Concurrency::auto_partitioner,1>_>_> ::vfunc_0(byte param_1);
void Concurrency::details:: _MallocaArrayHolder<Concurrency::task_handle<Concurrency::_Parallel_chunk_helper<Concurrency::details::_Vector_iterator<Concurrency::concurrent_vector<plasma::QuadFace,std::allocator<plasma::QuadFace>_>,plasma::QuadFace>,int,<lambda_37224fa58ba67e25838a8994307bb82e>,Concurrency::auto_partitioner,1>_>_> ::vfunc_0(byte param_1);
void Concurrency::details:: _MallocaListHolder<Concurrency::task_handle<Concurrency::_Parallel_chunk_helper<Concurrency::details::_Vector_iterator<Concurrency::concurrent_vector<plasma::QuadVertex*,std::allocator<plasma::QuadVertex*>_>,plasma::QuadVertex*>,int,<lambda_c31a3785b8ee29a1ce8445e019cbe6ee>,Concurrency::auto_partitioner,1>_>_> ::vfunc_0(byte param_1);
void Concurrency::details:: _MallocaListHolder<Concurrency::task_handle<Concurrency::_Parallel_chunk_helper<Concurrency::details::_Vector_iterator<Concurrency::concurrent_vector<plasma::QuadVertex*,std::allocator<plasma::QuadVertex*>_>,plasma::QuadVertex*>,int,<lambda_fe4ce4a6aaf0318c62c756eaccc0431b>,Concurrency::auto_partitioner,1>_>_> ::vfunc_0(byte param_1);
void Concurrency::details:: _MallocaListHolder<Concurrency::task_handle<Concurrency::_Parallel_chunk_helper<Concurrency::details::_Vector_iterator<Concurrency::concurrent_vector<plasma::QuadEdge,std::allocator<plasma::QuadEdge>_>,plasma::QuadEdge>,int,<lambda_9843e8019373a7557d3f3e498d32c258>,Concurrency::auto_partitioner,1>_>_> ::vfunc_0(byte param_1);
void Concurrency::details:: _MallocaListHolder<Concurrency::task_handle<Concurrency::_Parallel_chunk_helper<Concurrency::details::_Vector_iterator<Concurrency::concurrent_vector<plasma::QuadEdge,std::allocator<plasma::QuadEdge>_>,plasma::QuadEdge>,int,<lambda_e3fd6255bcf168381cb2d01c4cfc52ca>,Concurrency::auto_partitioner,1>_>_> ::vfunc_0(byte param_1);
void Concurrency::details:: _MallocaListHolder<Concurrency::task_handle<Concurrency::_Parallel_chunk_helper<Concurrency::details::_Vector_iterator<Concurrency::concurrent_vector<plasma::QuadFace,std::allocator<plasma::QuadFace>_>,plasma::QuadFace>,int,<lambda_37224fa58ba67e25838a8994307bb82e>,Concurrency::auto_partitioner,1>_>_> ::vfunc_0(byte param_1);
void Concurrency::details::_Chore::ctor_4(byte param_1);
void Concurrency::details::_Chore::ctor_5(byte param_1);
void Concurrency::details::_Chore::ctor_0(byte param_1);
void Concurrency::details::_Chore::ctor_1(byte param_1);
void Concurrency::details::_Chore::ctor_2(byte param_1);
void Concurrency::details::_Chore::vfunc_0(byte param_1);
void Concurrency::details::_Chore::ctor_3(byte param_1);
void std::bad_alloc::vfunc_0(byte param_1);
void Concurrency::missing_wait::vfunc_0(byte param_1);
void lib_fn_6712c0(int *param_1,int *param_2);
uint lib_fn_671340(int *param_1);
void Catch_All_00672f4f(void);
void Catch_All_0067795a(void);
void Catch_All_00677b82(void);
void Catch_All_00677e05(void);
void Catch_All_0067e0a5(void);
void Catch_All_0067e1cf(void);
void plasma::PlasmaFont::ctor_0(undefined4 param_1,undefined4 param_2);
int lib_fn_67e4d0(void);
void lib_fn_67f1b0(undefined4 param_1,float *param_2,float *param_3,float param_4,float param_5);
void lib_fn_67f980(undefined4 param_1,float *param_2,float *param_3,float *param_4,float *param_5, float param_6);
void lib_fn_67fa50(undefined4 param_1);
void Catch_All_0067fc38(void);
void Catch_All_0067fd6d(void);
void Catch_All_006812ef(void);
void Sleep(DWORD dwMilliseconds);
BOOL DeleteFileA(LPCSTR lpFileName);
HLOCAL LocalFree(HLOCAL hMem);
BOOL AreFileApisANSI(void);
void GetSystemTime(LPSYSTEMTIME lpSystemTime);
DWORD GetTempPathA(DWORD nBufferLength,LPSTR lpBuffer);
DWORD GetCurrentProcessId(void);
BOOL DeleteFileW(LPCWSTR lpFileName);
BOOL CloseHandle(HANDLE hObject);
BOOL GetVersionExA(LPOSVERSIONINFOA lpVersionInformation);
BOOL GetFileAttributesExW (LPCWSTR lpFileName,GET_FILEEX_INFO_LEVELS fInfoLevelId,LPVOID lpFileInformation);
void GetSystemInfo(LPSYSTEM_INFO lpSystemInfo);
HANDLE CreateFileMappingW(HANDLE hFile,LPSECURITY_ATTRIBUTES lpFileMappingAttributes,DWORD flProtect ,DWORD dwMaximumSizeHigh,DWORD dwMaximumSizeLow,LPCWSTR lpName);
HMODULE LoadLibraryA(LPCSTR lpLibFileName);
BOOL LockFileEx(HANDLE hFile,DWORD dwFlags,DWORD dwReserved,DWORD nNumberOfBytesToLockLow, DWORD nNumberOfBytesToLockHigh,LPOVERLAPPED lpOverlapped);
FARPROC GetProcAddress(HMODULE hModule,LPCSTR lpProcName);
DWORD GetLastError(void);
DWORD GetTempPathW(DWORD nBufferLength,LPWSTR lpBuffer);
BOOL FlushFileBuffers(HANDLE hFile);
int MultiByteToWideChar(UINT CodePage,DWORD dwFlags,LPCSTR lpMultiByteStr,int cbMultiByte, LPWSTR lpWideCharStr,int cchWideChar);
HANDLE CreateFileW(LPCWSTR lpFileName,DWORD dwDesiredAccess,DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes,DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes,HANDLE hTemplateFile);
BOOL ReadFile(HANDLE hFile,LPVOID lpBuffer,DWORD nNumberOfBytesToRead,LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped);
DWORD GetFileAttributesW(LPCWSTR lpFileName);
DWORD GetFileAttributesA(LPCSTR lpFileName);
DWORD FormatMessageW(DWORD dwFlags,LPCVOID lpSource,DWORD dwMessageId,DWORD dwLanguageId, LPWSTR lpBuffer,DWORD nSize,va_list *Arguments);
HMODULE LoadLibraryW(LPCWSTR lpLibFileName);
int WideCharToMultiByte(UINT CodePage,DWORD dwFlags,LPCWSTR lpWideCharStr,int cchWideChar, LPSTR lpMultiByteStr,int cbMultiByte,LPCSTR lpDefaultChar, LPBOOL lpUsedDefaultChar);
BOOL WriteFile(HANDLE hFile,LPCVOID lpBuffer,DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten,LPOVERLAPPED lpOverlapped);
DWORD FormatMessageA(DWORD dwFlags,LPCVOID lpSource,DWORD dwMessageId,DWORD dwLanguageId, LPSTR lpBuffer,DWORD nSize,va_list *Arguments);
void GetSystemTimeAsFileTime(LPFILETIME lpSystemTimeAsFileTime);
BOOL UnlockFileEx(HANDLE hFile,DWORD dwReserved,DWORD nNumberOfBytesToUnlockLow, DWORD nNumberOfBytesToUnlockHigh,LPOVERLAPPED lpOverlapped);
DWORD GetTickCount(void);
BOOL LockFile(HANDLE hFile,DWORD dwFileOffsetLow,DWORD dwFileOffsetHigh, DWORD nNumberOfBytesToLockLow,DWORD nNumberOfBytesToLockHigh);
BOOL UnlockFile(HANDLE hFile,DWORD dwFileOffsetLow,DWORD dwFileOffsetHigh, DWORD nNumberOfBytesToUnlockLow,DWORD nNumberOfBytesToUnlockHigh);
BOOL QueryPerformanceCounter(LARGE_INTEGER *lpPerformanceCount);
BOOL FreeLibrary(HMODULE hLibModule);
BOOL SetEndOfFile(HANDLE hFile);
BOOL UnmapViewOfFile(LPCVOID lpBaseAddress);
LPVOID MapViewOfFile(HANDLE hFileMappingObject,DWORD dwDesiredAccess,DWORD dwFileOffsetHigh, DWORD dwFileOffsetLow,SIZE_T dwNumberOfBytesToMap);
DWORD SetFilePointer(HANDLE hFile,LONG lDistanceToMove,PLONG lpDistanceToMoveHigh,DWORD dwMoveMethod );
DWORD GetFileSize(HANDLE hFile,LPDWORD lpFileSizeHigh);
HANDLE CreateFileA(LPCSTR lpFileName,DWORD dwDesiredAccess,DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes,DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes,HANDLE hTemplateFile);
DWORD GetFullPathNameA(LPCSTR lpFileName,DWORD nBufferLength,LPSTR lpBuffer,LPSTR *lpFilePart);
DWORD GetFullPathNameW(LPCWSTR lpFileName,DWORD nBufferLength,LPWSTR lpBuffer,LPWSTR *lpFilePart);
void __thiscall std::basic_ios<char,std::char_traits<char>_>::_Add_vtordisp2 (basic_ios<char,std::char_traits<char>_> *this);
void __thiscall std::basic_streambuf<char,std::char_traits<char>_>::_Lock (basic_streambuf<char,std::char_traits<char>_> *this);
void __thiscall std::basic_streambuf<char,std::char_traits<char>_>::_Unlock (basic_streambuf<char,std::char_traits<char>_> *this);
void __thiscall std::basic_streambuf<char,std::char_traits<char>_>::imbue (basic_streambuf<char,std::char_traits<char>_> *this,locale *param_1);
basic_streambuf<char,struct_std::char_traits<char>_> * __thiscall std::basic_streambuf<char,std::char_traits<char>_>::setbuf (basic_streambuf<char,std::char_traits<char>_> *this,char *param_1,__int64 param_2);
__int64 __thiscall std::basic_streambuf<char,std::char_traits<char>_>::showmanyc (basic_streambuf<char,std::char_traits<char>_> *this);
int __thiscall std::basic_streambuf<char,std::char_traits<char>_>::sync (basic_streambuf<char,std::char_traits<char>_> *this);
int __thiscall std::basic_streambuf<char,std::char_traits<char>_>::uflow (basic_streambuf<char,std::char_traits<char>_> *this);
__int64 __thiscall std::basic_streambuf<char,std::char_traits<char>_>::xsgetn (basic_streambuf<char,std::char_traits<char>_> *this,char *param_1,__int64 param_2);
__int64 __thiscall std::basic_streambuf<char,std::char_traits<char>_>::xsputn (basic_streambuf<char,std::char_traits<char>_> *this,char *param_1,__int64 param_2);
void __thiscall std::basic_streambuf<wchar_t,std::char_traits<wchar_t>_>::_Lock (basic_streambuf<wchar_t,std::char_traits<wchar_t>_> *this);
void __thiscall std::basic_streambuf<wchar_t,std::char_traits<wchar_t>_>::_Unlock (basic_streambuf<wchar_t,std::char_traits<wchar_t>_> *this);
void __thiscall std::basic_streambuf<wchar_t,std::char_traits<wchar_t>_>::imbue (basic_streambuf<wchar_t,std::char_traits<wchar_t>_> *this,locale *param_1);
basic_streambuf<wchar_t,struct_std::char_traits<wchar_t>_> * __thiscall std::basic_streambuf<wchar_t,std::char_traits<wchar_t>_>::setbuf (basic_streambuf<wchar_t,std::char_traits<wchar_t>_> *this,wchar_t *param_1, __int64 param_2);
__int64 __thiscall std::basic_streambuf<wchar_t,std::char_traits<wchar_t>_>::showmanyc (basic_streambuf<wchar_t,std::char_traits<wchar_t>_> *this);
int __thiscall std::basic_streambuf<wchar_t,std::char_traits<wchar_t>_>::sync (basic_streambuf<wchar_t,std::char_traits<wchar_t>_> *this);
ushort __thiscall std::basic_streambuf<wchar_t,std::char_traits<wchar_t>_>::uflow (basic_streambuf<wchar_t,std::char_traits<wchar_t>_> *this);
__int64 __thiscall std::basic_streambuf<wchar_t,std::char_traits<wchar_t>_>::xsgetn (basic_streambuf<wchar_t,std::char_traits<wchar_t>_> *this,wchar_t *param_1, __int64 param_2);
__int64 __thiscall std::basic_streambuf<wchar_t,std::char_traits<wchar_t>_>::xsputn (basic_streambuf<wchar_t,std::char_traits<wchar_t>_> *this,wchar_t *param_1, __int64 param_2);
void __thiscall std::basic_ios<char,std::char_traits<char>_>::_Add_vtordisp1 (basic_ios<char,std::char_traits<char>_> *this);
void __cdecl purecall(void);
void * __cdecl operator_new(uint param_1);
void __cdecl operator_delete(void *param_1);
/* WARNING: Function: __SEH_prolog4 replaced with injection: SEH_prolog4 */ /* WARNING: Function: __SEH_epilog4 replaced with injection: EH_epilog3 */ /* Library Function - Single Match __onexit Library: Visual Studio 2012 Release */ _onexit_t __onexit(_onexit_t param_1);
void lib_fn_68d74c(void);
/* Library Function - Single Match _atexit Library: Visual Studio 2012 Release */ int __cdecl _atexit(_func_4879 *param_1);
void * __cdecl memmove(void *_Dst,void *_Src,size_t _Size);
int __cdecl fclose(FILE *_File);
/* Library Function - Single Match @eh_security_check_cookie_4 Library: Visual Studio 2012 Release __fastcall __security_check_cookie,4 */ void __fastcall __security_check_cookie(int param_1);
void _CxxThrowException(void *pExceptionObject,ThrowInfo *pThrowInfo);
void __cdecl libm_sse2_cos_precise(void);
void * __cdecl memcpy(void *_Dst,void *_Src,size_t _Size);
void * __cdecl memset(void *_Dst,int _Val,size_t _Size);
void type_info::vfunc_0(byte param_1);
/* WARNING: Function: __SEH_prolog4 replaced with injection: SEH_prolog4 */ /* WARNING: Function: __SEH_epilog4 replaced with injection: EH_epilog3 */ /* Library Function - Single Match void __stdcall __ArrayUnwind(void *,unsigned int,int,void (__thiscall*)(void *)) Library: Visual Studio 2012 Release */ void __ArrayUnwind(void *param_1,uint param_2,int param_3,_func_void_void_ptr *param_4);
void __cdecl operator_delete__(void *param_1);
void __cdecl libm_sse2_pow_precise(void);
/* WARNING: This is an inlined function */ /* Library Function - Single Match __chkstk Library: Visual Studio */ void __alloca_probe(void);
void __cdecl libm_sse2_asin_precise(void);
void __cdecl libm_sse2_sin_precise(void);
void __cdecl libm_sse2_sqrt_precise(void);
void __cdecl libm_sse2_tan_precise(void);
/* Library Function - Single Match __alldiv Libraries: Visual Studio 2012 Release, Visual Studio 2015 Release, Visual Studio 2017 Release, Visual Studio 2019 Release */ undefined8 __alldiv(uint param_1,uint param_2,uint param_3,uint param_4);
/* Library Function - Single Match __allmul Library: Visual Studio */ longlong __allmul(uint param_1,int param_2,uint param_3,int param_4);
void __RTDynamicCast(void);
void __cdecl libm_sse2_acos_precise(void);
size_t __cdecl fread(void *_DstBuf,size_t _ElementSize,size_t _Count,FILE *_File);
long __cdecl ftell(FILE *_File);
void __cdecl free(void *_Memory);
void * __cdecl malloc(size_t _Size);
FILE * __cdecl fopen(char *_Filename,char *_Mode);
int __cdecl fseek(FILE *_File,long _Offset,int _Origin);
int __cdecl sprintf(char *_Dest,char *_Format,...);
void __cdecl longjmp(int *_Buf,int _Value);
void __cdecl setjmp3(void);
/* Library Function - Single Match ___raise_securityfailure Library: Visual Studio 2012 Release */ void ___raise_securityfailure(EXCEPTION_POINTERS *param_1);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ /* Library Function - Single Match ___report_gsfailure Library: Visual Studio 2012 Release */ void __cdecl ___report_gsfailure(void);
/* Library Function - Single Match ___report_rangecheckfailure Libraries: Visual Studio 2012 Release, Visual Studio 2017 Release, Visual Studio 2019 Release */ void ___report_rangecheckfailure(void);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ /* Library Function - Single Match ___report_securityfailure Library: Visual Studio 2012 Release */ void ___report_securityfailure(undefined4 param_1);
double __cdecl floor(double _X);
void * __cdecl realloc(void *_Memory,size_t _NewSize);
int __cdecl strncmp(char *_Str1,char *_Str2,size_t _MaxCount);
/* Library Function - Single Match __alldvrm Library: Visual Studio */ undefined8 __alldvrm(uint param_1,uint param_2,uint param_3,uint param_4);
/* Library Function - Single Match __allrem Library: Visual Studio */ undefined8 __allrem(uint param_1,uint param_2,uint param_3,uint param_4);
/* Library Function - Single Match __allshl Library: Visual Studio */ longlong __allshl(void);
/* Library Function - Single Match __aulldiv Library: Visual Studio */ undefined8 __aulldiv(uint param_1,uint param_2,uint param_3,uint param_4);
/* Library Function - Single Match __aulldvrm Library: Visual Studio */ undefined8 __aulldvrm(uint param_1,uint param_2,uint param_3,uint param_4);
/* Library Function - Single Match __aullrem Library: Visual Studio */ undefined8 __aullrem(uint param_1,uint param_2,uint param_3,uint param_4);
void __cdecl libm_sse2_exp_precise(void);
/* Library Function - Single Match __allshr Library: Visual Studio */ undefined8 __allshr(void);
/* WARNING: This is an inlined function */ /* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ /* Library Function - Single Match __alloca_probe_16 Library: Visual Studio */ uint __alloca_probe_16(void);
/* WARNING: This is an inlined function */ /* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ /* Library Function - Single Match __alloca_probe_8 Library: Visual Studio */ uint __alloca_probe_8(void);
void __cdecl qsort(void *_Base,size_t _NumOfElements,size_t _SizeOfElements,_PtFuncCompare *_PtFuncCompare);
void * __cdecl memchr(void *_Buf,int _Val,size_t _MaxCount);
void __cdecl libm_sse2_log_precise(void);
char * __thiscall std::exception::what(exception *this);
void __cdecl _lock(int _File);
void __cdecl _unlock(int _File);
void __dllonexit(void);
/* WARNING: This is an inlined function */ /* WARNING: Unable to track spacebase fully for stack */ /* Library Function - Single Match __SEH_prolog4 Library: Visual Studio */ void __SEH_prolog4(undefined4 param_1,int param_2);
/* WARNING: This is an inlined function */ /* Library Function - Single Match __SEH_epilog4 Library: Visual Studio */ void __SEH_epilog4(void);
void __thiscall type_info::~type_info(type_info *this);
void __cdecl terminate(void);
void __cdecl _crt_debugger_hook(int param_1);
LONG __cdecl __crtUnhandledException(EXCEPTION_POINTERS *exceptionInfo);
void __cdecl __crtTerminateProcess(UINT uExitCode);
void __cdecl _amsg_exit(int param_1);
/* Library Function - Single Match __FindPESection Library: Visual Studio 2012 Release */ PIMAGE_SECTION_HEADER __cdecl __FindPESection(PBYTE pImageBase,DWORD_PTR rva);
/* Library Function - Single Match __IsNonwritableInCurrentImage Library: Visual Studio 2012 Release */ BOOL __cdecl __IsNonwritableInCurrentImage(PBYTE pTarget);
/* Library Function - Single Match __ValidateImageBase Libraries: Visual Studio 2012 Release, Visual Studio 2015 Release */ BOOL __cdecl __ValidateImageBase(PBYTE pImageBase);
/* Library Function - Single Match ___security_init_cookie Library: Visual Studio 2012 Release */ void __cdecl ___security_init_cookie(void);
void __cdecl initterm_e(void);
void __cdecl initterm(void);
void __cdecl except_handler4_common(void);
void __cdecl __crtSetUnhandledExceptionFilter(LPTOP_LEVEL_EXCEPTION_FILTER exceptionFilter);
void __cdecl _invoke_watson(wchar_t *param_1,wchar_t *param_2,wchar_t *param_3,uint param_4,uintptr_t param_5);
errno_t __cdecl _controlfp_s(uint *_CurrentState,uint _NewValue,uint _Mask);
void GetAdaptersInfo(void);
void lib_fn_68f990(undefined4 param_1,uint param_2,uint param_3);
void thunk_FUN_006b3c40(void);
void __cdecl free(void *_Memory);
void thunk_FUN_006cf090(undefined4 param_1,int param_2,int param_3);
void gluNewTess(void);
void gluDeleteTess(void);
void gluTessBeginPolygon(void);
void gluTessBeginContour(void);
void gluTessVertex(void);
void gluTessEndContour(void);
void gluTessEndPolygon(void);
void gluTessProperty(void);
void gluTessCallback(void);
BOOL IsProcessorFeaturePresent(DWORD ProcessorFeature);
char * __cdecl strncpy(char *_Dest,char *_Source,size_t _Count);
char * __cdecl strrchr(char *_Str,int _Ch);
long __cdecl atol(char *_Str);
char * __cdecl strstr(char *_Str,char *_SubStr);
void __cdecl libm_sse2_atan_precise(void);
/* Library Function - Single Match ___common_srl Libraries: Visual Studio 2012, Visual Studio 2015, Visual Studio 2017, Visual Studio 2019 */ undefined8 ___common_srl(uint param_1,int param_2,byte param_3);
/* Library Function - Single Match ___common_sll Libraries: Visual Studio 2012, Visual Studio 2015, Visual Studio 2017, Visual Studio 2019 */ longlong ___common_sll(uint param_1,int param_2,byte param_3);
void std::error_category::ctor_0(void);
void std::error_category::ctor_1(void);
void std::error_category::ctor_2(void);

#endif
