// game_misc (cube) — reconstructed declarations.
#ifndef CUBE_GAME_MISC_GAME_MISC_H
#define CUBE_GAME_MISC_GAME_MISC_H
#include "../include/cube_types.h"

void copyBytes(undefined1 *param_1,undefined1 *param_2,undefined1 *param_3);
void vectorString_popBack(undefined4 param_1,undefined4 param_2);
void signal_dispatchArg(undefined4 param_1,undefined4 param_2);
void swap_u32(undefined4 *param_1,undefined4 *param_2);
void string_moveConstruct2(undefined4 *param_1);
void vectorString_copyElem(int *param_1);
void abstr::Machine::ctor_1(void);
void string_moveAssign(undefined4 *param_1);
void string_fillAssign(int param_1,size_t param_2,char param_3);
/* WARNING: Removing unreachable block (ram,0x00405d2b) */ void filebuf_endWrite(void);
void string_appendFill(uint param_1,undefined4 param_2);
void string_assignPtrLen(int *param_1,uint param_2);
undefined4 * string_data(void);
uint memcmp_traits(byte *param_1,byte *param_2,uint param_3);
void abstr::Method0<abstr::Machine,int>::ctor_0 (basic_istream<char,std::char_traits<char>_> *param_1);
undefined1 filebuf_openInstantiate(undefined4 *param_1);
void vectorPOD_insertAt(uint param_1);
void dispatch_callbackChain(int param_1);
void ostrstream_str(void);
undefined4 ostrstream_str_wrap(undefined4 param_1);
basic_ostream<wchar_t,std::char_traits<wchar_t>_> * wostream_insertNarrow(basic_ostream<wchar_t,std::char_traits<wchar_t>_> *param_1,char *param_2);
basic_ostream<wchar_t,std::char_traits<wchar_t>_> * wostream_insertWide(basic_ostream<wchar_t,std::char_traits<wchar_t>_> *param_1,wchar_t *param_2);
facet * useFacet_ctypeW(locale *param_1);
void setPair_a(undefined4 param_1,undefined4 param_2);
void setColor4b(undefined1 *param_1,undefined1 param_2);
void vec2_scale(float param_1);
char * getTargetEntity(void);
void proximityCheck(void);
void array_lerp(float *param_1,float *param_2,int param_3,float param_4);
void copy16bytes(undefined8 param_1,undefined8 param_2);
void vec4_scale(float *param_1,float param_2);
float10 vec2_dot(float *param_1);
void mat4_identity(void);
void vec2_normalize(void);
float10 asinf_f(float param_1);
void mat4_mulRight(float *param_1,float *param_2);
undefined4 * copyVec4Array(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void vectorErase8(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void resizeChildBuffers_type8(undefined4 param_1);
void vec3i64_setFromGen(void);
void vec3i64_toFloat(longlong *param_1);
void vec6_copy(undefined4 *param_1);
undefined4 * vec6_copyAndScale(undefined4 *param_1,undefined4 param_2,undefined4 param_3);
void arena_allocSlot0x11c(int *param_1);
uint * vec3i64_copySub(uint *param_1,uint *param_2);
uint * vec3i64_copyAdd(uint *param_1,uint *param_2);
undefined4 int64_ltGen(void);
void GameController_clearContainers(void);
void vec3i64_toIntFloor(int *param_1,undefined4 *param_2);
void int64_subGen(int *param_1);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ undefined * array_atChecked4(int param_1);
undefined * world_getColumnData(undefined4 param_1,undefined4 param_2,int param_3,undefined4 param_4);
void world_getColumnAtFixedPos(uint param_1,int param_2,uint param_3,int param_4,uint param_5,int param_6, undefined4 param_7);
byte getFlagBit6(void);
undefined4 world_getRegionCell64(uint param_1,uint param_2);
void textBuffer_eraseSelection(void);
int int64_gtFixed16(uint param_1);
void listHead_initWithNode(void);
void struct_initWithBuf(void);
bool ptr_equalsFirst(int *param_1);
void list_allocNode20(undefined4 *param_1,undefined4 *param_2);
float10 curve_diminishing01(int param_1);
undefined4 item_materialCategory(undefined4 param_1);
void combat_updateBombFuse(void);
float10 stat_calcArmor(void);
void stat_calcWeaponDamage(void);
float10 curve_diminishingx3p1(int param_1);
uint creature_isSpecialForm(void);
bool ability_isUsable(int param_1);
float10 curve_diminishingN1(int param_1);
float10 stat_calcManaRegen(void);
float10 curve_diminishingx3p15(int param_1);
void drop_getCountRange1(undefined4 param_1,undefined4 *param_2,undefined4 *param_3);
void drop_getValueRange(undefined4 param_1,undefined4 *param_2,undefined4 *param_3);
bool combat_rollHitChance(float param_1);
int combat_getStaminaCost(uint param_1);
bool combat_rollElementProc(void);
undefined4 creature_hasFireAffinity(void);
int creature_isBossType(void);
undefined4 creature_hasWaterAffinity(void);
uint ability_isChanneled(void);
float10 stat_calcAttackDamage(void);
int combat_getComboWindow(void);
int combat_selectAttackVariant(void);
undefined4 combat_advanceAttackTimer(void);
float10 math_pow2Mul(void);
float10 math_pow2Div(void);
float10 curve_inverse20p1(float param_1);
void Player_resetFull(void);
void Player_resetState(void);
float10 stat_calcSpirit(void);
float10 curve_diminishingP1(int param_1);
void projectile_getMuzzlePosition(uint *param_1);
int combat_getReloadFrames(uint param_1);
float10 curve_diminishingHalf(int param_1);
void render_bindNodeTransformA(void);
void render_setVec3Uniform5c(undefined4 param_1);
void render_setUniform30(undefined4 param_1);
void render_uploadBoneMatrices(undefined4 param_1,int param_2);
void render_setVec3Uniform58(undefined4 param_1);
basic_ostream<char,std::char_traits<char>_> * ostream_writePadded(basic_ostream<char,std::char_traits<char>_> *param_1,char *param_2);
undefined4 ostream_writeEpilogue(void);
void handle_freeMember4(void);
bool handle_isOpen(void);
undefined4 db_openBlobStore(undefined4 *param_1);
undefined4 db_loadBlobByKey(undefined4 param_1,undefined4 *param_2,size_t *param_3);
undefined1 db_getBlobInto(undefined4 param_1,undefined4 *param_2);
int list_makeNodeWrapper(undefined4 param_1,undefined4 param_2,undefined4 param_3);
int WorldInfo_allocMapNodeCopyKey(int param_1);
void clearTwoFields(void);
void refcount_initTo1(undefined4 param_1);
void reset_0x148Struct(void);
void dtor_13Strings_0x118(int param_1);
undefined4 * allocNode_0x48_copyHead(void);
byte isNonNegativeFlag(void);
void deserializeRegionChunk(int param_1,int param_2);
void sparseArray_setAt(int param_1,undefined1 *param_2);
void sparseArray_resize(uint param_1,int param_2);
void bytesToVec3Float(byte *param_1);
bool strEqual_cstr(int param_1,char *param_2);
undefined4 string_assign(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void dtor_stringRange_0x18(undefined4 *param_1,undefined4 *param_2);
int * moveStringRange_0x18(int *param_1,int *param_2,int *param_3);
void string_assignSwapTmp(undefined4 param_1,undefined4 *param_2,undefined4 param_3);
void pair_assign_2dword(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void Struct_reset_off14to46(void);
void Struct_copy_skipIdx1(undefined4 *param_1);
void Struct_reset_0dDwords(void);
void Struct_init_off3c_3f(void);
void Struct_init_off10_scale1(void);
void Struct_init_withFactory78(void);
void Struct_reset_1cDwords_flag(void);
void setQuadFaceFromNormal(undefined1 *param_1,int param_2,float *param_3);
void Struct_copy_1cDwords_b(undefined4 *param_1);
bool predicate_notFUN_2f4a0(undefined4 param_1);
undefined8 * ftol64_ofFloat(undefined8 *param_1);
float * vec3_negateSwapYZ(float *param_1);
void vec3_divScalar(float *param_1,float param_2);
bool less_stringKey_map(int param_1,undefined4 *param_2);
void Container_dtor_at78(void);
void * array_alloc_stride18(uint param_1);
void listNode_free_ownsString(void);
void ios_setstateFailIfZero(void);
void findNearestEntityDistSq(void);
void drawBillboardModelRotated(float param_1,float param_2,float *param_3,float param_4,char *param_5, float param_6);
void drawModelAtProjectedPos(float param_1,float param_2,float *param_3,float param_4,int param_5,float param_6 );
void hasNearbyAllyEntity(void);
undefined4 getChunkCellAt(int param_1,int param_2);
uint * fixed16_vec_lengthSquared(uint *param_1);
void GameController_buildWorldList(void);
float10 acosf_wrap(float param_1);
void GameState_addOrUpdateHitEntry(char param_1,char param_2,char param_3,char param_4,undefined4 param_5);
float10 item_computeBlockValue(void);
float10 item_computeStat_regen(void);
float10 item_computeValue(void);
float10 item_computeStat_armor(void);
void GameState_removeHitEntry(undefined4 param_1,undefined4 param_2,undefined4 param_3);
float10 item_computeStat_ranged(void);
float10 item_computeStat_variant2(void);
uint item_rerollStackCount(float param_1,char param_2);
void move_range_3(undefined1 *param_1,undefined1 *param_2,undefined1 *param_3);
int AdaptionWidget_vector_resize_3(uint param_1);
int int3_notEqual(int param_1);
int QuestText_cloneNode(undefined4 param_1);
undefined4 * GameController_snapshotEntityLists(int param_1);
void struct_copy3_andCall(undefined4 *param_1,undefined4 param_2);
void QuestText_copyTree_b(int *param_1,undefined4 param_2);
void QuestText_insertRebalance(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
void Container_ctor_default(undefined4 param_1);
void map_insert_string_key(int param_1);
void map_insert_string_key2(int param_1);
undefined4 * map_lower_bound_string(undefined4 *param_1);
void QuestText_substitute_placeholders(undefined4 param_1,undefined4 param_2,int param_3,int *param_4,int *param_5);
void format_object_singular_name(undefined4 param_1,undefined4 param_2,char *param_3,undefined4 param_4, undefined4 param_5);
undefined1 color_equals3(int param_1);
int * vec3_divide_scalar(int *param_1,int param_2);
void VoxelModel_load_from_file_or_buffer(int param_1,size_t param_2,int param_3);
void VoxelModel_allocate(undefined4 param_1,undefined4 param_2,int param_3);
void VoxelModel_set_data(undefined4 param_1,undefined4 param_2,int param_3,void *param_4,char param_5);
void VoxelModel_build_mesh(void);
float10 VoxelModel_compute_ao(int param_1,int param_2,int param_3,int *param_4);
int map_alloc_node_swap(undefined4 *param_1);
void map_insert_rebalance(undefined4 *param_1,char param_2,undefined4 *param_3,undefined4 param_4, int *param_5);
undefined4 * map_insert_with_hint(undefined4 *param_1,int *param_2,int *param_3,undefined4 param_4);
void map_insert_unique(undefined4 *param_1,char param_2,int *param_3,undefined4 param_4);
void string_assign_cstr(char *param_1);
undefined4 * map_subscript_int(int *param_1);
void IntMap_SetScalar(undefined4 param_1,undefined4 param_2,undefined4 *param_3);
void abstr::Method1<cube::System,int,int>::ctor_0 (undefined4 param_1,undefined4 param_2,undefined4 param_3);
void abstr:: Method1<cube::System,int,std::basic_string<char,std::char_traits<char>,std::allocator<char>_>_> ::ctor_0(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void abstr:: Method2<cube::System,int,std::basic_string<char,std::char_traits<char>,std::allocator<char>_>,std::basic_string<char,struct_std::char_traits<char>,class_std::allocator<char>_>_> ::ctor_0(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void abstr:: Method0<cube::System,std::basic_string<char,std::char_traits<char>,std::allocator<char>_>_>:: ctor_0(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void abstr:: Method1<cube::System,std::basic_string<char,std::char_traits<char>,std::allocator<char>_>,int> ::ctor_0(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void abstr:: Method2<cube::System,std::basic_string<char,std::char_traits<char>,std::allocator<char>_>,std::basic_string<char,struct_std::char_traits<char>,class_std::allocator<char>_>,std::basic_string<char,struct_std::char_traits<char>,class_std::allocator<char>_>_> ::ctor_0(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void abstr::Method1<cube::System,void,int>::ctor_0 (undefined4 param_1,undefined4 param_2,undefined4 param_3);
void abstr:: Method1<cube::System,void,std::basic_string<char,std::char_traits<char>,std::allocator<char>_>_> ::ctor_0(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void abstr:: Method2<cube::System,void,std::basic_string<char,std::char_traits<char>,std::allocator<char>_>,std::basic_string<char,struct_std::char_traits<char>,class_std::allocator<char>_>_> ::ctor_0(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void Vec3_IntToFloat(int *param_1);
void Vec2_DoubleToInt(int param_1);
void Pair_Copy2(undefined4 *param_1);
int MapNode_CreateXY(undefined4 *param_1);
int MapNode_CreateB(int param_1);
void Struct_InitScaleDefaults(void);
void Entity_CopyState(int param_1);
void Struct_InitDefaults(void);
void Member_Destroy(void);
void Vec3_Add(int *param_1,int *param_2);
void Array_ElementPtr12(int *param_1,int param_2);
undefined8 * Float_FromRef(undefined8 *param_1);
uint Vec2_Less(uint *param_1);
uint Vec2_LessEqual(uint *param_1);
void CombatBehavior_applyMeleeHit(undefined4 *param_1,int param_2,float param_3);
void CombatBehavior_spawnProjectileHit(float param_1,int param_2,float param_3,char param_4,undefined4 param_5, float param_6,undefined4 param_7,float *param_8,float *param_9,undefined4 param_10, char param_11,int param_12,undefined4 param_13,char param_14);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ undefined * VoxelChunk_cellAt(int param_1,int param_2,int param_3);
float10 Terrain_sampleHeightAtWorldXY(uint param_1,uint param_2);
void CombatBehavior_spawnHitParticles(undefined8 *param_1,undefined8 *param_2,float param_3,char param_4,int param_5, int param_6);
undefined4 Terrain_blockTypeAtTime(undefined4 param_1,undefined4 param_2,undefined8 param_3);
void Terrain_fillCuboid(int param_1,int param_2,int param_3,int *param_4,undefined4 param_5,char param_6);
void Terrain_spawnFallingBlock(undefined4 param_1,int *param_2,float param_3,float param_4,undefined4 param_5);
/* WARNING: Removing unreachable block (ram,0x0059b33d) */ /* WARNING: Removing unreachable block (ram,0x0059b346) */ /* WARNING: Removing unreachable block (ram,0x0059b34b) */ /* WARNING: Removing unreachable block (ram,0x0059b34d) */ /* WARNING: Removing unreachable block (ram,0x0059b357) */ /* WARNING: Removing unreachable block (ram,0x0059c3af) */ void Creature_spawnDeathEffects(int param_1,undefined4 param_2);
void World_enterCriticalSection(void);
void Terrain_paintDisk(int param_1,int param_2,int param_3,float param_4,byte *param_5,undefined4 param_6 ,char param_7,char param_8);
void Terrain_paintSphere(int param_1,int param_2,int param_3,float param_4,byte *param_5,undefined4 param_6 ,char param_7,char param_8);
void Entity_stepToward(uint *param_1,uint *param_2,undefined4 param_3,float param_4);
void Terrain_getBlockPacked(undefined4 *param_1,undefined4 param_2);
double * Terrain_sampleHeightNoise(double *param_1,int param_2,int param_3);
undefined4 Terrain_sampleBlockAt_fwd(undefined4 param_1,undefined1 *param_2);
float10 Terrain_sampleBlockBrightness(undefined4 *param_1);
undefined4 getField14(void);
void Entity_onStateChangeEmitEffect(int *param_1,int param_2,char param_3);
undefined4 Structure_getWidthByRotation(void);
undefined4 Structure_getHeightByRotation(void);
undefined4 getField_0x6c(void);
float10 vec2_lengthSquared(void);
void transformCoordsByRotation(int *param_1,int *param_2);
float10 terrainNoiseDensityAt(int param_1,float param_2);
float * randomizeVec3(float *param_1);
undefined2 * WorldMap_lookupTileValue2(undefined2 *param_1,int param_2,int param_3);
void NameGen_generateRegionName(undefined2 *param_1,uint param_2,int param_3);
void moveConstruct9Field(undefined4 *param_1);
int allocObjectWithVec3(undefined4 param_1,undefined4 param_2,undefined4 *param_3);
int allocNodeMovePayload(undefined4 param_1);
undefined4 lexicographicalLess(int *param_1,int *param_2,int *param_3,int *param_4);
void initStruct6Fields(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 *param_4);
void PathNodeMap_insertOrUpdate(undefined4 *param_1);
undefined4 AStar_coordExceedsBound(void);
undefined4 * PathNode_allocFromKey(void);
void Pathfinding_reconstructPath(int param_1);
void PathMap_probeClosedSet(undefined4 param_1,undefined4 param_2,undefined4 param_3);
int AStar_octileHeuristic(uint *param_1);
void AStar_pushOpenNode(int param_1,undefined4 param_2,undefined4 param_3,undefined4 *param_4);
/* WARNING: Removing unreachable block (ram,0x005aa8d9) */ /* WARNING: Removing unreachable block (ram,0x005aa43e) */ /* WARNING: Removing unreachable block (ram,0x005aa381) */ /* WARNING: Removing unreachable block (ram,0x005aa3ad) */ /* WARNING: Removing unreachable block (ram,0x005aa46d) */ /* WARNING: Removing unreachable block (ram,0x005aa98f) */ void Creature_expandNeighbors(int param_1);
/* WARNING: Removing unreachable block (ram,0x005abcd8) */ /* WARNING: Removing unreachable block (ram,0x005ab7ba) */ /* WARNING: Removing unreachable block (ram,0x005ab8ae) */ /* WARNING: Removing unreachable block (ram,0x005abb81) */ /* WARNING: Removing unreachable block (ram,0x005abddb) */ /* WARNING: Removing unreachable block (ram,0x005abf27) */ /* WARNING: Removing unreachable block (ram,0x005ac170) */ /* WARNING: Removing unreachable block (ram,0x005ac26b) */ void Creature_runPathfindingLoop(int param_1);
void Region_scatterProps(int param_1,uint *param_2);
void vec4_floatToInt(int param_1);
void fixedPointToInt_xy(undefined4 *param_1);
void setVec4_5aea50(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void structConstruct7Dword(undefined4 *param_1,undefined4 param_2);
/* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ /* WARNING: Removing unreachable block (ram,0x005b60f2) */ /* WARNING: Removing unreachable block (ram,0x005b1b25) */ /* WARNING: Removing unreachable block (ram,0x005b1af9) */ /* WARNING: Removing unreachable block (ram,0x005b6248) */ /* WARNING: Removing unreachable block (ram,0x005b6345) */ /* WARNING: Removing unreachable block (ram,0x005b65ab) */ /* WARNING: Removing unreachable block (ram,0x005b6478) */ /* WARNING: Removing unreachable block (ram,0x005b61c2) */ /* WARNING: Removing unreachable block (ram,0x005b61eb) */ /* WARNING: Removing unreachable block (ram,0x005b636e) */ /* WARNING: Removing unreachable block (ram,0x005b65d4) */ /* WARNING: Removing unreachable block (ram,0x005b64a1) */ /* WARNING: Removing unreachable block (ram,0x005b6271) */ /* WARNING: Removing unreachable block (ram,0x005b6646) */ /* WARNING: Removing unreachable block (ram,0x005b666f) */ /* WARNING: Removing unreachable block (ram,0x005b678a) */ void Chunk_generateObjects(int param_1,undefined4 *param_2);
undefined4 * spawnRandomObject7(undefined4 *param_1,undefined4 *param_2,undefined4 param_3);
void spawnRandomObjectPositioned(undefined4 param_1,uint *param_2,undefined4 param_3,int param_4);
undefined4 * spawnRandomObject4(undefined4 *param_1,undefined4 *param_2,undefined4 param_3);
int * spawnRandomObject3(int *param_1,int *param_2,int param_3);
undefined8 packWorldCoord64(uint param_1,uint param_2,uint param_3);
void copyByteTripleToInts(byte *param_1);
void copy2_helper(undefined1 *param_1,undefined1 *param_2,undefined1 *param_3);
void copy3_helper(undefined1 *param_1,undefined1 *param_2,undefined1 *param_3);
void init_call_46d4b0(void);
void init_call_65ae80(void);
void set4(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void copyctor_obj0x140(undefined4 *param_1);
void ctor_obj0x140(void);
void ctor_zero6i(void);
void ctor_from_two_vec3(undefined4 *param_1,undefined4 *param_2);
void dtor_free_two_buffers(void);
int * map3i_at(int *param_1);
int array24_at(int param_1);
uint * uint128_sub(uint *param_1,uint *param_2);
float * terrain_biomeColorFromNoise(float *param_1,int param_2,int param_3);
undefined1 * voxelVolume_at(int param_1,int param_2,int param_3);
float * clampRGB(float *param_1,float *param_2);
void dungeon_splitRegion_recursive(int *param_1,int *param_2,int *param_3,int *param_4);
void terrain_surfaceColor_blend(undefined4 *param_1,uint param_2,uint param_3,int param_4,float param_5, float param_6,undefined4 param_7);
void terrain_generateColumnColor(uint param_1,uint param_2,undefined4 param_3);
void terrain_rockColor_blend(float *param_1,int param_2,int param_3,int param_4,undefined4 param_5);
void ** creature_initBehaviorByType(int param_1,undefined4 param_2);
float10 getTemperatureAt(undefined4 param_1,undefined4 param_2,undefined4 param_3);
float10 getHumidityAt(undefined4 param_1,undefined4 param_2,undefined4 param_3);
/* WARNING: Removing unreachable block (ram,0x005c9891) */ /* WARNING: Removing unreachable block (ram,0x005c955c) */ /* WARNING: Removing unreachable block (ram,0x005c934a) */ /* WARNING: Removing unreachable block (ram,0x005c9131) */ /* WARNING: Removing unreachable block (ram,0x005c8f1f) */ /* WARNING: Removing unreachable block (ram,0x005c8d06) */ /* WARNING: Removing unreachable block (ram,0x005c8af4) */ /* WARNING: Removing unreachable block (ram,0x005c88e2) */ /* WARNING: Removing unreachable block (ram,0x005c86c9) */ /* WARNING: Removing unreachable block (ram,0x005c8517) */ /* WARNING: Removing unreachable block (ram,0x005c85c0) */ /* WARNING: Removing unreachable block (ram,0x005c87d2) */ /* WARNING: Removing unreachable block (ram,0x005c89eb) */ /* WARNING: Removing unreachable block (ram,0x005c8bfd) */ /* WARNING: Removing unreachable block (ram,0x005c8e16) */ /* WARNING: Removing unreachable block (ram,0x005c9028) */ /* WARNING: Removing unreachable block (ram,0x005c923a) */ /* WARNING: Removing unreachable block (ram,0x005c9453) */ /* WARNING: Removing unreachable block (ram,0x005c9665) */ /* WARNING: Removing unreachable block (ram,0x005c976e) */ /* WARNING: Removing unreachable block (ram,0x005c99b4) */ /* WARNING: Removing unreachable block (ram,0x005c9166) */ /* WARNING: Removing unreachable block (ram,0x005c8917) */ /* WARNING: Removing unreachable block (ram,0x005c8b29) */ /* WARNING: Removing unreachable block (ram,0x005c937f) */ /* WARNING: Removing unreachable block (ram,0x005c86fe) */ /* WARNING: Removing unreachable block (ram,0x005c969a) */ /* WARNING: Removing unreachable block (ram,0x005c926f) */ /* WARNING: Removing unreachable block (ram,0x005c8e4b) */ /* WARNING: Removing unreachable block (ram,0x005c8a20) */ /* WARNING: Removing unreachable block (ram,0x005c85f5) */ /* WARNING: Removing unreachable block (ram,0x005c8807) */ /* WARNING: Removing unreachable block (ram,0x005c8c32) */ /* WARNING: Removing unreachable block (ram,0x005c905d) */ /* WARNING: Removing unreachable block (ram,0x005c9488) */ /* WARNING: Removing unreachable block (ram,0x005c98c6) */ /* WARNING: Removing unreachable block (ram,0x005c8d3b) */ /* WARNING: Removing unreachable block (ram,0x005c99e9) */ /* WARNING: Removing unreachable block (ram,0x005c9591) */ /* WARNING: Removing unreachable block (ram,0x005c97a3) */ /* WARNING: Removing unreachable block (ram,0x005c8f54) */ /* WARNING: Removing unreachable block (ram,0x005c9ac6) */ void loot_generateItemTable(void);
void World_generateMonsterSpawnList(void);
void World_applyDropTableToEntities(int *param_1,undefined4 param_2,undefined4 param_3);
/* WARNING: Removing unreachable block (ram,0x005cab45) */ /* WARNING: Removing unreachable block (ram,0x005caa3c) */ /* WARNING: Removing unreachable block (ram,0x005ca820) */ /* WARNING: Removing unreachable block (ram,0x005ca607) */ /* WARNING: Removing unreachable block (ram,0x005ca3f5) */ /* WARNING: Removing unreachable block (ram,0x005ca230) */ /* WARNING: Removing unreachable block (ram,0x005ca2ec) */ /* WARNING: Removing unreachable block (ram,0x005ca4fe) */ /* WARNING: Removing unreachable block (ram,0x005ca710) */ /* WARNING: Removing unreachable block (ram,0x005ca933) */ /* WARNING: Removing unreachable block (ram,0x005cac68) */ /* WARNING: Removing unreachable block (ram,0x005caa71) */ /* WARNING: Removing unreachable block (ram,0x005cab7a) */ /* WARNING: Removing unreachable block (ram,0x005ca745) */ /* WARNING: Removing unreachable block (ram,0x005ca321) */ /* WARNING: Removing unreachable block (ram,0x005ca533) */ /* WARNING: Removing unreachable block (ram,0x005ca968) */ /* WARNING: Removing unreachable block (ram,0x005ca42a) */ /* WARNING: Removing unreachable block (ram,0x005ca63c) */ /* WARNING: Removing unreachable block (ram,0x005ca855) */ /* WARNING: Removing unreachable block (ram,0x005cac9d) */ /* WARNING: Removing unreachable block (ram,0x005cad7a) */ void World_generateNpcSpawnList(void);
void World_findNearestObjectAtLevel(undefined8 *param_1,int param_2,int param_3);
void World_findNearestObjectRegion2(int param_1,int param_2);
void World_computeStructurePlacement(undefined4 param_1,uint *param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5,undefined4 param_6,int param_7);
void World_fillVoxelBox(int param_1,int param_2,int param_3,int *param_4,undefined3 *param_5, undefined4 param_6);
void World_carveTerrainFeatureA(int param_1,int param_2,int param_3,int param_4,int param_5,int param_6, undefined4 param_7);
void World_carveTerrainFeatureB(int param_1,int param_2,int param_3,int param_4,int param_5,int param_6, undefined4 param_7);
/* WARNING: Function: __alloca_probe replaced with injection: alloca_probe */ void World_populateRegionDecorations(int param_1,undefined4 param_2,int *param_3,int *param_4,int param_5,char param_6);
/* WARNING: Type propagation algorithm not settling */ void World_buildStructureMesh(int param_1,int param_2);
void World_generateFoliageBlob(int param_1,int param_2,int param_3,float param_4,float param_5,undefined8 param_6 ,float param_7,undefined8 param_8,float param_9,int param_10,undefined4 param_11);
void World_generateVegetationCluster(uint param_1,uint param_2,int param_3);
void World_generateTreeRecursive(int param_1);
/* WARNING: Removing unreachable block (ram,0x005da210) */ /* WARNING: Removing unreachable block (ram,0x005da223) */ /* WARNING: Removing unreachable block (ram,0x005da1fd) */ void World_generateTreeRoot(int param_1,int param_2,int param_3);
/* WARNING: Type propagation algorithm not settling */ void World_buildPropInstance(int param_1,undefined4 *param_2,int *param_3);
void World_fillVoxelColumnTyped(int param_1,int param_2,int param_3,int *param_4,byte *param_5,float param_6, undefined4 param_7,byte param_8);
/* WARNING: Removing unreachable block (ram,0x005e2b58) */ /* WARNING: Removing unreachable block (ram,0x005e2bf1) */ void World_generateWaterOrPathFeature(uint param_1,uint param_2,float param_3,int param_4,int param_5,int param_6, int param_7);
int World_resolveStructureFootprint(int param_1,int param_2,int param_3,int param_4,uint param_5,int *param_6, int *param_7);
void assign_two_dwords(undefined4 *param_1,undefined4 *param_2);
float * World_getColumnDataAt(float *param_1,int param_2,int param_3);
void World_appendMeshBatch(undefined4 param_1,undefined4 param_2,int param_3);
undefined1 get_bool_flag(void);
void World_findNearestObject(int param_1,int param_2);
void World_getRegionCellPtr(int param_1,int param_2);
float10 vec3_dot_or_distance(double *param_1,double *param_2,double *param_3);
void World_copyCellRecord(int *param_1,int *param_2);
float10 noise2d_sample(int param_1,int param_2,int param_3);
void World_placeObjectWithSpacing(uint param_1,uint param_2,float param_3);
void get_zero_or_stub(void);
void World_getOrCreateEntry(uint param_1);
void World_scaleFixedByLevel(int param_1,undefined4 param_2,char param_3);
void World_emitDecalOrParticle(byte *param_1,undefined4 param_2,undefined4 param_3);
void World_serializeCellData(undefined4 param_1,uint *param_2,uint param_3,int param_4);
/* WARNING: Removing unreachable block (ram,0x005f7735) */ /* WARNING: Removing unreachable block (ram,0x005f76d3) */ /* WARNING: Removing unreachable block (ram,0x005f7671) */ /* WARNING: Removing unreachable block (ram,0x005f760f) */ /* WARNING: Removing unreachable block (ram,0x005f75ad) */ /* WARNING: Removing unreachable block (ram,0x005f754b) */ /* WARNING: Removing unreachable block (ram,0x005f74e9) */ /* WARNING: Removing unreachable block (ram,0x005f7484) */ /* WARNING: Removing unreachable block (ram,0x005f7455) */ /* WARNING: Removing unreachable block (ram,0x005f7787) */ /* WARNING: Removing unreachable block (ram,0x005f76f5) */ /* WARNING: Removing unreachable block (ram,0x005f7631) */ /* WARNING: Removing unreachable block (ram,0x005f756d) */ /* WARNING: Removing unreachable block (ram,0x005f74a9) */ /* WARNING: Removing unreachable block (ram,0x005f750b) */ /* WARNING: Removing unreachable block (ram,0x005f75cf) */ /* WARNING: Removing unreachable block (ram,0x005f7693) */ /* WARNING: Removing unreachable block (ram,0x005f7754) */ undefined4 dtor_geometryBuffer(void);
/* WARNING: Removing unreachable block (ram,0x005f79aa) */ undefined4 dtor_listBuffer(int param_1,int param_2,int param_3);
/* WARNING: Removing unreachable block (ram,0x005f8504) */ void World_buildParticleBatch(undefined4 param_1,undefined4 param_2,int param_3);
undefined2 * Item_generateStats(undefined2 *param_1,undefined2 param_2);
float10 vec3_distanceSquared(uint *param_1,uint *param_2);
float * vec3_store4(float *param_1,int param_2,int param_3,int param_4);
float * vec3_computeNoiseOffset(float *param_1,int param_2,int param_3);
undefined4 get_const_dword_a(void);
undefined4 get_const_dword_b(void);
float * vec2_store(float *param_1,int param_2,int param_3);
float * vec3_store4_b(float *param_1,int param_2,int param_3,int param_4);
void swap_two_int_ptrs(int *param_1,int *param_2);
void copy_two_int_ptrs(int *param_1,int *param_2);
void octree_leafOp(int param_1,int param_2,int param_3,undefined4 *param_4);
void octree_nodeVisitA(undefined4 *param_1,undefined4 *param_2);
void octree_nodeVisitB(int param_1,int param_2);
void octree_nodeSplit(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void octree_recursiveTraverse(int param_1,int param_2,int param_3,undefined4 param_4);
void octree_applyLeaf(undefined4 *param_1,int param_2,undefined4 param_3);
void octree_applySplit(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3,undefined4 param_4);
void leave_critical_section_b(void);
void vec3_lerp(float *param_1,undefined8 *param_2,int param_3,float param_4);
void tree_insertRecursive(int *param_1,undefined4 param_2);
undefined4 * tree_cloneRecursive(undefined4 *param_1,undefined4 param_2,undefined4 param_3);
void vec3_copy_608d40(int *param_1,int *param_2,int *param_3);
void tree_insertEntry(undefined4 param_1);
void forward_to_678520(void);
undefined4 * tree_build(int param_1);
void tree_populate(int param_1);
void setter_stub(int *param_1);
undefined4 get_rng_dword(void);
void compute_index_pair(int *param_1,uint *param_2);
/* WARNING: Removing unreachable block (ram,0x0060a066) */ /* WARNING: Removing unreachable block (ram,0x00609ebe) */ /* WARNING: Removing unreachable block (ram,0x00609e07) */ /* WARNING: Removing unreachable block (ram,0x00609fbb) */ /* WARNING: Removing unreachable block (ram,0x0060a0b4) */ void vec_normalize_or_distance(int param_1,float *param_2,float *param_3,float param_4);
undefined4 build_and_link(undefined4 param_1);
byte get_byte_flag(void);
void direction_from_angle(int param_1);
undefined4 codec_bitreaderInit(int param_1,int param_2);
undefined8 codec_readBits(undefined4 param_1,uint param_2,int param_3);
int codec_decodeFloor(int param_1,undefined4 param_2,undefined4 param_3,int *param_4,int *param_5);
int codec_decodePacketRecursive(int *param_1,undefined4 param_2,undefined4 param_3,uint param_4,int param_5, uint param_6,int param_7,undefined4 param_8,int param_9,int param_10,int *param_11, int param_12,int param_13);
undefined4 codec_setupHelperA(void);
void codec_setupHelperB(void);
int codec_synthesizeWindow(undefined1 *param_1,int param_2,int param_3);
longlong codec_recursiveSum(int param_1,int param_2);
/* WARNING: Removing unreachable block (ram,0x00626063) */ void codec_decodeMapping(int param_1,uint param_2,int param_3);
/* WARNING: Removing unreachable block (ram,0x0062648a) */ /* WARNING: Removing unreachable block (ram,0x006261ec) */ /* WARNING: Removing unreachable block (ram,0x00626121) */ /* WARNING: Removing unreachable block (ram,0x006263bf) */ /* WARNING: Removing unreachable block (ram,0x006266d4) */ /* WARNING: Removing unreachable block (ram,0x006264b1) */ undefined4 codec_decodeSetup(int *param_1,uint param_2,int param_3);
int codec_windowOverlapAdd(int param_1,short *param_2,int param_3,int param_4,int param_5,int param_6, undefined4 *param_7,code *param_8,undefined4 param_9);
undefined4 codec_decodeInit(void);
/* WARNING: Removing unreachable block (ram,0x0062710e) */ int codec_setupHeaders(void *param_1,size_t param_2,int param_3,code *param_4,int param_5,int param_6);
int codec_decodeStreamEntry(undefined4 param_1,undefined4 *param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5,undefined4 param_6,undefined4 param_7,undefined4 param_8);
void plasma::NamedObject::ctor_4(undefined4 param_1,int param_2,undefined4 param_3);
void plasma::Widget::ctor_0(void);
void tree_eraseRecursive(int param_1,undefined4 param_2);
undefined4 * tree_clear(undefined4 *param_1);
void Widget_measure(void);
void Widget_computeBoundsFloat(float *param_1);
void Widget_setScroll(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void Widget_layoutChildren(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void Widget_layoutChildrenGuarded(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5);
void Widget_measureContentEntry(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void Widget_updateCaption(int param_1,char param_2);
void get_widget_field(int param_1);
void Widget_applyBoundsAndRefresh(void);
void Widget_measureGuarded(void);
int tree_allocNode(int param_1);
int tree_findOrInsert(undefined4 param_1,undefined4 param_2,undefined4 param_3);
undefined4 * tree_cloneSubtree(undefined4 *param_1,undefined4 param_2,undefined4 param_3);
void tree_insertPair(undefined4 *param_1,undefined4 *param_2);
undefined4 * tree_nodeAlloc(void);
void tree_destroyRecursive(void *param_1);
undefined4 Node_is_ancestor_chain(int param_1);
int Node_clone_subtree(uint param_1);
/* WARNING: Type propagation algorithm not settling */ void Widget_render_subtree(uint param_1);
undefined4 Node_get_first_child_id(undefined4 param_1);
void Node_collect_matching_children(int *param_1,undefined4 *param_2);
/* WARNING: Restarted to delay deadcode elimination for space: stack */ void Node_project_bounds_recursive(float *param_1,float *param_2,float *param_3,char *param_4,undefined4 param_5);
void Node_get_first_material_name(undefined4 *param_1);
void Node_transform_pair_to_screen(float *param_1,float *param_2);
/* WARNING: Type propagation algorithm not settling */ void Node_compute_screen_aabb_recursive(float *param_1,float *param_2,float *param_3);
void Node_attach_transform_multiply(float param_1,int param_2);
undefined4 Node_detach_or_remove_child(int param_1,int param_2);
int Node_clone_subtree_v2(uint param_1);
void Node_frustum_visibility_test(void);
void Node_set_font_slot(int param_1);
void Node_set_style_slot(int param_1);
void Node_clear_layout_flag_2d(void);
void Node_set_adaption_slot(int param_1);
void Node_detach_all_slots_recursive(void);
void AdaptionWidget_full_layout_pass(undefined4 param_1);
void AdaptionWidget_layout_pass_child(undefined4 param_1,char param_2,char param_3);
void plasma::Edit::ctor_0(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void FontCache_find_or_create_scalable(int param_1);
void plasma::SmoothMeshShape::ctor_0(undefined4 param_1,undefined4 param_2);
void SmoothMeshShape_rebuild_buffers(void);
undefined4 StaticMeshShape_build_from_buffers(void);
void NamedValue_move_two_strings(undefined4 *param_1);
void NamedValue_move_construct_pair(undefined4 *param_1,undefined4 *param_2);
void NamedValue_assign_pair_free(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void Attribute_deserialize_int_keyframes(basic_istream<char,std::char_traits<char>_> *param_1,int *param_2);
void Attribute_deserialize_keyframes_v2(basic_istream<char,std::char_traits<char>_> *param_1,int *param_2);
void Attribute_deserialize_keyframes_v3(basic_istream<char,std::char_traits<char>_> *param_1,int *param_2);
void Attribute_deserialize_matrix_keyframes(basic_istream<char,std::char_traits<char>_> *param_1,int *param_2);
void Attribute_deserialize_double_keyframes(basic_istream<char,std::char_traits<char>_> *param_1,int *param_2);
void Attribute_deserialize_vec3_keyframes(basic_istream<char,std::char_traits<char>_> *param_1,int *param_2);
void Attribute_deserialize_vec4_keyframes(basic_istream<char,std::char_traits<char>_> *param_1,int *param_2);
void Attribute_deserialize_scalar_keyframes(basic_istream<char,std::char_traits<char>_> *param_1,int *param_2);
uint istream_read_u32(basic_istream<char,std::char_traits<char>_> *param_1);
void plasma::ContinuousAttribute<plasma::Vector<4,float>_>::ctor_0 (undefined4 param_1,undefined4 param_2);
void plasma::DiscreteAttribute<int>::ctor_2(undefined4 param_1,undefined4 param_2);
void NamedValue_dtor_free_strings(void);
void Node_dtor_free_vectors(void);
void Widget_set_flag_bit8_0x128(char param_1);
void Widget_set_flag_bit4_0x128(char param_1);
undefined4 * Registry_push_node_locked_0x8c(undefined4 *param_1);
undefined4 * Registry_push_node_locked_0x08(undefined4 *param_1);
undefined4 * Registry_push_node_locked_0x74(undefined4 *param_1);
undefined4 * Registry_push_node_locked_0x84(undefined4 *param_1);
/* WARNING: Type propagation algorithm not settling */ void Widget_ensure_frame_subwidget(undefined4 param_1);
void Widget_fit_content_and_set(void);
undefined4 Button_new_instance(undefined4 param_1,undefined4 param_2,undefined4 param_3);
undefined4 DiscreteAttributeInt_new_instance(undefined4 param_1);
undefined4 Edit_new_instance(undefined4 param_1,undefined4 param_2);
undefined4 GenericShape_new_instance(undefined4 param_1,undefined4 param_2);
undefined4 ListWidget_new_instance(undefined4 param_1,undefined4 param_2);
undefined4 NamedObject_find_or_create(int param_1);
undefined4 PopUpButton_new_instance(undefined4 param_1,undefined4 param_2);
undefined4 ScrollButton_new_instance(undefined4 param_1,undefined4 param_2);
undefined4 ScrollSlider_new_instance(undefined4 param_1,undefined4 param_2);
undefined4 ContinuousAttributeVec3_new_instance(undefined4 param_1);
void FontNode_unregister_and_release(undefined4 *param_1);
void Object_release_if_nonnull(undefined4 *param_1);
void Node_unregister_notify_release(undefined4 *param_1);
void StyleNode_unregister_and_release(undefined4 *param_1);
void Widget_pop_render_layer(void);
void istream_read_chunk_header(undefined8 *param_1,basic_istream<char,std::char_traits<char>_> *param_2);
void FontCache_load_font_by_name(int param_1,float param_2,undefined4 param_3,float param_4,char param_5);
void ehepilogue_restore_cookie(void);
int Button_deserialize(basic_istream<char,std::char_traits<char>_> *param_1);
void SmoothMeshShape_deserialize(basic_istream<char,std::char_traits<char>_> *param_1,undefined4 param_2);
/* WARNING: Removing unreachable block (ram,0x006547e9) */ undefined4 Edit_deserialize(basic_istream<char,std::char_traits<char>_> *param_1);
void GenericShape_deserialize(basic_istream<char,std::char_traits<char>_> *param_1);
/* WARNING: Removing unreachable block (ram,0x00654ed9) */ undefined4 ListWidget_deserialize(basic_istream<char,std::char_traits<char>_> *param_1);
void PopUpButton_deserialize(basic_istream<char,std::char_traits<char>_> *param_1,undefined4 param_2);
void FontCache_create_font_from_path(void **param_1,undefined4 param_2,undefined1 param_3,void *param_4);
undefined4 * Pair_constructMoveKeyString(undefined4 *param_1,undefined4 *param_2,undefined4 param_3);
void plasma::ScalableFont::ctor_0(undefined4 param_1);
void GameController_clearAllEntities(void);
void Font_drawTextTransformed(undefined4 param_1,undefined4 param_2,undefined4 param_3,float param_4, undefined4 param_5,undefined4 param_6,undefined4 param_7,float param_8, undefined4 param_9,undefined4 param_10,undefined4 param_11,uint param_12, undefined4 param_13);
void Font_measureTextLine(undefined4 *param_1,float *param_2,float *param_3,uint param_4,int param_5, undefined4 param_6);
void Font_measureTextBlock(undefined4 *param_1,int param_2,float *param_3,float *param_4,uint param_5);
void Font_measureTextScaled(undefined4 param_1,undefined4 param_2,float param_3,undefined4 param_4, undefined4 param_5,undefined4 param_6,float param_7,float *param_8,float *param_9, uint param_10,undefined4 param_11,undefined4 param_12,undefined4 param_13);
void Font_loadByFileExtension(undefined4 param_1,int param_2,int *param_3);
void Font_loadFaceFromFile(undefined4 param_1,undefined4 param_2);
void Font_loadFaceFromMemory(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void Image_setPixelData(int param_1,int param_2,void *param_3,int *param_4);
void plasma::Attribute::ctor_0(undefined4 param_1);
undefined4 Container_resetAndInsert(undefined4 param_1);
void Anim_playTrackByName(int param_1,int param_2);
void Anim_removeTrackReferences(int param_1);
void Anim_removeEntryByKey(int param_1);
undefined4 Spline_evaluateAtTime(int *param_1,int param_2);
void Spline_setTimeAndEvaluate(undefined4 param_1);
void Spline_resetTime(void);
char Spline_advanceTime(int param_1);
void plasma::Object::ctor_1(undefined4 param_1);
int vector_moveConstructBackward(int param_1,int param_2,int param_3);
undefined4 * vector_moveAssignStringRange(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void vector_fillDefaultStrings(undefined2 *param_1,int param_2,undefined4 param_3);
void vector_destroyStringRange(int param_1,int param_2,int param_3);
void plasma:: DiscreteAttribute<std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>_>_> ::ctor_0(undefined4 param_1,undefined4 param_2);
void vector_insertN(int *param_1,int param_2,uint param_3,undefined4 param_4);
int * vector_erase(int *param_1,int param_2,int param_3);
void plasma::NamedObject::ctor_6(undefined4 param_1,undefined4 param_2);
int list_sumFieldAcrossNodes(void);
char Container_updateChildren(undefined4 param_1);
void plasma::ContinuousArrayAttribute<float>::ctor_1(undefined4 param_1,undefined4 param_2);
void plasma::ContinuousArrayAttribute<plasma::Vector<2,float>_>::ctor_1 (undefined4 param_1,undefined4 param_2);
void plasma::ContinuousArrayAttribute<plasma::Vector<4,float>_>::ctor_0 (undefined4 param_1,undefined4 param_2);
void plasma::ContinuousAttribute<plasma::Matrix<float>_>::ctor_0 (undefined4 param_1,undefined4 param_2);
void plasma::ContinuousAttribute<plasma::Vector<2,float>_>::ctor_0 (undefined4 param_1,undefined4 param_2);
void plasma::DiscreteAttribute<int>::ctor_1(undefined4 param_1,undefined4 param_2);
void AdaptionWidget_buildMeshIndices(void);
void AdaptionWidget_buildTopology(uint param_1);
void plasma::StaticMeshShape::ctor_0 (undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5);
void plasma::NamedObject::ctor_2(undefined4 param_1,undefined4 param_2);
void plasma::ContinuousAttribute<plasma::Vector<3,float>_>::ctor_0(int *param_1,undefined4 param_2);
void Widget_setFieldAndClamp388(undefined4 param_1);
void Widget_setByteField380(undefined1 param_1);
void Widget_setClampedField388(int param_1);
void thunk_vector_int_assign(void);
void plasma::GenericShape::ctor_0(int *param_1,undefined4 param_2,undefined4 param_3);
void plasma::ListWidget::ctor_0(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void plasma::PopUpButton::ctor_0(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void plasma::PixelFont::ctor_0(undefined4 param_1,undefined4 param_2);
void ArrayAttribute_readInts(int *param_1);
void ArrayAttribute_readVariant2(int *param_1);
void ArrayAttribute_readVariant3(int *param_1);
void Attribute_readScalar(int *param_1);
void Attribute_readMatrix64(int *param_1);
void Attribute_readVec8(int *param_1);
void Attribute_readVec3(int *param_1);
void Attribute_readVec4(int *param_1);
uint istream_readValue(void);
float10 istream_readFloat(void);
void plasma::Exception::ctor_2(undefined4 param_1);
void plasma::Exception::ctor_3(undefined4 param_1);
void plasma::Exception::ctor_4(undefined4 param_1);
void Attribute_readSequence(undefined4 param_1);
void plasma::NamedObject::ctor_3(int param_1,int param_2);
/* Library Function - Multiple Matches With Same Base Name private: static void __cdecl std::locale::facet::_Facet_Register(class std::locale::facet *) void __cdecl std::_Facet_Register(class std::_Facet_base *) Libraries: Visual Studio 2010 Release, Visual Studio 2012 Release */ void Facet_Register(undefined4 param_1);
/* WARNING: Function: __SEH_prolog4 replaced with injection: SEH_prolog4 */ /* WARNING: Function: __SEH_epilog4 replaced with injection: EH_epilog3 */ /* Library Function - Single Match void __stdcall `eh vector destructor iterator'(void *,unsigned int,int,void (__thiscall*)(void *)) Library: Visual Studio 2012 Release */ void _eh_vector_destructor_iterator_ (void *param_1,uint param_2,int param_3,_func_void_void_ptr *param_4);
ulonglong float_to_uint64_round_guarded(void);
ulonglong float_to_uint64_round(void);
/* WARNING: Function: __SEH_prolog4 replaced with injection: SEH_prolog4 */ /* WARNING: Function: __SEH_epilog4 replaced with injection: EH_epilog3 */ /* Library Function - Single Match void __stdcall `eh vector constructor iterator'(void *,unsigned int,int,void (__thiscall*)(void *),void (__thiscall*)(void *)) Library: Visual Studio 2012 Release */ void _eh_vector_constructor_iterator_ (void *param_1,uint param_2,int param_3,_func_void_void_ptr *param_4, _func_void_void_ptr *param_5);

#endif
