// game_misc (server) — reconstructed declarations.
#ifndef SERVER_GAME_MISC_GAME_MISC_H
#define SERVER_GAME_MISC_GAME_MISC_H
#include "../include/cube_types.h"

void __thiscall String_reserveGrow(void *this,uint param_1,size_t param_2);
int * __thiscall String_assign(void *this,int *param_1,uint param_2);
void __fastcall Matrix4_setIdentity(undefined4 *param_1);
int __fastcall Vec3i64_randomize(int param_1);
float * __thiscall Vec3i64_toFloatScaled(void *this,longlong *param_1);
undefined4 * __thiscall Copy24Bytes(void *this,undefined4 *param_1);
uint * __thiscall Vec3i64_subtract(void *this,uint *param_1,uint *param_2);
uint * __thiscall Vec3i64_add(void *this,uint *param_1,uint *param_2);
void __fastcall World_clearContainers(int param_1);
void __cdecl Vec3i64_toBlockCoords(int *param_1,uint *param_2);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ undefined * __thiscall Column_getBlockChecked(void *this,int param_1);
undefined * __thiscall World_getBlockAt(void *this,uint param_1,uint param_2,int param_3,int param_4);
void __thiscall World_getBlockFloat(void *this,uint param_1,uint param_2,uint param_3,uint param_4,uint param_5, uint param_6,int param_7);
int __thiscall Chunk_getColumnAt(void *this,uint param_1,uint param_2,int param_3);
undefined4 __thiscall Grid_lookup1024(void *this,int param_1,int param_2);
undefined4 __thiscall Region_getChunkCell(void *this,uint param_1,uint param_2);
undefined4 * __fastcall Struct_initWithBuffer0x100(undefined4 *param_1);
undefined4 __cdecl mapItemTypeToSlotIndex(undefined4 param_1);
float10 __thiscall Combat_getResistFactor(int param_1,undefined4 param_2,int param_3);
undefined1 __fastcall Combat_isSpecialSpiritActive(int param_1);
int __fastcall Combat_getStaminaRegenRate(int param_1);
float10 __fastcall Combat_computeMaxHealth(int param_1);
char __fastcall Combat_selectNextAttackAnim(int param_1);
int __fastcall Combat_selectSpiritAttackId(int param_1);
float10 pow2Mul(void);
float10 pow2MulDiv(void);
void __thiscall Combat_upsertBuffEntry(void *this,char *param_1);
undefined4 * __fastcall string_dataPtr(undefined4 *param_1);
uint __thiscall SpeechDb_readBlobByKey(void *this,undefined4 *param_1,uint *param_2,uint *param_3);
undefined1 * __thiscall struct_copy0x118(void *this,undefined1 *param_1);
float10 __fastcall Combat_equipHealthBonus(char *param_1);
void malloc_thunk(size_t param_1);
undefined4 __cdecl utf32_to_utf16(undefined4 *param_1,int *param_2,uint *param_3,uint param_4);
undefined4 __cdecl utf_convert_variant(undefined4 *param_1,int *param_2,uint *param_3,uint param_4);
int __thiscall Pool_allocBlock(void *this,uint param_1,int *param_2);
uint * __cdecl Pool_allocElementNode(int *param_1,uint param_2);
void __thiscall Pool_mallocAlignedBlock(void *this,int param_1);
ushort * __cdecl encodeUtf16Codepoint(ushort *param_1,uint param_2);
int * __cdecl XmlPool_allocAttrNode(int param_1,int *param_2);
uint * __cdecl XmlPool_allocChildNode(uint param_1,int *param_2,uint param_3);
uint __cdecl Transcode_dispatch(int *param_1,uint *param_2,uint param_3,uint *param_4,uint param_5,char param_6);
undefined4 __cdecl Utf16BE_byteSwapToNative(int *param_1,uint *param_2,int param_3,uint param_4,char param_5);
undefined4 __cdecl Utf8_toUtf16Alloc(undefined4 *param_1,int *param_2,uint *param_3,uint param_4);
int __cdecl Utf32BE_countUtf16Units(uint *param_1,int param_2,int param_3);
ushort * __cdecl Utf32_toUtf16(uint *param_1,int param_2,ushort *param_3);
ushort * __cdecl Utf32BE_toUtf16(uint *param_1,int param_2,ushort *param_3);
int __cdecl Utf8_countUtf16Units(uint *param_1,uint param_2,int param_3);
void __cdecl Utf8_decodeToUtf16(uint *param_1,uint param_2,ushort *param_3);
int __cdecl Xml_detectEncoding(int param_1,char *param_2,uint param_3);
undefined4 __cdecl Utf16_copyOrPassthrough(undefined4 *param_1,uint *param_2,void *param_3,uint param_4,char param_5);
undefined * __cdecl XmlParse_selectHandler(uint param_1);
ushort * __cdecl Xml_normalizeTextRun(ushort *param_1);
void __thiscall Xml_parseMainLoop(void *this,ushort *param_1,uint *param_2,uint param_3,undefined4 param_4);
void __thiscall Xml_skipDoctypeSubset(void *this,int *param_1,undefined4 param_2,char param_3);
void __thiscall Xml_skipMarkedSection(void *this,int *param_1);
void __thiscall Xml_skipQuotedOrComment(void *this,undefined4 *param_1);
void __thiscall Xml_parseCommentOrCData(void *this,int *param_1,uint *param_2,uint param_3,undefined4 param_4);
void __thiscall Xml_parseProcInstr(void *this,int *param_1,uint *param_2,uint param_3,short param_4);
void __thiscall Xml_shiftBufferForNewline(void *this,int *param_1,int param_2);
ushort * __cdecl Xml_scanCDataContent(ushort *param_1,short param_2);
ushort * __cdecl Xml_scanCommentContent(ushort *param_1,short param_2);
ushort * __cdecl decodeXmlEntity(ushort *param_1,void *param_2);
void Tree_destroyRec_oneStr(int *param_1);
undefined4 * __thiscall Tree_eraseRange_variant(void *this,undefined4 *param_1,int *param_2,int *param_3);
void __thiscall SpeechMap_findOrInsert(void *this,undefined4 *param_1,undefined4 *param_2,ushort *param_3,undefined4 param_4);
void __thiscall SpeechMap_insertEach(void *this,int *param_1,int *param_2);
void __thiscall QuestTextNode_copyRec(void *this,uint param_1);
short __cdecl isPunctuation(short param_1);
undefined4 * __cdecl copyVec12Range(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void __thiscall vec12_reallocate(void *this,uint param_1);
void __thiscall vec12_reserveGrow(void *this,uint param_1);
void buyNode120(undefined4 *param_1,undefined4 *param_2);
void buyNode80(undefined4 *param_1,undefined4 *param_2);
void __thiscall vecInt_reallocate(void *this,uint param_1);
void __thiscall vecInt_reserveGrow(void *this,uint param_1);
int __thiscall World_getTileAtCoords(void *this,uint param_1,uint param_2);
void __fastcall Speech_mapNode_dtor(undefined4 *param_1);
void __thiscall World_findNearestEntityInRegion(void *this,int param_1,int param_2);
void __cdecl vec3b_copyBackward(undefined1 *param_1,undefined1 *param_2,undefined1 *param_3);
undefined1 * __cdecl vec3b_uninitCopy(undefined1 *param_1,undefined1 *param_2,undefined1 *param_3);
void __thiscall vec3b_reallocate(void *this,uint param_1);
void __thiscall vec3b_reserveGrow(void *this,uint param_1);
void __thiscall vec_ptr_resize(void *this,uint param_1);
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */ undefined * __thiscall VoxelGrid_cellAt3D(void *this,int param_1,int param_2,int param_3);
float10 __thiscall World_roadField(void *param_1,uint param_2,uint param_3);
void Creature_moveToward(uint *param_1,uint *param_2,char param_3,float param_4);
double * __thiscall World_sampleTerrainGradient(void *this,double *param_1,int param_2,int param_3);
float10 __cdecl valueNoise2D(undefined4 param_1,undefined4 param_2,double param_3);
/* WARNING: Removing unreachable block (ram,0x004d72e4) */ /* WARNING: Removing unreachable block (ram,0x004d7570) */ /* WARNING: Removing unreachable block (ram,0x004d77b4) */ void __thiscall Creature_stepAlongPath(void *this,uint *param_1,float *param_2,float param_3,char param_4,char param_5);
void __thiscall VoxelGrid_remapCoords(void *this,int *param_1,int *param_2);
undefined4 * __thiscall Object_construct6(void *this,undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 *param_4 );
void NavGraph_reconstructPath(void *param_1);
bool __thiscall NavGraph_openSetContains(void *this,undefined4 *param_1,int param_2,int param_3);
int __cdecl NavGraph_heuristicCost(uint *param_1);
undefined4 * __thiscall NavGraph_lookupNode(void *this,undefined4 *param_1,int param_2,int param_3);
void __thiscall NavGraph_addNode(void *this,undefined4 *param_1,int param_2,int param_3,undefined4 *param_4);
/* WARNING: Removing unreachable block (ram,0x004ddc29) */ /* WARNING: Removing unreachable block (ram,0x004dd78e) */ /* WARNING: Removing unreachable block (ram,0x004dd6d1) */ /* WARNING: Removing unreachable block (ram,0x004dd6fd) */ /* WARNING: Removing unreachable block (ram,0x004dd7bd) */ /* WARNING: Removing unreachable block (ram,0x004ddcdf) */ void __thiscall NavGraph_expandNeighbors(void *this,void *param_1);
/* WARNING: Removing unreachable block (ram,0x004df1bb) */ /* WARNING: Removing unreachable block (ram,0x004deb9a) */ /* WARNING: Removing unreachable block (ram,0x004dec8e) */ /* WARNING: Removing unreachable block (ram,0x004def61) */ /* WARNING: Removing unreachable block (ram,0x004df550) */ /* WARNING: Removing unreachable block (ram,0x004df64b) */ /* WARNING: Removing unreachable block (ram,0x004df0b8) */ /* WARNING: Removing unreachable block (ram,0x004df307) */ void __thiscall NavGraph_findPath(void *this,void *param_1);
void __thiscall World_findNearestFeatureCell(void *this,undefined8 *param_1,int param_2,int param_3);
void __thiscall World_biomeBorderDistance(void *this,int param_1,int param_2);
void World_siteDistanceSq(void);
float * World_terrainOffset2D(float *param_1,int param_2,int param_3);
void __thiscall World_waterProximityInfluence(void *this,int param_1,int param_2);
float10 __cdecl pointSegmentDistanceSq(double *param_1,double *param_2,double *param_3);
float10 __thiscall World_falloffSquared(uint *param_1,uint *param_2,uint *param_3);
/* WARNING: Removing unreachable block (ram,0x0052fae6) */ /* WARNING: Removing unreachable block (ram,0x0052f93e) */ /* WARNING: Removing unreachable block (ram,0x0052f887) */ /* WARNING: Removing unreachable block (ram,0x0052fa3b) */ /* WARNING: Removing unreachable block (ram,0x0052fb34) */ void __thiscall Creature_resolveSeparation(void *this,int param_1,uint *param_2,uint *param_3,float param_4);
/* WARNING: Function: __SEH_prolog4 replaced with injection: SEH_prolog4 */ /* WARNING: Function: __SEH_epilog4 replaced with injection: EH_epilog3 */ /* Library Function - Single Match void __stdcall `eh vector constructor iterator'(void *,unsigned int,int,void (__thiscall*)(void *),void (__thiscall*)(void *)) Library: Visual Studio 2012 Release */ void _eh_vector_constructor_iterator_ (void *param_1,uint param_2,int param_3,_func_void_void_ptr *param_4, _func_void_void_ptr *param_5);
/* WARNING: Function: __SEH_prolog4 replaced with injection: SEH_prolog4 */ /* WARNING: Function: __SEH_epilog4 replaced with injection: EH_epilog3 */ /* Library Function - Single Match void __stdcall `eh vector destructor iterator'(void *,unsigned int,int,void (__thiscall*)(void *)) Library: Visual Studio 2012 Release */ void _eh_vector_destructor_iterator_ (void *param_1,uint param_2,int param_3,_func_void_void_ptr *param_4);

#endif
