// game_misc (server) — reconstructed declarations.
#ifndef SERVER_GAME_MISC_GAME_MISC_H
#define SERVER_GAME_MISC_GAME_MISC_H
#include "../include/cube_types.h"

void __thiscall String_reserveGrow(void *this,uint param_1,size_t param_2);
int * __thiscall String_assign(void *this,int *param_1,uint param_2);
void __fastcall Matrix4_setIdentity(undefined4 *param_1);
int __fastcall Vec3i64_randomize(int param_1);
float * __thiscall Vec3i64_toFloatScaled(void *this,longlong *param_1);
undefined4 * __thiscall Copy24Bytes(void *this,undefined4 *param_1);
uint * __thiscall Vec3i64_subtract(void *this,uint *param_1,uint *param_2);
uint * __thiscall Vec3i64_add(void *this,uint *param_1,uint *param_2);
void __fastcall World_clearContainers(int param_1);
void __cdecl Vec3i64_toBlockCoords(int *param_1,uint *param_2);
undefined * __thiscall Column_getBlockChecked(void *this,int param_1);
undefined * __thiscall World_getBlockAt(void *this,uint param_1,uint param_2,int param_3,int param_4);
void __thiscall World_getBlockFloat(void *this,uint param_1,uint param_2,uint param_3,uint param_4,uint param_5, uint param_6,int param_7);
int __thiscall Chunk_getColumnAt(void *this,uint param_1,uint param_2,int param_3);
undefined4 __thiscall Grid_lookup1024(void *this,int param_1,int param_2);
undefined4 __thiscall Region_getChunkCell(void *this,uint param_1,uint param_2);
undefined4 * __fastcall Struct_initWithBuffer0x100(undefined4 *param_1);
undefined4 __cdecl mapItemTypeToSlotIndex(undefined4 param_1);
float __thiscall Combat_getResistFactor(int param_1,undefined4 param_2,int param_3);
undefined1 __fastcall Combat_isSpecialSpiritActive(int param_1);
int __fastcall Combat_getStaminaRegenRate(int param_1);
float __fastcall Combat_computeMaxHealth(int param_1);
char __fastcall Combat_selectNextAttackAnim(int param_1);
int __fastcall Combat_selectSpiritAttackId(int param_1);
float pow2Mul(void);
float pow2MulDiv(void);
void __thiscall Combat_upsertBuffEntry(void *this,char *param_1);
basic_ostream<char,std::char_traits<char>_> * ostream_writeCString(basic_ostream<char,std::char_traits<char>_> *param_1,char *param_2);
undefined4 __fastcall ostream_writeCleanupHandler(undefined4 param_1,int *param_2);
undefined4 * __fastcall string_dataPtr(undefined4 *param_1);
uint __thiscall SpeechDb_readBlobByKey(void *this,undefined4 *param_1,uint *param_2,uint *param_3);
undefined4 __thiscall SpeechDb_loadBlobToVector(void *this,undefined4 *param_1,undefined4 *param_2);
undefined1 * __thiscall struct_copy0x118(void *this,undefined1 *param_1);
float __fastcall Combat_equipHealthBonus(char *param_1);
void malloc_thunk(size_t param_1);
undefined4 __cdecl utf32_to_utf16(undefined4 *param_1,int *param_2,uint *param_3,uint param_4);
undefined4 __cdecl utf_convert_variant(undefined4 *param_1,int *param_2,uint *param_3,uint param_4);
undefined4 * __thiscall std_string_string_string(void *this,undefined4 *param_1);
int __thiscall Pool_allocBlock(void *this,uint param_1,int *param_2);
uint * __cdecl Pool_allocElementNode(int *param_1,uint param_2);
void __thiscall Pool_mallocAlignedBlock(void *this,int param_1);
ushort * __cdecl encodeUtf16Codepoint(ushort *param_1,uint param_2);
int * __cdecl XmlPool_allocAttrNode(int param_1,int *param_2);
uint * __cdecl XmlPool_allocChildNode(uint param_1,int *param_2,uint param_3);
uint __cdecl Transcode_dispatch(int *param_1,uint *param_2,uint param_3,uint *param_4,uint param_5,char param_6);
undefined4 __cdecl Utf16BE_byteSwapToNative(int *param_1,uint *param_2,int param_3,uint param_4,char param_5);
undefined4 __cdecl Utf8_toUtf16Alloc(undefined4 *param_1,int *param_2,uint *param_3,uint param_4);
int __cdecl Utf32BE_countUtf16Units(uint *param_1,int param_2,int param_3);
ushort * __cdecl Utf32_toUtf16(uint *param_1,int param_2,ushort *param_3);
ushort * __cdecl Utf32BE_toUtf16(uint *param_1,int param_2,ushort *param_3);
int __cdecl Utf8_countUtf16Units(uint *param_1,uint param_2,int param_3);
void __cdecl Utf8_decodeToUtf16(uint *param_1,uint param_2,ushort *param_3);
int __cdecl Xml_detectEncoding(int param_1,char *param_2,uint param_3);
undefined4 __cdecl Utf16_copyOrPassthrough(undefined4 *param_1,uint *param_2,void *param_3,uint param_4,char param_5);
undefined * __cdecl XmlParse_selectHandler(uint param_1);
ushort * __cdecl Xml_normalizeTextRun(ushort *param_1);
void __thiscall Xml_parseMainLoop(void *this,ushort *param_1,uint *param_2,uint param_3,undefined4 param_4);
void __thiscall Xml_skipDoctypeSubset(void *this,int *param_1,undefined4 param_2,char param_3);
void __thiscall Xml_skipMarkedSection(void *this,int *param_1);
void __thiscall Xml_skipQuotedOrComment(void *this,undefined4 *param_1);
void __thiscall Xml_parseCommentOrCData(void *this,int *param_1,uint *param_2,uint param_3,undefined4 param_4);
void __thiscall Xml_parseProcInstr(void *this,int *param_1,uint *param_2,uint param_3,short param_4);
void __thiscall Xml_shiftBufferForNewline(void *this,int *param_1,int param_2);
ushort * __cdecl Xml_scanCDataContent(ushort *param_1,short param_2);
ushort * __cdecl Xml_scanCommentContent(ushort *param_1,short param_2);
ushort * __cdecl decodeXmlEntity(ushort *param_1,void *param_2);
void Tree_destroyRec_oneStr(int *param_1);
undefined4 * __thiscall Tree_eraseRange_variant(void *this,undefined4 *param_1,int *param_2,int *param_3);
void __thiscall SpeechMap_findOrInsert(void *this,undefined4 *param_1,undefined4 *param_2,ushort *param_3,undefined4 param_4);
void __thiscall SpeechMap_insertEach(void *this,int *param_1,int *param_2);
void __thiscall QuestTextNode_copyRec(void *this,uint param_1);
short __cdecl isPunctuation(short param_1);
undefined4 * __cdecl copyVec12Range(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void __thiscall vec12_reallocate(void *this,uint param_1);
void __thiscall vec12_reserveGrow(void *this,uint param_1);
void buyNode120(undefined4 *param_1,undefined4 *param_2);
void buyNode80(undefined4 *param_1,undefined4 *param_2);
void __thiscall vecInt_reallocate(void *this,uint param_1);
void __thiscall vecInt_reserveGrow(void *this,uint param_1);
int __thiscall World_getTileAtCoords(void *this,uint param_1,uint param_2);
void __fastcall Speech_mapNode_dtor(undefined4 *param_1);
void __cdecl vec3b_copyBackward(undefined1 *param_1,undefined1 *param_2,undefined1 *param_3);
undefined1 * __cdecl vec3b_uninitCopy(undefined1 *param_1,undefined1 *param_2,undefined1 *param_3);
void __thiscall vec3b_reallocate(void *this,uint param_1);
void __thiscall vec3b_reserveGrow(void *this,uint param_1);
void __thiscall vec_ptr_resize(void *this,uint param_1);
void __thiscall FUN_004cea80(void *this,uint *param_1,void *param_2,undefined4 *param_3);
int FUN_004d18c0(int param_1,int param_2);
undefined * __thiscall VoxelGrid_cellAt3D(void *this,int param_1,int param_2,int param_3);
void __thiscall FUN_004d1a70(void *this,uint param_1,uint param_2,int param_3,int param_4,int param_5,int param_6);
uint __thiscall FUN_004d2340(void *this,uint param_1,uint param_2,undefined8 param_3);
byte __thiscall FUN_004d24a0(void *this,uint param_1,uint param_2,int param_3,int param_4,int param_5);
void __thiscall FUN_004d2500(void *this,int param_1,int param_2,int param_3,int *param_4,int param_5,char param_6);
void FUN_004d2810(undefined1 *param_1,uint *param_2,float param_3,float param_4,void *param_5);
void __thiscall FUN_004d44c0(void *this,int param_1,int param_2,int param_3,float param_4,byte *param_5,int param_6, char param_7,char param_8);
void __thiscall FUN_004d4820(void *this,int param_1,int param_2,int param_3,float param_4,byte *param_5,int param_6, char param_7,char param_8);
void Creature_moveToward(uint *param_1,uint *param_2,char param_3,float param_4);
void __thiscall FUN_004d5740(void *this,uint *param_1,float *param_2);
double * __thiscall World_sampleTerrainGradient(void *this,double *param_1,int param_2,int param_3);
float __thiscall FUN_004d5c80(void *param_1,uint *param_2);
void __thiscall Creature_stepAlongPath(void *this,uint *param_1,float *param_2,float param_3,char param_4,char param_5);
void FUN_004d7ae0(void);
void __thiscall FUN_004d8e60(void *this,void *param_1);
void __thiscall VoxelGrid_remapCoords(void *this,int *param_1,int *param_2);
float __thiscall FUN_004d9010(void *param_1,float param_2,float param_3,int param_4);
void __thiscall FUN_004d9160(void *this,int param_1,int *param_2,uint param_3,uint param_4);
void __thiscall FUN_004d9410(void *this,int *param_1,uint *param_2);
float * FUN_004d9720(float *param_1);
undefined4 * __thiscall Object_construct6(void *this,undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 *param_4 );
void NavGraph_reconstructPath(void *param_1);
void FUN_004db200(void *param_1,int param_2);
bool __thiscall NavGraph_openSetContains(void *this,undefined4 *param_1,int param_2,int param_3);
int __cdecl NavGraph_heuristicCost(uint *param_1);
undefined4 * __thiscall NavGraph_lookupNode(void *this,undefined4 *param_1,int param_2,int param_3);
void __thiscall NavGraph_addNode(void *this,undefined4 *param_1,int param_2,int param_3,undefined4 *param_4);
void __thiscall NavGraph_expandNeighbors(void *this,void *param_1);
void __thiscall NavGraph_findPath(void *this,void *param_1);
void __thiscall FUN_004e0740(void *this,int param_1,uint *param_2);
undefined4 * __cdecl FUN_004e1e50(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
void FUN_004e28e0(int param_1,uint *param_2);
void __cdecl FUN_004f38a0(int param_1,int param_2,int param_3,float *param_4);
void __cdecl FUN_004f39e0(int param_1,int param_2,int param_3,float *param_4);
void __cdecl FUN_004f4860(float *param_1,float *param_2);
void __cdecl FUN_004f49d0(float *param_1,float *param_2);
void __cdecl FUN_004f4b50(int param_1,int param_2);
void __cdecl FUN_004f4dd0(int param_1,int param_2);
void __cdecl FUN_004f5170(float *param_1,float *param_2,float *param_3);
void __cdecl FUN_004f55b0(float *param_1,float *param_2,float *param_3);
void __cdecl FUN_004f5ac0(int param_1,int param_2,int param_3,float *param_4);
void __cdecl FUN_004f5bc0(int param_1,int param_2,int param_3,float *param_4);
undefined4 * __cdecl FUN_004f71e0(int param_1,int param_2,undefined4 *param_3);
void __thiscall FUN_004f8230(void *this,uint param_1);
float * __thiscall FUN_004f82d0(void *this,float *param_1,int param_2,int param_3);
void __thiscall FUN_004f9450(void *this,undefined4 *param_1,float param_2,float param_3,int param_4,float param_5, float param_6,int param_7);
float __thiscall FUN_004fc100(void *param_1,float param_2,uint param_3,int param_4);
float __thiscall FUN_004fc140(void *param_1,uint param_2,uint param_3,int param_4);
void __thiscall World_findNearestFeatureCell(void *this,undefined8 *param_1,int param_2,int param_3);
void __thiscall FUN_004feec0(void *this,int param_1,int param_2);
void __thiscall FUN_004ff3f0(void *this,int param_1,int param_2,int param_3,int param_4,int param_5,int param_6, int param_7);
void __thiscall FUN_004ffbf0(void *this,int param_1,int param_2,int param_3,int param_4,int param_5,int param_6, int param_7);
void FUN_00500300(uint param_1,undefined4 param_2,uint *param_3,uint *param_4,uint param_5, char param_6);
void FUN_0050bd60(int param_1,int param_2,int param_3,float param_4,float param_5,undefined8 param_6 ,float param_7,undefined8 param_8,float param_9,int param_10,int param_11);
void __thiscall FUN_0050c550(void *this,uint param_1,uint param_2,int param_3);
void __thiscall FUN_0050d260(void *this,int param_1);
void __thiscall FUN_005104e0(void *this,int param_1,uint *param_2,int *param_3);
void __thiscall FUN_00513400(void *this,int param_1,int param_2,int param_3,int *param_4,byte *param_5,float param_6 ,int param_7,byte param_8);
void FUN_00513760(float param_1,uint param_2,float param_3,int param_4,int param_5,int param_6, int param_7);
float * FUN_00522320(float *param_1,int param_2,int param_3);
void __thiscall World_biomeBorderDistance(void *this,int param_1,int param_2);
void __thiscall World_waterProximityInfluence(void *this,int param_1,int param_2);
float __cdecl pointSegmentDistanceSq(double *param_1,double *param_2,double *param_3);
float __thiscall FUN_00523b90(void *param_1,float param_2,uint param_3,int param_4,int param_5);
void __thiscall FUN_00524540(void *this,void *param_1,uint *param_2,uint param_3,undefined4 param_4,int param_5, int param_6,char param_7,int *param_8,int param_9);
void __thiscall FUN_005287b0(void *this,int param_1,int param_2,char param_3);
void * __thiscall FUN_005290d0(void *this,float param_1,float param_2,int param_3,undefined4 param_4);
float * __thiscall FUN_0052d030(void *this,float *param_1,float param_2,uint param_3,int param_4,int param_5);
float * __thiscall FUN_0052d5d0(void *this,float *param_1,int param_2,int param_3);
float * FUN_0052d870(float *param_1,int param_2,int param_3);
float * __thiscall FUN_0052db90(void *this,float *param_1,int param_2,int param_3,int param_4);
void __thiscall Creature_resolveSeparation(void *this,int param_1,uint *param_2,uint *param_3,float param_4);
void __thiscall FUN_00530470(void *this,uint param_1,uint param_2,int param_3);
void __thiscall FUN_005308b0(void *this,int param_1);
void GameController_updateSubsystems(uint param_1,int *param_2,void *param_3);
/* Library Function - Single Match void __stdcall `eh vector constructor iterator'(void *,unsigned int,int,void (__thiscall*)(void *),void (__thiscall*)(void *)) Library: Visual Studio 2012 Release */ void _eh_vector_constructor_iterator_ (void *param_1,uint param_2,int param_3,_func_void_void_ptr *param_4, _func_void_void_ptr *param_5);
/* Library Function - Single Match void __stdcall `eh vector destructor iterator'(void *,unsigned int,int,void (__thiscall*)(void *)) Library: Visual Studio 2012 Release */ void _eh_vector_destructor_iterator_ (void *param_1,uint param_2,int param_3,_func_void_void_ptr *param_4);

#endif
